strangerstudios/paid-memberships-pro

- scheduled/crons.php
Let us execute our own expiration actions at the time the membership expires (clean up roles, delete DB entries, etc)
> Hook for a post-expiration / pre email action

- includes/profile.php
Switch to using selected() and test whether $user->membership_level->ID is set before attempting to use it.
> Fix issue reported against profile.php

- pages/invoice.php
"Print" was hardcoded as reported by @ecoeficiente. Now translatable.
> I18N issue

- pages/popup-cvv.html
The correct term is CVV (Card Verification Value) but the page uses CCV instead. This fixes that error. (Didn't touch the image names though.)
> Corrected acronym "Card Verifcation Value"

- classes/gateways/class.pmprogateway_stripe.php
**NOTE**: The only real change here is lines 1409-1410.  The rest was removing excess whitespace and converting all line endings to CRLF.  (general cleanup)
--
This change is to allow other plugins to modify the subscription object before sending to Stripe. This is most useful for setting a custom ‘trial_end’ timestamp inside Stripe (which cannot be done inside the Stripe plan object).
https://stripe.com/docs/api/php#create_subscription
The Stripe plan object only lets you set a number of ‘trial_period_days’ — which is not granular enough if you want subscriptions to renew at a specific time of day — like noon or 3pm or whatever.
--
This pull request suggested by Jason in the v1.8 BETA blog post:
http://www.paidmembershipspro.com/2015/03/v1-8-beta-download-available-now-full-release-in-1-w …
> Adding a new filter called pmpro_stripe_create_subscription_array

- includes/functions.php
When calling number_format function we check if
$pmpro_currencies[$pmpro_currency]['decimal_separator'] and
$pmpro_currencies[$pmpro_currency]['thosuands_separator'] values are set
before passing them as arguments.
> BUG: fixed pmpro_formatPrice function which casted PHP notices everywhere

- adminpages/membershiplevels.php
Set $count = 0 before use/increment. PHP allows uninitiated variables, but has started complaining in recent versions.
> Fix for issue #198 (Uninitiated variable)

- includes/init.php
Please also apply this extra check for the case when the child theme is active but it does not have a plugin template override. Thanks
> Add extra check for shortcode overrides when the child theme is active 

- preheaders/checkout.php
On one hand, I like PMPro's streamlined registration process, but on another, I like Buddypress' activation system (aka email confirmation). I have merged the two with these changes in the plugin, and I could submit my code as a Gist for others wanting to use BP's activation system with PMPro.
Obviously, I avoid changing a plugin's code like the plague, but I didn't see any way to use BP's system without changing PMPro. What I found is that PMPro needs a couple extra filters to make the registration process more flexible. I had to replace the user creation with Buddypress', and then skip PMPro's user setup, so that it didn't automatically login the user.
In case you're interested, here's how I'm using those filters in `functions.php` to integrate Buddypress' system. I used the Register …
> Allow customization of user creation during checkout

- preheaders/cancel.php
Fixes #216
`empty($current_user->membership_level->ID)` returns null since it doesn't exist in `$current_user` when a user is logged out. 
This checks if it's set and if not, redirects the user to the membership levels page as the code expects.
> Use isset, add exit

- includes/content.php
The function `pmpro_body_classes()` returnes a notice error on archives because in that case `$post` object does not have the `ID` property. On taxonomy archives there's `term_id` instead of `ID` for instance.
> Ensure the object used for body class is of type post

- preheaders/levels.php
Fix for issue where [pmpro_levels] shortcode is used on same page as [membership level="2"] shortcode (level value is just an example) and membership levels have been reordered in WP Admin. [membership] uses the function pmpro_getLevel() which expects the global $pmpro_levels to have arrays keys values that match the membership level id.
As the code currently stands it chamges the global $pmpro_levels so that its array key values differ from the membership level id. This fix honors the sort order specified by pmpro_getOption('level_order') but makes sure the array key values in $pmpro_levels correspond to the membership level id.
An alternative fix may be to remove the section of code from lines 31-52 from /preheaders/levels.php since similar code is already included in /pages/levels.php
> Fix for issue with [pmpro_levels] with [membership] shortcode

- classes/gateways/class.pmprogateway_stripe.php
Not sure how this hook would ever be run, but there's a typo in the variable name.
> Typo of $morder variable

- services/applydiscountcode.php
- services/authnet-silent-post.php
- services/braintree-webhook.php
- services/ipnhandler.php
- services/stripe-webhook.php
- services/twocheckout-ins.php
Fix an issue happening when applying discount code on checkout when WordPress is setup as a sub-directory. #61
I replaced the direct access detection from `if ( !defined('WP_USE_THEMES') )` with `if ( !defined('ABSPATH') )` which fixed the issue in my case.
If someone tries to access the file directly with the same WordPress configuration it'll still fail but if I understood well direct access has been deprecated.
PS: Sorry for the white space diffs. Might be worth adding a .editorconfig to avoid that in the future
> Fix direct access detection

- css/frontend.css
I _think_ we need to define the display mode in "form.pmpro_form label.pmpro_normal" as inline-block, regardless of screen size.
> Ensure inline-block for TOS checkbox & label

- pages/levels.php
In current code, the translation will be retrieved & displayed while the expectation of the code is to concatenate the translation with the <strong></strong> elements.
> Translation should be retrieved & concatenated

- classes/gateways/class.pmprogateway_payflowpro.php
> FIX: PayPal requires HTTP 1.1 from POST request

- adminpages/memberslist-csv.php
Add actions: `pmpro_before_members_list_csv_export` and `pmpro_after_members_list_csv_export`.
`pmpro_after_members_list_csv_export`  supplies a list of users included in the export and could be used to estimate memory requirements for the process and use `php_ini('memory_limit')` to support really big export jobs.
`pmpro_after_members_list_csv_export` can be used to clean up after the export job if needed.
> Add before/after CSV export actions

- classes/gateways/class.pmprogateway_paypal.php
Allow PayPal more than the default 5 seconds before timing out the request
> Set timeout for server connection to 60 seconds

- classes/gateways/class.pmprogateway_paypalstandard.php
Probably meant to include the actual variable in the `die()` call.
> ENH: Nondescript error message

- classes/gateways/class.pmprogateway_twocheckout.php
- scheduled/crons.php
When processing for membership expiration notices, the system would return users who'd been deleted or had NULL or 0 as their membership_id.
> FIX: Don't return users w/membership ID of 0 or NULL

- adminpages/memberslist-csv.php
- adminpages/reports/memberships.php
- includes/content.php
- services/authnet-silent-post.php
- services/braintree-webhook.php
- services/ipnhandler.php
- services/stripe-webhook.php
- services/twocheckout-ins.php
(or didn't return any data when it ought to have)
FIX: Arrays of level IDs weren't handled properly in `pmpro_getCancellations()`
FIX: All-time startdate value set to 1970-01-01 which makes sense in an OS & plugin context
ENH: Use `LAST_DAY()` SQL function to find last day of month when using the "this month" option for Cancellation reports.
ENH: Added PHPdoc for `pmpro_getCancellations()`
> FIX: Cancellations in reports weren't always accurate 

- classes/gateways/class.pmprogateway_stripe.php
FIX: Wouldn't save the member order on a gateway update
FIX: Didn't trigger activation/deactivation hooks
> FIX: Didn't trigger activation/deactivation hooks

- classes/class.memberorder.php
"H:i:s" is the correct format instead of "H:s:i"
> Fix format for current time in date function

- includes/functions.php
Added the old_levels parameter to the
pmpro_before_change_membership_level action, so that those who hook can
determine where the user WAS in addition to where they are going.
> Pass old levels in before_change_membership_level action

- includes/functions.php
Strip off the unexpected quotes for the dates lest they become double-quotes in the SQL statement
> FIX: Latent start/end date formatting issues

- pages/billing.php
ENHANCEMENT: Add `pmpro_hide_billing_cc_fields` filter (false by default) 
Allows user to hide Credit card section from billing page (only update billing address if needed)
> ENHANCEMENT: Filter pmpro_billing_hide_cc_fields

- adminpages/memberslist-csv.php
- classes/gateways/class.pmprogateway_check.php
- pages/billing.php
- shortcodes/pmpro_account.php
BUG: Assumed that the level object is well formed and it exists
BUG: pmpro_isLevelFree() test would always fail
ENHANCEMENT: Re-introduce the pmpro_members_list_sql filter
> Fixes against V1.8.9.3 

- pages/billing.php
When the "Address for Free Levels" add-on is installed, the billing page will enforce the presence of the billing address & CardType fields, but won't show the billing info.
> BUG: Doesn't show required fields w/AFFL add-on

- classes/class.memberorder.php
- classes/gateways/class.pmprogateway_stripe.php
- includes/content.php
- includes/functions.php
- preheaders/checkout.php
- shortcodes/pmpro_account.php
Mostly, this is a reworking of the preheader for the checkout page to
accommodate MMPU. But to support it, a new function needed to be added
- pmpro_areLevelsFree - that checks if multiple levels are all free;
and the pmpro_checkDiscountCode function was also reworked to
accommodate MMPU in addition to the current static level call.
There are some unresolved issues with the checkout preheader still:
- current_user->membership_level is set on line 6 (for no reason?) but
then on line 826. This is problematic both for setting, but also later
for getting.
- I left a note on line 61 for Jason to check on.
- We’ll still need to modify pmpro_changeMembershipLevel a little bit,
but can get that next.
- Emails are still oogly; they will send once per level purchased,
which isn’t what most …
> Checkout Preheader for MMPU (plus related function includes)

- scheduled/crons.php
Because we didn't filter for the date/pmpro_expiration_notice in the JOIN, any record with an expiration date > the interval would be returned, regardless.
> BUG: Returns all records with expiration meta

- classes/class.memberorder.php
- includes/functions.php
- preheaders/checkout.php
Added a filter - pmpro_send_checkout_emails - that can be set to true
or false (default is true) to turn the checkout e-mails on and off. For
MMPU, we’ll turn it off, then replace with our own.
> Add filter for sending emails from checkout preheader.

- classes/gateways/class.pmprogateway_payflowpro.php
PayPal PayFlow doesn't use the NotifyURL argument (and as such, it's a little confusing to have it on our gateway handler).
> ENH: Removed NOTIFYURL argument

- includes/functions.php
Often, it is helpful to have the user_id when modifying the membership
levels for the user (e.g., to alter them conditionally based on who it
is). This adds the user_id parameter to the filter for both
single-level and multi-level filters.
> Add user_id to pmpro_get_membership_level[s]_for_user

- includes/functions.php
The hook pmpro_before_change_membership_level should be placed before the membership levels are deactivated. So that the $level_id returns the old_level of the user.
The current implementation of the hook returns the new level id in the parameter passed which makes it impossible to detect the old membership level when a user changes/switches the membership.
> Shift Hook : pmpro_before_change_membership_level

- includes/lib/Braintree/Braintree/Util.php
Braintree payments do not work unless you use these new non-deprecated functions. Found this fix at: http://doginthehat.com.au/2015/03/deprecated-error-with-lemonstand-v1-and-braintree-payments/
> Fixed Braintree payments

- classes/gateways/class.pmprogateway_stripe.php
Will enable users to add unique identifiers or otherwise modify order descriptions in order to aid accounting departments in differentiating these payments from other lines of business paid through the same gateway
> Add filter for modifying the order description in Stripe

- includes/functions.php
For both single and MMPU instances, you may want to filter the orders
that get cancelled on cancellation (e.g., only cancel most recent; only
cancel some but not others based on criteria). This adds a filter to
allow people to hook on and do that.
> Added filter for other order IDs to cancel

- pages/checkout.php
If a site chooses to offer discount codes but declines to use the discount code UI, in order to reduce checkout page friction, it is possible to include `?discount_code=<code>` in the URL. This works in conjunction with hiding the checkout form field by returning `false` from the `pmpro_show_discount_code` filter. 
In this case, the discount code gets lost at the PayPal order review step. This diff ensures that the discount code, as passed back by PayPal in the callback URL, gets submitted with the checkout form at order review.
> Ensure discount codes passed in URL is preserved through PayPal review step

- classes/gateways/class.pmprogateway_check.php
Stripped basic HTML tags from Instructions on display of instruction textfield.
> BUG FIX: Didn't allow formatting of instructions

- classes/gateways/class.pmprogateway_paypalstandard.php
BUG FIX: PayPal was not accepting amounts over $1000, changed `number_format` to include decimals.
> BUG FIX: PayPal not accepting amounts over $1000

- includes/functions.php
If PMPro Levels page was not set (ie: `$url` is empty) the value returned from `add_query_arg()` was `/wp-login.php?action=register` resulting in a redirect loop.
> BUG: Fixed redirect error if PMPro Levels page was not set.

- includes/functions.php
An example is the "Choose Levels to Hide Ads From" settings under Memberships >> Advanced. Selected levels would not be saved.
> BUG: Arrays would lose data when saved to options

- pages/invoice.php
When viewing an order of other users, the top membership level name
(bullet) would show current user opposed to the order’s level.
> BUG FIX: Level name would show for current user not from order.

- pages/billing.php
According the WP documentation:
https://developer.wordpress.org/reference/functions/wp_redirect/
`wp_redirect()` does not exit automatically and must be followed by an exit() statement.
> BUG: Added exit() after wp_redirect().

- includes/lib/recaptchalib.php
Occasionally, on some systems, file_get_contents will not work (returns false or whatever) when being used with Google reCAPTCHA.
This updates PMPro to instead use cURL and uses POST instead, as per the documentation.
> Updates recaptchalib to use POST instead of GET/file_get_contents

- classes/gateways/class.pmprogateway_braintree.php
When displaying Web Hook URL setting, we should do the same for Braintree as we do for all other gateways.
> ENHANCEMENT/FIX: Use AJAX over direct execution

- adminpages/paymentsettings.php
- classes/gateways/class.pmprogateway_check.php
- classes/gateways/class.pmprogateway_paypalstandard.php
- pages/confirmation.php
BUG FIX: Avoid double-encoding the API version in PayPal Standard gateway
ENHANCEMENT/FIX: Avoid double-encoding the PayPal API version number
>  BUG FIX: Didn't unslash instructions for check gateway

- css/admin.css
Removes bullet from level checkboxes from Gutenberg post-editor. Non-gutenberg screen seem unaffected, as seen in screencast.
[Screencast shows checkbox with/without Gutenberg](https://api.monosnap.com/rpc/file/download?id=RhNMtK6KT2jXT7CTByNBnIb54QR03h)
> Pbrx gutenberg

- scheduled/crons.php
Pmpro with the additional multiple memberships plugin fails to expire users, resulting in daily email spam reminders about an expired membership and a permanent membership. This is due to a missing optional argument in the change membership function in the core pmpro.
> Fix expiry not working with multiple memberships

- classes/class.pmproemail.php
I've been using `pmpro-email-templates` and I disabled the admin email on checkout.
When successfully registering, the page dies because the hooks handling the emails aren't expecting a potential `false` value.
I noticed the same conflict in `pmpro-register-helper`, I also submitted a pull request there. I haven't checked the other addons.
> fix conflict with pmpro-email-templates when emails are disabled

- pages/billing.php
This removes the Update/Cancel button on the billing page for payment gateways that do not capture billing details such as PayPal etc.
> Remove Update button on billing field for some gateways.

- services/ipnhandler.php
It appears that PayPal send a 'recurring_payment_skipped' IPN rather than 'recurring_payment_failed'.
> PayPal Failed Payment

- preheaders/checkout.php
If there are character like '+' in the username wordpress will remove that character in the insert_user.
> True in strict conditions on sanitize_user

- includes/filters.php
Adjust the confirmation and level description to filter on wpautop instead of the_content. Some page builders were breaking because of multiple 'the_content' calls.
> convert 'the_content' to use wpautop rather

- CONTRIBUTE.md
Page title doesn't render correctly.
Add space between hash sign and text of page title
> Fix markup of page title

- includes/privacy.php
Specify priority and number of arguments when pmpro_after_checkout_update_consent is installed as action. When this is not done, 2checkout flow errors with:
```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function pmpro_after_checkout_update_consent(),
1 passed in /home/cpbotha/webapps/wp_vxuni/wp-includes/class-wp-hook.php on line 288 and
exactly 2 expected in /home/cpbotha/webapps/wp_vxuni/wp-content/plugins/paid-memberships-pro/includes/privacy.php:483
``
> Fix 2checkout pmpro_after_checkout_update_consent

- includes/adminpages.php
Pages as assigned under Memberships > Page Settings are now labeled in the "All Pages" dashboard page in WordPress.
https://github.com/strangerstudios/paid-memberships-pro/issues/736
> Added a filter for display_post_states to identify special PMPro pages

- classes/gateways/class.pmprogateway_stripe.php
There was an issue that it was duplicate logic code to hide the Stripe Version. Removed the duplicate code.
> Minor fixes for hiding Stripe Version

- includes/currencies.php
Added Kenyan Shilling to currency list. This will enable easier integration to mobile payment solutions in Kenya such as M-pesa
> Added Kenyan Shilling to currency list

- adminpages/functions.php
When using Stripe, there used to be text that said you couldn't create a level with billing cycle limits. That warning was removed in commit 649bf536e9ffafd71ec0acef95ed789255a19425.
However, if billing limits are set on the membership level, an error message is displayed on the admin levels page as well as the admin page for the individual level in question.
Assuming the Stripe integration really does support billing cycle limits now, this warning is incorrect and can be removed.
> BUG FIX: remove Stripe billing limit warnings on membership levels page

- shortcodes/pmpro_account.php
Adding IDs to action links for better CSS/JS targeting on the page.
IDs added include:
`#pmpro_actionlink-renew
#pmpro_actionlink-update-billing
#pmpro_actionlink-change
#pmpro_actionlink-cancel
#pmpro_actionlink-levels
#pmpro_actionlink-profile
#pmpro_actionlink-password
#pmpro_actionlink-invoices
`
> Adding IDs to action links in the account shortcode

- services/ipnhandler.php
- services/stripe-webhook.php
Adding the cancelled level ID to the function that calls the pmpro cancel email class so the cancellation email doesn't say "All Levels" wine a single level was cancelled by the gateway.
> Updating Stripe Webook and IPN Handler to send the cancelled level ID

- includes/functions.php
Default checkout level if no level is passed in, or if the post_meta for default level doesn't exist.
Filter Added: "pmpro_default_level" which passes the default level ID for checkout - this will help developer's filter this without setting the post meta but set it more dynamically.
> Enhancement: Default checkout level

- includes/deprecated.php
- services/getfile.php
Updated getfile service to use "blocklist" instead of "blacklist". Create a new "deprecated" file for holding our no longer used actions.
> Updating to use 'blocklist' and adding a deprecated file

- adminpages/discountcodes.php
Updated the Discount Codes page to use buttons for "edit", "copy", and "delete"; Added option to "copy" a code (it generates a new code ID and "code" when duplicating but keeps all other code settings the same.
> Adding "copy" option for a discount code

- adminpages/membershiplevels.php
- classes/class.pmproemail.php
- email/checkout_check.html
- email/checkout_express.html
- email/checkout_free.html
- email/checkout_freetrial.html
- email/checkout_paid.html
- email/checkout_trial.html
Updates the email class and email templates to respect the level setting and include the confirmation message if set.
> Adding level meta option to include confirmation message in email

- adminpages/discountcodes.php
This update adds a "orders" link to view a filtered list of orders for the given discount code on the "Discount Codes" admin settings page. If there are no "uses" (orders) for the code, the button appears but is disabled (not linked).
> Added a button to view discount code "orders"

- includes/pointers.php
- includes/updates/upgrade_1.php
Also changed the name of the admin pointer
New initial option =  'pmpro_not_applicable'
'pmpro_v2_tour' renamed to 'pmpro_v2_menu_moved'
> This PR adds an initial option for new installs and then checks permissions for showing admin pointer

- classes/class.pmproemail.php
Use "display_name" and "user_email" in the array. The cancel email template is using this fields, but the sendCancelEmail method isn't.
To avoid that the email contains !!display_name!! (!!user_email!!) I include those in the data array.
> Bug Fix Cancel email data.

- preheaders/billing.php
Move the `wp_euqueue_script` call to before `do_action( 'pmpro_billing_preheader')` so we can use that action to dequeue the script. Use case is replacing the form on the page with a custom form that has its own validation.
**NOTE:** In the checkout preheader, the action already comes after enqueueing the script.
> Allow dequeueing of jquery.creditCardValidator on billing page

- services/twocheckout-ins.php
This was causing fatal errors when returning from 2Checkout.
pmpro_after_checkout_update_consent() requires a user ID and an order:
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/privacy.php#L483
> Bug fix: Fixed fatal error on return from 2Checkout.

- includes/functions.php
We have a site that is firing off this specific function multiple times (I haven't done a trace but I assume it's because there is a large number of "posts" on the page and it's checking members level for each one).
This is just a quick solution to reduce those queries and is limited to each request if there is no persistent object cache and will be persisted if there is (making future references quicker as well).
I set expiration to one day but it might need to be shorter depending on your opinion of how often levels change.
> ENHANCEMENT: Cache user levels to reduce MySQL queries

- services/twocheckout-ins.php
Updated the `pmpro_subscription_recuring_stopped` and `pmpro_subscription_recuring_restarted` actions to filter the $morder (not the $last_order which isn't passed to the function). Added a duplicate action to correct the spelling of "recurring". 
We will need to deprecate this incorrect filter name and remove eventually. See issue: https://github.com/strangerstudios/paid-memberships-pro/issues/942
> Updating action to use $morder; Fixing action misspelling

- preheaders/checkout.php
PHP 7.2.0 was causing issues with the `$pmpro_confirmed` variable.
Temporarily fix this by renaming the $pmpro_confirmed variable with the extract call.
> PayPal Express 7.2.0 bug fix.

- shortcodes/pmpro_member.php
Bug Fix: Removed the "membership_code" attribute from the `[pmpro_member]` as it was non existent in our getmembershiplevelforuser call.
ENHANCEMENT: added membership_description and membership_confirmation attributes in the shortcode. This may be useful for users.
> removed 'membership_code' from attribute.

- pages/checkout.php
One of the dividers on the checkout page was outside the checkout section. I moved this for consistency and to make sure that you can target and hide or adjust these dividers using CSS and the box it contains.
> Adjusting placement of divider hr on checkout page for consistency.

- pages/checkout.php
Turn off autocomplete for honeypot. Currently we don't get a report of a lot of spam and it seems that Chrome now supports autocomplete properly.
We should look at improving this in the future to work with timestamps.
Issue: https://github.com/strangerstudios/paid-memberships-pro/issues/893
> Turn off autocomplete for honeypot.

- includes/functions.php
- includes/upgradecheck.php
ENHANCEMENT: Added support for up to 8 decimal places. This trims any trailing 0's from the amount. For example if you have `5.021000` It would show as `5.021`.
ENHANCEMENT: Filter the decimal places using `pmpro_decimal_places`, this defaults to 2 and max value is 8.
This also updates the database decimal places automatically to 8 decimals.
> ENHANCEMENT: Support Up to 8 Decimal Places

- adminpages/membershiplevels.php
- classes/gateways/class.pmprogateway_braintree.php
Make Braintree plan ID's filterable to avoid conflicts if using multiple sites
Resolves #1040 
1. Create new recurring level
2. Insert this Gist in a PMPro Customizations plugin: https://gist.github.com/dparker1005/302a691d0ae7c82b4bbc0e65b552b950
3. Verify that error messages tell you to create a Braintree plan that is consistent with the one you built via the Gist
4. Create the plan in Braintree
5. Checkout
6. Verify that transaction and subscription were successful in Braintree
Added filter pmpro_braintree_plan_id
> Added filter for Braintree Plan ID's

- adminpages/admin_header.php
- adminpages/paymentsettings.php
- includes/functions.php
- paid-memberships-pro.php
This will adjust the "Testing Only" gateway to "Default" if there are only free levels available for signup.
This will change the gateway name to "Default" if only free levels are available for signup. This will help reduce confusion when running a free membership level site.
Closes Issue: https://github.com/strangerstudios/paid-memberships-pro/issues/897
1. Ensure only 'free' levels are available for new signups.
2. The gateway name should change to "Default" and the notification about "SSL & Payment gateway" should disappear.
3. Enabling non-free levels for new signups should revert back the gateway name to "Testing Only" and show the "SSL & Payment gateway" notification in the admin area.
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if …
> Adjust gateway name for only free levels.

- adminpages/reports/memberships.php
* [ X ] Have you followed the [Contributing guideline](CONTRIBUTING.MD)?
* [ X ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ X ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change? 
Fixing bad SQL that was causing daily Membership Report to not populate. See https://github.com/strangerstudios/paid-memberships-pro/commit/03c20e7d57fabb479530b681adf4baeff71c0222 for a similar fix applied to the Sales report.
-Go to Membership Stats report.
-Change period to "Daily", month to current month, then click Generate Report.
-Stats for the current period (in daily view) will be inaccurate or missing.
* [ X ] Have you added an explanation of what your …
> fixing membership stats sql

- pages/invoice.php
Updating the membership invoice frontend page to pull expiration date from the invoice user.
Closes Issue: #1018.
1. Set expiration date on a user
2. View an invoice on the frontend.
3. See their correct expiration date on the invoice. 
BUG FIX: Showing invoice user's expiration date not the current_user so that administrator or membership manager can view accurate invoices on the frontend.
> Updating Expiration Date to pull data for invoice user not current_user.

- includes/functions.php
Trim decimal places for amounuts that may have a lot of decimal places. (2+)
Fixes minor bug where prices like `$25.00 now` will be converted to `$25. now`
Closes Issue: N/A.
1. Create a membership price that ends in .00
2. See the memberships level page.
3. Run tests by setting decimal places to 8 and set price to variations of xx.0001000 or xx.0123001300
Bug Fix: prices would be trimmed down if ending on .00 and this should only happen if the number is not .00 and something like .120130
> Trim trailing zeroes for numbers with long decimal places

- classes/gateways/class.pmprogateway_stripe.php
During the getSubscription() function for Stripe, we check whether $this->customer->subscriptions is empty after we call $this->customer->subscriptions->retrieve(), so if the subscription object is empty, it causes an error. This error is handled on PHP <7 due to the enclosing try/catch, but not on PHP 7+. See here: https://www.php.net/manual/en/language.errors.php7.php Need to create separate PR to update all try/catch blocks to handle Throwables.
Forum topic (mods only):
https://www.paidmembershipspro.com/forums/topic/wordpress-notification-experiencing-a-technical-issue/
Test environment: Wordpress 5.2.2, PHP 7.2.15, PMPro 2.0.7
BUGFIX: checking for subscription object before retrieving subscriptions by ID when checking at Stripe
> moving check for subscription earlier when retrieving subscription from Stripe

- includes/profile.php
Translate the word 'Paid' status on profile page. I18N function was implemented (echo __).
Closes Issue: #1030
1. Translate the plugin. The word Paid will be translated.
2.
3.
Translate the word 'Paid' status on profile page. I18N function was implemented (echo __).
> Paid status i18n on profile page

- includes/functions.php
Custom templates were overriding any default templates when using `pmpro_{$type}_custom_template_path`. Now, instead of replacing $templates with $user_templates, we split $templates into an array of default templates and an array of custom templates, then merge them in that order. Custom templates are still loaded first, but now it will fall back to default template paths.
Closes Issue: #543
1. Install the code recipe from the following article: https://www.paidmembershipspro.com/new-method-load-custom-templates-pmpro-generated-pages-system-generated-emails/
2. Visit a PMPro page that *doesn't* have a custom template in pmpro-customizations/pages
3. Expected behavior before this fix: template doesn't load, page displayed but no content
4. Expected behavior after fix: template correctly …
> BUGFIX: fixed issue where default templates would fail to load if a custom template was specified

- pages/billing.php
The conditional statement that starts on line 75 of billing.php with `if(pmpro_isLevelRecurring($level)) { ` lost its `else` statement when it was updated, so now the "Logged in as NAME" text displays twice and "This subscription is not recurring. So you don't need to update your billing information" message shows up if subscription is recurring.
1. on current version: go to Billing page while logged in as a member with a recurring Stripe subscription
2. After the billing info fields, at the bottom of the page see additional login details and "This subscription is not recurring. So you don't need to update your billing information".
3. install this commit, then repeat step 1
4. added bit after billing info fields now gone
Fixed issue that caused Billing page to display non-recurring text …
> fixing missing else on Billing page

- includes/cleanup.php
This PR adds a notice when admin tries to delete users. It checks if any users for deletion have membership and shows an appropriate message for a single or multiple user deletion informing admin that membership and active subscriptions will be terminated after deletion.
1. Go to Users admin page.
2. Select a single user with no level for deletion. No message should be shown. 
3. Select a single user with a level for deletion. A message should be shown. 
4. Select multiple users, some with a level, for deletion. A different message should be shown. 
* ENHANCEMENT: Showing a notice on the Delete User form so admin knows that membership and subscriptions will be cancelled.
> Showing admin notice on Delete User Form if any users for deletion have membership.

- adminpages/memberslist-csv.php
- adminpages/orders-csv.php
Conditionally use readfile() if fpassthru() is disabled on this Wordpress installation. This has mostly been affecting Flywheel Hosted users (see https://getflywheel.com/wordpress-support/what-php-functions-are-disabled/) -
Closes Issue: #1071
1. Disable the fpassthru function in php.ini (https://www.php.net/manual/en/ini.core.php#ini.disable-functions)
2. Go to Memberships > Members and export members list csv
3. 503 or other server error, if generated .csv is downloaded it will be blank
4. Install this commit then repeat step 2
5. csv generated correctly, no server error
> BUGFIX: Fixed an issue that caused member/order list exports to give a 503 error on hosting setups where fpassthru is disabled (like Flywheel Hosted)
> fix for fpassthru disabled error

- classes/gateways/class.pmprogateway_paypal.php
There is a user who wanted first name, last name, and email to be sent to Payments Pro, but didn't want to require the user to give a billing address. This PR removes the requirement for an address to be present in order for name/email information to be sent.
1. Set gateway to Payments Pro with valid credentials
2. Make billing fields not required for payment
3. Check out with giving first name, last name, and email
> Send name/email to payments pro, even if there is no address

- includes/functions.php
Checking that the function `has_block()` exists before using it (implemented in v5.0). Also WPCS for that function.
Closes Issue: 1076.
1. Set up a WordPress site with version 4.9.10 (or likely any version <5)
2. Install PMPro from this PR
3. Generate pages and go to your levels page
4. Verify that there is no error
> has_block check

- adminpages/orders-csv.php
There were two instances where users were trying to perform large CSV order exports and entries were missing. I believe this line was a typo, but I would like confirmation for other developers to make sure.
Looking at the debug log generated with the old version, the first 2000 orders were being skipped during the export. After this line was changed, all orders were successfully exported. I have, however, noticed some behavior where orders would be exported multiple times.
1. Have orders dataset with more than the iteration limit of orders (defaulted to 2000(
2. Export to CSV
3. Verify that all orders are present in CSV
> Fixed entries being skipped in order csv

- adminpages/orders.php
After moving the order row's "buttons" into row actions, the elements did not display when using the tab method to toggle through links on page. This is particularly important for accessibility and UX cases.
The WP admin has a class `has-row-actions` that should be added to any table <td> element when the element has row actions so that they appear when the element is in focus.
> Adding "has-row-actions" CSS class to td element in orders admin

- adminpages/membershiplevels.php
- css/admin.css
- css/frontend.css
This update adds two new filters to the membership levels admin settings page. The filters `pmpro_membership_levels_table_extra_cols_header` and `pmpro_membership_levels_table_extra_cols_body` can be leveraged by other Add Ons or custom code to display additional level setting data in the all view.
To better accommodate new columns and match the UI of other settings pages, the Edit, Copy and Delete buttons were moved to row actions under the level's name. A minor CSS update to the admin stylesheet was needed for this adjustment.
ENHANCEMENT: Added filters `pmpro_membership_levels_table_extra_cols_header` and `pmpro_membership_levels_table_extra_cols_body` to allow for new columns on the Membership Levels settings admin page.
> Extend columns via filter on admin "Membership Levels" settings page

- css/frontend.css
Making the CSS for payment information section a little more bulletproof to support iframe input fields in Stripe Elements.
> Forcing full width, block, not floated labels in Payment Information section.

- includes/functions.php
Related to PR #1046 - see that commit for details of the initial change. Missed the step of actually assigning the merged template array to `$templates`, so the fix wasn't being applied properly.
> wasn't actually assigning merged custom templates to $templates

- includes/sessions.php
BUG FIX: Check if session is set, stops a warning from happening when sessions aren't set.
Closes Issue: N/A
BUG FIX: Session variable not set causing warning in array_exists check.
> Check if session is available

- adminpages/addons.php
- adminpages/admin_header.php
- adminpages/dashboard.php
- includes/adminpages.php
- includes/license.php
This PR moves the PMPro License page from Settings > PMPro License to Memberships > License. There is a new tab in the plugin's admin page area for "License". Links within the plugin have been updated to point to this new location.
There may be old version of the Memberlite theme and certainly documentation and videos on the site pointing to the old URL / location.
Old url is: /wp-admin/options-general.php?page=pmpro_license_settings
New url is: /wp-admin/admin.php?page=pmpro-license
> Moving PMPro License page to a tab under Memberships and under the Memberships Menu.

- adminpages/orders.php
Small Orders admin page column title change for consistency.
> Changing column name "User" to "Username" for consistency across our plugins + WP Users admin

- adminpages/orders.php
Two small adjustments to improve the table view of orders.
I did a small class name cleanup from the merged PR by aquiferweb .
I also updated the table's column to show "Level" as a level name, not ID. We more consistently use this across other admin areas of the plugin.
> Fixing a class on the orders table view; Now showing level NAME not ID

- classes/class.pmproemail.php
`wp_mail()` has a default value of `array()` for the `attachments` parameter. This PR sets the default value inside the PMPro email class to match what is expected by `wp_mail()`, to play nicely with email logging plugins such as Email Log.
Closes Issue: #1131.
1. Install the Email Log plugin. `wp plugin install email-log`
2. Trigger an email in PMPro.
3. View the email in Email Log.
4. Visit your local error_log file, and see no warning notice.
> Adjusts the default type for $this->attachments to be an empty array

- includes/sessions.php
When calling `pmpro_get_session_var()`, the call to `array_key_exists()` can return a warning notice, if `$_SESSION` doesn't exist, is `NULL`, or isn't an array.
This change replaces `array_key_exists()` with `isset()`, which is more performant, and caters to the type casting, to sidestep the warning notice.
Closes Issue: #1117.
1. Checkout this branch on your local environment.
2. Call `pmpro_get_session_var()`, and functions which call `pmpro_get_session_var()`.
3. Ensure no warning notices as a result.
4. Please test around this issue.
> Uses isset() instead of array_key_exists() to prevent a warning notice.

- includes/adminpages.php
I forgot to do the PR for this update. This adds conditional red or green color to the "License" menu item in the submenu and admin bar menus.
> Conditional for License menu item color red or green based on validation

- classes/class.memberorder.php
This PR adds Edit User and Edit Order links to the email when a gateway subscription fails to cancel. This email is only sent to the blog admin who has access to these edit links.
When managing error canceling emails, I am constantly searching my site for the user edit link in question in this email message. This will reduce the time admins must spend searching a members list for the specific user the email was generated for.
The email already includes the Order ID and User ID, so this code is leveraging that existing data to display more information to speed up membership site management.
ENHANCEMENT: Adding Order Edit and User Edit links to the Error Canceling email sent to the blog admin.
> Adding Edit User and Edit Order links to the Error Canceling admin email

- services/stripe-webhook.php
- services/twocheckout-ins.php
Resolves #1169 (setting timestamp corruptly when Stripe Webhooks is delayed). Also fixed this issue for 2Checkout.
Follow instructions in associated issue and ensure that the timestamp is set correctly.
Fixed bug where the timestamp for Stripe orders may be incorrect.
> Resolved #1169

- includes/profile.php
Fixed some timezones having first month be December in month dropdown, which would save the incorrect month when updating user expiration date.
Should also check for this bug elsewhere in the plugin.
Closes Issue: 1174.
1. Set WP timezone to somewhere in Europe (this causes the issue on my personal setup)
2. Ensure that months when setting an expiration date begin with January
> Fixed some timezones having first month be December in month dropdown

- adminpages/memberslist.php
Fixed Memberslist CSV export not accounting for selected level and search field.
1. From WP Dashboard, go to Memberships>Members
2. Select a membership level filter or insert search criteria
3. Click the export to CSV button
4. Verify that exported CSV only has records within the given filters
> Fixing memberslist csv export options

- css/frontend.css
- pages/billing.php
* BUG FIX: Fixing potential duplicate "logged in as" message on Membership Billing page for members with a non-recurring level.
* BUG FIX/ENHANCEMENT: Improving appearance of "City, State Zip Code" fields in Billing Address areas where the theme may force a width of 100% on input elements.
> Frontend CSS adjustment; Removed duplicate message from Membership Billing page

- classes/class-pmpro-members-list-table.php
Replaced $item->$column_name with $item[$column_name] to allow content to be displayed for 'custom' columns added via the new filter.
Closes Issue: #1184.
1. Add a new column via a custom plugin and the filter pmpro_memberslist_extra_cols:
```
function pp_memberslist_extra_cols_header($columns){
$columns['parish'] = "Parish Name";
return $columns;
}
add_filter('pmpro_memberslist_extra_cols','pp_memberslist_extra_cols_header',10,1);
```
2. Add content for the column using pmpro_members_list_user filter:
```
function pp_memberslist_extra_cols_body($item){
if(get_user_meta($item->ID, "parishname", true))  $item->parish = get_user_meta($item->ID, "parishname", true);
return $item;
}
add_filter('pmpro_members_list_user','pp_memberslist_extra_cols_body',10,1);
```
3. New column appears in table …
> Replaced object property with array index - fixes #1184

- classes/gateways/class.pmprogateway_authorizenet.php
Bug Fix: CVV value wasn't being passed through to Authorize.net API.
Bug Fix: CVV not passing to Authorize.net API
Bug Fix: CVV not passing to Authorize.net API
> Bug Fix: CVV not passing through to API

- pages/confirmation.php
- pages/invoice.php
The payment details section on the Membership Confirmation page and Membership Invoice single pages had bad formatting when the payment gateway on the order was "Check". This PR includes a few updates to improve the formatting.
I've also added a new div with class name "pmpro_payment_instructions" to wrap the payment instructions when output on the confirmation or invoice pages.
> Pay by check formatting updates

- classes/gateways/class.pmprogateway_paypal.php
- classes/gateways/class.pmprogateway_paypalexpress.php
Prevent trying to cancel subscription at gateway if processing an IPN cancellation (double cancel)
Resolves #1208
Still needs testing on a development site which can receive IPN messages, but the general steps are as follows:
1. Have user check out for subscription via PayPal
2. Cancel subscription at PayPal gateway
3. Ensure that no email was received by site admin saying that there was an error canceling the subscription at the gateway
> Paypal ipn cancel once

- adminpages/memberslist-csv.php
- classes/class-pmpro-members-list-table.php
Fixed issue where memberslist may show incorrect count and enddate
Resolves #1207 
1. Find a user who has had multiple memberships in the past, but is now an old user
2. Navigate to Memberships > Members and change the "Show" dropdown to "Old Members"
3. Count the number of members shown and ensure that it is equal to the number shown next to the search bar
4. Find your user from step 1 and see that their enddate is the most recent of all their memberships 
> Fixed issue where memberslist may show incorrect count and enddate

- classes/class.activityemail.php
- paid-memberships-pro.php
This is the first step toward the new "Admin Activity Email" for Paid Memberships Pro. This PR stubs out the entire email body and general setup/sections. 
For temporary testing purposes, you can trigger a test email by navigating to your site URL and appending it with `/wp-admin/?send_test_email=true`. This testing process needs to be removed from the `/classes/class.activityemail.php` before final launch.
> Adding the Admin Activity Email barebones layout and new class for email.

- includes/content.php
- includes/functions.php
- includes/login.php
- preheaders/account.php
- Filters the_content of membership account page to insert pmpro_login_form().
- Remove admin redirect to wp-admin and treat like other users.
- Login via membership account page now redirects non-members to levels page (filter available for overriding this)
- Login via membership account page now redirects members back to referrer (membership account page, other) or passed in redirect_to attribute.
- Redirecting wp-login.php to Membership Account page for login.
> First steps toward frontend login

- includes/currencies.php
A user requested Ghanian Cedi added to the list. In doing this, I also fixed a format with the JPY currency symbol position as noted in a .org support ticket and issue in this repository.
Closes Issue: 1055.
* BUG FIX: Adjusted currency symbol position for JPY currency to 'left'. 
* ENHANCEMENT: Added Ghanian Cedi as a currency.
> Adding Ghanian Cedi currency; Format update to Japanese Yen - JPY.

- includes/currencies.php
- includes/functions.php
This PR revisits the `pmpro_implodeToEnglish` function to add the Oxford comma in the comma-separated lists, specifically how this is output when using the !!levels!! string replacement in a non-member text .
1. Assign three or more levels to a post or page.
2. View the post or page as a non-member.
3. The multiple levels output in the non-member text should read as follows:
`This content is for Free, Enhanced, and Premium members only.`
* ENHANCEMENT: Updating the 'pmpro_implodeToEnglish' function to use an Oxford comma.
> Oxford comma levels string

- includes/compatibility/elementor.php
- includes/compatibility/elementor/class-elementor-restriction.php
- includes/compatibility/elementor/class-elementor.php
Enhancement: Create Elementor widget settings for Paid Memberships Pro. This allows to hide widgets based on user's membership level/show to non-members.
TODO: Support columns better. Currently you will need to select each widget and not set the main 'parent' column to show/hide for members.
Enhancement: Create Elementor widget settings for Paid Memberships Pro. This allows to hide widgets based on user's membership level/show to non-members.
1. Setup Elementor, create a page using Elementor.
2. Navigate to the selected Widget (i.e. Text) and choose "Advanced" tab.
3. In the Advanced Tab, go to "Paid Memberships Pro" and select what levels should access that widget. …
> Enhancement: Support Elementor Widgets Require Membership Settings

- classes/class.pmproemail.php
- email/billing_failure.html
- email/billing_failure_admin.html
Update the default formatting of the billing failure notice to be more cross-gateway compatible. Currently, users that check out with an offsite gateway would receive this billing_failure.html notice and it would look like a credit card failure with missing information for card number, type, expiration, and address. 
If a site owner wants to add this information back to these emails and is only using onsite credit card checkout, they can use the Email Templates Admin Editor to include this data.
Additionally, the admin version of the billing failure email had a link to the Membership Billing frontend page. This page is not useful to the admin. I have replaced the !!login_url!! variable to instead take the admin to the "Edit User" page for the account with failed payment.
1. Install the …
> Updating default template for billing failure notices to user and admin

- adminpages/advancedsettings.php
- includes/menus.php
Adds new setting to hide admin bar from non-administrator users. Users can still access this setting on the "Edit Profile" admin page. We may want to consider adding the CSS to hide that row.
ENHANCEMENT: Adding an Advanced Setting to "Hide the Toolbar from non-Administrator users.".
> Adding Advanced Setting to Hide Admin Bar.

- includes/adminpages.php
- includes/menus.php
- shortcodes/pmpro_member_profile_edit.php
Adding new section to menus management screens for "Paid Memberships Pro". Includes filter for custom Log In and Log Out menu items.
1. Go to appearance > menus and use the new "Paid Memberships Pro" menu links type.
2. Go to Customize > Menus > Edit and Add Items to a menu using the new "Paid Memberships Pro" menu links type.
3. Test that your Log In link (if added) is hidden when logged in.
4. Test that your Log Out link (if added) is hidden when logged out.
5. Test that Log In and Log Out do the appropriate thing.
* ENHANCEMENT: Making it easier to add PMPro Pages to your Menus via new metabox/customizer section.
* ENHANCEMENT: Now supporting adding a Log In or Log Out link (hidden for appropriate user state) to any menu location.
> Nav menu metabox; Customize menu item type; Log In and Log Out menu links filters

- includes/lib/name-parser.php
Closes #1252 
This PR fixes PHP 7.4 deprecation notices that are shown to the user.
1. Install PHP 7.4
2. Have WP_DEBUG set to true.
3. Visit any page on the site and you'll receive a deprecation notice.
> Fix PHP 7.4 deprecation notice regarding curly braces when pulling in array values.
> Removing curly braces. PHP 7.4 compatibility.

- includes/notifications.php
Wrap an `is_array` check 
> PHP 7.4 compatibility with array check.
> Adding array check when retrieving user meta.

- includes/compatibility/beaver-builder.php
Add Beaver Builder compatibility for row and module visibility. 
Closes Issue: #1260
1. Install Beaver Builder and Paid Memberships Pro
2. Edit a row/module and you'll see a PMPro tab.
3. Ensure membership levels are honored for module visibility.
* [ x Have you added an explanation of what your changes do and why you'd like us to include them?
> Add Beaver Builder compatibility for row and module visibility.
> Adding beaver builder compatibility with PMPro.

- paid-memberships-pro.php
Bug fix: clear activity email cron when PMPro is deactivated
1. Enable PMPro
2. Disable PMPro
3. Ensure that 'pmpro_cron_admin_activity_email' is not present
> Now clearing activity email cron on deactivation

- includes/login.php
- pages/billing.php
- pages/checkout.php
- preheaders/checkout.php
Fixing all places we use the term "Email" to remove hyphen. I have not removed them in the language files but I can if needed.
> Removing hyphen in email label

- includes/functions.php
- includes/login.php
* Function added "pmpro_are_any_visible_levels". This returns true/false if levels are available for signup.
* Adjust the register link to show Join Now if levels page is set and levels are available, otherwise redirect to default wp-login.php?action=register link.
> Adjust register link for front-end login.

- preheaders/billing.php
- preheaders/cancel.php
- preheaders/confirmation.php
- preheaders/invoice.php
Redirecting core pmpro pages if not logged in: invoice, cancel, confirmation, and billing should redirect to `pmpro_login_url()` (default redirect is is account page).
Now passing the `redirect_to` query arg for the page you were on, including url parameters.
Redirecting core pmpro pages if no level once logged in:
- cancel page returns you to membership account page.
- confirmation page redirects to account page, not homepage.
- invoice page: show your past invoices if you have any. show that you have none if you have none.
- billing page: had logic there for non-member users.
- checkout: goes to "a first found" level checkout
> Redirects for frontend login

- adminpages/pagesettings.php
Showing a link to "Generate" only the new Member Profile Edit page. This will help people upgrading to 2.3 easily create the appropriate and shortcode.
Once you have used the "generate" button to create this page we do not show it again (do not want duplicate pages generated).
1. Unset your member profile edit page, if set, under Memberships > Settings > Page Settings.
2. Click the "generate" link for the page.
3. The page is created.
4. Unset the page for member profile edit.
5. The generate link should not return.
> Show link to "generate" member profile edit page only

- adminpages/advancedsettings.php
- css/frontend.css
- includes/content.php
- includes/login.php
- includes/menus.php
- includes/profile.php
- includes/widgets.php
- shortcodes/pmpro_login.php
- Adding a missing hr to the change password form to match other form submit buttons.
- Updating the name of the member forms menu to avoid a conflict with Memberlite and the "Member" menu area in the top right of header.
- Updating the default content messages; Updating the description in settings page to reflect available replacement variables for three content message types.
- Updates to include a new handler function `pmpro_login_forms_handler` for displaying various states of the frontend login / logged in member experience. The `pmpro_login_form` function now better mirrors the core WP wp_login_form function and accepts the same array of `$args`.
- Edits to `frontend.css` for general style improvements for frontend login.
> Continuing v2.3 Development

- classes/class.memberorder.php
Now using `get_date_from_gmt()` to convert timestamps to local time.
Pre-fix:
1. Change timezone to Melbourne, Australia
2. Save order on Mar 15
3. See that it loses an hour when saved
Post-fix:
1. Change timezone to Melbourne, Australia
2. Save order on Mar 15
3. See that time saves correctly
> Fixed issues where orders could lose an hour when saved.

- css/frontend.css
This is just a small CSS fix for the Stripe grid layout billing information section - it was adding double the spacing needed.
> Adjusting the grid layout of the Stripe checkout fields where double spacing was being added.

- includes/login.php
* Redirect user's to referrer on login via widget by default.
* ENHANCEMENT:  filter added to disable the redirect for widget logins `pmpro_login_widget_redirect_back`
> Redirect widget logins to referrer by default.

- adminpages/advancedsettings.php
- adminpages/dashboard.php
- adminpages/license.php
- classes/class-pmpro-admin-activity-email.php
- includes/login.php
- includes/menus.php
- includes/widgets.php
Renamed menu to make better sense in terms of who sees it.
Renamed widget per discussion with Jason
Renamed the form nav action separator filter as this may eventually be used in other places down the road.
Fixed widget logic where show menu was set to "false" but still showing because false is a string (not empty).
Now showing the Log In Widget menu to both members and non-members. This can be adjusted using the nav menus add on.
> V2.3 Admin email design, renaming menu and widget, widget menus for non-members, 

- blocks/blocks.php
* [ x Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
Adding `wp_set_script_translations` so JS can be translated.
This will be difficult to test because the translators must translate the Gutenberg strings, then a JSON language pack is generated, and we'd have to switch to that language to ensure everything is translated correctly.
> JavaScript files are now translatable.
> Adding i18n for JS functionality.

- blocks/login/block.php
- includes/login.php
- shortcodes/pmpro_login.php
Some bugs around the block order of parameters, fixing shortcode attributes that weren't validating as bool, changing the show_menu check to a bool (! empty ) rather than an exact string check.
> Logged in member view of login shortcode/block/function fixes

- includes/login.php
Added filters for the_title and the document_title_parts['title'] when viewing the log in page for a specific action (reset password process).
Fixing two notices and update to use pmpro_is_login_page instead of $pmpro_pages global.
> Filter the_title and document_title_parts['title'] on log in page

- includes/upgradecheck.php
Now following rule to have two spaces after `PRIMARY KEY` when using `db_delta()` function.
> Added second space after PRIMARY KEY in pmpro_db_delta()

- classes/gateways/class.pmprogateway_paypalexpress.php
- services/ipnhandler.php
The change updates the IPN handler and PayPal Express class to support the recurring_subscription_failed. This change fixes issue https://github.com/strangerstudios/paid-memberships-pro/issues/1080.
1. Use the gist like https://gist.github.com/ideadude/8e05f2429914ca2869319c68cebb50aa but update txn_type to recurring_subscription_failed. Ask Kim for a real IPN record from the live site that you can test with.
2. Run the fake IPN. 
3. The user will cancel membership.
* BUG FIX: Updated to support the `recurring_subscription_failed` IPN transaction type where PayPal will fail to collect the recurring payment but keep the profile open. We now cancel the profile and membership.
> Update to process cancellation for the recurring_subscription_failed txn_type

- pages/billing.php
- preheaders/billing.php
This update will show the "Check Payment Instructions" on the Billing Information page. It also adds a "View your membership account" back link for both PayPal and check payment members that view this page.
1. Complete checkout for a recurring order using a check payment gateway.
2. Visit the billing information page to see payment instructions.
* BUG FIX/ENHANCEMENT: Billing Information page updated to show check payment instructions.
> Updating the billing page for check payment gateway notes. Adding "back" link to account.

- adminpages/dashboard.php
- adminpages/orders.php
Warning for empty level->name is now caught in two places. "deleted" or "none" in place of level name using logic similar to how we do a deleted user.
> Fixing warning on Dashboard and Orders 

- adminpages/orders.php
Added custom filters capability for osers admin page. This is because in many cases we might need to filter the orders list on specific conditions.
1. Add a WordPress' filter that adds a custom filter to the order admin page
2. Add a WordPress' filter to check if the orders admin page is loaded with that filter and apply a condition
> Add custom filters for orders (adminpages)

- adminpages/advancedsettings.php
- includes/content.php
Updated replacement suggestion for login_page_url to use login_url. 
Now supporting login_page_url, login_url, levels_page_url, and levels_url in the replacements for these variables.
> Updating for bug with !!login_page_url!! in content message description text

- shortcodes/pmpro_account.php
We created a new filter in v2.3+ to allow users to filter the links shown under the bullets in the "profile" section of the account shortcode/page. We changed this filter earlier in the page where it was used within the "membership" section to use action_links but this filter was not updated to that better naming / format. This PR swaps the filter created to its permanent name: `pmpro_account_profile_action_links`
* BUG FIX/ENHANCEMENT: Fixed `pmpro_account_profile_action_links` filter name newly added in v2.3.
> Updating new filter name to 'pmpro_account_profile_action_links'

- adminpages/advancedsettings.php
This PR removes the line "Ads from the following plugins will be automatically turned off: Easy Adsense" since this is no longer an active plugin and may be misleading as there are newer plugins that we do not integrate with that are called "Easy Google Adsense" and "Easy Peasey Adsense".
The function itself still checks for the presence of the `EzAdSense` class. We should look to deprecate this integration and consider other new ad plugins we can have built-in filters for.  
* BUG FIX/ENHANCEMENT: Removed text on Advanced Settings for "Hide Ads" section where it may be misleading that we integrate with newer Adsense plugins (Easy Adsense is no longer in development).
> Updating the advanced settings page to remove message about "EasyAdsense"

- classes/class-pmpro-admin-activity-email.php
Adds $recipient param to activity email function and `pmpro_after_admin_activity_email_cron` action to run additional code during the send admin activity email cron. Can be used to send additional admin activity emails to various recipients.
1. Add Gist here: https://gist.github.com/dparker1005/6bf650370a12aef44adf8c8c26d3e906/edit
2. Manually run the pmpro admin activity email cron
3. Verify that additional emails were sent.
* [ x Have you successfully run tests with your changes locally?
> Send additional admin activity emails

- includes/functions.php
As discussed with Jason, it's better to force the order status to "error" when Initial Payment fails, instead of cancelled (which creates confusion and makes reports dirty).
> Force order status to "error" when Initial Payment fails (paypalexpress)

- classes/class-pmpro-members-list-table.php
Checking for empty start and join dates in Members List
Customer ticket here (admins only): https://www.paidmembershipspro.com/forums/topic/membership-start-date-showing-as-today/
> Fixed issue where empty dates would show current date in memberslist

- adminpages/advancedsettings.php
- uninstall.php
Added advanced setting to control whether PMPro should be uninstall when the plugin is deleted.
> Added "Uninstall PMPro on Deletion" advanced setting

- pages/billing.php
Now showing the payment method to be used or just updated so the users know that their payment method update was successful.
There is a filter `pmpro_billing_show_payment_method` to disable the display for sites using a service like Churnbuster that can get out of sync with the user's usermeta values for card type, account number, and expiration date.
Users previously had no way to see what card they were paying with or whether the update was successful after update.
BUG FIX/ENHANCEMENT: Added a notice of the payment method being used for subscription on the Membership Billing page.
> Adding the current user's payment method used for subscription to Billing Information page

- adminpages/orders.php
Do not escape the $link in $actions on the PMPro Orders page. Escaping should be done in any functions that filter the $actions value via `pmpro_orders_user_row_actions` filter.
1. Install PMPro Add Member from Admin Add-on without this change made
2. See that "+order" hover link does not display correctly on order page
3. Make change from this PR
4. See that link now displays correctly
> Undoing escaping of link in actions on Orders table

- services/ipnhandler.php
Resolve undefined property notice when PayPal IPN is triggered:
PHP Notice: Undefined property: MemberOrder::$notes in /site/wp-content/plugins/paid-memberships-pro/services/ipnhandler.php on line 771
Instructions to replicate in this ticket (admins only): https://www.paidmembershipspro.com/forums/topic/bug-pmpro-core-php-notice-in-ipnhandler-php-after-update-to-v2-3-3/
Then can test after fix to see that notice no longer shows.
Note that this change will assume that there are no notes for the order before that line is run as they would be deleted on this line, but that seems like a safe assumption since we are creating the order from scratch and there are no actions beforehand.
> Resolve undefined property order::notes notice in ipnhandler

- includes/rest-api.php
* Removed undefined function and passed through $method to pmpro_get_rest_api_methods function.
> REST API Fatal Error Fix

- includes/admin.php
- includes/profile.php
- shortcodes/pmpro_account.php
Users who are blocked from accessing the dashboard but are using a site that has not assigned a frontend profile edit page were being redirected to the homepage when clicking "Edit Profile" or "Change Password" from the Membership Account "Profile" page section.
This PR will hide those links if a frontend page is not selected and the PMPro option to hide the dashboard is on. This will not account for a case where the dashboard is blocked by another plugin like Theme My Login. Users with that setup must assign the TML profile page as the "Member Profile Edit Form" page under Memberships > Settings > Pages in the WordPress dashboard.
Users are also asking that the member profile edit form default fields can be adjusted to remove some of the default WP User Object fields OR add additional …
> Updating account profile edit, change password links to hide if dashboard is blocked.

- includes/profile.php
Fixing bug where memberships may lose one day on profile save.
Can test this by going to a user's profile page in the WP dashboard, giving their membership an expiration date, saving, and checking that the date is shown correctly when the page loads. Can follow these same steps for other WP timezone settings.
> Fixed issue where memberships may lose a day on profile save.

- classes/gateways/class.pmprogateway_paypalexpress.php
Separate cancelGateway logic, useful when you want to cancel at gateway without changing the order status (i.e. order status = error but not cancelled at gateway for any reason and still trying to get the money)
> Separate cancel/cancelGateway logic in PayPal Express

- adminpages/reports/memberships.php
- adminpages/reports/sales.php
Closes #1106
The correct Epoch date is 1970-01-01. Some systems are able to handle dates that go beyond the epoch, while some are unable.
Closes Issue: #1106.
1. On an affected installation, try to access the PM Pro Dashboard.
> Set epoch date to 1970-01-01 (previously 1960-01-01)
> Set epoch date to 1970-01-01

- classes/gateways/class.pmprogateway_stripe.php
This change removed calls to a deprecated function in the Stripe-PHP library.
The deprecated call can be seen here:  https://github.com/strangerstudios/paid-memberships-pro/blob/00e7e8130ad667808c161f0c3964ae732798a3df/classes/gateways/class.pmprogateway_stripe.php#L1940
This function (i.e. Stripe\Customer::invoices()) was deprecated in the Stripe PHP Library in this commit: https://github.com/stripe/stripe-php/commit/8a046cfd119e50a048645f8d4249490a566379bc#diff-814438c52fc09aaad9ad47d5fa40351c
Having queries this with the Stripe support team, the recommended approach is now to use the list function on the Invoice object with the appropriate customer id and status (of open). This approach is documented at:  https://stripe.com/docs/api/invoices/list?lang=php
1. Create a new member & …
> Removing deprecated stripe-php function calls

- includes/functions.php
- includes/profile.php
Now using CONVERT_TZ SQL function when getting `startdate` and `enddate` from database. Query should now get the time from the DB in local time, meaning that no additional conversions are required. Fixes issues were SQL time settings could cause off-by-one error when showing enddate on profile page.
> Now using CONVERT_TZ for start and enddates

- includes/sessions.php
Now checking if headers sent before starting session. Should avoid `PHP Warning: session_start(): Cannot start session when headers already sent in /site/wp-content/plugins/paid-memberships-pro/includes/sessions.php on line 21` warning from being logged.
NOTE: This PR still needs to be tested to ensure that sessions still work as expected when we need them to. Would also be nice to not fail silently if headers already sent, not sure if there is a better error message that we could show.
1. Use a customizations plugin to send headers before the `pmpro_checkout_preheader_before_get_level_at_checkout` action is run
2. Verify that without this patch a warning is shown, and with this patch it is not
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if …
> Now checking if headers sent before starting session

- classes/gateways/class.pmprogateway_twocheckout.php
2Checkout recently deprecated their `sandbox.2checkout.com` service and moved the testing behavior over to their live accounts. More info on this here: https://knowledgecenter.2checkout.com/API-Integration/Transition_guides/Transition_Guide_for_2Checkout_Sandbox
This PR points both the sandbox and live payment requests directly to `https://www.2checkout.com/checkout/purchase`. These requests are differentiated by the `demo` `$tco_args` arg, which is set to `Y` for sandbox checkouts earlier in the code.
Setup 2Checkout alongside PMPro and ensure that both live and sandbox checkouts work as expected. Note: I have not yet explicitly tested that live checkouts still work, but this change shouldn't affect live checkouts whatsoever.
> Enter a summary of all changes on this Pull Request. This …
> Fixing 2checkout sandbox

- adminpages/reports/memberships.php
- adminpages/reports/sales.php
This resolves an issue where the reports page was
failing with a 502 error on some sites.
1. Open the reports page on an affected installation
> Bug Fix: Fixed issue where the reports page was causing a 502 error on some sites.
> fix: Set start date to epoch on reports page

- classes/gateways/class.pmprogateway_paypalexpress.php
It would be really easy (1 api call) to get the Gateway Status for a Payment if we had the transaction_id even for initial payments. By the way, we don't have initial payment transaction_id (payment_transaction_id == subscription_transaction_id for initial payment orders). Because of that I need to use multiple api call (and triple safe checks) to be sure to collect the correct payment_transaction_id for initial payments. This sucks, but it works.
1. Take any initial payment order
2. Run this code:
```
<?php
$order = new MemberOrder();
$order->getMemberOrderByCode( $order_code );
$status = $order->Gateway->getTransactionStatus( $order );
var_dump( $status );
```
> PayPal Express: implement getTransactionStatus

- classes/class-pmpro-members-list-table.php
Resolved parse error that could occur: `*Parse error*: syntax error, unexpected ‘[’ in
*/htdocs/wp-content/plugins/paid-memberships-pro/classes/class-pmpro-members-list-table.php*
on line *410*`
> No longer pulling array value directly from funciton call in memberslist

- adminpages/orders.php
This commit fixes the Expiration Date Input when This input is readonly.
* [x ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
Bug fix: When you have the Expiration Date as readonly on Orders admin view, it is not visible, this fix, makes it visible again.
1. Add ExpirationDate to array inside **pmpro_orders_read_only_fields** filter (adminpages/orders.php line 172)
2. Go to Orders page inside Paid Memeberships pro -> Edit
3. Now Expiration Date is visible
* [x ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x ] Have you successfully run tests …
> Expiration Date Input On readonly fix

- includes/rest-api.php
Adding API function to get Checkout Level given the current fields set at checkout.
1. Add Gist: https://gist.github.com/dparker1005/399266c69f5351abb60ef4706c74d3a4
2. Can click "Test API" button on checkout page to see what the checkout level will be given the current checkout fields
> Added checkout_level API call

- includes/functions.php
Fix PHP Notice: Trying to access array offset on value of type null
Issue: https://github.com/strangerstudios/paid-memberships-pro/issues/1401
Closes Issue:https://github.com/strangerstudios/paid-memberships-pro/issues/1401.
1.
2.
3.
PHP Notice: Trying to access array offset on value of type null in /…/wp-content/plugins/paid-memberships-pro/includes/functions.php on line 1329
The line should be:
if ( isset( $prev_values[ $i ] ) ) {
instead of:
if ( $prev_values[ $i ] ) {
> Fix PHP Notice: Trying to access array offset on value of type null

- includes/login.php
Just a simple code comment added here to advise custom code to use the login_redirect WP filter over the PMPro pmpro_login_redirect_url filter documented here: https://www.paidmembershipspro.com/hook/pmpro_login_redirect_url/.
> Adding note to login redirect function to use core WP filter, not ours which we have only left for posterity.

- includes/login.php
We found another core WP error (retrieve_password_email_failure) that we need to handle on the frontend which relates to a server's ability to use the wp_mail function.
You can see this in core WP here: https://github.com/WordPress/WordPress/blob/7b192d406a3aceae04bc8ca3c2119410802dbbef/wp-login.php#L452-L461. 
This PR adds an an error type in the password reset function in : https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/login.php
1. In your WP site, disable email somehow. In my test, I just edited the wp_mail function in wp-includes/pluggable.php to always return false.
2. Test a password reset.
3. You should get this error:
* BUG FIX/ENHANCEMENT: Catching another password reset failure case where wp_mail is not functional on the server.
> Enter a summary of …
> Catching password reset error for core WordPress 'retrieve_password_email_failure' case.

- adminpages/dashboard.php
- adminpages/discountcodes.php
- adminpages/memberslist-csv.php
- adminpages/reports/login.php
- classes/class-pmpro-members-list-table.php
- classes/class.memberorder.php
- classes/class.pmproemail.php
- includes/functions.php
- pages/invoice.php
- shortcodes/membership.php
- shortcodes/pmpro_account.php
Use `CONVERT_TZ()` everywhere we use `UNIX_TIMESTAMP()` as the timezone of the SQL server should not ever change the time that is shown in WordPress. This change should remove the SQL timezone from the equation altogether.
> Now using CONVERT_TZ for all UNIX_TIMESTAMP calls

- blocks/checkout-button/block.php
- shortcodes/checkout_button.php
Another PR requested this feature a long while ago - I am revisiting some PRs now and think this is a good update. This PR adds a wrapping <span class="span_pmpro_checkout_button">...</span> for the output of the [pmpro_checkout_button] shortcode or Checkout Button Block.
> Wrapping checkout button shortcode output and block in a span so it can be targeted with CSS.

- pages/billing.php
- preheaders/billing.php
If a site changes its primary gateway, there are cases where a previous member may have their membership managed by the previous primary gateway. We currently just show the Billing Information update form for the new gateway, however that form would not do anything to update an active membership with another gateway.
There are more approaches we could take to resolve this, such as sending the $gateway for the user's active subscription through to the filters on billing page used to swap in other gateway classes including `pmpro_include_billing_address_fields` and `pmpro_include_payment_information_fields` but that has broader implications for sites using those filters already, and for each gateway class and the checkout pages.
This update takes a more straightforward approach to resolve …
> Handling case where membership billing order gateway is not the same as primary site gateway.

- adminpages/dashboard.php
Small adjustment to the dashboard where the get involved links are - the underlines with the icons was strange. This is more uniform especially now that there are additional links in place.
> Moving to a list format for ways to get involved so links aren't underlined oddly.

- classes/class.pmproemail.php
Fixed incorrect UNIX_TIMEXTAMP call when getting enddate in confirmation email.
> Fixed UNIX_TIMESTAMP call in checkout email

- pages/invoice.php
Enddate on the single invoice had a notice for cases where the invoice was referencing orders for not the current user's membership. We reevaluated and decided "enddate" on the invoice really didn't make sense since it represents a payment at a point in time.
We also decided to have the status match that on the Membership Account "Invoices" section, where statuses like 'success', 'cancelled' and '' reflect "Paid" rather than the actual status which may be confusing since cancelled doesn't mean it wasn't paid successfully.
> Updating invoice status to match format on the account page; removing enddate.

- includes/rest-api.php
Added MMPU-Compatible `/pmpro/v1/checkout_levels` API call. Includes information about each level being checked out for along with the total initial payment that will be charged. Necessary for MMPU compatibility for Stripe Payment Methods.
> Added checkout_levels REST API call

- pages/checkout.php
We were using wpautop to format the content of the TOS page. This causes conflicts for site using the block editor (empty <p> tags wrapping block editor html comments.
This update removes the default wpautop filter and adds a filter that sites can use to adjust the content or run their own filters before display.
Here is an example gist using this new hook:
https://gist.github.com/kimcoleman/e2c7d0b709ab6b9bb3d3c86421a7f2b8
> Adding filter and adjusting how we load the content of the Terms of Service page

- classes/gateways/class.pmprogateway_stripe.php
Now using `self::get_webhook_ids();` instead of `get_webhooks()` in function to get webhooks that PMPro saved instead of querying Stripe.
> fixed update_webhook_ids in stripe gateway

- includes/filters.php
Resolves #1406 
Now ignoring the checkout time when compensating user for un-used time during membership renewal. This prevents off-by-one errors when a user checks out after the time of day of their original checkout.
> Fixed losing a day on membership renewal

- includes/profile.php
New hook pmpro_member_profile_edit_form_tag replicates the core WP hook here: https://developer.wordpress.org/reference/hooks/user_edit_form_tag/
This hook is used by Register Helper here: https://github.com/strangerstudios/pmpro-register-helper/blob/b35bb8b2e87acab6d0276e4c1a7f743703613f2f/pmpro-register-helper.php#L1064-L1071
We should test file uploads in pmpro without that form type on the file upload - they may work as is. Most avatar upload systems need this encoding on the form so that we can support a plugin like Simple Local Avatars on our frontend form.
> Adding a hook to the member profile edit form tag.

- includes/addons.php
WP 5.5 RC-2 compatibility on the plugins screen with core auto-updates UI interface for third-party plugins/add-ons.
1. Install patch.
2. Install several add-ons.
3. Roll back these add-ons.
4. Use a tool like Easy Updates Manager and force updates in their Advanced->Force Updates interface. This will mimick core auto-updates. Alternatively, use cron, but this is more complicated as the cron needs to be run naturally rather than manually using something like WP Control.
5. Test with and without a license.
6. Possibly update non-licensed update errors with a link to some docs or the license tab with an upsell.
> Compatibility with WP 5.5 Core Automatic Updates.
> Adding WP 5.5 compatibility with core auto-updates.

- pages/invoice.php
Fixed fatal error and now showing order date in local time, which is consistent with viewing an individual invoice.
Resolves #1464 .
View invoice list and see that the error no longer shows with the fix implemented.
> Resolved fatal error when viewing invoice page

- includes/profile.php
Currently, there's no space between "Paid" and the amount:
The change adds a space between "Paid" and the amount.
> Add a space between "Paid" and price on the profile page
> Add missing space between "Paid" and price on the profile page

- adminpages/orders.php
* ENHANCEMENT/BUG FIX: Fix an issue where locales like Italian caused JavaScript errors (due to single quotes being used inside the translation).
Moved the delete prompt wording outside of the HTML to make it easier to work with.
Resolves https://github.com/strangerstudios/paid-memberships-pro/issues/1357
1. Set locale to Italian.
2. Delete an order from inside the WordPress dashboard.
3. Ask Prompt should be in Italian and no JS errors.
> Adjust order delete prompt to support other locales.

- classes/class-pmpro-members-list-table.php
Reset the current page number in the Members List when the shown level is changed. This can avoid situations where you switch from "All Levels" page x to a level with only one page of users, but see none displayed.
1. View your Members List
2. Change which page you are viewing
3. Change the level you are viewing
4. See that the page number goes back to 1 when the page loads
> Now resetting memberslist page number when changing shown level

- includes/login.php
Resolved issue where password reset link would send incorrectly when plain permalink are used.
Resolves #1476.
See issue.
> Fixed issue where non-pretty permalinks may break frontend password reset

- classes/gateways/class.pmprogateway_braintree.php
Added method to get a subscription's next payment date to the Braintree gateway. This function can be run every time that the next payment date is calculated by adding the following PHP to your site:
`add_filter('pmpro_next_payment', array('PMProGateway_braintree', 'pmpro_next_payment'), 10, 3);`
> Added Braintree functions to get next payment date

- classes/gateways/class.pmprogateway_stripe.php
- css/frontend.css
There is one  spot here we link out to Stripe documentation. Jason mentioned we may instead want to link to our own site docs.
Here are the lines:
- https://github.com/strangerstudios/paid-memberships-pro/blob/v2.5/classes/gateways/class.pmprogateway_stripe.php#L415 links to https://stripe.com/docs/stripe-js/elements/payment-request-button#verifying-your-domain-with-apple-pay
We also link to the Stripe Dashboard > API Keys page directly in the error messages related to the $payment_request_error in the admin. This may be the most helpful place to link but we could instead link to a page on "how to find and update your stripe publishable and secret keys". 
Here is a screenshot of the frontend of checkout in Chrome with 'google pay' enabled.
> Frontend updates and adjusting messages in admin for Payment Request Buttons.

- classes/class.memberorder.php
- includes/functions.php
- services/authnet-silent-post.php
- services/braintree-webhook.php
- services/ipnhandler.php
- services/stripe-webhook.php
- services/twocheckout-ins.php
Contains part of the fixes needed to ensure that tax is calculated correctly on renewal orders.
Resolves XXX.
1. The PMPro Vat Tax Add On should be active
2. Proceed through checkout for a recurring membership
3. Tax should be correct. The this fix should ensure that the tax rates and values show correctly on renewals too
Tax rates are now recorded correctly on renewal orders
> Recurring order tax fixes

- classes/gateways/class.pmprogateway_paypalexpress.php
- includes/login.php
- preheaders/checkout.php
* BUG FIX: Removed sanitize_text_field calls for password fields as it was stripping characters in some cases.
calling `sanitize_text_field` on passwords would remove certain characters from the password. For example "my<pass>" would result in the password being saved as "my".
* BUG FIX: Removed sanitize_text_field calls for password fields as it was stripping characters in some cases.
> Remove sanitize_text_field on password fields

- classes/gateways/class.pmprogateway_braintree.php
- includes/lib/Braintree/lib/Braintree/Util.php
These changes resolve errors that occurred during checkout when using the Braintree gateway
1. Have an existing membership (untested if this occurred because of another gateway being used before)
2. Sign up for a new membership 
3. Errors will show up and prevent you from being redirected to the confirmation page
Errors resolved that would show during checkout from the Braintree payment gateway
> Fixes notices and undefined variables when using Braintree

- classes/gateways/class.pmprogateway_stripe.php
- js/pmpro-admin.js
- Fixed issue where Stripe Webhook events would not be fixed
- Removed caching of Stripe Webhooks
- Removed redundant code
- Created ajax function to rebuild a webhook (delete then create)
- Warning user if Stripe Webhook is disabled or API version is out of date. Gives option to rebuild.
Create webhooks in Stripe with missing events, old API version, or disabled status and see that the correct warning is shown and you are given an option to fix the issue.
> Stripe webhook detection improvements

- adminpages/discountcodes.php
- adminpages/functions.php
- adminpages/membershiplevels.php
Show warning to user if membership levels/discount codes have recurring payment periods longer than 1 year while Stripe is set as gateway. Recurring payment periods longer than 1 year are not supported by the Stripe API:
https://stripe.com/docs/api/plans/create#create_plan-interval_count
1. Create a membership level with a billing period longer than 1 year
2. Save the level and see that a warning is shown on levels page/while editing level
> Warning user if stripe billing period longer than 1 year

- adminpages/orders-csv.php
- adminpages/orders.php
Added filter 'pmpro_orders_show_coupon_amounts' to allow site to reenable these fields.
> Hide 'couponamount' in order edit and order csv export

- includes/profile.php
BUG FIX: Fixed an issue where pmpro_personal_options_update would run on page load. This now only runs when updating a user's profile.
> BUG FIX: Moved pmpro_personal_options_update

- classes/gateways/class.pmprogateway_twocheckout.php
- services/twocheckout-ins.php
Resolves The following problems regarding discount codes and 2checkout :
1- Increase user count when discount code is used
2- Reads the new enddate after the discount code is applied
1. You need to have a Live fully functional 2checkout account integrated with pmpro
2. Create a Discount Code, edit the expiry date to a custom value different from the original membership
3. Test the Discount Code and you should see the increase of the user count that used this coupon and the custom expiry date should be applied
> Fixing 2Checkout Discount Codes User Count and Custom Expiration Date (enddate) Settings

- includes/init.php
- includes/recaptcha.php
BUG FIX: fixed priority in which reCAPTCHA was being loaded on checkout page.
> BUG FIX: reCAPTCHA not working

- classes/gateways/class.pmprogateway_stripe.php
I must admit I spent a while to find this one; I'm using PayPal Express only and have Stripe disabled. But Stripe has few lines of codes still running around, these are just few. These lines are disabling required billing fields on checkout even when just PayPal Express is selected. Well, PayPal Express disables these fields as well, but when you try to remove PayPal Express hooks you'll see that there are also that function hooked to `pmpro_required_billing_fields`.
PayPal Express gateway is implemented with this if condition as well.
I made tests with PayPal Express only. Tests should be run with Stripe as well.
> Conditionally load billing fields filter for Stripe Gateway

- includes/functions.php
PHP8 Deprecated Notices Fixed. It's frowned upon to have an optional variable in a function followed by a required variable. We should either switch them around (not doing this here), or give both variables a default value in the function.
Errors that occurred upon activate:
```
[02-Dec-2020 10:15:24 UTC] PHP Deprecated:  Required parameter $totalitems follows optional parameter $page in /srv/users/phptesting/apps/php8/public/wp-content/plugins/paid-memberships-pro/includes/functions.php on line 1382
[02-Dec-2020 10:15:24 UTC] PHP Deprecated:  Required parameter $level_id follows optional parameter $user_id in /srv/users/phptesting/apps/php8/public/wp-content/plugins/paid-memberships-pro/includes/functions.php on line 2068
```
Depreciated notices fixed for PHP8 compatibility.
> Enter a …
> PHP8: Deprecated Notices Fixed

- adminpages/discountcodes.php
- adminpages/orders.php
There was an issue with pagination of the Orders admin page if you selected to filter by a discount code. Page 2 of the view, even if there were orders that fit the filter, would be blank. This PR resolves the error.
* BUG FIX: Fixed pagination of the Order admin page when filtering by a discount code used.
> Fixing pagination and export issues with a discount code filter on the Orders admin page.

- services/stripe-webhook.php
1. Check out using Stripe while collecting billing address.
2. Change billing address via PMPro.
3. In Stripe, find subscription, click the "update" button, and check the "Reset billing cycle" box so that it charges immediately
4. Check in PMPro that the new order has the new billing address information.
> Stripe will now pull billing address info for recurring orders from webhooks

- includes/rest-api.php
This could cause the incorrect amount to be shown in Apple Pay/Google Pay, even though the correct amount is charged.
Using `floatval()` instead of `intval()` around initial payment prices.
> Fixed issue where checkout_levels endpoint could return wrong initial payment

- services/twocheckout-ins.php
Fixes the following issues when checking out using 2Checkout:
- Discount code not affecting membership level when changed (specifically when calculating expiration date)
- Membership renewals resetting expiration date instead of extending them
Note that changes being made via the `pmpro_checkout_level` filter still ARE NOT applied during the membership level change. This specifically affects custom code which modifies the expiration date of a membership. 
Resolves #1531
1. Create a discount code with a different expiry time than the level it is discounting
2. Set gateway to 2Checkout
3. Check out for membership level using discount code
4. Verify that expiration date is set correctly.
> Fixed level change issues during 2Checkout checkout

- adminpages/license.php
The License Key field in the WordPress admin was previously a masked "password" type field, however this field was not actually masked in the page source or hashed in the database at all. Having this appear as a masked field implied it was a secure field. Additionally, we did some spot check for other plugin and license key handling to find that these fields are not commonly masked.
This should also reduce support for people who are trying to find what account is linked to their key.
> Changing license key field to text type and unmasked.

- shortcodes/pmpro_member.php
Many users have asked for a way to show a current user's avatar on the Membership Account page and in other places in their membership site.
This PR adds support for a "avatar" field type when using the [pmpro_member] shortcode. We are using the default size for an avatar display (96px square) in WordPress.
> Adding avatar as a valid field type for the [pmpro_member] shortcode.

- classes/class-pmpro-admin-activity-email.php
There was code to show the Site Title at the top of the admin activity email but it wasn't actually being echoed. I also updated the subscribe link to our YouTube channel.
* BUG FIX: Fixed issue where the Site Title wasn't displaying in the admin activity email.
> Fixed bug where blog name wasn't showing in email; updated YouTube subscribe link.

- js/pmpro-stripe.js
Stripe expects the `amount` passed to be an integer containing the number of cents (I think they call it sub-currency units or something) to show as the charge amount when a user clicks the Payment Request Button. Sometimes our API call would pass an initial payment that contains partial cents. I am using Math.Round here to ensure that the amount we pass is an integer and not a decimal.
> Now rounding amount sent with Stripe payment request button.

- includes/login.php
BUG FIX: Fixed an issue where the password reset link for some sites would not work when using the frontend Paid Memberships Pro page.
> BUG FIX: Fixed an issue on some sites where password link was incorrect.

- pages/checkout.php
Add an action to hook anything before the form. In my case I'm used to hook notices.
Examples:
- a notice when you are upgrading a plan
- a notice when you are re-activating a cancelled plan but still have some remaining days (thanks to cancel-on-next-payment addon)
- a notice when you are buying a gift level
- a notice when you are activating a gift level
- ...
> Add action pmpro_checkout_before_form
> Add action pmpro_checkout_before_form

- classes/gateways/class.pmprogateway_paypalexpress.php
Separate the temporary hack to recover a missing transaction id for PayPal Express Gateway, to have a method to call directly when the missing transaction id is needed to do debug, refund automation...
> Temporary method to getRealPaymentTransactionId

- adminpages/orders.php
> Add a space between state and zip code in billing info

- adminpages/userfields.php
- css/admin.css
[x] “Restrict Group for Membership Levels” should be a checkbox list
[x] “name” (meta key) should not allow dashes; make sure name is smart and detects whether it uses an invalid key.
[x] yes/no as dropdown vs. radio for required and readonly. default to no, have no / yes order in dropdown.
[x] remove conditional right now.
[x] hint should be a textarea vs. input text.
[x] move edit | duplicate | delete as hover on row.
[x] left align close field and maybe darker background on + add field.
[x] up / down arrows in order column; maybe have to keep the numbers reordered.
> Continued wireframes code for user fields admin page post-call notes.

- license.txt
> Bump license year 2021 (🎉 10 years!)

- adminpages/advancedsettings.php
- adminpages/discountcodes.php
- adminpages/functions.php
- adminpages/membershiplevels.php
- includes/functions.php
- includes/localization.php
- includes/profile.php
- includes/setup.sql
- includes/updates/upgrade_2_6.php
- includes/upgradecheck.php
- pages/confirmation.php
- paid-memberships-pro.php
- preheaders/checkout.php
- scheduled/crons.php
- shortcodes/pmpro_account.php
Introduces granular expiration dates to levels. You can now set an expiration period to hours. Expirations are also set on a date and time basis where memberships can expire within an hour instead of a day.
1. Create a level and set the expiration date to x hours
2. The same option is available in a discount code
3. Sign up for the level you created
4. Cancel your level
5. An expiration date will be set for x amount of hours from your current time.
> Granular Expiration Dates Introduced, allowing you to expire memberships down to the hour/minute.
> Granular expirations

- services/ipnhandler.php
Check the mc_gross values before the amount value. This is because when a recurring payment comes with a cumulative price (because of one or more previous missed payments) the amount value is the recurring amount, but the mc_gross value is the total, comprehensive of the previous missed payments. This is the real transaction price.
Check this up: [gist](https://gist.github.com/mircobabini/9a02f185e895d4e999371d179ed7ec0b)
1. You have to generate a recurring payment transaction for a cumulative amount. Or you can just trust me :)
> Fix total amount of recurring payment order from PayPal Express

- classes/class.memberorder.php
If a user wants to manually set the total for an order to $0, this cannot currently be done if there are values in the subtotal/tax fields. This is a problem in cases such as AvaTax, which will calculate the subtotal/tax fields based off of the new total field after the order save is complete.
This PR allows users to enter `0` as a total and not have that value overwritten during the save function, just like this would work for any other total amount (ie subtotal 5, tax 1, total 10 currently saves successfully, total 0 should as well).
> Allowing order total to be set to 0 regardless of subtotal/tax

- css/frontend.css
- pages/confirmation.php
- pages/invoice.php
This PR helps the plugin frontend pages to allow for better customization of how addresses are shown. In the current version, our address follows a very US-centric format. This method will instead allow CSS to modify the display of addresses, such as moving individual address pages to single lines or removing the "comma" added after the city name.  
* BUG FIX/ENHANCEMENT: Now wrapping the frontend address display with custom CSS selectors to allow for international custom address formatting.
> Adding span and class selectors when showing billing addresses so sites can customize the display.

- adminpages/membershiplevels.php
This PR adds a new hook `pmpro_membership_level_after_billing_details_settings` on the Edit Membership Level admin page. This hook should be used by Add Ons that have price-adjusting features, such as Subscription Delay, so that their settings are as close to the other payment information on the level as possible.
There was previously only one hook in place on the Edit Level settings page pmpro_membership_level_after_other_settings that many Add Ons use to add fields to the level edit page, resulting in an unknown order of additional settings in this single location.
Resolves #1574.
* ENHANCEMENT: Added `pmpro_membership_level_after_billing_details_settings` action hook after Billing Details section on Edit Membership Level admin page.
> New hook after billing details section on edit level page

- classes/class.memberorder.php
- services/ipnhandler.php
- services/stripe-webhook.php
Added MemberOrder method find_billing_address() to simplify pulling billing information from previous orders, and started using that method in PayPal IPN handler and Stripe webhook handler. This means that billing addresses will now be remembered for recurring PayPal payments.
Also fixed Stripe bug where billing name would not be pulled from Stripe charge.
> added method find_billing_address()

- classes/class.pmproemail.php
`$user->membership_level` was returning the empty string before this change, causing the `!!membership_level_name!!` and `!!membership_id!!` email variables to show up blank. This change ensures that information is filled in if the user still has the membership level associated with the invoice.
> Fixed missing membership data in billing failure email

- js/pmpro-stripe.js
Addresses issues that may cause double-charges for users who submit repeat checkout submissions too quickly.
Set up ApplePay/Google Pay and verify that it is not possible to submit multiple payments before the first is processed.
> Hide Payment Request button when form submitted

- adminpages/dashboard.php
- adminpages/orders.php
- adminpages/reports/sales.php
- adminpages/templates/orders-email.php
- adminpages/templates/orders-print.php
- classes/class-pmpro-admin-activity-email.php
- classes/class-pmpro-members-list-table.php
- includes/functions.php
- pages/billing.php
- pages/confirmation.php
- pages/invoice.php
- shortcodes/pmpro_account.php
- shortcodes/pmpro_member.php
Occasionally, sites using HTML markup in their level cost text or via the pmpro_format_price filter would not display as HTML but rather output on the screen. This PR adds a new function to escape prices using the wp_kses filter and a filter to allow additional HTML via the pmpro_escape_price filter. 
1. Add a custom gist to your site that uses pmpro_format_price and adds raw HTML to the price format. 
2. View the Memberships > Dashboard WordPress admin page and see that there is HTML output as plain text.
3. Switch to this updated code. The HTML is now rendering as expected.
* ENHANCEMENT: Added pmpro_escape_price filter to allow HTML to be used in formatting prices for display.
> New function to escape prices and allow certain html. New filter pmpro_escape_price

- services/ipnhandler.php
PayPal Express does not handle in-page credit card informations, so we can get these from the stored values. Also, this PR fills the billing values from the referred order.
Resolves #1551. Forget about the messy description there, just check the screenshot attached.
> Remove notices in debug.log (related to issue #1551)

- includes/functions.php
There is no reason to keep the args optional; they must be set. This one was:
`function pmpro_getSpecificMembershipLevelForUser( $user_id = null, $level_id ) `
then changed to null/null in PR #1572 because of deprecation in PHP8.0.
Btw, doesn't make sense to keep them optional.
> Change optional args to mandatory in pmpro_getSpecificMembershipLevelForUser

- classes/gateways/class.pmprogateway_paypalexpress.php
When something goes wrong with PayPal Express, the subscribe() method returns an error, but the user will stay on that page. URL is something like /checkout/?level=1&review=X&token=EC-Y&PayerID=Z. If the user hits F5, the order (which status already changed to review or error) got set to review once again. So we just lose the progress information and since a level agreement is already set for that order, we are unable to restore it but manually. This PR is to avoid double processing the same review request.
1. Force an order to give error during subscribe()
2. Try to reload the error page
3. See the error (A successful Billing Agreement has already been created for this token) and check the order status (review).
Avoid PayPal double processing of the same review request.
> PayPal Express: avoid double processing of the same review request

- pages/confirmation.php
- pages/invoice.php
These was a lingering <small> HTML tag wrapping the $0.00 amounts on invoices and confirmation page. This was an unnecessary design element and I have removed it.
1. Check out for a free level
2. View the invoice from your Membership Account page
3. Pricing should appear just the same as other values.
> Removing the small HTML wrapper for $0.00. It isn't needed.

- .gitignore
- includes/login.php
Change escape function from `esc_html` to `esc_html__` to make text strings localized in `/includes/login.php`.
1. "Log In" string displayed in widget is now translatable.
2. "Reset Password" heading is now translatable on pages with `[pmpro_login]` shortcode that is not the assigned default Log In page in options.
3. "Password Reset" heading is now translatable on pages with `[pmpro_login]` shortcode that is not the assigned default Log In page in options
Resolves [1604](https://github.com/strangerstudios/paid-memberships-pro/issues/1604).
1. Go to Appearance > Themes and set active theme as Memberlite.
2. Go to Appearance > Widgets and add the "Log In - PMPro" widget to the "Post and Arches", "Pages", and "Footer Widgets" localtions
3. Go to Pages > Add New and create a page containing …
> Improve localization for some strings - fixes 1604

- includes/content.php
BUG FIX: Fixed an issue when trying to add `pmpro-level-` to a post when the level no longer exists or was NULL.
Screenshot reference:
I am unable to figure out exact steps to recreate this error.
> BUG FIX: Sometimes post's level is missing when adding class to post.

- adminpages/orders.php
- classes/class.memberorder.php
We no longer have to wait until after the order is saved to call `$order->updateTimestamp()` on our `/adminpages/orders.php` page. Instead, the timestamp is now saved on `$order->saveOrder()` as expected.
> No longer calling $order->updateTimestamp() on orders adminpage

- js/pmpro-admin.js
Fixed deprecated jQuery functions in `pmpro-admin.js`.
Note: Similar changes may have to be made in other core PMPro files and in Add Ons.
1. Install the "Enable jQuery Migrate Helper" plugin: https://wordpress.org/plugins/enable-jquery-migrate-helper/
2. Ensure all of the checkboxes in `Tools > jQuery Migrate` are checked
3. See that deprecation warnings from `pmpro-admin.js` are shown on PMPro admin pages are shown before changes, but not after
> Fixed deprecated jQuery functions in pmpro-admin.js

- pages/confirmation.php
- pages/invoice.php
When we updated to pull billing information from user meta, the billing address shown on the Invoice was not displaying because the conditional relies on the "Billing Name" field. This update will instead have the Billing Address shown on Confirmation and Invoice pages based on whether the Billing Street field is present.
> Updating conditional for Billing Address on Invoice and Confirmation page

- classes/gateways/class.pmprogateway_stripe.php
Check out for a level with a recurring subscription and make sure the subscription is still created.
> REFACTOR: Now using the create_subscription() method whenever creating a subscription to avoid redundant code.
> Use create_subscription() when creating a subscription

- adminpages/advancedsettings.php
- adminpages/discountcodes.php
- adminpages/orders.php
- adminpages/reports/login.php
- adminpages/reports/memberships.php
- adminpages/reports/sales.php
- includes/content.php
- includes/functions.php
- includes/metaboxes.php
- pages/levels.php
- paid-memberships-pro.php
- preheaders/levels.php
New function `pmpro_get_ordered_levels` to reorder any retrieved array of levels (objects or IDs) based on the sorted option; updates to use this where level are listed.
Resolves https://github.com/strangerstudios/paid-memberships-pro/issues/1122.
* BUG FIX/ENHANCEMENT: Now ordering all places we display a list of level or level names according to the admin-sorted level order.
> New function pmpro_get_ordered_levels

- includes/login.php
If we can't get a permalink to redirect to, don't override the url on the filter.
Resolves #1519
1. Delete the login page.
2. When not logged in, load /wp-admin/
3. Does it loop redirect?
> Avoid a redirect loop if login page is deleted.

- includes/functions.php
resolves #1628
To use this action, you would:
1. Hook into `pmpro_after_all_membesrhip_level_changes`
2. Loop through `$pmpro_old_user_levels` array arg passed into function, and for each user:
3. -- Get their old levels from the `$pmpro_old_user_levels` array. Use this to determine what courses/audiences/etc they were subscribed to (`$unsubscribes`)
4. -- Get their current levels by calling `pmpro_getMembershipLevelsForUser()`. Use this to determine what courses/audiences/etc they should now be subscribed to (`$subscribes`)
5. -- `array_unique()` both `$subscribes` and `$unsubscribes`
5. -- Subscribe users to all courses/audiences/etc in `array_diff( $subscribes, $unsubscribes )`
6. -- Optionally remove users from all courses/audiences/etc in `array_diff( $unsubscribes, $subscribes )`
> …
> Added pmpro_after_all_membesrhip_level_changes

- includes/login.php
Fixed password reset link in new user notification email when using plain permalinks. Also removed duplicate function.
> Fixed pw reset link in new user notification email for plain permalinks

- includes/functions.php
Account for `$include_active` in `pmpro_getMembershipLevelsForUser()` cache.
resolves #984 
> accounting for $include_active in level cache

- adminpages/orders.php
Change the existing "username" column on the orders list table to "user". In each row, show the user's display name and email address.
Resolves #1516 .
View orders page.
> Username column on orders page is now User, shows email

- includes/content.php
Do not pass associative array `$pmpro_pages` into query parameter `post__not_in`. Instead, just pass the page IDs.
Resolves #1634 .
> Fixed query parameter in pmpro_search_filter

- adminpages/reports/sales.php
- Fixes bug where months with 31 days may not show data on daily sales report depending on SQL settings
- Shows orders reports based on local time instead of GMT.
Resolves #1611.
> Sales report fixes

- adminpages/orders.php
- css/frontend.css
- includes/functions.php
- Moved the email address added to the Orders admin screen outside the hyperlink to the Edit User screen
- Adjusted and added new CSS selector for a new `pmpro_price_part_sub` where the price part item should be displayed as a nested/depth 2 appearance.
- Adjusted the `pmpro_get_price_parts` function to sanitize the part's 'key' before using in the generated CSS selector so it would be valid CSS.
> Orders user email outside hyperlink; adjustments to price parts for sanitization and frontend styling

- includes/functions.php
BUG FIX: Fixed issue where the default_level was calling min() on an empty variable. Improve the logic.
> BUG FIX: Fixed warning when all_levels were empty

- adminpages/reports/sales.php
Fixed issue where "All Time Sales" would always be 0
Go to the reports page and see that all time sales is 0 before this fix, and has the correct numbers after.
> Fixed issue where "All Time Sales" would always be 0

- includes/functions.php
Before this fix, we were resetting the array keys in the array passed out of this function. And so on the level page, we would set the $pmpro_levels global var to use the ordered (and re-keyed) array. This caused issues later when the pmpro_getLevel() function expected the $pmpro_levels array to have keys corresponding to the level ids. $pmpro_levels[1] may or may not be level 1.
We thought about changing the $pmpro_getLevel function to not have that expectation, but that's a bigger change and it is useful to have the level arrays keyed this way. It's worth trying to maintain IMO.
For now, this one commit should fix the issues that have come up since the introduction of the pmpro_sort_levels_by_order() function.
> Sets keys in the array returned from pmpro_sort_levels_by_order() to correspond to the level ids. Some code expects that for level arrays.

- services/getfile.php
Fixes #1670
Prevents "File not found." errors from showing by removing query parameters from the URI path used for the `file_exists()` call.
1. Lock down files by [enabling getfile.php](https://www.paidmembershipspro.com/locking-down-protecting-files-with-pmpro/)
2. Be logged into a member that should have access
3. Take a file URL and add a query string to it `some-file.zip?from=account-area`
4. File should be served like normal, you should NOT see a "File not found." error
> Prevent "File not found" errors when delivering files through `getfile.php` by removing query parameters from the file URI path.
> Remove query string from URI path to prevent "File not found" errors

- js/pmpro-login.js
BUG FIX: Use wp.passwordStrength.userInputDisallowedList() instead of deprecated wp.passwordStrength.userInputBlacklist() function.
This has been deprecated since WordPress 5.5.0
> BUG FIX: Adjusted deprecated function

- classes/gateways/class.pmprogateway_authorizenet.php
- classes/gateways/class.pmprogateway_braintree.php
- classes/gateways/class.pmprogateway_cybersource.php
- classes/gateways/class.pmprogateway_paypal.php
- classes/gateways/class.pmprogateway_paypalexpress.php
- classes/gateways/class.pmprogateway_paypalstandard.php
- classes/gateways/class.pmprogateway_stripe.php
- classes/gateways/class.pmprogateway_twocheckout.php
- css/admin.css
Hide with ******* the PayPal's gateways configuration passwords. Still recoverable using inspection of course.
Resolves #268.
1. The only one still untouched is the `cybersource_securitykey` which is a textarea. [Can be hidden using javascript](https://stackoverflow.com/questions/16058008/is-there-a-known-way-to-have-a-textarea-with-the-password-type).
1. We DON'T want to encrypt the fields, just use asterisks to hide values.
> Ideally we would do this to the API key fields for other gateways at the same time.
> 
> I also think it would be good to add an eye icon to reveal the API key, similar to what WP does on the default login page now.
> 
> I also wonder if we should set an attribute autocomplete="one-time-code" in the input to keep browsers from trying to save or restore these …
> Hide gateways passwords behind asterisks

- includes/deprecated.php
The deprecated`pmpro_getClassForField` function was missing the return statement. As a result, the classes were not added to the fields.
Resolves missing inputs classes in checkout form when **Paid Memberships Pro: Multiple Memberships per User** addon is used.
1. Activate **Paid Memberships Pro: Multiple Memberships per User** addon
2. Go to the checkout page
3. All required fields have the `pmpro_required` class
BUG FIX: Missing return statement in `pmpro_getClassForField` function.
> BUG: Missing return statement in deprecated function

- includes/content.php
BUG FIX: Fix a warning when $pmpro_pages not set at all and searches occur. Check if $pmpro_pages is array.
> BUG FIX: FIx warning in searches/pages when PMPro pages is not set.

- includes/compatibility/divi.php
Resolves #1658. Fixes the if statements that are supposed to check if `$modules['et_pb_row']` and `$modules['et_pb_section']` exist and are objects.
1. Use Divi theme.
2. Use PHP 8.
3. Open the Divi visual builder on a page.
4. Check your site's PHP error log to ensure there are no PHP warnings generated.
> Fixed PHP warnings being generated when using Divi and PHP 8.
> Fix warnings being generated when using PHP 8 and Divi

- preheaders/checkout.php
Useful to un-hook some security filters added by third party plugins to the 'authenticate' filter, which can break the atomic pmpro checkout process ending up with users not associated to orders and with no membership activated.
> Add a new action during checkout process, just before user auth

- services/applydiscountcode.php
Fix to applydiscountcode.php where javascript is written by php and not always escaped with _pmpro_no_quotes_. This where causing issues with i18n as reported in the issue below.
Resolves #1662.
1. Check the linked issue which contains the explanation.
> i18n apply discount code

- classes/class.memberorder.php
I was debugging on the order status flow in case of issues with PayPal Express. After a while, I was able to recall that the status can change even when the `MemberOrder::saveOrder()` method is not called, because of `updateStatus`. This PR adds the update/updated actions every time runs an update query on `$wpdb->pmpro_membership_orders`.
⚠️ Also noticed there is a useless updateStatus [here](https://github.com/strangerstudios/paid-memberships-pro/blob/d0a252dfa967dca080f95cedacb1982410ff6847/classes/class.memberorder.php#L940) because it's already done by the early query above, to avoid race conditions.
⚠️ Last but not least, [this note](https://github.com/strangerstudios/paid-memberships-pro/blob/d0a252dfa967dca080f95cedacb1982410ff6847/classes/class.memberorder.php#L957) should be …
> Always fire pmpro_update_order/pmpro_updated_order

- services/applydiscountcode.php
This finishes the work from #1663 and makes sure the contents (that can be filtered) are proper and clean for the usage we intend.
1. Have a discount code for a level
2. Go to checkout for that level
3. Apply the discount code
4. Look at text next to level at the top of page
5. Ensure it's bolding correctly and not showing HTML
> Improve the output when applying discount codes in checkout so that it prevents accidental JS breakage.
> Improve escaping for Apply Discount Code JS

- classes/gateways/class.pmprogateway_payflowpro.php
This brings full compatibility/compliance with Card on File requirements for recurring transactions.
Fixes #1674 
1. Check out with a new recurring membership
2. All communication to Payflow should include `CARDONFILE=CITR`
3. All subsequent communication to Payflow to modify the profile should include `CARDONFILE=MITR`
> Add compatibility with new Payflow Pro compliance requirements for `CARDONFILE` parameter for recurring payments on memberships.
> Add CARDONFILE compatibility for Payflow Pro gateway

- classes/gateways/class.pmprogateway_paypalexpress.php
This one is the last of a series. There are three commits included:
1. Handle missing PROFILESTATUS, save the orders status=error and stop the review process.
2. Don't set status=error when just an API issue is detected.
3. Stop the review process when an API issue is detected during Gateway->subscribe().
Resolves #1590.
PayPal must send you back to the site as it was a success, but with no PROFILESTATUS when doing ->subscribe(). I've still found no way to replicate the issue, but I'm testing it on a live website on which occurs 20-30 times in a day. It's working.
> Handle missing PROFILESTATUS and fix api error handling

- classes/gateways/class.pmprogateway_stripe.php
- Have separate connection buttons for live and sandbox modes of Stripe connect
- Fixed bugs where correct keys would not be used when using connect in live mode
> Stripe connect now handles live and sandbox separately.

- adminpages/discountcodes.php
Found a missing i18n on a string, hard to spot because it's in a title tag attribute.
> Add i18n to a string provided to sprintf

- includes/login.php
- preheaders/account.php
Data Erasure and Data Export requests were not properly being submitted nor showing a message to the user that the request was confirmed, even though the requests were successfully being processed in some cases. The action should have been added to the login page so that both logged out and logged in users could complete requests.
1. Submit a user's email on the Tools > Erase Personal Data.
2. Check your email for the confirmation link
3. Click the link. You should be taken to the login page with the confirmation message shown.
I have tested this both when logged in to the account requests the erasure/export as well as for a logged out user.
* BUG FIX: Resolved issue with Data Erasure and Data Export requests to show correct message to user on login page.
> Enter a summary of all changes …
> Fixing data erasure and data export request action for login page.

- classes/gateways/class.pmprogateway_stripe.php
Now archiving Stripe products after checkout.
Note: This solution is a half-measure. Ideally, we would have one product in Stripe per membership level and just create a new price for checkouts if necessary. This "archiving" solution will still create a stripe product for each checkout, but at least they will be under the archived tab. Products cannot be deleted once they have been used, which is why we are only archiving.
1. Check out for recurring level with Stripe
2. Check that Product in Stripe is archived.
> Now archiving Stripe products after checkout.

- includes/email.php
In cases where a PMPro Email is being sent to an email address that is not associated with a WP User (for example if a gift membership is being purchased and automatically sent to a recipient), PHP warnings would be thrown as `$user` would not be populated.
This PR adds checks to ensure that a `$user` exists before working with user data. Also updates some text domains.
> Fixed warnings if recipient of email does not exist as a user

- adminpages/reports/login.php
[x] Have you followed the [Contributing guideline](https://github.com/strangerstudios/paid-memberships-pro/blob/master/.github/CONTRIBUTING.md)?
[x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
[x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?
Set cookie `pmpro_visit` as HttpOnly and secure if possible.
Resolve warning about:
> Cookie “pmpro_visit” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite …
> Set `pmpro_visit` cookie http only and secure, if available

- classes/gateways/class.pmprogateway_stripe.php
Return `false` or `array()` when there is an error getting or creating Apple Pay domains with Stripe so that `empty()` checks work as expected.
> Better returns when there is an error getting or creating apple pay domain

- classes/class.pmproemail.php
- includes/email-templates.php
- includes/email.php
Fixed issue where admin_change email could have double periods in the `!!membership_change!!` variable. We had workarounds for this built into PMPro Email Templates, but they were no longer working so we are now just doing it the right way.
> Fixed issue where admin_change email could have double periods

- includes/notifications.php
Small update to the allowed HTML in our notifications to allow <strike> tag for crossout pricing when we run a promotion banner.
> Allow strike in notifications we push to the dashboard.

- includes/deprecated.php
The deprecation for Email Templates Admin Editor needs to include the case if a user installed via WP.org (the folder name is different in this one - odd, old issue we don't have to worry about anymore!).
1. Use the .org version and/or change the folder name to 'pmpro-email-templates-addon'.
2. Go to the dashboard.
3. The email templates admin editor Add On should deactivate and the word "Email Templates" should be included in the notice on dashboard pages.
> Also checking for the .org version of Email Templates Admin Editor in deprecation script.

- adminpages/advancedsettings.php
- css/admin.css
- includes/profile.php
Scrollbars across newer browser can be disabled. When this is the case, elements that we set a fixed height on aren't obviously scrollable. This CSS class pmpro_scrollable forces the display of a scrollbar so that the user knows the element has more contents.
> Establishing style for scrollable boxes throughout core plugin.

- shortcodes/pmpro_account.php
The original granular expirations work was showing expiration time as the default. In our discussions, we decided that fewer sites will be offering hourly membership so defaulting to NOT show expiration time makes more sense.
[Here is an example of using the `pmpro_show_time_on_expiration_date` filter](https://gist.github.com/kimcoleman/0f9528f9871c733a43f44e998f61a49b).
> Adjusting default for expiration time filter to false; using the site time format to format the expiration time if applicable.

- includes/rest-api.php
Enhancement: Remove 'couponamount' from REST API response for Zapier.
> Remove 'couponamount' from REST API response

- readme.txt
This is a text-only update to the readme for WordPress.org. Updates include:
- Mentioned REST API + Native Zapier
- Added Course / LMS features to highlight as a use case + the Add On
- Updated link for email template editing as this is now a core feature
- Mentioned Member History
- Added note on expiration periods available, including hourly as a 2.6+ feature.
- Adjusted Sitewide Sales link to that website (not our Add On version that is replaced by this more fully featured standalone plugin).
> Updating readme to include some 2.6+ features and other things not mentioned that are awesome.

- includes/functions.php
Resolves #1731.
1. Have a currency set that uses 0 decimals
2. Attempt to round price
3. See the rounded price has decimals still set
> Fix problem where `pmpro_round_price()` would not take into account currencies with decimals set to 0.
> Replace !empty() check with isset() for decimal option

- includes/email.php
In PHP 8 this change was made:
> Attempting to write to a property of a non-object. Previously this implicitly created an stdClass object for null, false and empty strings.
https://www.php.net/manual/en/migration80.incompatible.php
Because of this, `pmpro_email_templates_email_data` is currently throwing fatal errors whenever the calls to [`get_user_by`](https://developer.wordpress.org/reference/functions/get_user_by/) within the function return `false`, because the attempt to set `$user->membership_level` will fail. And this has been happening to me on one of my sites recently, every time the admin activity email is supposed to be sent. (Because of the fatal error, it never actually gets sent.)
```
[16-Aug-2021 10:30:03 UTC] PHP Warning:  Attempt to read property "ID" on bool in …
```
> Fix PHP 8 fatal error that could occur in pmpro_email_templates_email_data

- includes/email.php
- includes/functions.php
Since we added email templates as default feature for PMPro, I think autoload templates is not necessary.
We need a little change for `pmpro_setOption` function to achieve this.
Do not autoload all email templates by default on every request to WordPress.
> Do not autoload email templates since we added that feature as default

- includes/content.php
Resolve PHP Warning:
`PHP Warning:  Attempt to read property "ID" on null in .../wp-content/plugins/paid-memberships-pro/includes/content.php on line 398`
Actually, this var is unused in this function so can be safely removed.
This PHP Warning shows up by requesting non-post pages like `http://xxx.com/tag/<tag>/comments/feed/`.
Remove PHP Warning on non-post pages.
Also remove some unused/duplicate PHP code.
> Remove unused variable which generates PHP Warning

- adminpages/dashboard.php
The Dashboard setup steps should include a link to the new email templates editing page in the admin.
1. Navigate to Memberships > Dashboard
2. See the new link under "Other Settings" in the main box.
3. That link should take you to the Email Templates admin screen.
> Added Email Templates as a link on dashboard for getting started.

- classes/gateways/class.pmprogateway_stripe.php
If legacy keys are being used with Stripe, show that the site is connected to Stripe using legacy keys instead of showing that the site is not connected at all. This was causing confusion with users thinking that the Stripe integration was no longer working when using legacy keys.
> Update Stripe connected status to consider legacy keys

- CHANGELOG.txt
- includes/scripts.php
- paid-memberships-pro.php
- readme.txt
Resolves #1723.
1. Load any admin page that isn't ours
2. Confirm our admin script/css is not loaded
3. Load any admin page that is ours
4. Confirm our admin script/css is loaded
> Ensure our admin scripts/styles only load on PMPro admin pages
> Ensure our admin scripts/styles only load on our pages

- adminpages/discountcodes.php
- adminpages/membershiplevels.php
- adminpages/orders.php
1. Enhance code readability of extra row actions for orders
2. Add a filter for extra row actions on discountcodes and membershiplevels
> Abstract admin actions and make them filterable for Discount Codes, Membership Levels, and Orders

- includes/addons.php
Condition is always 'true' because 'empty( $addon['License'] ) || $addon['License'] == 'wordpress.org'' is already 'false' at this point (see **line 117**).
Remove unused condition check.
> Remove check for condition which always 'true' because of prev check

- classes/class-pmpro-members-list-table.php
Make the Username the first column in the members list. This ensures that the Members List view on mobile will still populate even if the ID column is being hidden.
Resolves #1751
> Made username the first column in the members list

- adminpages/advancedsettings.php
- css/admin.css
Update to set a standard for clickable labeled elements in a list of (sometimes) fixed height clickable checkbox lists.
* ENHANCEMENT: Improved admin UI for checkbox lists.
> Updating css for clickable labels in checkbox boxes; building selectors array 

- adminpages/orders.php
Avoid the highlighted trailing space:
> Admin page: orders.php > Remove trailing space

- adminpages/discountcodes.php
Use already assigned variables instead of $_REQUEST direct access. It's safer and easier to maintain.
> Don't access $_REQUEST for already parsed params

- adminpages/admin_header.php
- adminpages/discountcodes.php
- adminpages/membershiplevels.php
- adminpages/orders.php
- adminpages/reports/login.php
- includes/adminpages.php
- preheaders/checkout.php
Use `admin_url(...)`, which is the `get_admin_url(null,...)` shortcut.
> Use admin_url(...) instead of get_admin_url(null,...)

- preheaders/checkout.php
ENHANCEMENT: Pass through billing data to pmpro_replaceUserMeta function that was captured during checkout. This prevents the checkout from trying to process non-existing data.
This also fixes an issue where Paid Memberships Pro - WooCommerce Integration tries to sync data between WooCommerce and Paid Memberships Pro (Register Helper).
> ENHANCEMENT: Only update user meta that is passed through.

- classes/gateways/class.pmprogateway_stripe.php
There are still some unknown issues with using Stripe Connect. So in the meantime, we'd like to make it easier to access the legacy Stripe API settings if needed.
1. Go to the payment settings tab.
2. Choose Stripe as the gateway.
3. Click the link to show the legacy API settings.
4. You should notice the settings. They should remain on the page if/when you change gateways/environments.
5. If you are using the pmpro_stripe_show_legacy_keys_settings filter set to true to always show keys, you will always see the keys and no message.
Technically the link in the message should be a button instead of an a tag. I didn't know how to style it to look like a link. I'm okay to push this and fix later either with our entire gateway settings overhaul or a quick PR for just that 1 accessibility …
> Add link to show Stripe legacy API settings.

- services/stripe-webhook.php
Fixed issue where secret key would not be set correctly in Stripe webhook while in Sandbox mode.
> Fixed retrieving sandbox secretkey in Stripe webhook

- shortcodes/pmpro_account.php
Fixes issue where custom code that filter on `pmpro_account_membership_expiration_text` may have an undesired dash before the intended content. For example, this tooltip will show a dash before the user's renewal date: https://www.paidmembershipspro.com/display-a-membership-renewal-date-to-your-recurring-members/
> Prevent echoing dash early on account page expiration field

- classes/gateways/class.pmprogateway_stripe.php
Deprecating Stripe Subscription Updates in favor of having users update the subscription directly in Stripe.
This will end up simplifying the Stripe class code by offloading this functionality to Stripe, and give users a more intuitive way to modify existing subscriptions.
Will probably want a UI PR to make this look better, but this is the core functionality.
> Deprecate Stripe subscription updates

- classes/gateways/class.pmprogateway_stripe.php
Broke up else ifs in Stripe getCustomer() method to avoid edge cases.
> Broke up elseifs in Stripe getCustomer method

- services/stripe-webhook.php
Removed assumptions that subscription_transaction_id can be a customer_id from Stripe (this was changed years ago) and deprecated some functions that are never used.
> Remove deprecated customer logic from Stripe webhook.

- classes/class-pmpro-site-health.php
This addition to Site Health follows #1827 and is set up to just make it easy to merge both without conflicts. 
* Add helpful information about certain PMPro constants and their values if they are manually set
1. Set `PMPRO_DEFAULT_LEVEL` or any of the supported constants
2. Look in Tools > Site Health > Info > Paid Memberships Pro
3. See constant shows up now and includes the value it's set to
`define( 'PMPRO_DEFAULT_LEVEL', 123 );`
```
pmpro-constants-PMPRO_CRON_LIMIT: 'testing'
pmpro-constants-PMPRO_DEFAULT_LEVEL: 'testing'
pmpro-constants-PMPRO_USE_SESSIONS: false
pmpro-constants-PMPRO_STRIPE_WEBHOOK_DELAY: 'testing'
pmpro-constants-PMPRO_STRIPE_WEBHOOK_DEBUG: 'testing'
```
> Add helpful information about certain PMPro constants and their values if they are manually set
> Add Constant Info to Site Health

- includes/functions.php
- services/stripe-webhook.php
Added function pmpro_send_200_http_response(). Useful to avoid issues like timeouts from gateways during webhook/IPN handlers. Works with Apache and Nginx.
The following code will disable this functionality:
`add_filter( 'pmpro_send_200_http_response', '__return_false' );`
> Added function pmpro_send_200_http_response()

- readme.txt
Just a simple PR to set the required PHP version in readme.txt so that WordPress.org and plugin installs/updates can be aware of the version requirement.
> Update minimum PHP version in readme.txt so that it's exposed to WordPress.org

- preheaders/checkout.php
When someone is setting an expiration date in hours expiration_period is what needs to be checked to calculate the end time correctly, otherwise, hours have been defaulting to 23:59.
Resolves XXX.
1.
2.
3.
FIX: Calculate correct end date in minutes and hours when using HOURS.
> Change Hours check on expiration_time, not cycle_period

- classes/gateways/class.pmprogateway.php
- classes/gateways/class.pmprogateway_authorizenet.php
- classes/gateways/class.pmprogateway_braintree.php
- classes/gateways/class.pmprogateway_check.php
- classes/gateways/class.pmprogateway_cybersource.php
- classes/gateways/class.pmprogateway_payflowpro.php
- classes/gateways/class.pmprogateway_paypal.php
- classes/gateways/class.pmprogateway_paypalexpress.php
- classes/gateways/class.pmprogateway_stripe.php
- includes/functions.php
Now including time when calculating profile start date. This should help to ensure that user's recurring payments are charged around the same time that the checkout occurred on the site.
> Now including time when calculating profile start date.

- classes/class-pmpro-site-health.php
* Adds .htaccess checks to Site Health for getfile.php and presence of Expires cache rules
* Also improves Custom Templates check in Site Health to show path as well as support checking parent vs child theme
1. Add getfile.php rule(s) to your .htaccess (see below)
2. Add Expires cache rules (see below)
3. Go to Tools > Site Health and look at the Paid Memberships Pro section
4. See the usage detection as expected (with presence of or absence of the rules)
```
RewriteRule ^wp-content/uploads/(.*)$ /wp-content/plugins/paid-memberships-pro/services/getfile.php [L]
RewriteRule ^wp-content/test/(.*)$ /wp-content/plugins/paid-memberships-pro/services/getfile.php [L]
```
```
<IfModule mod_expires.c>
ExpiresActive On
ExpiresByType image/jpg "access plus 1 year"
ExpiresByType image/jpeg "access …
```
> Add .htaccess checks to Site Health

- classes/gateways/class.pmprogateway_stripe.php
Allow users to view and delete upcoming Stripe subscription updates for users so that there are not any surprises when the update occurs. Eventually, this UI should be deleted once subscription updates are entirely removed.
User profiles also now link to the Stripe Customer instead of to an individual subscription.
> Allow users to view and delete existing subscription updates for users.

- includes/scripts.php
In a previous update we added a check to only load admin.css on "PMPro admin pages". This caused an issue because we also need to load that CSS on the edit user/profile page. In reality, we potentially will use the styles in admin.css on any number of admin pages. I'd rather our design team only have to manage the one admin.css file for all admin styles.
If there are conflicts from loading these styles on an admin page, we should update our CSS code to better target it instead of unloading the CSS.
One minor issue that is still present is that the dashicon we add to the Memberships menu in the admin bar is not showing up when viewed from a frontend page. We can fix this later by inserting that specific CSS into the admin bar code via filter.
> We need to load admin.css on all admin pages.

- includes/compatibility.php
- includes/compatibility/wp-com.php
Ensure that WordPress.com Jetpack SSO continues to work as expected when using a custom login page in PMPro.
Prerequisite: PMPro site must have a Custom Login page set in PMPro.
1. Log into wordpress.com
2. Go to any dashboard for a site with PMPro
3. Click on Memberships menu or go to any submenu item
4. See the expected page, you should NOT be redirected only to be stopped at the login form to log in again
> Add compatibility with WordPress.com for the Jetpack Single Sign On auto-login feature when using a Custom Login page in Paid Memberships Pro
> Add WP.com compatibiltiy for Jetpack SSO

- includes/functions.php
Ensuring that we have a server protocol in `pmpro_send_200_http_response()`. Should resolve issues where the following error may be shown during the Stripe webhook:
`malformed header from script 'php73.cgi': Bad header: 200 OK`
> Ensuring that we have a server protocol

- includes/functions.php
Super useful to get all the membership/level order metas, when not passing the $key param.
> get_metadata wrappers need $key param to be optional

- classes/gateways/class.pmprogateway_paypalexpress.php
This one allows performing actions on order status = token, just before sending the user to the gateway to complete the payment.
Expecially useful to save pmpro_signup_username / pmpro_signup_password / pmpro_signup_email into order metas, to be used when trying to recover checkout failure if the browser session is lost, as reported #1338.
To be combined with this snippet: https://gist.github.com/mircobabini/bf9b65010124e4ab1e04c0c634681364
> Add new action pmpro_before_commit_express_checkout

- services/authnet-silent-post.php
- services/braintree-webhook.php
- services/ipnhandler.php
- services/stripe-webhook.php
- services/twocheckout-ins.php
As reported by Victor Garcia, our webhook handlers were not properly escaping content that was output to the browser or emailed to the admin when the webhook debug log options were being used.
While tricky to do, motivated actors could generate post requests to the webhook handlers that would output HTML or JavaScript to the webhook handler URL to either spoof content on your site or further attack the site through cross site scripting.
This PR escapes all output and email content in the webhook handlers.
> Escaping output and email content in our webhook handlers.

- includes/functions.php
Added option to have old entries for a membership level deactivated when that level is changed to. This behavior is currently defaulted to off, but can be enabled using the `pmpro_remove_duplicate_membership_entries` filter. We may want to consider having this enabled be the default behavior.
This is useful in cases where users have multiple active memberships for a particular membership level. Typically, this should not happen, however there are edge cases (such as with WooCommerce Add On and potentially membership imports) where it could.
> Add option to remove duplicate levels after memberhsip level change.

- classes/gateways/class.pmprogateway_stripe.php
Fixed issue where profile start date sent to Stripe could be off by a day.
1. Set timezone to Paris
2. Check out for yearly recurring membership
3. Pre-patch, the trial would have an extra day. Post patch, the recurring payment will be charged exactly 1 year from checkout.
> Fixed Stripe profile date off by one issue

- includes/functions.php
Changing the default for the `pmpro_send_200_http_response` filter to `false`.
This change is in response to the `pmpro_send_200_http_response` causing issues on some setups while processing Stripe webhooks, which results in more support than before this functionality was originally implemented.
Once merged, the `pmpro_send_200_http_response` behavior can be enabled by adding the following line of code to your site:
`add_filter( 'pmpro_send_200_http_response', '__return_true' );`
> Changing default for pmpro_send_200_http_response to false

- classes/gateways/class.pmprogateway_paypal.php
1. Remove the `SHIPTOPHONENUM` parameter so that the update does not error out when we don't pass the rest of the user's shipping information
2. URL encode parameters that are passed in the update method
> Fixing update function for PayPal Website Payments

- includes/rest-api.php
We're currently referencing $discount_code->end when it should reference $discount_code->expires for the expiration date. 
Sample of existing POST request to create a discount code: 
After the changes have been made: 
Fixed a bug where the discount code expiration date wasn't being used in the REST API.
> Expiration date invalid on Discount Code REST API Endpoint

- services/ipnhandler.php
Uses the correct cancel method when trying to cancel from ipn using PayPal Standard.
Without this fix, PayPal Standard cancellation from IPN are incompatible with "Paid Memberships Pro - Cancel on Next Payment Date" addon, because using pmpro_changeMembershipLevel without the fourth param (`$cancel_level`) we dont know which level we should keep. Also, it may be incompatible with other addons because of the lack of that param.
1. Create a fresh install of pmpro + cancel on next payment addon
1. Import an order status = success
1. Simulate a cancellation request from paypal standard ipn
Without this fix, the membership is immediately cancelled. With this fix, it works as expected.
> PayPal Standard: Use correct cancel method when cancelling an order

- classes/class-pmpro-members-list-table.php
The `members_page-pmpro-memberslist` page name seems to get partially transport. 
This means that the screen name becomes `membresia_page_pmpro-memberslist` when changing to Spanish. 
As a band-aid, we're checking for the last part of the screen name now. 
Relates to #1876 
1. Steps on how to recreate this can be found in #1876 
2. Add the code recipe https://www.paidmembershipspro.com/add-custom-column-members-list-users-admin-pages/
3. Change site language to anything except English
4. The column will disappear after changing languages
Fixes around the `pmpro_manage_memberslist_columns` filter to accommodate sites that aren't in English
> Current screen name gets partially translated

- adminpages/pagesettings.php
1. Correct `post_type` argument for all instances where `wp_dropdown_pages` are used.
2. New filter hook `pmpro_admin_pagesetting_post_type` that supersedes old `pmpro_admin_pagesetting_post_type_array` hook with some backward compatibility.
This filter allows setting which post type should be used for PMPro pages.
Resolves [#1865.](https://github.com/strangerstudios/paid-memberships-pro/issues/1865)
1. Create an hierarchical Custom Post Type, e.g. `movie`
2. Add customization code that hooks into the filter setting this CPT to be used for PMPro pages 
```php
function my_pmpro_pages_custom_post_type( $post_type ) {
$post_type = 'movie';
return $post_type;
}
add_filter( 'pmpro_admin_pagesetting_post_type', 'my_pmpro_pages_custom_post_type' );
```
3. Go to Memberships > Settings > Pages
4. …
> Pagesetting post type

- adminpages/orders.php
The Edit Order screen has labels for each field row. Probably someone ran a linter that pushed the " :</label>" to a new line, creating a "space" in the view between the text of the label and the colon.
> Fixing line breaks that created a space between the order field edit label and colon.

- .github/ISSUE_TEMPLATE/support.md
- README.md
- adminpages/dashboard.php
- adminpages/license.php
We offer a few paid plans, and the language throughout the core plugin only references "Plus". There is more work to do here, but these are a few places that needed to be updated to speak about plans in general vs. specifically Plus.
* Enhancement: Generalized language about support license / membership options throughout the admin.
> Beginning to remove the term "Plus" from the core plugin and use more general language about plans.

- includes/content.php
Resolves issues with creating excerpts from Elementor Pro content when that post/page is protected.
I've had trouble reproducing this issue but was able to test the fix against a working example from Kim here https://clean.pixeltalk.xyz/2021/06/14/community-blend/ (note: with the fix, it no longer shows style output)
> Ensure styles are removed from excerpts generated for protected content
> Use wp_strip_all_tags to remove contents of script/style tags

- services/ipnhandler.php
Until now, when an order has no user (pretty common for errored subscriptions from PayPal Express even when the flows complete), we were not changing the order status. That's bad for reports and order's list readability.
1. Ask @mircobabini
> PayPal Express IPN: set cancelled/error even when a membership has no user

- classes/class-pmpro-site-health.php
The levels information we add to the Site Health screen wasn't including hidden levels. This update to add a second 'true' parameter for the pmpro_getAllLevels function that calls levels fixes this.
BUG FIX: Now including all levels (public and hidden) in the Paid Memberships Pro section of Site Health information. 
> Update to force Site Health to report on all levels, including hidden.

- includes/rest-api.php
ENHANCEMENT: Add more membership statuses to trigger on when polling for membership information. This is useful for Zapier Application to trigger on more than just active accounts. This will help with cancelled and expired level changes too.
> Change status to receive new membership information

- services/authnet-silent-post.php
The error that this fixes:
```
Uncaught Error: Attempt to assign property "name" on null in /EXAMPLE_SITE/public_html/wp-content/plugins/paid-memberships-pro/services/authnet-silent-post.php:107
```
From the PHP 8 ["Backward Incompatible Changes" page](https://www.php.net/manual/en/migration80.incompatible.php):
> A number of warnings have been converted into Error exceptions:
> - Attempting to write to a property of a non-object. Previously this implicitly created an stdClass object for null, false and empty strings.
>
> [...]
Fixes a fatal error that occurs in PHP 8 when the code in `paid-memberships-pro/services/authnet-silent-post.php` runs. Similar fixes were made in other spots in #1808, but this one was overlooked.
I'm not really sure how to test it. I just noticed the issue …
> Fix PHP 8 fatal error in `services/authnet-silent-post.php`.

- adminpages/advancedsettings.php
- pages/checkout.php
Based on the issue #1840, its better to remove the option of having reCAPTCHA for free levels only. You should be able to have it on for all, or off completely. This reduces other possible edge cases such as a paid level that becomes free after a discount code. 
Relates to #1840 
1. If you had previously set reCAPTCHA to only show for Free Levels, it will now show for all members
2. The dropdown option in the Advanced Setting defaults to Yes - All Membership Levels if the option of Free Levels was previously selected
Removed the option of displaying reCAPTCHA for free membership levels.
> Recaptcha free levels

- classes/class-pmpro-site-health.php
Includes member page URL's in the Site Health information
1. Navigate to the Site Health Information page
2. Scroll down to the Paid Memberships Pro section
3. The 'Membership Pages' section has now been added
Membership pages included in Site Health Information
> Includes Member Pages in Site Health Information

- classes/gateways/class.pmprogateway_stripe.php
Saves Stripe Product IDs for live mode and sandbox mode separately so that swapping between gateway environments does not cause issues.
> Stripe products separate environments

- classes/gateways/class.pmprogateway_stripe.php
Fixed issue where trial period days can be calculated incorrectly for Stripe subscriptions. Specifically, cases when the billing frequency was not 1 could cause initial subscription trials to have incorrect lengths in Stripe.
- BUG FIX: Resolved issue where subscriptions could have incorrect trial lengths in Stripe.
> Fixed issue where trial period days can be calculated incorrectly for Stripe subscriptions

- classes/gateways/class.pmprogateway_stripe.php
Improved error message when `create_subscription_for_customer_from_order()` fails in Stripe class.
This change is made in an effort to help customers debug issues that may occur when subscription creation fails.
* BUG FIX/ENHANCEMENT: Improved error messages when creating subscriptions with Stripe.
> Improved error message when create_subscription_for_customer_from_order() fails

- css/blocks.editor.css
Resolves problem with SelectControl height in WordPress 5.9 FSE for our blocks.
1. Load up WP 5.9 (beta/rc/final)
2. Install a block theme or use Twenty Twenty-Two
3. Open up Site Editor
4. Add PMPro Checkout Button block to any template
5. Open block and see SelectControl for Membership Level is normal height
> Fixed visual issue with WordPress 5.9 in the new Site Editor (FSE) where the height of certain select fields in PMPro blocks appeared extra tall
> Set height to auto for SelectControl in our block elements

- adminpages/pagesettings.php
BUG FIX: Fixed fatal error for sites running PHP version < 7.4 and navigating to the PMPro Page Settings.
Resolves XXX.
1. Test on an older PHP version (i.e. PHP 7.2)
2. See the error by navigating to Memberships > Settings > Pages.
3. Apply this patch, and view the Admin Pages as in step 2.
BUG FIX: Fixed fatal error for sites running PHP version < 7.4 and navigating to the admin page settings.
> Backwards compatibility for sites pre 7.4

- adminpages/pagesettings.php
BUG FIX: Fixed fatal error on sites older than PHP 7.3 when trying to use the admin pages settings. Updating previous PR to be simpler and use reset method instead.
BUG FIX: Fixed fatal error on sites older than PHP 7.3 when trying to use the admin pages settings.
> BUG FIX: Fix fatal error for older PHP sites when visiting the page settings in admin dashboard.

- classes/class-pmpro-field.php
Resolves problems when attribute names and values are output but not escaped.
1. Add any custom field and define 'html_attributes' with an array of unescaped values.
2. See they are properly escaped on output
> Better escape custom HTML attributes in field rendering
> Add new filter `pmpro_field_custom_html_attributes` to customize the HTML attributes used for fields before render
> Better escape custom HTML attributes in field rendering and add new hook to customize them before render

- classes/gateways/class.pmprogateway_stripe.php
Fixing issue where billing address may not added to Stripe customer. We weren't adding the billing address at all pre-2.7, so nothing was working then but broken here. New functionality just wasn't firing.
- BUG FIX/ENHANCEMENT: Billing address is now being added to Stripe Customers.
> Fixing issue where billing address not added to Stripe customer

- css/frontend.css
Form input fields on the newest WP theme Twenty Twenty-Two were very vertically short. This adjustment sets a min height for all of our form fields equal to 1.5x the base font size for the stylesheet/agent. This is a failsafe to make sure that form inputs aren't too small.
* ENHANCEMENT: Setting a min-height for input fields of 1.5em (1.5 x base font size) for usability.
> Small fix to ensure that form input fields aren't insanely tiny/short.

- includes/cleanup.php
* Added WordPress Coding Standards to cleanup.php
* Removed a stray `global $wpdb` in the pmpro_delete_user function
> WPCS on cleanup.php file

- css/frontend.css
Small adjustment to set the TOS at checkout font color to a darker grey/almost black. We discussed this and agreed that instead of inherit font color from page, set the bg color of that block to white and dark text.
> Adjusting the default color of text in the TOS at checkout for better contrast and accessibility

- classes/gateways/class.pmprogateway_stripe.php
Since 2019, the Stripe API allows you to send a "name" field in addition to the email and description when creating a customer. 
1. Checkout with Stripe. Make sure a name is captured in the billing address or through the "add name to checkout add on"
2. Check the customer in Stripe. Edit the information on the customer page.
3. There should be a separate name field filled in with the user's name.
There was no change to how our Stripe class calculates the name. It look for first_name and last_name, and if not found, uses the user_login.
This change only fixes things for new checkouts for new users. Existing users/customers won't be updated. We have a separate issue to sync emails on user updates. We should perhaps sync names as well when we get to working on that. …
> Sending name to Stripe. Has been an option since April 2019.

- classes/class-pmpro-subscription.php
Fill empty enddates when cancelled subscription is saved.
> Subs-table-default-enddate

- adminpages/memberslist-csv.php
- classes/class-pmpro-members-list-table.php
If you performed certain colon searches that had 0 results, a warning about a bad DB query would show up in your error log due to the `IN()` in the query. So we make sure there is something there for the query while still ensuring 0 results.
1. Perform a member's list search like `meta:notarealmetakeyorvalue`
2. There should be 0 results.
3. There should be no warning in the error log.
> BUG FIX: Fixed PHP warnings that happened when members list "colon" searches had 0 results.
> Avoiding a warning from IN() in the query. But we still want 0 results.

- js/pmpro-admin.js
Resolves conflicts with other plugins using non-prefixed class names.
Fixes #1723 again because the changes made there were backed out due to unforeseen places the JS needed to be run on. This fix is more direct and only deals with the JS calls to show/hide things based on those classes that were conflicting.
1. Go to /wp-admin/admin.php?page=pmpro-emailtemplates
2. Verify the template fields (Disable header, disable this email, subject text field, body textarea) are not showing.
3. Choose the Default Email Template from the dropdown.
4. Verify the template fields (Disable header, disable this email, subject text field, body textarea) are now showing as expected.
5. Choose the `--- Select a Template to Edit ---` from the dropdown.
6. Verify the template fields (Disable header, disable …
> Add .pmpro_admin to the path for certain un-prefixed classes

- services/authnet-silent-post.php
- services/braintree-webhook.php
- services/stripe-webhook.php
- services/twocheckout-ins.php
I want to keep the history, can't log into pmpro plugin folder.
I want to keep the history of the log files, it must be saved out of the plugin folder.
We did something similar with the filter pmpro_ipn_logfile on paypal 2 years ago.
We may also do the same refactoring on the log if/else structure in case. https://github.com/strangerstudios/paid-memberships-pro/commit/4ead1200536e64f3dd567a380813aa409a8823cc
`pmpro_stripe_webhook_logfile`
`pmpro_twocheckout_ins_logfile`
`pmpro_braintree_webhook_logfile`
`pmpro_authnet_silent_post_logfile`
We also have `pmpro_ipn_logfile` since May 2020.
```php
add_filter( 'pmpro_ipn_logfile', function ( $filepath ) {
$today = date( 'Ymd' );
@mkdir( WP_CONTENT_DIR . '/logs', 0755, true );
$filepath = WP_CONTENT_DIR . "/logs/debug-paypal-ipn-$today.log"; …
```
> Add filters to change gateway ipn/webhook logfile

- classes/gateways/class.pmprogateway_braintree.php
Added filter 'pmpro_braintree_transaction_sale_array' to allow adding or adjusting of the sale transaction method.
This allows developer's to add their merchant_account_id and other custom fields etc.
See related docs: https://developer.paypal.com/braintree/docs/reference/request/transaction/sale#specify-merchant-account-id
> Add filter for BrainTree transactions to allow additional data to be passed to BrainTree.

- classes/gateways/class.pmprogateway_stripe.php
Resolves #1920.
As reported into the issue, this function declaration sends two deprecation notices to the output. Then, he gets the "headers already sent" which is just a consequence of the errors displayed. This is gonna fix the issue.
> Fix deprecation notice "required parameter follows optional parameter"
> Fix deprecation notice "required parameter follows optional parameter"

- services/stripe-webhook.php
Resolves #1850.
And makes `$old_order` checks consistent.
> Ensure $old_order is an existing order on getOldOrderFromInvoiceEvent()

- adminpages/emailtemplates.php
- css/admin.css
Adjusted the variables reference to use the <code> tag for each so they are easier to double click and copy.
Adjusted the tables where the variable references are listed to better use the full width of the page.
Moving the wp-header-end marker so the random messages appear before the title.
* ENHANCEMENT: Improved the UI for email template variables reference on the Settings > Email Templates admin page.
> Adjusting email templates variables reference and other ui on email templates admin page

- classes/class-pmpro-site-health.php
- classes/gateways/class.pmprogateway_braintree.php
- classes/gateways/class.pmprogateway_stripe.php
- classes/gateways/class.pmprogateway_twocheckout.php
- includes/compatibility.php
We want to give our support team a way to see if other plugins are loading outdated versions of libraries and provide affected customers with a solution for resolving these kinds of conflicts. This PR adds code to record the path and version of plugins that load libraries before PMPro loads ours and add this information to the Site Health tool. Having this information should make it easier to debug plugin conflicts with PMPro.
Screenshot shows example of sample plugin loading a different version of the Stripe library than PMPro (simple-stripe-subscriptions) and demonstrates how conflicts can be shown for multiple libraries.
ENHANCEMENT: Now tracking plugins that could potentially be …
> Now tracking library conflicts and displaying in site health

- shortcodes/pmpro_account.php
Add additional level ID parameter to pmpro_member_action_links filter.
This may be helpful to set custom action links per membership level of the user if the user has multiple levels.
Add additional level ID parameter to pmpro_member_action_links filter.
1. Create a function with $pmpro_member_action_links and $level_id as arguments
2. Create a conditional change if the $level_id matches X to one of the action links
3. Hook function into `pmpro_member_action_links` filter
4. Visit the Membership Account page to view results
> Enhancement: Add additional level ID parameter to pmpro_member_action_links filter to allow customization of member action links per membership level of the user.
> Add level_id parameter

- classes/gateways/class.pmprogateway_paypalexpress.php
- classes/gateways/class.pmprogateway_stripe.php
- services/ipnhandler.php
- services/stripe-webhook.php
- We check if an order has been refunded already so that the webook doesn't process or try and mark it as refunded again
- Correct user object sent through in admin refunded email 
- Order notes show if the order note comes from the admin dashboard or a webhook
- 
1. Refund from the orders page
2. The same refund shouldn't be processed a second time from the webhook
> Duplicate Refund Processes

- includes/rest-api.php
* ENHANCEMENT: Add 'membership_id' to recent_orders REST API route.
This adds the membership ID specifically for Zapier integration.
> Add membership_id to REST API response for recent orders.

- classes/gateways/class.pmprogateway_stripe.php
Before we send a user to Checkout, we create a list of line items. Previously, this would include an initial payment line item and a subscription line item with a delay.
This PR makes three checks and combines the two line items into one if they are are all true:
1. There is not a free trial set for the level
2. No custom code is filtering the profile start date
3. The payment amounts for initial and recurring payments are the same
Otherwise, we will resort back to sending the two line items separately.
> Now combining intial and recurring payments for Stripe Checkout

- classes/class.memberorder.php
- pages/billing.php
- shortcodes/pmpro_account.php
As 'cancelled' order status is being deprecated in subscription tables update, we should stop using it throughout core PMPro.
Uses in IPN/Webhook handlers are being address in a separate PR.
> Removing uses of cancelled order status

- classes/class.memberorder.php
Example use-case: Orders are imported onto a site but the user does not currently have the membership level associated with the imported order. In this case, we still want to track the subscription if it may be active at the gateway.
> Allow MemberOrder to create PMPro_Subscription without user having level

- classes/class-pmpro-subscription.php
- classes/class.memberorder.php
Right now, we just have a cancel() method in the PMPro_Subscription class, but there’s really two cases when you would want to call that function:
1. When you would like to cancel the subscription at the gateway
2. When you would like to mark the subscription as cancelled in PMPro
This PR separates these two cases into separate methods in an effort to make the code more intuitive
> Splitting cancel method of PMPro_Subscription

- includes/deprecated.php
- includes/gateway-request-handlers.php
- includes/gateway_request_handlers.php
- paid-memberships-pro.php
- services/braintree-webhook.php
- services/ipnhandler.php
- services/stripe-webhook.php
Previously, all of our IPN/webhook handlers were coded in vacuums causing a lot of similar code across the platform. This change is the first step in making these IPN/webhook handlers more modular so that they are easier to develop and update in the future.
> Refactored IPN/webhook handlers for subscription cancelled messages

- classes/class-pmpro-subscription.php
We split up the PMPro_Subscription `cancel()` methods into two functions:
1. `cancel_at_gateway()`
2. `mark_as_cancelled()`
The goal of this change was to separate out these actions so that you can call one independently of the other. It also had the "clever" perk that if you cancelled the subscription  at the gateway, you didn't need to mark the subscription as cancelled in the database since the IPN/webhook handler would do that work for you.
While testing this behavior, I ran into a conflict with PMPro CONPD where if you check out for a subscription with Stripe and then cancel it, CONPD would give the user's membership back to them and then the Stripe webhook handler would remove the returned membership.
After some thought, it seems right to get rid of the cleverness. …
> Changing cancel_at_gateway() to also mark subscription as cancelled

- css/admin.css
- includes/functions.php
Small CSS tweak for admin to make sure our pmpro_message class elements ( when they otherwise don't have a contextual color set ) are dark nearly black text for accessibility.
Fixed a warning in the membership required messages replacements function when looking for a deleted level's Name.
> CSS in admin accessibility; Fixing a warning for a deleted level

- classes/class.pmproemail.php
- classes/gateways/class.pmprogateway_paypalexpress.php
- classes/gateways/class.pmprogateway_stripe.php
- includes/email-templates.php
- services/ipnhandler.php
- services/stripe-webhook.php
This PR rewrites the default email content for the Refund and Refund (admin) email templates. I also adjusted the methods to include the order object so that we can show populate order-related template variables in the emails.
I removed the old level ID information. Refunds are exclusively about the invoice/order data and don't affect membership level for the invoice's user.
> Updating the email for refund and refund admin

- adminpages/orders.php
Fixing issue where saving an order in admin would reset order date to current time.
> Fixing updating order timestamp from admin dashboard

- classes/class-pmpro-wisdom-integration.php
Now sending all level data to Wisdom. 
It is important to note that the `$stats['plugin_options_fields']['pmpro_level_setups']` data may be very large as it contains the settings for all membership levels. Not sure if this will cause issues for sites with many levels.
> Now sending all level data to Wisdom

- includes/crons.php
Since 2.8 the activity report has been sent hourly instead of weekly because of a mismatch in array keys (using `recurrence` instead of `interval`).
> Crons: fix array key for interval

- adminpages/orders.php
Trailing commas in functions call are valid since PHP 7.3. We are 5.6+ compatible, then we should avoid it.
> Remove a trailing comma which can cause issues

- includes/compatibility/divi.php
When you protect a post using the Require Membership box with Divi, it has a fairly decent appearance. That same page protection on a single page, though, have no wrapping container and span the full width of the page with no padding or margins.
This PR update the CSS classes added to the no_access message for Divi to make it look better without too much formatting,
1. Protect a page at the page level with Divi using the Require Membership metabox
2. View on the frontend as a non-member
3. With this css selector added to the content message it should look decent in the page.
* ENHANCEMENT: Improved appearance of no_access messages with Divi builder.
> Wrapping the no_access message in a divi selector so it doesn't full wrap

- adminpages/advancedsettings.php
Fix compatibility with AdBlocks.
Resolves #2029.
1. Enable an AdBlock
2. Now you should be able to see the Ad related dropdown in adv settings
> Fix AdBlock compatibility
> Rename #hideads to #pmpro-hideads

- css/admin.css
This is the "Sales" report. Not looking good because with i18n (italian in that case) some rows height is double.
This PR aims to:
- right align "Revenue" label in table head
- vertical align table values
> Sales Report: push Revenue label right and align vertical

- services/stripe-webhook.php
Fixing PHP Fatal error:  Uncaught Error: Attempt to assign property "billing" on null in .../wp-content/plugins/paid-memberships-pro/services/stripe-webhook.php:976
> Fixing variable name

- services/stripe-webhook.php
That pmpro_doing_webhook() called before wp bootstrap causes error 500.
1.
2.
3.
> Direct include avoid Call to undefined function pmpro_doing_webhook()

- adminpages/reports/memberships.php
`Warning: Array to string conversion` in case of multiple levels passed in.
1. Create 2+ levels
2. Create a snippet with `pmpro_getCancellations('today',[1,2])`
3. Check the debug log for the warning
> Avoid a warning in case of multiple levels passed in

- classes/gateways/class.pmprogateway_stripe.php
Fixed issue where the PMPro Stripe Settings would tell user that they are using Connect credentials when, in reality, they were using legacy keys.
Now also showing reccomendation to disconnect from Stripe hwne using legacy API keys.
> Improved wording around using Stripe legacy API keys

- includes/login.php
*BUG FIX: Fixes an issue to only redirect to the set PMPro login page if the page is published.
Resolves: https://github.com/strangerstudios/paid-memberships-pro/issues/2068.
1. Delete the Log In page from the pages list. (Or even unpublish it).
2. Logout.
3. Try to login via the default wp-admin (should redirect to default wp-login.php)
> Fix login redirect issue for trashed pages.

- includes/filters.php
We have a filter pmpro_pmpro_subscribe_order_startdate_limit() in filters.php that is meant to detect cases where we are going to set the subscription start date to > 1 year in the future. PayPal can't handle this, so we try to "squeeze" the extra time into a free trial if possible.
However, that was meant to figure out the number of days for the trial would always be set to 365 instead of having that as an upper limit.
This update correctly calculates the days past 1 year and only if it's > 1, sets the trial up.
This issue might have come up randomly for 1 year recurring levels or more consistently if you had custom code or level settings that would result in subscriptions with renewals > 1 year.
1. Create a recurring level for $5 every 370 days.
2. Checkout with PayPal Express.
3. Note …
> We were incorrectly calculating the TrialBillingFrequency in pmpro_pmpro_subscribe_order_startdate_limit filter.

- classes/class-pmpro-subscription.php
In the original code, PMPro only marks a subscription as cancelled in the database after actually cancelling the sub in the gateway. This causes a race condition between the PMPro_Subscription's `mark_as_cancelled()` method and the IPN/webhook message that is sent from the payment gateway. If the IPN/webhook is processed before the `mark_as_cancelled()` finishes running, then users may have their membership level removed when it shouldn't be.
This PR removes this race condition by marking the subscription as canclled in the database before reaching out to the gateway, causing IPN/webhook handlers to not process those cancellations.
Since originally the subscription was always marked as cancelled in the PMPro_Subscription `cancel_at_gateway()` method regardless of what happened during the …
> Subs table IPN/webhook race condition

- classes/class-pmpro-field.php
We should not add filters unless we absolutely need them so that we have more control over how the PMPro_Field class flows.
For most of the filters removed, users can customize functionality by setting up fields differently.
> Removing unnecessary filters from PMPro_Field class

- includes/fields.php
Fixing undefined $user_id in lines `pmpro_check_field_for_level( $field, "profile", $user_id )`
> Fixing some calls to pmpro_check_field_for_level()

- adminpages/userfields.php
- includes/functions.php
* ENHANCEMENT: Added in function to format field names, replaces dashes and spaces with underscores.
Resolves XXX.
1. Save a field name to be something like 'my field' or 'my-field'.
2. See field name after change, should be changed to 'my_field'.
> Format field names to have underscores.

- adminpages/paymentsettings.php
- classes/gateways/class.pmprogateway_stripe.php
From a conversation on slack:
> [...] we don't limit those. We used to have a card type drop down (it's detected from the number now) and so used those check boxes to populate that list. So for Stripe, those can be ignored and we should probably remove the checkboxes.
We had a gist for this: https://gist.github.com/andrewlimaza/aac5c0c93a4ed6c3224e3d9a67fbc303
Hide the credit cards selection field in Stripe's options and show this message in checkout: "We accept all major credit cards"
1. Activate stripe
2. Check stripe's settings and checkout message
> Disable credit card selection for Stripe

- services/stripe-webhook.php
Log some more webhook cases, where we have an event id for a non-handled event type.
> Log and throw "unhandled webhook" for not handled event types

- adminpages/membershiplevels.php
The level name field has been set to required using the browser's default functionality. 
Resolves #2130 
1. Create a level
2. Leave the level name field empty
3. Try and save the level
4. A default browser tooltip will show when trying to save an empty field.
Creating a new level requires a level name before saving
> Level name is required when creating a level

- includes/deprecated.php
- includes/updates.php
Update notice for Better Logins Report Add On has been removed. Added to the deprecated notice list.
Resolves #1961 
1. Install the archived version of Better Logins Report Add On
2. The new deprecated notice will show up on the admin dashboard
Better Login Reports Add On deprecated notice adjusted
> Update notice removed, deprecated notice added for Better Login Reports

- css/admin.css
- includes/updates.php
Useful for future PMPro updates where we want to warn users about breaking changes.
I have not been able to test this completely since this would require having an update for PMPro that includes an update notice; however, the code does work when setting PMPro to an old version and adding the following line of code at the top of the `pmpro_maybe_show_upgrade_notices()` function:
`$update_data->upgrade_notice = 'Your update notice...';`
Based off of this article: https://andidittrich.com/2015/05/howto-upgrade-notice-for-wordpress-plugins.html
> Showing update notices when update is available for PMPro

- includes/notifications.php
Remove that line break at the end of our "powered by" html comment.
```
```
> Avoid line breaks in "powered by" html comment

- adminpages/orders.php
Allows you to add &user=XXX where XXX is a user ID which autofills in the user ID field
Resolves #2021 
1. Add wp-admin/admin.php?page=pmpro-orders&order=-1&user=1 to your URL
2. The User ID will auto fill in the user ID field
Support to autofill user ID in new Order page from query parameter
> Autofill user ID value from query param

- includes/functions.php
Reworked the format meta key method to take all special characters and replace it with an underscore, as well as lowercase the field name. This should help prevent issues of naming, uppercase field keys.
> Format meta key names better.

- adminpages/membershiplevels.php
We moved the `<hr class="wp-header-end">` element so that our page titles/actions and the content of the page wouldn't be separate by any admin notices from our own plugin or other plugins.
When we did this, it meant that our Add Ons like MMPU that add buttons to the page title actions couldn't add their buttons where we wanted them to.
This PR adds a new filter `pmpro_membershiplevels_page_action_links` to add or modify the buttons for the Settings > Membership Levels admin page.
* ENHANCEMENT: Added filter `pmpro_membershiplevels_page_action_links` to add/modify buttons on the Settings > Membership Levels admin page.
> Adding filter to page title actions on Membership Levels settings page.

- classes/class.memberorder.php
* BUG FIX: Minor fix for v2.9 MemberOrder total calculations always set to 0 (even for paid orders). Thanks for the help @dparker1005
> Bug fix total amounts showing as 0 always.

- adminpages/membershiplevels.php
This update clears a warning when $page_msg is empty.
I also removed the output of the unique message on single edit for membership level. The idea was that we'd show page-specific messages separate of general plugin status/settings alerts. This needs more thought and development.
> Fixing warning when page_msg is empty; Removing unused output of message on single edit

- adminpages/membershiplevels.php
- includes/functions.php
A few fixes from Theunis' testing feedback
- fixed display of categories to protect on level edit if categories are hierarchical.
- made add new and edit links for posts or pages in the content settings section open in a new tab.
> Fix for hierarchical categories; open edit and add new content links in new tag

- js/pmpro-stripe.js
If pmpro-stripe.js is loaded on a page with a non-checkout PMPro form, it would prevent submit buttons from working. This could often be the case when using this code recipe which sets up a checkout form on every page:
https://www.paidmembershipspro.com/process-membership-checkout-in-a-modal-or-popover-window/
This change tries to minimize this issue by only preventing default if a checkout form was submitted. The criteria for checking this is currently if there is a "level" input in the form, but we can revise this later if necessary if there are additional cases where issues come up.
> Now checking if actually on a checkout form before preventing default

- services/stripe-webhook.php
Found an unused variable, fixed it.
1. Create a stripe order
2. Trigger a webhook on it in order to run the func `pmpro_stripe_webhook_populate_order_from_payment`
3. Now check the order details (first/last name)
> Fix "Unused local variable 'name_parts'"

- includes/deprecated.php
- includes/functions.php
The pmpro_register_helper_deprecated() function in includes/deprecated.php is creating some functions and classes that don't exist when the old Register Helper plugin is deactivated. This will make sure that sites using old custom code and gists that use the old RH names of things continue to work.
However, when activating Register Helper, PMPro puts the functions in place, but then RH throw an error when trying to define those functions on activation.
This update adds a new function pmpro_activating_plugin() which can be used to tell if a specific plugin (or any plugin) is being activated. So when activating RH, we don't create the functions to swap.
We should consider an update to RH to avoid creating these functions when the core PMPro ones exist. But also, people shouldn't be using …
> Fix/error when activating Register Helper

- includes/email.php
We are filtering the `$email->email` value later in its own callback, so it doesn't really matter, but it's possible other stuff hooked in is looking for the email.
1. Activate PMPro
2. Go to Settings -> Email Templates
3. Choose an email template.
4. Change the test email address to something you'll notice.
5. Send the test email.
You will get the email. It will have been sent to the to address you set.
> ENHANCEMENT: Fixed test email setup to set the $email->email property properly.
> The property of the email object we want to set is ->email.

- pages/checkout.php
- services/applydiscountcode.php
The level information we output on the checkout page as several sections including description, price, expiration, and discount code.  These were difficult to target with CSS because they don't have unique selectors that break apart the price from expiration, etc.
This PR wraps each price component on the checkout page in a div so CSS can style these sections independently.
* ENHANCEMENT: Improved frontend level cost details output on the checkout page with classes for better design control.
> Wrapping sections of the level cost on checkout page so that it can be styled with CSS

- classes/class.memberorder.php
Added unset magic method for MemberOrder. Resolves fatal error at checkout with PMPro Zapier.
> Added unset magic method for MemberOrder

- classes/gateways/class.pmprogateway_stripe.php
Fixed functionality for plugins that use the `pmpro_confirmation_url` filter with Stripe Checkout running.
> Now filtering confirmation url for Stripe Checkout

- services/ipnhandler.php
Was investigating these messages in my logs:
> ERROR: Could not cancel membership. No user attached to order #...
Then noticed it was not handling a cancellation; instead it was logging an error creating a subscription profile.
We can have this more meaningful error in that case (since we are not creating the user if the initial subscription fails for a guest, it's intended to receive an ipn request for an initial failure without an user associated).
> IPN: Logs the "ERROR" message only if needed. Otherwise just log a meaningful message

- classes/class.pmproemail.php
Added MMPU compatibility for some emails by pulling the membership ID related to the email from the passed `$invoice` instead of from `pmpro_getMembershipLevelForUser()`.
The cancellation emails still need MMPU compatibility for when multiple levels are cancelled at once, and the admin change emails need compatibility for when multiple levels are added/removed.
> Added MMPU compatibility for some emails

- classes/gateways/class.pmprogateway_stripe.php
- services/stripe-webhook.php
Fixing issue where Stripe Checkout would not track discount code uses where a payment is still required.
1. Create discount code that does not make level free
2. Check out with Stripe Checkout
3. See that order discount code is empty before patch, but filled after patch
> Fixing Stripe Checkout tracking discount code uses

- preheaders/billing.php
When we don't have an $order_id, we are forcing $worked = true: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/preheaders/billing.php#L265
We still don't have an order though, then this line was triggering a Notice:
`PHP Notice:  Undefined variable: morder in /wp-content/plugins/paid-memberships-pro/preheaders/billing.php on line 277`
1.
2.
3.
> Fix for "PHP Notice: Undefined variable: morder" when ! $order_id

- classes/class.pmproemail.php
- scheduled/crons.php
Added MMPU compatibility for membership expiration and expiration warning crons.
Also considered updating the credit card expiration warning and trial ending crons, but CC expiration really needs subscriptions table to be done nicely and the trial ending cron hasn't been running since 2013 and should maybe be deprecated.
> Added MMPU compatibility for some crons

- includes/setup.sql
- includes/upgradecheck.php
The vast majority of subs table queries will be when we have the subscription transaction ID, gateway, and gateway_environment, when we are looking for subscriptions for a particular user, or when we are trying to find subscriptions with upcoming next payment dates.
For any query including subscription transaction ID, gateway, and gateway_environment, there will only ever be one subscription that fits those meaning that indexing is a huge help.
Since SQL only benefits from the index that narrows down the search to the fewest number of results, in any query that includes a user ID, indexing by user ID should return a very small number of subscriptions. I doubt that indexing any other value in this table could do better when a user ID is present.
Searching for subscriptions with upcoming …
> Optimize subs table indexing

- css/frontend.css
Very long checkbox label:
Inline:
1. RH or User Fields create a checkbox with a very long label.
> Checkout checkboxes: avoid line breaks in case of very long labels

- pages/cancel.php
As widely discussed, not having a double-click limit on the "confirm cancel" button in cancel confirmation page, causes issues with CONPD.
- First request => set and enddate.
- Second request => completely cancel the membership.
1.
2.
3.
> Avoid double cancellation requests

- adminpages/membershiplevels.php
- classes/class-pmpro-levels.php
We no longer cancel all of the subscriptions associated with a membership level upon deleting it. Instead, members should be canceled first before deleting the level. Language around this has also been adjusted.
1. Have a member with an active membership level and subscription
2. Delete the level from Memberships > Settings > Level
3. Their subscription should still remain active in the gateway
We no longer cancel subscriptions when deleting a membership level.
> PR2 - Don't cancel subscriptions when deleting a level

- pages/checkout.php
For consistency (and probably order data correctness) we should set the country correctly even if our store does not permit international addresses.
> Use the default country value when international addresses are disabled

- includes/countries.php
Found a duplicated key, removed.
> Remove duplicated country array key VE (Venezuela)

- css/frontend.css
2.9.4 has a CSS snafu where the form.pmpro_form is added to a selector list that sets up some field default display. That was done in error.
In this PR, I took a more specific look at our field CSS so that we are more hardened across various popular themes and for our most common field types in User Fields settings.
* BUG FIX/ENHANCEMENT: Improved CSS for frontend form fields.
> CSS adjustments for form field types

- includes/fields.php
If you have fields for admin only, the former code would stop the loop and return the function... so every other field following wouldn't appear.
This update changes the logic so the fields continue and the loop keep going.
* BUG FIX: Fixed case where user fields wouldn't show for users if earlier fields/groups were only for admins.
> Continue loop if fields are for admins only

- classes/class-pmpro-field.php
- css/frontend.css
- js/pmpro-checkout.js
Some field types like radio, date, checkbox, and checkbox grouped were having a weird placement of the required asterisk.
This PR reworks how the required field is set up and will move it to a better position across field types.
**OLD WAY:**
**NEW WAY:**
This PR also includes a fix for the "hidden" field type not to show the label.
It also adds a fallback "long dash" (the same HTML entity we use on the members list and other places in admin where the field is "empty" if the field is our readonly field type to show the dash if there is no value for the field.
(This won't show a dash in an empty form field element for any field with the readonly property on the form element, just the specific readonly field "type").
> Field required asterisks

- includes/fields.php
- js/pmpro-admin.js
Updated the label for select-type field to say "Select / Dropdown".
Now supporting select2 field type in user field settings GUI.
* ENHANCEMENT: Added no-code fields support for select2 field type.
> Updating select field type label; now support select2 field type in user fields

- classes/class-pmpro-wisdom-integration.php
Our (opt in) tracking cron was failing because a function in the includes/addons.php file was not available, since that file is only included in the admin dashboard and WP cron runs outside the "admin".
This fix simply requires that file in place as needed there. The addons.php file hooks up some plugin update related things that typically only happen on admin, but shouldn't affect other crons in any negative way.
> Wisdom tracker needed the addons.php file loaded.

- adminpages/reports/sales.php
Allows you to show both New and Renewals, Only New or Only Renewals on your Sales & Revenue chart
1. Navigate to Memberships > Reports > Sales & Revenue
2. Choose if you want to show both or only new or only renewals from the dropdown
You can now choose if you'd like to only view New or Renewals on your Sales & Revenue chart
> Only show renewals or new on charts

- adminpages/wizard/done.php
- adminpages/wizard/general.php
- adminpages/wizard/wizard.php
Created a function to hold all the site types that are available in the wizard. This will make it easier to update the list going forwards if we add more site types.
Creating that function also allows us to fix an issue on the "Done" page where the site type would not be in a localized, human-friendly format. For example, you may have seen: "You indicated you're building a physical_products membership site. Here are some recommended Add Ons for your business."
We are also no longer including some of that line if the user did not choose a site type, and are now only showing them "Here are some recommended Add Ons for your business."
> Created function to get all site types

- adminpages/membershiplevels.php
@kimcoleman
> if you edit an existing membership level, then save changes, the success message says “membership level added successfully”. should say “updated”.
> Change message on membership level save ("updated")

- classes/gateways/class.pmprogateway_stripe.php
- services/stripe-webhook.php
Fixes issue where "file" type user fields would not be saved when sending users to Stripe Checkout
Resolves XXX.
> Stripe Checkout now saves uploaded files
