services/ipnhandler.php

updated payment status and payment type so that its recorded in the order created. Payment status was not set so it was showing empty.

Updated payment status and type

---

adminpages/addons/pmpro-woocommerce.php

Perhaps a link or something like I added? Also fixed a typo.

Give some context for WooComerce add-on? (link?)

---

includes/profile.php

Add textdomain for not paying status

---

adminpages/paymentsettings.php
preheaders/confirmation.php

Add support Bitcoin Gateway plugin - https://wordpress.org/plugins/gourl-bitcoin-paid-memberships-pro/
Two small changes only.

Add support GoUrl Bitcoin Gateway plugin

---

adminpages/admin_header.php
adminpages/orders.php
classes/class.memberorder.php
classes/gateways/class.pmprogateway.php
classes/gateways/class.pmprogateway_authorizenet.php
classes/gateways/class.pmprogateway_braintree.php
classes/gateways/class.pmprogateway_check.php
classes/gateways/class.pmprogateway_cybersource.php
classes/gateways/class.pmprogateway_payflowpro.php
classes/gateways/class.pmprogateway_paypal.php
classes/gateways/class.pmprogateway_paypalexpress.php
classes/gateways/class.pmprogateway_stripe.php
includes/functions.php
includes/init.php

Change setup to set up

---

pages/checkout.php

Add filter 'pmpro_email_field_type' for email type field and add acronym for asterisk with span - required field

Add filter and accessibility

---

adminpages/discountcodes.php

Added a parameter of the discount code ID to the
pmpro_discount_code_after_settings action call.

Minor change to a do_action in discountcodes.php

---

preheaders/checkout.php

This is a really minor change that makes the `pmpro_setup_new_user` filter more robust.

Improve pmpro_setup_new_user filter

---

css/frontend.css

With the new Theme My Login (currently in beta) and Wordpress 4.3 updates, this edit fixes style issues with the front end generate password fields.  See bug here: https://github.com/jfarthing84/theme-my-login/issues/14

Remove TML style conflicts

---

adminpages/orders-print.php
adminpages/orders.php
classes/class.memberorder.php
classes/class.pmproemail.php
classes/gateways/class.pmprogateway.php
classes/gateways/class.pmprogateway_authorizenet.php
classes/gateways/class.pmprogateway_braintree.php
classes/gateways/class.pmprogateway_check.php
classes/gateways/class.pmprogateway_cybersource.php
classes/gateways/class.pmprogateway_payflowpro.php
classes/gateways/class.pmprogateway_paypal.php
classes/gateways/class.pmprogateway_paypalexpress.php
classes/gateways/class.pmprogateway_paypalstandard.php
classes/gateways/class.pmprogateway_stripe.php
classes/gateways/class.pmprogateway_twocheckout.php
includes/lib/recaptchalib.php

Transition to __construct() for classes & a couple of bug fixes I stumbled across.

Class constructor update + minor bugs

---

adminpages/orders-print.php

Typo in argument for admin_url()

Generates 404 error

---

includes/functions.php

Didn't apply `pmpro_has_membership_level` filter to all of the returned values from `pmpro_hasMembershipLevel()`.

Not applying pmpro_has_membership_level filter

---

adminpages/paymentsettings.php

I18N consistency improvements

---

adminpages/emailsettings.php

FIX: Didn't translate in all languages

I18N consistency improvement

---

classes/gateways/class.pmprogateway_payflowpro.php
classes/gateways/class.pmprogateway_paypal.php
classes/gateways/class.pmprogateway_paypalexpress.php

Set the description used for PayPal on their site when describing the transaction/subscription.

ENH: pmpro_paypal_level_description filter.

---

adminpages/orders.php

Added a third parm to the pmpro_orders_user_row_actions filter to pass
the actual order as well.

Added order to the row actions for the orders list

---

adminpages/orders-csv.php
adminpages/orders.php
preheaders/checkout.php
services/ipnhandler.php
services/stripe-webhook.php

FIX: Would sometimes throw uncaught exception error during processing of webhook event.

FIX: Would sometimes throw uncaught exception error 

---

includes/functions.php

Formatting of INSERT statement would sometimes cause DB error

BUG: Didn't always update the users membership

---

pages/checkout.php

There's a leading whitespace in the `class=""` attribute for the CVV input field.

BUG: CVV field fails HTML validation

---

adminpages/memberslist-csv.php
adminpages/memberslist.php

Adding a user filter prior to display will allow plug-ins (e.g., MMPU)
to alter fields.

Add filters to memlist & memlist CSV

---

adminpages/functions.php

ENHANCEMENT: added $wpdb->prepare() for SQL queries

ENHANCEMENT: added $wpdb->prepare()

---

adminpages/membershiplevels.php
css/admin.css
includes/addons.php
includes/functions.php
preheaders/billing.php
readme.txt

Multiple commits

---

pages/billing.php
pages/cancel.php

BUG: RegEx missing required delimiters

BUG: Didn't always load help pop-up

---

includes/functions.php

Reverts strangerstudios/paid-memberships-pro#380

Revert "Shift Hook : pmpro_before_change_membership_level"

---

adminpages/pagesettings.php

@strangerstudios Dunno if this is on the right branch, but it bugged me. 😄

Added missing space pmpro_confirmation shortcode label

---

includes/functions.php

Update the pmpro_url function to use add_query_arg
EDIT: Commit d94a9dd has the correct fix. Commits f1df561 and 9f3c50c happened as a result of my mis understanding of the working of the function.

fix for #409 : Use add_query_arg in pmpro_url

---

adminpages/discountcodes.php

fix for #326: Search at Discount page isn't working

---

classes/gateways/class.pmprogateway_stripe.php

Otherwise it makes it look like the credit card number is 17 digits instead of 16

Placeholder account number (X's) should be 12 not 13 in length

---

adminpages/membershiplevels.php

added SQL statements with $wpdb->prepare() 
Please feel free to comment if I have missed anything

ENHANCEMENT: wpdb->prepare() for membershiplevels.php

---

adminpages/reports/memberships.php

The last bug fix didn't actually fix the issue.  This fixes it for realz!

BUG: Cancellations showing 0 for All Time under Membership report

---

adminpages/discountcodes.php

$wpdb->prepare() implementation adminpages/discountcodes.php

$wpdb->prepare() implementation

---

shortcodes/pmpro_account.php

Allow users to filter the text displayed for the expiration date (use custom date formats, append HTML to highlight text, etc).

ENHANCEMENT: Add filter for level expiration text

---

classes/class-deny-network-activation.php
paid-memberships-pro.php

Added a class to check that the plugin doesn't get network-activated
lines 27-29 of main file

Deny Activation class

---

classes/gateways/class.pmprogateway.php
classes/gateways/class.pmprogateway_check.php
classes/gateways/class.pmprogateway_cybersource.php

Changed $this->Billing_Period and $this->Billing_Frequency to $order->Billing_Period and $order->Billing_Frequency.

Fixed some null variables in gateways

---

adminpages/reports/memberships.php

Added pmpro_admin_reports_included_levels to indicate the max # of membership levels to include in the memberships report

ENHANCEMENT: Added filter for level count included

---

classes/class.mimetype.php
includes/currencies.php

Added in support for Russian Ruble currency by default.

Russian ruble

---

classes/class.mimetype.php

Enhancement:
* Added docx mime type by default
* Added ‘pmpro_mimetype_array’ filter to allow to easily add/remove
filetypes from the mimetypes list.

Mimetype Enhancements

---

includes/profile.php

Didn't wrap 'Not paying.' text in quotes

BUG FIX: JavaScript error due to invalid variable

---

shortcodes/membership.php

Added a filter for [membership] shortcode

Enhancement: Filter for membership shortcode access

---

adminpages/reports/memberships.php

Allow a user to reorder the levels without having to use the Membership Levels page drag & drop sort ordering.

ENHANCEMENT: Filter lets user change level order

---

includes/updates/upgrade_1_9_4.php
includes/upgradecheck.php

Show a notice if a user is using a custom page template and assume that
it’s still using the HTML table.

Upgrade Notice 1.9.4 div notice.

---

preheaders/billing.php

If there's a change in gateways, the current release won't let those ('legacy') members update their billing info.

ENHANCEMENT/FIX: Let users update billing info

---

pages/billing.php

Removed duplicate labels on billing page.

BUG FIX: Duplicate Labels on Billing Page

---

adminpages/advancedsettings.php

Renamed labels and fields for reCAPTCHA

---

includes/sessions.php

General comments for session file.

Comments for Sessions File

---

includes/login.php

Fix compatibility with TML 7

---

includes/login.php

This fix also has the added benefit of redirecting the requsted
action to the proper TML action.
Fixes #719

Ensure that a TML action exists before attempting to redirect

---

classes/gateways/class.pmprogateway_stripe.php

Shows Stripe version used on Payment Settings page.

Show Stripe version on Payment Settings

---

adminpages/membershiplevels.php

Removed billing cycle warning for Stripe.

Remove billing cycle warning for Stripe

---

paid-memberships-pro.php

Taking the Description from the marketing text in the recommended plugins.
Adjusted the protocol in the doc block
WPCS doc block

Marketing reset

---

adminpages/orders-csv.php

Added the Order "Code" to the Orders Export to fix https://github.com/strangerstudios/paid-memberships-pro/issues/793

Order code export

---

adminpages/orders-csv.php
adminpages/orders.php
adminpages/reports/memberships.php

Enhancement: Added in ability to filter  for free orders only. (Orders equal to $0)
Enhancement: Added in ability to filter  for paid orders only. (Orders greater than $0)
Enhancement: Added in ability to filter membership reports for free levels only.
Enhancement: Added in ability to filter membership reports for paid levels only.

Enhancements: More filtering options for free vs paid

---

adminpages/addons.php

New license server setting for 'HideFromAddOnsList' is now being used to filter Add Ons from the admin area in PMPro.

Updating the Add Ons admin page to filter hidden add ons

---

includes/functions.php

Calculate the next payment date with time, not SQL

Dev prepare nextpaydate

---

adminpages/memberslist.php

Adding links to filter search by other filters or search all users when no members are found in a Members List search.

Adding additional quick search links when no members are found in members list search

---

shortcodes/pmpro_account.php

Enhancement: Show order "status" on account page under "Past Invoices".
Inlcudes 'refunded' orders.

Enhancement: Show Order Status on Account Page.

---

includes/compatibility.php
includes/compatibility/beaver-builder.php
includes/compatibility/elementor.php
includes/compatibility/siteorigin.php
paid-memberships-pro.php

Added theme compatibility for Beaver Builder, Elementor and Page Builder by siteorigin.

Theme Compatability

---

adminpages/advancedsettings.php
includes/recaptcha.php
pages/checkout.php

Implementation of Invisible Recaptcha.
* Added ID to submit button on checkout page.
* Added in setting to use Invisible Captcha or normal Captcha.
* Updated Recaptcha.php code to include invisible Captcha.

Enhancement: Invisible Recaptcha

---

includes/updates/upgrade_1.php

See error here: http://7thqueen.com/public-files/gabi/Screenshot_2019-01-28_at_11.28.53.png
The recommended pull request should fix it.

Fix database upgrade error on localhost environment

---

includes/email.php

Now using pmpro_retrieve_password_message filter to add HTML tags to system password reset emails.

Fixed bug with HTML password reset emails.

---

includes/metaboxes.php

Fixed issue https://github.com/strangerstudios/paid-memberships-pro/issues/898

Added 'high' priority to Require Membership metabox.

---

readme.txt

This replaces the video for our .org repository page to use the correct new voiceover done by Travis and does not include screenshots of the pricing page on our site.

Updating readme video URL; Updating tested up to value

---

includes/rest-api.php

Bug Fix: Fix issue on sites that don't have REST API enabled.

Bug Fix: REST API Fatal error

---

pages/checkout.php

Keep discount code link if it's applied to the URL and then the user logs in and returns to checkout.

Keep discount code link in URL

---

.github/PULL_REQUEST_TEMPLATE.MD

Fix the Pull Request Template "Pulls" link.

Fix PR template

---

adminpages/advancedsettings.php
adminpages/discountcodes.php

Fix https://github.com/strangerstudios/paid-memberships-pro/issues/939

---

pages/billing.php

This adds in an edge-case where cancelled users or logged-in non-members would see "This subscription is not recurring. So you don't need to update your billing information." message when viewing the Billing page. This now supports an upsell method for logged-in non-members and cancelled/expired members.
Closes Issue: https://github.com/strangerstudios/paid-memberships-pro/issues/938.
1. Cancel your membership level and navigate to "Billing" page.
2. There is a fallback if the user's last/old level is no longer available, this will choose next available level.
3. If the fallback occurs, the text changes accordingly from "Renew" to "Sign up" for a membership level.
Enhancement: Adjusts …

Enhancement: Billing Page update for cancelled/expired members

---

classes/gateways/class.pmprogateway_payflowpro.php
classes/gateways/class.pmprogateway_paypal.php
classes/gateways/class.pmprogateway_paypalexpress.php
classes/gateways/class.pmprogateway_paypalstandard.php

See issue #1008 
Closes Issue: #1008 .

Now using add_query_arg() for ipnhandler urls

---

adminpages/functions.php
adminpages/orders.php
adminpages/templates/orders-print.php

This update moves the "Email" order modal window into a helper function. Primarily we are doing this so that the Member History Add On can leverage the same modal code to send an email.
The PR also moves all of the Order row actions (edit, copy, delete, print, email) into row actions under the order's code in the table. The row action links appear on row hover and can be appended using the previous pmpro_orders_user_row_actions filter.  We should consider adding all of the links  present to this filter so that it can be completely adjusted. The links are now also using the add_query_arg function to generate admin links with an array of query variables.
The PR also adds "Print" and "Email" as buttons in the h2 section of the single order view.
The PR also adjusts the Invoice "Print" view …

Email order modal function and Orders admin improvements

---

includes/currencies.php

Fixes: #1032 
1. Go to plugin payment settings (`/wp-admin/admin.php?page=pmpro-paymentsettings`)
2. Select Russian Ruble currency 
3. Enjoy
Related: https://wordpress.org/support/topic/currency-customization/
Update Russian Ruble (RUB) currency format

Update Russian Ruble (RUB) currency format

---

classes/gateways/class.pmprogateway_stripe.php
css/frontend.css
pages/checkout.php

1. Enable Stripe as the main gateway.
2. Look at the checkout page's Payment Information section.
3. Confirm the boxes are styled well.

CSS to support new Stripe checkout; Minor Stripe checkout updates

---

pages/checkout.php

Filter added to adjust the number of years the "Expiration Year" dropdown shows on checkout.

Filter: pmpro_num_expiration_years

---

classes/gateways/class.pmprogateway_stripe.php

bug fixes/enhancements for 2.1 beta

---

adminpages/memberslist-csv.php

Removed unnecessary if statement which is always true.
1. Export members to CSV and verify that it works. Try with amount of users > $max_users_per_loop as well as < $max_users_per_loop

Removed if statement that is always true.

---

css/frontend.css

Small CSS addition to improve appearance of the "Payment Information" section when a user has set content in the "SSL Seal Code" admin setting field. 
More specific CSS selectors for form elements that have the `.pmpro_error` class added after field validation.

CSS Improvements for checkout.

---

css/frontend.css
js/pmpro-stripe.js
pages/checkout.php

Duplicates the pmpro_message div to bottom of checkout form above the submit button. Adjustment to the stylesheet for additional margin on form. Adjustment to stripe gateway JS to show bottom message on submit.

Duplicating checkout form message to bottom of form above submit button

---

js/pmpro-checkout.js

Fixed bug when applying discount codes.

---

adminpages/memberslist.php

Small members admin page column title change for consistency.

Changing "Membership" to "Level" on members list.

---

shortcodes/pmpro_account.php

ENHANCEMENT: Support date_i18n on the membership account page to support translations.
Closes Issue: https://github.com/strangerstudios/paid-memberships-pro/issues/1090.
1. View Membership Account page while using a different locale.
ENHANCEMENT: Support date_i18n on the membership account page to support translations.

Enhancement: Support date_i18n on account page

---

classes/gateways/class.pmprogateway_stripe.php

BUG FIX: Preserving trials during 'now' Subscription Updates.

---

css/admin.css
includes/notifications.php
js/pmpro-admin.js

Initial commit for the new notification commit.
Following Changes:
* Store archived notification based on user meta.
* Read new notification systems from new API.
* Hide notifications if start/end date are before/after.

Notifications

---

adminpages/advancedsettings.php
includes/notifications.php

Added in show_if/hide_if rules.
* Hide notification if a plugin is active.
* Show a notification if a plugin is a specific version.
TODO: Support multiple plugins.

Hide notifications / Rules

---

includes/notifications.php

Notification to test the user's site URL, uses strpos to see if any word matches.

Function to test site_url match

---

adminpages/discountcodes.php
adminpages/orders.php
classes/gateways/class.pmprogateway_stripe.php

Fixing other month off by 1 errors

---

classes/class-pmpro-members-list-table.php

Removed `PMPro_Members_List_Table::get_column_count()`, which is already declared in the parent class `WP_List_Table`, and fixed some undefined variables in the members list.

Members list fixes

---

css/frontend.css

BUG FIX: Updating CSS to remove min-width for first column (level name) on Membership Levels table and in the "Membership" section of the Membership Account page.

Responsive update for smaller device viewports for Membership Levels tables.

---

classes/gateways/class.pmprogateway_authorizenet.php

Added filter `pmpro_authorizenet_level_description` to edit the order description sent to Authorize.net
1. Set payment gateway to Authorize.net with valid credentials
2. Install this Gist which prepends a username to an order description and un-comment the last line to enable the Authorize.net filter: https://gist.github.com/dparker1005/f048542f620038d91bc96f9baa4d9cc5
3. Perform a test checkout
4. Ensure that the user's username was included in the Authorize.net order description
* ENHANCEMENT: Added filter "pmpro_authorizenet_level_description"

Added filter pmpro_authorizenet_level_description

---

classes/gateways/class.pmprogateway_stripe.php
includes/functions.php

* Added pmpro_are_levels_recurring.
* Adjusted conditions to load stripe.js on billing page based on user's level status.

Stripe Billing Page Fix for Non-recurring members.

---

includes/functions.php

Fix pmpro_check_plugin_version
1.
2.
3.

Fixed pmpro_check_plugin_version

---

pages/checkout.php

Add filter pmpro_checkout_login_redirect to add additional parameters to the checkout page the user is redirected to after login
Resolves #1202 .
1. Use filter pmpro_checkout_login_redirect to add extra parameter to URL
2. Log in during checkout process
3. Ensure that the parameter is in the url after the redirect back to the checkout page

Added filter pmpro_checkout_login_redirect

---

pages/popup-cvv.html

Enhancement: Stop search engines from indexing this page.
Enhancement: Improve font-size for readability on desktop and mobile devices.
Enhancement: Stop search engines from indexing popup-cvv.html page.
Enhancement: Improve font-size for readability on desktop and mobile devices for popup-cvv.html page.
Closes Issue: https://github.com/strangerstudios/paid-memberships-pro/issues/1203
1. View the popup-cvv.html page in a browser of your choice.
Enhancement: Stop search engines from indexing popup-cvv.html page.
Enhancement: Improve font-size for readability on desktop and mobile devices for popup-cvv.html page.

Improve popup-cvv.html files

---

includes/login.php

Adjust login_url filter to load later to try load last.

Enhancement: Change login_url hook to load later.

---

includes/login.php

Enchancement: Front-end password reset functionality.
1. Test 'forgotten password'.
2. Check email for link.
3. Click email link, and reset password.
4. Try to break it to test error handling.

Frontend login password

---

includes/login.php

Enhancement: Added hook for `pmpro_login_url` redirect.
Enhancement: Added in hook for `pmpro_wp_signup_location` redirect.
Slightly improved code to use pmpro_hasMembershipLevel() instead of SQL.
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted
* Enhancement: Added hook for `pmpro_login_url` redirect.
* Enhancement: Added in hook for `pmpro_wp_signup_location` redirect.
* Slightly improved code to use pmpro_hasMembershipLevel() instead of SQL..

Enhancement: Hooks added

---

includes/login.php
includes/menus.php
includes/widgets.php
paid-memberships-pro.php
shortcodes/pmpro_login.php

Added a new shortcode [pmpro_login] with attributes like:
`[pmpro_login display_if_logged_in="1" show_menu="0" show_logout_link="1"]`
* We probably want to add support here for other variables like "true and yes" or "no and false".
Added new widget "Member Login/Log Out - Paid Memberships Pro"
Added new menu for "Member Form". This menu will be shown in the logged-in state of the pmpro_login_form() shortcode as handled by the new display state for a logged in member - pmpro_logged_in_welcome().

Login updates

---

includes/login.php

Only rewrite login_url if there is no redirect_to set.

Only rewrite login_url if no redirect_to is set.

---

includes/login.php

Bug Fix: Redirect login broke in attempt to improve code. `pmpro_hasMembershipLevel` not available at the time of login so put the SQL back.

Bug Fix: Redirect login broke in previous commits.

---

adminpages/pagesettings.php
css/frontend.css
includes/init.php
includes/profile.php
pages/member_profile_edit.php
paid-memberships-pro.php
preheaders/member_profile_edit.php
shortcodes/pmpro_account.php
shortcodes/pmpro_member_profile_edit.php
uninstall.php

1. Create new page for "Member Profile Edit" and insert shortcode: [pmpro_member_profile_edit] 
2. View the page on the frontend of your site
3. Update fields and save.
ENHANCEMENT: Adding new Member Profile Edit frontend page and form.
ENHANCEMENT: Adding new hooks to display additional frontend profile fields (pmpro_show_user_profile) and save them (pmpro_personal_options_update).

Adding frontend profile edit, member profile edit page, shortcode, form.

---

includes/login.php

Fixed issue missing `$wpdb->get_var`

Fixed redirect issue.

---

classes/gateways/class.pmprogateway_stripe.php
css/admin.css

Stripe connect changes in progress

---

includes/compatibility.php
includes/compatibility/theme-my-login.php
includes/login.php

1. Install any version of TML, 7.x or 6.4
2. Test login/logout/forgot password procedures.
3. All requests should go to TML instead of our own frontend.
* Enhancement: Moved Theme My Login Integration into it's own compatibility & rewrite some logic to improve performance/ease-of-use.
* Enhancement: Improved user authentication error handling logic to support more types of errors such as missing password, incorrect username etc.
* Filter: `pmpro_remove_frontend_login_hooks` allows a switch to turn off all of our front-end login logic if using another plugin to handle frontend profiles/login etc.
* Bug Fix: Improved handling of referrer and login redirect causing a false positive.

Theme My Login Compatibility + General Improvements.

---

adminpages/advancedsettings.php
adminpages/reports/memberships.php
adminpages/reports/sales.php
classes/class-pmpro-admin-activity-email.php
classes/class.activityemail.php
paid-memberships-pro.php
scheduled/adminactivityemail.php
scheduled/crons.php

Filled in the content for the Admin Digest Email
1. Set up this branch on your site
2. Disable and re-enable PMPro to set up the Activity Email cron
3. If you go to Advanced Settings and set the email to send daily, you can then navigate to `yoursite.com/wp-content/plugins/paid-memberships-pro/scheduled/adminactivityemail.php` to send an email for yesterday. You can also call the `sendAdminActivity()` function directly.

Filled in information for Admin Digest Email

---

adminpages/orders.php
classes/class.memberorder.php

Added time fields while editing an order
1.
2.
3.

Timestamps take2

---

includes/rest-api.php

Please note that this may still be a work in progress and is V1.
* Updated REST API further to support creating levels, discount codes and getting membership information from new route `pmpro/v1`.
* Requires new classes (Discount codes and Levels).
* TODO: Documentation to be updated with examples.
* Create/Update discount codes.
* Create/Update/Delete membership levels.
* Get user access for a post.
* Get level information for a user.
* Improved permissions for READABLE (subscriber) and WRITABLE (admin only) calls.

Rest api update

---

classes/class-pmpro-discount-codes.php
classes/class.discountcodes.php
paid-memberships-pro.php

* Initial commit for discount code class.
* Create/Update a discount code.

Discount class

---

includes/login.php

* Fixed general warnings when request parameters were not set.
* Fixed redirect issue when redirecting from wp-login via a link to membership account page. Improved our authentication to only run when form is submitted.

Frontend bug fixes

---

includes/login.php

* Minor logic fix.
* Always redirect to our frontend page.

Fixed bugs again.

---

classes/class-pmpro-discount-codes.php
includes/rest-api.php

Resolved some undefined index notices in REST api

---

includes/compatibility/beaver-builder.php

Resolves module visibility for Beaver Builder.
1. Install PMPro and Beaver Builder
2. Mark a module as protected
3. View the page incognito and the module should not be visible.

Removing user log in requirement for module visibility.

---

css/frontend.css
includes/login.php
includes/profile.php
includes/widgets.php
preheaders/member_profile_edit.php
shortcodes/pmpro_account.php
shortcodes/pmpro_member_profile_edit.php

* Frontend profile form adjustments
* Frontend password change for logged in user; TO DO: keep user logged in.
* Formatting and style adjustments
* Adding "Register" link to log in form to replicate core WP functionality.
* Adjusting frontend password reset error messages

Frontend login

---

css/frontend.css
includes/profile.php
pages/billing.php
pages/cancel.php
pages/confirmation.php
pages/invoice.php
pages/levels.php

Standardizing the class "pmpro_btn" for all form submit.
Updating our shortcode/pages nav to use our own class and design (no longer theme supported).
Adding "cancel" link for profile edit and change password.

Pmpro submit button updates

---

adminpages/advancedsettings.php
includes/content.php

* Added custom variables to non-member settings area: `!!login_url!!` and `!!levels_page_url!!`.
* Adjusted default message to include these variables instead of hardcoded links.

Content variables

---

includes/login.php

* Keep username field stored when login fails. if accepted.

Keep email when login failed.

---

classes/class-pmpro-members-list-table.php

1. Clear unused functions out of Memberslist table class
2. Break default_column() function into separate individual callback functions
3. Add new filters to standardize editing table columns
New filters:
- pmpro_manage_memberslist_columns
- pmpro_manage_memberslist_custom_column

Memberlist list table

---

classes/class.pmproemail.php

* Change !!login_link!! to use pmpro_login_url() instead for email class.f accepted.

Change wp_login_url to use pmpro_login_url

---

css/frontend.css
includes/login.php
includes/profile.php

Fixing responsive layouts and form widths.
Adjusting profile fields as discussed.
Adding hooks to logged in widget view.

Form class adjustments; Responsive forms adjustments; Frontend profile fields

---

css/frontend.css

Adding some additional spacing to forms

---

includes/login.php

Update to add a wrapping div to logged in version of the handler just like other form parts.

Wrapping div for logged in member view of forms handler

---

classes/class-pmpro-admin-activity-email.php

Fixed issues with Admin Activity Email

2.3 activity email fixes

---

includes/profile.php

* Added name attribute to Update Profile button and fixed minor spacing issue with wrapped text.

Add name attribute to submit button.

---

classes/class-pmpro-admin-activity-email.php

- Cleaning up the format / layout for some cases where cellspacing wasn't being respected.
- Now using the number_format_i18n function to format values in email (for sites with 1,000+ members).
- Fixed a few spots where esc_html and echo were being used - replaced with esc_html_e
- Fixed the logic to highlight to "required updates" for add on as red or leave blank if 0.
- Added PMPro icon and link to get support at footer

Admin email design adjustments

---

classes/class-pmpro-admin-activity-email.php
includes/email.php

Now removing header and footer from Admin Activity emails

Now removing header and footer from Admin Activity emails

---

blocks/blocks.js
blocks/blocks.php
blocks/login/block.js
blocks/login/block.php
blocks/login/inspector.js
js/blocks.build.js

1. Adds a login form block.
2. Four options the same as the `pmpro_login_forms_handler` function (`display_if_logged_in`, `show_menu`, `show_logout_link`, `location`).
1. Open up the Gutenberg editor.
2. Type '/login`
3. Install the block.
4. Configure the options, update, and view the page.
> Adding login block.

Adding login block.

---

css/frontend.css
includes/login.php
includes/profile.php
js/pmpro-login.js

- Fixed a typo where "reset" was missing an e.
- Updated logged in password change to use same field names.
- Updated the JS for strength meter to only check on pass1 (now used in both places)
- Some css updates for strength meter and fields.

Password Reset and Change Password Updates

---

blocks/blocks.js
blocks/blocks.php
blocks/member-profile-edit/block.js
blocks/member-profile-edit/block.php
js/blocks.build.js

Add a Member Profile Edit block.
1. Install the block on a post or page.
2. View the page.
3. Observe it now has editable fields for your profile.

Adding member profile edit block.

---

css/frontend.css
includes/functions.php
includes/login.php
shortcodes/pmpro_account.php

- Updating action links on the login page and the membership account page (2 locations) to build a filterable array.
- Adding new function to all filtering the separator in action links.
- Fixing title filters for logged in view of login page plus other bug with filtering more than just the main title of page.

Updates to action links; title filters; adds log out link to account page.

---

license.txt

updating copyright year

---

includes/compatibility/woocommerce.php

Fixed undefined constant bug #1331

---

includes/compatibility/elementor/class-pmpro-elementor-content-restriction.php
includes/compatibility/elementor/class-pmpro-elementor.php

* Enhancement: Support section blocking with membership levels.
* Enhancement: Improved docblocks and method names.
* Enhancement: Added in the following filters -
`pmpro_elementor_section_access`
`pmpro_elementor_has_access`

Support sections in Elementor

---

classes/class-pmpro-admin-activity-email.php

Hooked up pmpro_admin_activity_email_sections filter and added docblock.

Pmpro admin activity email sections fix

---

includes/login.php

Fix issue where is_main_query was causing fatal error in some cases. There was fatal error with https://wordpress.org/plugins/themeisle-companion/ when enabling the Social Media Sharing module.

Fix is main query

---

classes/class-pmpro-admin-activity-email.php

The word "Membership" may be filtered in the subject line of the Admin Activity email. This changes "Paid Memberships Pro" to "PMPro" in that subject line.

Updated subject line of admin activity email

---

services/ipnhandler.php

- Some refactoring;
- Logic fix: should avoid counterintuitive interpretation of false;
- Filter on ipn_logfile: I want to keep the history, can't log into pmpro folder;

PMPRO_IPN_DEBUG logic refactoring

---

classes/gateways/class.pmprogateway_stripe.php
js/pmpro-stripe.js
services/stripe-webhook.php

Stripe connect

---

classes/class-pmpro-admin-activity-email.php

Removed "Great Work!" text from admin activity email
Send admin activity email and verify that the text "Great Work!" is no longer present.

Removed "Great Work!" from admin activity email

---

classes/gateways/class.pmprogateway_authorizenet.php

Added filter `pmpro_authorizenet_post_values` to filter values sent to Authorize.net.

Added filter pmpro_authorizenet_post_values

---

adminpages/emailsettings.php
includes/admin.php
includes/lib/SendWP/installer.js
includes/lib/SendWP/sendwp.php

SendWP Integration initial commit.
TODO: Improve design/layout.

SendWP Integration.

---

includes/login.php

Fix fatal error: `Fatal error: Can’t use function return value in write context in /site/wp-content/plugins/paid-memberships-pro/includes/login.php on line 7`

Fixed fatal error when passing function as param to empty

---

classes/gateways/class.pmprogateway_stripe.php

- Application fee issue fixed
- Fixed credentials being deleted on payment settings page save
- URL params now cleared after connecting to Stripe

Stripe connect various updates

---

js/pmpro-admin.js

Checking that we are on Payment Settings page before running payment settings-specific JS code.

Fixing JS error when on admin pages

---

adminpages/dashboard.php

#1170 
I added in two additional links to the "Get Involved" section of the Membership Dashboard:
1) Subscribe to our YouTube Channel.
2) Follow us on Facebook.
I have tested the links and all seems to work as it should.
View screenshot here: https://snipboard.io/FzieNO.jpg
Added two additional social media links (YouTube & Facebook) to the Paid Memberships Pro - Member Dashboard.

Added in links to 'Get Involved' section of member dashboard.

---

includes/login.php

Fixes issue https://github.com/strangerstudios/paid-memberships-pro/issues/1383

Add the filter for login_url after WordPress is loaded.

---

includes/compatibility.php
includes/compatibility/wp-engine.php

Added WP Engine compatibility file to fix issue where attempting to reset a password on a WP Engine site would throw a 502 error.

Added WP Engine compatibility file

---

readme.txt

Adding new user to our readme for the "organization" account.

Adding new Paid Memberships Pro user to plugin readme.

---

includes/rest-api.php

* Bug Fix: Fixed typo for permission_callback for discount_code REST API route.

Adjust permission_callback for discount code.

---

includes/capabilities.php

Check that a role exists before adding capabilities to that role.

Resolving error if admin role does not exist.

---

readme.txt

Need date in changelog

---

shortcodes/pmpro_account.php

Because of a missing </a> tag, invoices weren't showing up properly on the account page.
Resolves invoices not showing up on the account page.
> Added missing </a> tag to account shortlink

Added missing </a> tag to account shortlink

---

includes/functions.php
preheaders/checkout.php
services/applydiscountcode.php

Fix issues in MMPU where correct price would may be shown after discount code is applied and where discount code may not apply successfully if it doesn't work for all membership levels:
https://github.com/strangerstudios/pmpro-multiple-memberships-per-user/issues/47
^ Want to do more testing.

applydiscountcode.php mmpu compatibility

---

includes/compatibility.php
includes/compatibility/divi.php

Includes compatibility with the Divi Page Builder. 
1. Install the Divi Page Builder
2. Create a new Section and Row
3. Click on the Row Settings -> Paid Memberships Pro, and then choose a level you'd like to restrict the content to
Integrates with the Divi Page Builder

Added Divi Compatibility

---

css/frontend.css

Fixing the frontend stylesheet for Stripe gateway when the payment request button is shown as well as custom content in the SSL Seal option.

Adjusting layout for payment request button when SSL seal code is present

---

includes/currencies.php

Add Ukrainian Hryvnia currency

---

includes/compatibility/beaver-builder.php

* ENHANCEMENT: Added in non-members option for Beaver Builder module.
1.  Install Beaver Builder.
2. Create a row/element inside a page/post using Beaver Builder and restrict to non-members
3. View content as non-member and/or member to show/hide the item accordingly.
* ENHANCEMENT: Added in non-members option for Beaver Builder module.

ENHANCEMENT: Include non-members to Beaver Builder module

---

classes/gateways/class.pmprogateway_stripe.php
js/pmpro-stripe.js

Fixed bug where incorrect currency may be charged while using Payment Request button. Also now getting the correct country for the Stripe account, which may prevent further issues.

Payment request currency

---

classes/gateways/class.pmprogateway_stripe.php

Avoid notices, even if never happened to me (because that code probably never run).

Avoid notice on undefined variable

---

pages/levels.php

Users can now have multiple levels show up as "Your Level". Necessary for adding PayPal compatibility for MMPU.

Cleaned up levels page template and added MMPU compatibility

---

preheaders/checkout.php

This is very useful to complete the pmpro-gift-levels lookup table proposed [here](https://gist.github.com/mircobabini/c694770e217e483b249be9941eb07ff3/) and based on another filter into pmpro-gift-levels PR'ed [here](https://github.com/strangerstudios/pmpro-gift-levels/pull/29).

New filter when a discount code is used

---

uninstall.php

Add meta tables to uninstall process

Add meta tables to uninstall process

---

classes/class-pmpro-members-list-table.php

Needed to avoid bad red highlights in PhpStorm:

Better return type in sql_table_data doc

---

includes/functions.php

Fix $param to @param (Argument PHPDoc missing)

---

classes/class.memberorder.php

Now passing billing street in pmpro_tax filter.

Now passing billing street in pmpro_tax filter.

---

includes/login.php

BUG FIX/ENHANCEMENT: Fixed an issue where the password reset form would show (but not submit) if reset key was invalid. This change now shows the password reset form if someone visits the password reset page with fake/incorrect keys.

BUG FIX/ENHANCEMENT: Fixed password reset UI

---

js/pmpro-stripe.js

ENHANCEMENT: Automatically set the locale of the Stripe checkout fields based on the user's browser locale. Improves translations.

Allow translation of Stripe's hosted fields.

---

includes/rest-api.php

ENHANCEMENT: Improve security by sanitizing and escaping on query parameters in the REST API.

Escaping and Sanitizing REST API

---

pages/checkout.php
preheaders/checkout.php

Move reCAPTCHA field to above submit button and show for logged-in users.

reCAPTCHA is now shown for logged-in users

---

css/admin.css

User reported that the Members List formatting was not satisfactory. I took another look at this and agreed that we shouldn't set a min width on certain columns. Also, I found that WP core list table UI is forcing a min width on the display name column. 
This PR also does a WPCS pass on the admin.css file to fix up formatting.

Admin css members list

---

blocks/membership/block.js
js/blocks.build.js

Fix the checkboxes not working in the "Require Membership" block

Fixed require membership block checkboxes

---

pages/checkout.php

New filter for developers. Permits to specify a more informative message when something goes wrong on checkout. Useful when PP returns "Internal Error" if you try to set up a recurring payment using a bank account with no CC fallback.
New pmpro_checkout_message filter for checkout error message

New pmpro_checkout_message filter for checkout error message

---

services/twocheckout-ins.php

Fix pmpro_twocheckout_validate filter.

Fixed pmpro_twocheckout_validate filter

---

languages/email/de_DE/admin_change.html
languages/email/de_DE/admin_change_admin.html
languages/email/de_DE/billing.html
languages/email/de_DE/billing_admin.html
languages/email/de_DE/billing_failure.html
languages/email/de_DE/billing_failure_admin.html
languages/email/de_DE/cancel.html
languages/email/de_DE/cancel_admin.html
languages/email/de_DE/checkout_check.html
languages/email/de_DE/checkout_check_admin.html
languages/email/de_DE/checkout_express.html
languages/email/de_DE/checkout_express_admin.html
languages/email/de_DE/checkout_free.html
languages/email/de_DE/checkout_free_admin.html
languages/email/de_DE/checkout_freetrial.html
languages/email/de_DE/checkout_freetrial_admin.html
languages/email/de_DE/checkout_paid.html
languages/email/de_DE/checkout_paid_admin.html
languages/email/de_DE/checkout_trial.html
languages/email/de_DE/checkout_trial_admin.html
languages/email/de_DE/credit_card_expiring.html
languages/email/de_DE/footer.html
languages/email/de_DE/invoice.html
languages/email/de_DE/membership_expired.html
languages/email/de_DE/membership_expiring.html
languages/email/de_DE/trial_ending.html

* changed file encoding to UTF8 (from ANSI Western Windows1252) to properly display german umlauts
* corrected some small spelling errors in checkout_express_admin.html and invoice.html
Resolves https://www.paidmembershipspro.com/forums/topic/utf-8-encoded-german-email-templates/#post-330219.
1. with german locale use any action which creates an eMail notification
2.
3.
> changed file-encoding to UTF8

file-encoding to UTF8 for de_DE eMail template files

---

adminpages/reports/history.php
includes/deprecated.php
includes/profile.php

Member history Merging into core

---

includes/deprecated.php

Fix conditional for deprecated notice, fixes an issue where it always shows.

BUG FIX: Deprecated notice showing incorrectly

---

includes/init.php

Fix to the Users page in the WordPress admin to allow sort by Membership Level custom column.
* BUG FIX: Fixed bug with sortable column Membership Level on Users page in the WordPress admin.

Users membership level sort

---

includes/init.php

Class is now applied to html body if PMPro page block is used.
Resolves #967 .

Class is now applied to html body if PMPro page block is used.

---

adminpages/discountcodes.php
adminpages/membershiplevels.php

Not linking to the checkout page from the admin levels table or discount code table if PMPro pages are not set up
Resolves #1113.
See issue above.

Not linking to checkout page if pages not set up.

---

css/admin.css

Fixed a merge conflict in the CSS for admin area.

Resolving a merge conflict in admin.css

---

includes/functions.php

`global $wpdb` is not needed (anymore?).

Clean code -- remove useless scope

---

adminpages/orders.php

This PR adds back the "order saved successfully" message when an order is updated on the Memberships > Order > Edit Order page. It was mistakenly removed in this merged PR: https://github.com/strangerstudios/paid-memberships-pro/commit/144b157723d6f0b2a5f5088c992e7d81134679eb

Adding message back when an order is successfully saved/updated.

---

classes/gateways/class.pmprogateway_paypalexpress.php

Safely access session contents

---

includes/lib/stripe-apple-pay/stripe-apple-pay.php

Fixed non-prefixed function name

---

adminpages/dashboard.php
adminpages/reports/login.php
classes/class-pmpro-members-list-table.php

Convert `user_registered` time from GMT to local when showing in reports.
Resolves #1665 .

User registered date is now shown in local time.

---

adminpages/membershiplevels.php
adminpages/orders.php

Add additional actions to the Order and Level admin forms for more customizations.
Non-breaking changes allow you to continue to add/edit Membership Levels and Orders.
> Add `pmpro_membership_level_after_content_settings` and `pmpro_after_order_settings_table` actions to the Level and Order admin forms for more customizations.

Add new actions and add phpcdoc for hooks where possible

---

services/getfile.php

BUG FIX: Fixed a minor issue where query parameters were swapped around for the getfile script.

BUG FIX: Fix explode parameters

---

adminpages/emailtemplates.php
classes/class.pmproemail.php
css/admin.css
email/payment_action_admin.html
includes/deprecated.php
includes/email-templates.php
includes/email.php
js/pmpro-admin.js

* Improvements to layout of the Memberships > Settings > Email Templates admin page.
* Fix styling of the template updates, errors, etc. messages shown on the form processing.
* Fixed typo in the subject line for word "udpated" => "updated". Note: the language packs need to be rebuilt for this, I only modified the default.
* Added fallback option to get_user_by email address before fallback to current_user for the `pmpro_email_templates_email_data` function.
* Updated the message on deprecated Add Ons to be deleted.
* Added a few template variable replacements to emails where that data is and should be available.

UI, documentation, and functionality improvements for email templates merge to core

---

.github/workflows/generate-translations.yml

Implements new GitHub Action for Generate Translations manual workflow.
1. After merge, manually trigger the action and specify the branch under the repo at Actions > Generate Translations
2. It will generate the translations and commit to that branch
N/A

Add Generate Translations manual workflow action

---

classes/class.pmproemail.php
includes/email-templates.php

Make capitalization uniform in subject lines.

Make capitalization uniform in subject lines

---

classes/class-pmpro-subscription.php
classes/class.memberorder.php
classes/gateways/class.pmprogateway.php
classes/gateways/class.pmprogateway_paypalexpress.php
classes/gateways/class.pmprogateway_stripe.php
includes/functions.php
includes/setup.sql
includes/upgradecheck.php
paid-memberships-pro.php
preheaders/checkout.php
services/braintree-webhook.php
services/ipnhandler.php
services/stripe-webhook.php

Just a sync PR, not merging anything to any releases

Bring over current Subs Table work from fork

---

adminpages/paymentsettings.php
classes/gateways/class.pmprogateway_stripe.php

Adjusted the destination of a few documentation links now that the new documentation has been published.

Adjusting links to our docs sites for newly created pages.

---

blocks/blocks.php

1. Go to post editor (or any editor that has PMPro blocks enabled)
2. See Require Membership block is available
3. Can use Require Membership block in post and choose from list of levels
> Fix Block dependency needed for showing Membership Levels.

Add information needed by the Blocks JS for levels

---

adminpages/emailsettings.php

Small link update to where the View Your SendWP Account link directs to (they changed their URL structure).
* BUG FIX/ENHANCEMENT: Updated the link to SendWP account for their new account page URL.

Updating account URL for SendWP per their new dashboard area.

---

includes/admin.php

Fixes #1748
1. Install [Paid Memberships Pro](https://wordpress.org/plugins/paid-memberships-pro/).
2. Go to Memberships -> Setttings -> Advanced (`/wp-admin/admin.php?page=pmpro-advancedsettings`).
3. Enable the "Block all users with the Subscriber role from accessing the Dashboard." option.
4. Install [MailPoet](https://wordpress.org/plugins/mailpoet/).
5. Create a couple different MailPoet newsletter lists and add one of your users with a Subscriber role to the lists.
6. Log out and log in as the user with the Subscriber role.
7. Go to the "Manage your subscription" page (located at `yoursite.com/?mailpoet_page=subscriptions&mailpoet_router&endpoint=subscription&action=manage&data` by default)
8. Change which lists you're subscribed to and press Save.
9. Confirm the save is successful …

Check $pagenow for admin-post.php on whether to block dashboard

---

includes/functions.php

Fix a typo (in a comment)

---

adminpages/dashboard.php

Resolves the minor design issue in body colspan:

Dashboard widget body colspan match head number of columns

---

paid-memberships-pro.php

Housekeeping: bump credits year, fix a typo, align comments, i18n

---

adminpages/discountcodes.php

Defined some missing variables.

Define missing local and global variables

---

includes/deprecated.php

We had an issue because of the uninstall.php which runs on plugins uninstall even if disabled. This caused a complete pmpro's db related things cleanup on deletion of pmpro's duplicate. With this PR, we are essentially removing the uninstall.php on pmpro's duplicates, just a second before it's run.
The issue may happen in two cases:
1. With an old version of pmpro (before May 2020 release) which had no pmpro_uninstall option.
2. With a new version of pmpro if pmpro_uninstall is set to 1.
1. Create a membership
2. Create an order
3. Download an old pmpro's version without the pmpro_uninstall option in uninstall.php (added in [May 2020](https://github.com/strangerstudios/paid-memberships-pro/commit/c112b1ef19b1d9e9611c47bdb5582ac0d08bdddc#diff-445f7da6877bb1dda2e959aa7e2bfe91657e7738aca6c2e4 …

Dont let uninstall.php run on duplicates uninstall

---

js/pmpro-stripe.js

Added additional documentation to pmpro-stripe.js

Document pmpro-stripe.js

---

adminpages/emailtemplates.php

Added to list of available email variables
!!membership_level_confirmation_message!!

add missing email var

---

classes/gateways/class.pmprogateway_stripe.php

Refactor some re-used code in the Stripe class into its own private function.

Refactored Stripe currency unit multiplier logic

---

classes/gateways/class.pmprogateway_stripe.php

Now sending application info to Stripe when using the Stripe API. Based off of these Stripe docs: https://stripe.com/docs/building-plugins#setappinfo
>
After checking out this branch, check out with Stripe. Then in the Stripe Dashboard, go to `Developers > Logs` and check that the API calls made during that checkout include PMPro information in the "Source" section screenshotted above.

Setting app info for Stripe API calls

---

classes/gateways/class.pmprogateway_stripe.php

Simplified AJAX handling methods for creating/deleting/rebuilding Stripe webhooks.

Stripe webhook ajax cleanup

---

classes/class-pmpro-subscription.php

Made properties of PMPro_Subscription class private and added getters/setters.

Made properties of PMPro_Subscription class private

---

classes/class-pmpro-subscription.php
tests/wpunit/PMPro_SubscriptionTest.php

Updates tests for compatibility with #1839

Update tests for compatibility

---

paid-memberships-pro.php
readme.txt

Update plugin version and add changelog

---

adminpages/discountcodes.php
adminpages/orders.php

Fixes XSS issues with the discount codes page in the dashboard.
SECURITY: Updated escaping on the discount codes page in the dashboard to prevent XSS attacks. (Thanks, Erwan from WPScan)

Fix output escaping for attributes

---

includes/rest-api.php

Cleaned up REST API for Zapier requirements.
Added in function `pmpro_format_date_iso8601` to return a ISO-8601 date format which is required by Zapier triggers.
1. Test this with v1.0.2 Zapier native PMPro integration. (Zapier 1.0.2 won't work until you merge this PR in as it changes data structure).
Improve the REST API to support Zapier native requirements.

Cleaned up REST API For Zapier

---

adminpages/orders.php
adminpages/reports/sales.php
classes/class.memberorder.php

1. /wp-admin/admin.php?page=pmpro-orders - Shows if the order is a renewal or not
2. /wp-admin/admin.php?page=pmpro-reports&report=sales - Shows renewals and new orders on the chart

Queries updated in Charts & Orders Page

---

classes/gateways/class.pmprogateway_stripe.php

Replaced use of deprecated method set_customer()

Replaced use of deprecated method set_customer()

---

adminpages/pagesettings.php

Reverts strangerstudios/paid-memberships-pro#1913

Revert "Backwards compatibility for sites pre 7.4"

---

classes/class-pmpro-field.php

Adds new hooks to better support the needs of custom field types.
1. Check out this code
2. Add the example custom field type snippet: https://gist.github.com/sc0ttkclark/7a5b53a05b2ffbfd4d017c9db4426675
3. Go to Member Profile form / Checkout page and see three new example fields that shows off datetime/date/time HTML5 fields as created.
> Add new hooks to better support custom field types including `pmpro_field_set`, `pmpro_field_get_html_$type`, `pmpro_field_display_value_$type`, pmpro_field_display_value`, `pmpro_field_was_filled_if_needed_$type` and `pmpro_field_was_filled_if_needed`

Better support custom field types with new hooks

---

classes/class-pmpro-subscription.php
classes/class.memberorder.php
classes/gateways/class.pmprogateway_stripe.php

Implementing setter for PMPro_Subscription class.

Implementing setter for PMPro_Subscription class

---

logs/stripe-webhook.txt
services/stripe-webhook.php

Refactored Stripe webhook handler to remove duplicate code for adding billing and payment information to order. Also made various other improvement to Stripe Checkout webhook handling.

Stripe checkout webhook refactor

---

classes/gateways/class.pmprogateway_stripe.php

Took a pass on improvements to the descriptive information about Stripe Checkout beta and the fields in the settings page.

Updating field names, values, and descriptive text for Stripe Checkout beta.

---

classes/class-pmpro-subscription.php
tests/_support/Factories/PMPro_OrderFactory.php
tests/_support/TestCases/TestCase.php
tests/wpunit/PMPro_SubscriptionTest.php

Also implements orderby handling for PMPro_Subscription::get_subscriptions()

Introduce initial payment handling for PMPro_Subscription and get_orders() logic

---

classes/class-pmpro-subscription.php

Added some validation in save method of subscription class

Subs-table-save

---

classes/class-pmpro-subscription.php

Put together core functionlity for cancel() method of PMPro subscription object

Subs-table-cancel

---

classes/class-pmpro-subscription.php
classes/class.memberorder.php

Allowing for updating PMPro Subscriptions from unsupported gateways

Subs-table-default-next-payment-date

---

classes/class-pmpro-subscription.php

Fixed the variable name in PMPro Subscription's update method

Subs-table-update-method-var-names

---

classes/gateways/class.pmprogateway_paypalexpress.php

Now settings subscription start date for PPS subs

Subs-table-ppe-startdate

---

classes/class-pmpro-subscription.php

Update subscription when a recurring payment is made.

Subs-table-process-ipn-webhooks

---

classes/class-pmpro-subscription.php

Only set subscription enddate if we don't have one yet.

Subs-table-cancel-set-enddate

---

adminpages/advancedsettings.php

Fix typo in settings

---

classes/gateways/class.pmprogateway_paypal.php
classes/gateways/class.pmprogateway_paypalexpress.php
classes/gateways/class.pmprogateway_paypalstandard.php

This new action is useful when you have to:
- investigate the API responses for each http post call, to search for some specific data
- investigate the API responses for consistency and looking for weird cases
- catch some response values which might be useful later on (ex. PAYERID, EMAIL from GetExpressCheckoutDetails)

New filter to perform actions using http post request's response

---

includes/functions.php

This PR fixes and improves various PHPDocs in `includes/functions.php`.
Since only comments are changed. The only way to "test" this is to open the file in your IDE and hover over function names to see the improved PHPDocs, if your editor has that sort of feature.
* [n/a] Have you successfully run tests with your changes locally?
> Improved PHPDocs for various functions in `includes/functions.php`.

Fix/improve various PHPDocs in `includes/functions.php`.

---

adminpages/orders.php

Discount deletion message says which discount has just been deleted.
This was not the same for order's deletion. This is the fix.

Order's deletion message similar to discount's deletion message

---

includes/functions.php
includes/setup.sql
includes/upgradecheck.php
tests/class-base.php

Adding subscription meta table.

Adding subscription meta table

---

adminpages/orders.php

Updated the text to make it clear what will happen when the refund is ok'd.

Updating the Refund -> Ask First confirmation window text.

---

blocks/account-profile-section/block.js
blocks/login/block.js
blocks/member-profile-edit/block.js
blocks/membership/block.js

Resolves #2063.
Requires blocks rebuild and localization action to run.

Fix typos in membership and member-profile-edit blocks and account-profile-section

---

includes/fields.php

Implemented the changes from the following Register Helper pull requests:
- https://github.com/strangerstudios/pmpro-register-helper/pull/235
- https://github.com/strangerstudios/pmpro-register-helper/pull/239

Implemented changes from RH PRs

---

js/pmpro-admin.js

Could not completely test as there were some issues with the current User Fields branch. Going to look into those and then test afterwards.

Showing warning when user leaves user fields settings without saving

---

services/stripe-webhook.php

* Rework the getOldOrderFromInvoiceEvent method logic to support newer Stripe API versions. (includes minor WPCS)
Note: Try to get it from the object, then the invoice ID and lastly fallback to the event ID to support some cases.
* Rework the getOldOrderFromInvoiceEvent method logic to support newer Stripe API versions.

Rework getOldOrderFromInvoiceEvent function

---

includes/compatibility/divi.php

Since we're already using a singleton class to organize thing, let's move this new function into the class. This will also prevent issues if anyone was already using a gist with the function named divi_pmpro_element_class.
I also changed the other methods into static ones and changed $this to __CLASS__ in the add_filter calls. This makes it easier to unhook things if needed.

Some refactor of the Divi compatibility class

---

adminpages/userfields.php
js/pmpro-admin.js

The alternitative is to show a message when there are unsaved changes, but I couldn't get that message to look right. We can revisit this problem if this solution isn't good enough.

Now disabling the user fields save button until changes are made.

---

classes/class-pmpro-field.php

Missing a couple of properties, specifically for the "file" field type, but we can catch these as we go.

Declared most properties for PMPro_Field class

---

classes/gateways/class.pmprogateway_braintree.php

Added subs table compatibility for Braintree

Added subs table compatibility for Braintree

---

classes/class-pmpro-field.php
includes/fields.php

Double checking some escaping across the user fields/register helper stuff.
Using wp_kses_post for labels, descriptions, hints, etc.
Needs some testing.

User fields admin escaping

---

adminpages/addons.php
js/pmpro-admin.js

So far, fixing the "upgrade license" popup and fixing links on admin add on page. Also removed primary button styling.

Add On Admin Tweaks

---

css/admin.css

Small CSS improvement and RTL testing to the checkmark added to the button on the Memberships > Add Ons > Install/Activate JS behavior.

Fixing the checkmarked class for Add Ons install/activate button

---

license.txt

Bump license year 2022

---

adminpages/membershiplevels.php

* BUG FIX: Fix stray comma from sprintf in Membership Levels admin page.
Resolves: #2176

Remove stray comma from sprintf

---

includes/functions.php

Resolves #2164 and many others wrong docblocks in functions.php
+ adds some globals where missing.
+ fix a $statuses variable declaration misplaced.

Enhance docblocks in functions.php

---

css/admin.css

- The Add Ons admin page was breaking on smaller screens due to a missing curly brace to close a media query in the user fields CSS. This fixes that bug.
- Also formats CSS to use tabs in all indents (some were 2 or 4 spaces).
- Alphabetized some CSS properties.

Missing curly brace was breaking media queries and Add On ui; formatting and alphabetizing some properties

---

classes/gateways/class.pmprogateway_paypalexpress.php

PPE: Fix typo in docblock variable name

---

includes/fields.php

Removed unnecessary space
Resolves [2203](https://github.com/strangerstudios/paid-memberships-pro/issues/2203).
1. Create custom field programmatically and publish to pmpro_add_user_field( 'after_username', $field );
2. Navigate to the checkout page
3. Confirm that field is displayed after the username field on the checkout page.

Remove extra space

---

includes/fields.php

Correct spelling.
Resolves [2022](https://github.com/strangerstudios/paid-memberships-pro/issues/2202)

Correct spelling

---

includes/fields.php

Cleaning up checkout box names when used in HTML element IDs to avoid spaces and special characters.

Avoiding issues for checkout box names with spaces

---

includes/functions.php
js/pmpro-admin.js

Prevent field names from beginning or ending with underscores.

Trim underscores from field names

---

services/stripe-webhook.php

Fixes issue where PMPro memberships would not be cancelled when subscription is cancelled in Stripe.
In order to make the webhook handler more readable and to prevent these kinds of bugs in the future, the webhook handler has also been refactored to deprecate the `getOrderFromInvoiceEvent()` and `getOldOrderFromInvoiceEvent()` functions. Those functions were responsible for handling passed Charges, Invoices, and Subscriptions which made the logic confusing to follow and prone to errors. Instead, we are now using the exact logic needed for each individual event handler.

Fix webhook for subscription cancellations and refactor for clarity

---

includes/fields.php

Fields i18n: default group name should be translatable

---

classes/class-pmpro-wisdom-integration.php

Add function_exists for wp_get_environment_type

---

css/admin.css
includes/notifications.php

Also allowing `<strong>` tag in the escaping.
* ENHANCEMENT: Improved appearance of in-app notifications.

Improving our in-app notification styling

---

languages/pages/de_DE/popup-cvv.html
pages/popup-cvv.html

Fixing CSS causing text to not fit in popup.
Navigate to `https://yoursite.com/wp-content/plugins/paid-memberships-pro/pages/popup-cvv.html`

Fixing popup CSS

---

classes/gateways/class.pmprogateway_stripe.php

If a Stripe account is based in specific countries, an error will be thrown if PMPro tries to add an application fee. Here is an example error:
`Stripe doesn't currently support application fees for platforms in US with connected accounts in MX.`
This change is a temporary fix in order to avoid these errors from being thrown.

Avoid adding application fees for some countries

---

classes/gateways/class.pmprogateway_stripe.php

When SCA checks on subs fail, the sub was still created but orphaned and often billed the user double/extra later.
We hear that subs created without the SCA check tend to work or fail no matter how the initial check went, so... we can skip it. Even if the recurring payments fail, they will trigger the failed payment email/process and the invoice.payment_action_required email/process via the webhook handler.
This PR removes the SCA authorization prompts after a subscription is created at checkout.
If there are unforeseen issues with doing things this way, we will need to revert, but then also handle the case where SCA fails. We should clean things up by deleting the subscription that was created before showing the error to the user.
This PR replaces this one: …

This PR removes the SCA prompts after a subscription is created at checkout.

---

adminpages/wizard/done.php
adminpages/wizard/payments.php

Localizing and escaping some strings.

Localized and escaped some strings

---

adminpages/advancedsettings.php

* Added more HTML elements to the allowed HTML for field descriptions in advanced settings page.

Add more allowed HTML for field descriptions

---

classes/class.pmproemail.php

* ENHANCEMENT: Added !!levels_url!! to all email templates by default.
* ENHANCEMENT: Added docblocks to all methods of the PMProEmail class.
Note about improved WPCS to certain sections of the code.This was not an entire WPCS effort for the entire class. (This can be done after this PR is merged).
Resolves: https://github.com/strangerstudios/paid-memberships-pro/issues/2118

Added !!levels_url!!, docblocks and minor WPCS to sections of the email class.

---

adminpages/reports.php
adminpages/reports/login.php
css/admin.css

Adjusting appearance of logins report to start - added styles for the filter box.
Added submenu navigation for reports area to navigate between reports.

Feature reports improvements

---

classes/gateways/class.pmprogateway_stripe.php
services/stripe-webhook.php

Improved accuracy of checking Stripe webhooks and now checking for each event type individually.

Stripe webhook checker improvements

---

includes/deprecated.php
paid-memberships-pro.php

Deprecate CyberSource and PayPal Website Payments Pro.

Deprecate CyberSource and PayPal Website Payments Pro

---

includes/profile.php

* Remove `enddate = ''` check in SQL when expiration date is set to NO to resolve PHP warning on profile save.

Fix warning on user edit.

---

classes/gateways/class.pmprogateway_authorizenet.php

There were a debug echo in that code, older than 3 years. It's useless in production.
1. Subscribe for a recurring level using Authorize.net
2. It should still work

Remove a debug line in Authorize.net gateway

---

includes/content.php
includes/metaboxes.php
includes/terms.php
paid-memberships-pro.php

Restricting tags and improved categories

---

js/pmpro-admin.js

Just a small text update for misspelling :)

Fixing typo for add on install that cannot install.

---

languages/email/nl_NL/checkout_check_admin.html
languages/email/nl_NL/checkout_express_admin.html
languages/email/nl_NL/checkout_free_admin.html
languages/email/nl_NL/checkout_freetrial_admin.html
languages/email/nl_NL/checkout_paid_admin.html
languages/email/nl_NL/checkout_trial_admin.html

Seems like we merged in some broken tags for NL email templates.
Time to strip them out.

Fix nl_NL template tags

---

adminpages/addons.php
adminpages/reports/sales.php
includes/fields.php
services/twocheckout-ins.php

Using PhpStorm static analysis to fix some var references.

Fix some undefined vars

---

adminpages/discountcodes.php
adminpages/login-csv.php
adminpages/membershiplevels.php
adminpages/orders-csv.php
adminpages/orders.php
adminpages/reports/login.php
adminpages/reports/memberships.php
adminpages/reports/sales.php
classes/class-pmpro-admin-activity-email.php
classes/class-pmpro-discount-codes.php
classes/class.memberorder.php
includes/content.php
includes/functions.php
includes/profile.php
services/applydiscountcode.php
shortcodes/membership.php

Escape SQL and wpdb::prepare where possible

---

includes/functions.php

* SECURITY: Improved escaping for the pmpro_getCheckoutButton function. This fixes possible security issues with the pmpro_checkout_button shortcode and other instances.

Escaping output for the pmpro_getCheckoutButton

---

includes/fields.php

We made a [fix for the checkout field groups](https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/fields.php#L306) to sanitize the group name when adding to the CSS selectors. This same change wasn't reflected for fields added to the edit user profile page.
I'm not 100% sure on this change - should we keep it as a "class" selector on the frontend profile page groups or match the markup as we do on the checkout form? 
I'm open to either way - on the checkout form, it's the div ID. I think it might be better to match that so if you want that change I'll update. I don't think we should add the class="pmpro_checkout" though to groups added to the frontend profile edit screen at least for now.
1. Create a user field group with spaces in the name.
2. Check the HTML source …

Fixing fields group css selector added to frontend user profile

---

shortcodes/pmpro_member.php

1. Create a user field of type multiselect or select2 with a few options.
2. Edit your own user profile to choose a couple of these values.
3. Insert the shortcode [pmpro_member field="myfieldkey"]
4. Note that before this fix, the output will be "Array" with a notice in the error log. After, you get a comma separated string of the values in the array.
Note here that in my testing, a user field with values like "1:One;2:Two;3:Three" seemed to store the user meta value as One/etc instead of 1/etc. Let's make sure this is saving as intended... and also if we change it, it supports some kind of conversion. (sigh) And then if user fields are stored with keys instead of values, let's see if we can look up the values in the user meta field and output those instead of the keys.
Consider handling …

Convert arrays to comma separated strings.

---

services/stripe-webhook.php

Making sure that we have a valid user during the Stripe Webhook Handler.
Fixes this PHP error:
`[........] PHP Fatal error: Uncaught Error: Attempt to assign property “membership_level” on bool in /home/......../public_html/wp-content/plugins/paid-memberships-pro/services/stripe-webhook.php:124
Stack trace:
#0 /home/......../public_html/wp-content/plugins/paid-memberships-pro/includes/services.php(40): require_once()
#1 /home/......../public_html/wp-includes/class-wp-hook.php(308): pmpro_wp_ajax_stripe_webhook(”)
#2 /home/......../public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(”, Array)
#3 /home/......../public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /home/......../public_html/wp-admin/admin-ajax.php(203): do_action(‘wp_ajax_nopriv_…’)
#5 …

Making sure that we have a valid user during the Stripe Webhook Handler

---

classes/gateways/class.pmprogateway_stripe.php
includes/updates/upgrade_2_10.php
includes/upgradecheck.php

Increases Stripe application fee to 2%. Sites that are already using Stripe at 1% will continue to use that reduced fee.

Increasing stripe fee to 2% and cleanup

---

adminpages/admin_footer.php

Useful if you want to highlight / hide the "rate us" message to other managers and so on.

Rate us footer notice: add css class

---

classes/gateways/class.pmprogateway_stripe.php

Updating payment settings for Stripe to show correct application fee.

Updating wording to reflect increased stripe fee

---

css/admin.css
includes/admin.php

Small adjustment to style for dismiss buttons (in addition to the dismiss X we already show) in notifications.

Adjusting dismiss button in notification

---

adminpages/discountcodes.php
adminpages/login-csv.php
adminpages/memberships-csv.php
adminpages/memberslist-csv.php
adminpages/orders-csv.php
adminpages/orders.php
adminpages/reports/login.php
adminpages/reports/memberships.php
adminpages/reports/sales.php
classes/class-pmpro-admin-activity-email.php
classes/class-pmpro-members-list-table.php
includes/content.php
includes/functions.php
includes/init.php
services/applydiscountcode.php
shortcodes/membership.php

Fixing some SQL injection vulnerabilities by casting to `int`s and using `intval()` instead of using `esc_sql()`.

Fixing SQL injection vulnerabilities

---

license.txt

@kimcoleman year to be updated in [this blog post](https://www.paidmembershipspro.com/paid-memberships-pro-is-100-gpl-and-why/) too.

Bump year license

---

includes/filters.php

Default spam protection to enabled for new sites to avoid checkout spam.

Default spamprotection to enabled for new sites

---

includes/admin.php

Show notice for sites with spam protection disabled

---

classes/gateways/class.pmprogateway_stripe.php

We have seen some sites sent out duplicate refund notification emails after a Stripe payment was refunded in PMPro. This could potentially be due to a race condition where the Stripe refund webhook begins processing before the order status is updated to `refunded`.
If this is in fact the issue, this PR will make this race condition less likely to occur by updating the order status sooner.

Fixing webhook race condition in refund emails

---

classes/gateways/class.pmprogateway_stripe.php

Loop subscriptions only if there are some

---

js/pmpro-cancel.js
preheaders/cancel.php

Now disabling links on cancel page once one is clicked.

Prevent multiple clicks on cancel page

---

services/stripe-webhook.php

Adding actions `pmpro_stripe_webhook_event_received` and `pmpro_stripe_webhook_before_exit` to Stripe webhook handler.

Adding actions to Stripe webhook handler

---

css/frontend.css

Small adjustment to hover the discount code "apply" button. This was introduced in the larger accessibility PR that changed the Apply from a "link" to a "button" for accessibility.

Adjusting discount code apply button hover

---

adminpages/wizard/memberships.php
css/admin.css

Updates to the Membership tab of wizard to make it more understandable.
https://github.com/strangerstudios/paid-memberships-pro/assets/5312875/44ee87ef-780f-46e4-ab5e-e148111dcfbb

Adjusting the layout and functionality of the add levels section on wizard

---

shortcodes/pmpro_account.php

Fixes localization issues on the account page.

Fixing text domains in account page shortcode

---

js/pmpro-checkout.js

Update approved by Jason to add the HTML5 required attribute for accessibility and checkout experience improvement.
* ENHANCEMENT: Now using HTML5 required field attribute on required fields at membership checkout.

Add html5 required attribute to field to checkout fields

---

js/pmpro-checkout.js

Reverts strangerstudios/paid-memberships-pro#2511

Revert "Add html5 required attribute to field to checkout fields"

---

includes/login.php

Rework the password reset redirect functionality (Jason, Maxi and I) on a CodeTogether session to fix a potential issue where the login page ID that gets referenced returns an empty permalink, resulting in a broken link being shared.
The same function needs to be applied to other password reset functions.

Reworks the password reset redirect functionality

---

includes/login.php

Reworks the pmpro_do_password_reset function to return early where necessary

Reworks the do password reset function

---

includes/login.php

Reworked the login failed function to return early where necessary, along with some minor refactoring

Reworked the login failed function

---

includes/login.php

Reworks the login URL redirect filter to return early where necessary

Reworked the login URL filter

---

classes/class-pmpro-discount-code-list-table.php

Changes the item ID reference from an object to an array. 
This can be tested with this PR which adds a custom column to the new discount code list table. 
1. Add this recipe to the site https://github.com/strangerstudios/pmpro-snippets-library/pull/105
2. The fields should return the relevant descriptions where applicable

Fixes pmpro_manage_discount_code_list_custom_column ID reference

---

includes/compatibility/lifterlms.php

[bugfixing] fix remove_meta_box function call.

---

adminpages/advancedsettings.php
includes/compatibility.php
includes/compatibility/lifterlms.php

We want to streamline LifterLMS when it is installed for the first time if PMPro is active.
Based on this @MaximilianoRicoTabo's original PR: https://github.com/strangerstudios/paid-memberships-pro/pull/2518
Replaces this other PR too: https://github.com/strangerstudios/paid-memberships-pro/pull/2533

LifterLMS Streamline Take 4

---

adminpages/wizard/done.php

Fixes cases where the site can't connect to our license server, such as when using the [WordPress Playground](https://wasm.wordpress.net/?theme=memberlite&url=/wp-admin).
Before:
After:

Checking if Add On exists before showing

---

includes/notifications.php

Resolves XXX.
1. Uninstall PMPro
2. Create a new user admin and login
3. Install  PMPro.
4. Observe notifications.

* Pause notifications on install scenario

---

classes/gateways/class.pmprogateway_stripe.php

Adds a filter to the Stripe Checkout params array
1. Hook into the `pmpro_stripe_checkout_checkout_session_parameters` filter

Stripe Checkout Params Filter Added

---

css/admin.css
includes/compatibility/lifterlms.php

Update CSS to override the thing LifterLMS does to adjust WordPress core hr formatting in admin.
Adding UTM parameters to track filtered link in LifterLMS dashboard.

Adjusting CSS and UTMs for LifterLMS Compatibility

---

includes/cleanup.php
includes/compatibility.php
includes/compatibility/buddypress.php
includes/functions.php

Cancel subscriptions when a user chooses to delete their account in BuddyPress.

Buddypress cancel sub

---

classes/gateways/class.pmprogateway_stripe.php

Now caching data for the Stripe Webhook Status table to avoid delay every time that page is loaded.

Caching data for stripe webhook status table

---

includes/fields.php

* BUG FIX: Added better compatibility for User Fields and Groups created via code and only show fields in the checkout email that are for that particular checkout.
Resolves XXX.
1. Create User Fields and Groups via code and the settings page.
2. Test checkout and see that "Extra Fields" are correctly displaying for the current checkout level and both coded and setting fields show.

Improvements to "Extra Fields"

---

includes/compatibility.php
includes/compatibility/bluehost-wordpress-plugin.php

The "BlueHost WordPress Plugin" currently has a security feature that hooks into each time that a user logs in. When this happens, that plugin will check if their password is secure and, if not, redirect the user to an "insecure password" screen to reset their password.
During our checkout process, that functionality will interrupt checkouts if a new user chooses to create an account with an insecure password. In this case, users will be redirected from our checkout page to the password reset page and the purchase will not be completed.
This PR aims to resolve this issue during our checkout process by unhooking the "login check" code on our checkout page. This change will not affect non-checkout logins, so users who decide to check out with an insecure password will still be prompted to …

Adding compatibility with Bluehost Plugin

---

includes/deprecated.php

* Make option found flag explicitely boolean after query DB
Resolves XXX.
1. In the deprecated file comment code that prevents activating deprecated plugins such as Registration Helper
2. Activate Registration Helper.
3. Add some restrict by email or username options. 
4. Ensure data is not cached and query works. 
5. Look at memeberships dashboard page for the message.

* Fixing a performance issue with our deprecation code

---

blocks/account-invoices-section/block.js
blocks/account-links-section/block.js
blocks/account-membership-section/block.js
blocks/account-profile-section/block.js
blocks/checkout-button/block.js
blocks/checkout-button/block.php
blocks/checkout-button/inspector.js
blocks/membership/block.js

Also tested by rebuilding blocks.build.js live. NOT pushed.

Blocks: add missing i18n, cleanup, fix class/className usage in React context

---

adminpages/member-edit/pmpro-abstract-class-member-edit-panel.php
adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php
adminpages/member-edit/pmpro-class-member-edit-panel-user-info.php

- Remove duplicate code from Edit Member Membership panel
- Add save functionality for changing membership levels
- Update button/panel IDs to be more specific to avoid potential conflicts
- Fix some user-info panel error messages that are formatted incorrectly

Refactoring membership panel and save new level

---

preheaders/confirmation.php

MMPU compatibility for the confirmation preheader

---

css/frontend.css
pages/confirmation.php
pages/invoice.php

Fixes issue where confirmation page links can sometimes show twice. Also removes duplicate code in the template.

Refactoring confirmation, removing duplicate links

---

classes/class-pmpro-field.php
includes/checkout.php
includes/fields.php
includes/functions.php

Only allowing uploads of files associated with user fields and improving checks for file types/extensions when saving files before sending users to offsite payment gateways.

File upload security improvements

---

adminpages/orders.php

Overhaul the admin single order edit screen to use collapsible boxes

Overhaul admin single order to use collapsible boxes

---

adminpages/dashboard.php
adminpages/member-edit.php
adminpages/member-edit/pmpro-abstract-class-member-edit-panel.php
adminpages/reports.php
css/admin.css
css/frontend.css
css/print.css
includes/adminpages.php

This PR updates a few files that needed general help after the merge for 3.0.
I also updated the CSS root variables to use a pmpro prefix for better compatibility and lower integration issues.
There are other PRs coming after this one that leverage the CSS in this update, so best to merge this one first then can test and review the others. I'm trying to separate PRs out so its easier to code review.

Basic Updates to Admin Area and CSS Files

---

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php
adminpages/member-edit/pmpro-class-member-edit-panel-orders.php
adminpages/member-edit/pmpro-class-member-edit-panel-other.php
adminpages/member-edit/pmpro-class-member-edit-panel-subscriptions.php
adminpages/member-edit/pmpro-class-member-edit-panel-user-info.php

Updates to the entire Member Edit screen panels.

Updating Edit Member screen throughout

---

adminpages/functions.php
adminpages/member-edit.php
css/admin.css

Fix emailing invoices on edit member page.
Ideally this code would be in the "orders" panel class, but this code needs to be its own separate `<form>` so for now, that isn't possible. Hopefully we will have a solution for this down the road.

Fix emailing invoices on edit member page

---

adminpages/subscriptions.php
classes/class-pmpro-subscription.php
css/admin.css

Show error/success messages when editing a subscription.

Show error/success messages when editing a subscription.

---

classes/gateways/class.pmprogateway_authorizenet.php

Fixing variable

---

includes/adminpages.php

Adding a link to create a new member and edit the current user's membership information.

Add links to new member and edit member

---

adminpages/userfields.php

Allowing links in user field group descriptions.

Allowing links in user field group descriptions

---

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php

Removes the filter to hide membership level details on the Edit Member > Memberships panel. In the context of this screen, that doesn't really make sense. Other logic to address capabilities are in place here.
The filter `pmpro_profile_show_membership_level` will remain as an option to remove the digest info about memberships on the Edit User / Your Profile edit screens only.

Removing unnecessary filter in the context of the Edit Member page.

---

classes/class-pmpro-discount-code-list-table.php

Small quality of life update - showing the column "Levels" on the Discount Codes list table in the sorted level order.
* BUG FIX/ENHANCEMENT: Now sorting the Levels column by the sorted level order on Discount Codes list table.

Sorting the levels column on the Discount Codes list table by the sorted level order

---

adminpages/wizard/done.php

Added further check  to see is $site_types[ $site_type ] exists before to print link.
Resolves #2639 .
See the steps to reproduce in #2639 

Fix warning in the wizard

---

includes/adminpages.php

This PR sets up redirect logic for various edit screens in the admin. It validates if the item ID passed in the URL is the single type of thing that we expect it to be and that it exists, otherwise it redirects away.
Screens we will redirect from include:
- Editing an order ID that doesn’t exist on the Order page.
- Editing a member ID that doesn’t exist on the Edit Member page.
- Editing a level ID that doesn’t exist on the Edit Level page. 
- Editing a level group ID that doesn’t exist on the Edit Level page. 
- Editing a Discount Code ID that doesn’t exist on the Discount Codes page.
Subscriptions were already in v3.0 branch but I moved that code to this new admin_init function for organization with other like items.
Pass a non-existing ID for an order, user, subscription, discount …

Redirects for various places in admin

---

includes/updates/upgrade_3_0.php
includes/upgradecheck.php

Enable backwards-incompatible 3.0 queries.

Enable backwards-incompatible 3.0 queries

---

adminpages/orders.php

Just updating a tiny thing on the add new order.

Removing unnecessary message on new order add

---

adminpages/login-csv.php
adminpages/memberships-csv.php
adminpages/orders-csv.php

* Remove 'PMPRO_BENCHMARK' constant that was automatically set to `true` in certain admin CSV files.

remove 'PMPRO_BENCHMARK'

---

classes/class-pmpro-subscription.php
includes/updates/upgrade_3_0.php

No longer using `has_default_migration_data` subscription meta.
Also removing unnecessary called to `PMPro_Subscription->save()` since `PMPro_Subscription->update()` already calls the save method.

Simplifying migration to subs table

---

adminpages/member-edit/pmpro-class-member-edit-panel-subscriptions.php

Abstracted subscriptions table display on the Edit Member page for easier maintenance going forwards.
Also fixes PHP warnings when a user has an active subscription for a deleted level and shows the level ID for deleted levels in the table.

Abstraction and bug fixes for subs table display

---

classes/class-pmpro-subscription.php

Adding an email subject when a subscription fails to sync with the gateway.

Adding an email subject when a subscription fails to sync with the gateway.

---

includes/rest-api.php

Now allowing arrays in $route_caps so you can have a different permission per HTTP method.

Update to API permissions.

---

classes/class.memberorder.php

Before looking for a subscription, make sure that we have all the needed info

---

classes/class-pmpro-subscription.php

Tracking errors when a subscription fails to sync with the payment gateway.

Tracking errors when a subscription fails to sync

---

CHANGELOG.txt
package.json
paid-memberships-pro.php
readme.txt

Prep for the next beta release.

Updating readme and version numbers for 2.99.993

---

adminpages/membershiplevels.php
includes/services.php

Adding a nonce to `pmpro_update_level_order()` to prevent CSRF attacks.

Adding a nonce to pmpro_update_level_order()

---

js/pmpro-stripe.js

Remove called to undefined function.

Fixing Stripe payment request button

---

includes/https.php

* BUG FIX: Fixed an issue of infinite redirect loop in certain cases.
Resolves: https://github.com/strangerstudios/paid-memberships-pro/issues/2690

Remove esc_url for redirecting to HTTPS

---

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php

Fixing a few more spots in the Edit Member experience where the field label wasn't properly scoped on the field input.

Fixing a few label to field mismatches

---

adminpages/pagesettings.php

Adding `pmpro_` prefix. This function used to call pmpro_getOption().

Fixing saving additional pages

---

classes/class-pmpro-members-list-table.php

We wanted to change what columns were hidden by default on the Members List Table. It turns out our code to hide columns wasn't really being respected.
This change makes it so that any new user with access to view this screen has their screen option preferences set on the first load. This is necessary so that we can properly reflect what columns are disabled by default in the Screen Options dropdown panel.
The current columns we hide by default are:
'ID',
'first_name',
'last_name',
'address',
'membership_id',
'joindate',
I used this XWP plugin repo as inspiration here: https://github.com/xwp/stream/blob/develop/classes/class-list-table.php
To test this as a fresh visitor, you must delete this key for your admin user in wp_usermeta: 	managememberships_page_pmpro-memberslistcolumnshidden.

Actually setting hidden columns on Members List Table and storing for the user

---

shortcodes/pmpro_member.php

- Adds new shortcode attribute 'levels' for setting the "priority" for levels to be shown by the shortcode. Ex. `levels="1,2,3"` will show data for level 1 if the user has it, data for level 2 if they don't, and data for level 3 if they don't have either of those.
- Pulling data from PMPro_Subscription when helpful
- WPCS

3.0 compat for pmpro_member and WPCS

---

css/admin.css

Fields on the Edit Member > User Info or each User Field-created panel have a width set. This should not apply to the three parts of a "date" field type.

Styling for the small tag; fix for date type fields on edit member screen.

---

classes/class-pmpro-subscription.php

Preventing infinite loop when fixing migration data.

---

classes/class-pmpro-members-list-table.php

Allows searching for members by the subscription transaction ID of active subscriptions.

Allow searching by subscription transaction id on the members list.

---

classes/gateways/class.pmprogateway_authorizenet.php
classes/gateways/class.pmprogateway_braintree.php
classes/gateways/class.pmprogateway_payflowpro.php
classes/gateways/class.pmprogateway_stripe.php
pages/billing.php
preheaders/billing.php
shortcodes/pmpro_account.php

* ENHANCEMENT: Added supports()payment method updates features and refactored it slightly.
This PR is for the branch `fix/sub-sync` and adds support for this and update billing to use the same method so we can extend on this even further. Note: Other gateways will need to add this method to their class and copy the logic from one of our gateways.

Base (fix/sub-sync) - Added supports( $feature ) for other gateways and slight refactor around checking logic.

---

includes/profile.php

Removed last element from hour dropdown in expiration settings

Remove one element from hour dropdown in member edit expiration settings

---

pages/billing.php
pages/cancel.php
pages/checkout.php
pages/confirmation.php
pages/invoice.php
pages/levels.php

Updating page template versions for modified templates to 3.0

---

classes/gateways/class.pmprogateway_authorizenet.php
classes/gateways/class.pmprogateway_paypalexpress.php

Marking PPE and Auth.net as supporting subscription updates.

Marking PPE and Auth.net as supporting subscription updates

---

adminpages/dashboard.php
pages/cancel.php

Using pmpro_get_membership_expiration_text() on the cancel page and in the Recent Members report

---

includes/blocks.php
includes/init.php

* check register_block_type function exists
* check has_block function exists

Add support to use ClassicPress.

---

adminpages/member-edit.php
adminpages/member-edit/pmpro-abstract-class-member-edit-panel.php
adminpages/member-edit/pmpro-class-member-edit-panel-user-fields.php
adminpages/member-edit/pmpro-class-member-edit-panel-user-info.php

Using dashes in member edit panel slugs.

Using dashes in member edit panel slugs

---

pages/billing.php

$url was not defined, so changing it to `pmpro_url( 'levels' )` which is what is used in the current dev branch.

$url was not defined

---

includes/updates/upgrade_3_0.php

Speeding up 3.0 migration

---

classes/class-pmpro-subscription.php

Resolves XXX.
1. Have a cancelled order that has a pending order for the same subscription
2. Upgrade to 3.0
3. Run migration AJAX

Fixing infinite loop when migrating cancelled sub

---

adminpages/dashboard.php

Caching the recent orders and recent members dashboard reports.

Caching recent members and orders dashboard reports

---

classes/gateways/class.pmprogateway_stripe.php

Stripe past-due subs are active

---

classes/gateways/class.pmprogateway_stripe.php
pages/billing.php
preheaders/billing.php
shortcodes/pmpro_account.php

- Now passing subscription ID to update billing page instead of order
- If no subscription is passed but the user only has one subscription, update that single subscription
- Fixed incorrect "supports" parameter for Stripe

Update billing improvements

---

readme.txt

Adding a line about supporting multiple levels per user to readme.

Adding MMPU to readme

---

includes/content.php

Fixes PHP uncaught type error.

Make sure that we do not pass null to array_values()

---

classes/class.memberorder.php

Adding searching orders by date and returning the order count instead of order objects. This is to help performance and to allow this function to be used for use cases such as generating reports.
Also compliments this Discount Codes PR where getting order counts efficiently is very important:
https://github.com/strangerstudios/paid-memberships-pro/pull/2883

Allow searching orders by date and returning counts

---

pages/checkout.php
preheaders/checkout.php

Adding nonce to checkout form. Will only be checked if using a page template with version 3.0+.

Adding nonce to checkout form

---

css/admin.css
css/frontend.css

A few small CSS adjustments for cross theme compat. We'll do more in v3.1+ but this was a few lingering things that users / team reported.

Small fixes for theme compatibility in Kadence, BuddyBoss; date field input alignment fix

---

adminpages/levels/delete-level.php
classes/class-pmpro-levels.php

When a level is deleted, remove it from the level group.

When a level is deleted, remove it from the level group

---

includes/functions.php

Fixing issue where `pmpro_account_membership_expiration_text`, which is only meant to be run on the frontend, would not run on the frontend.
https://www.paidmembershipspro.com/display-a-membership-renewal-date-to-your-recurring-members/

Fixing filter pmpro_account_membership_expiration_text

---

includes/profile.php

Fixes misspelling.
Resolves XXX.
1.
2.
3.
* BUG FIX: Fixed typo in core and translation files for term "Recommended"

Fixing typo misspelling of Recommended

---

js/pmpro-admin.js

Hiding the PMPro message when switching tabs on the Edit Member page.
Resolves XXX.

Hiding the PMPro message when switching tabs on the Edit Member page.

---

css/admin.css

A few tweaks to improve how our admin screens look on smaller screens and mobile. We could go farther with this, but the primary views are improved and really, the screens people need to use like 
* BUG FIX/ENHANCEMENT: Improvements to the plugin's admin area pages for mobile/responsive screens.

Improving mobile/responsive screen view for admin

---

adminpages/advancedsettings.php
adminpages/pagesettings.php
classes/class.pmproemail.php
classes/gateways/class.pmprogateway_stripe.php

Removing uses of pmpro_getOption()

---

includes/functions.php

Only trimming strings to avoid PHP error

---

adminpages/levels/edit-level.php

Fixing URL that changed for a post we link to from admin warning.

Updating post URL

---

adminpages/userfields.php

Small tweak to the text since these also show on the Edit Member screen + docs link.

Updating user fields help box and adding link to docs

---

adminpages/membershiplevels.php
includes/services.php

Adding nonce for AJAX call to adjust level group order.

Adding nonce to pmpro_update_level_group_order

---

includes/functions.php

Adding the `pmpro_deactivate_old_levels` filter back, which was lost in the 3.0 migration.
Resolves XXX.
1. Install PMPro PBC
2. Set up a "donations only" level
3. See that purchasing that level removes previous membership before PR, but doesn't after PR.

Adding back filter pmpro_deactivate_old_levels

---

classes/class-pmpro-admin-activity-email.php

* [ x] Have you successfully run tests with your changes locally?

Fixing over-escaped strings in admin activity email

---

classes/class-pmpro-subscription.php

Fixes an issue where sometimes a new subscription would be mistakenly inserted with ID 0 instead of the auto-increment amount.

Switch to pmpro_insert_or_replace()

---

includes/functions.php

* Just that
Resolves #2998 .
1.
2.
3.

* Deprecate unused "pmpro_showRequiresMembershipMessage" function

---

adminpages/membershiplevels.php

- Fixed broken link to Approvals documentation page
- Fixed group ID for creating a level with no group specified after previously opening the "Add New Level" popup for a specific group.

Fix broken external links

---

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php
adminpages/userfields.php
classes/class-pmpro-orders-list-table.php
includes/compatibility/lifterlms.php
includes/updates.php

Some strings can now be localized
Some strings can now be localized

Some strings can now be localized

---

adminpages/pagesettings.php

* Just that
Resolves XXX.
1.
2.
3.

* Replace Register Help hint  and link with User Fields version.

---

services/ipnhandler.php

When a PPE payment fails, cancel the subscription if it has been suspended. If so, cancel the subscription entirely.

When a PPE payment fails, cancel the subscription if it has been suspended.

---

adminpages/designsettings.php
css/admin.css
js/pmpro-admin.js

Live preview instantly updates in the Design Settings tabs as the user chooses different colors.
I do not know if this needs more sanitization here.

JS to update the live preview of the design settings as colors are changed

---

classes/gateways/class.pmprogateway_braintree.php
classes/gateways/class.pmprogateway_check.php
classes/gateways/class.pmprogateway_stripe.php
css/frontend/high_contrast.css
css/frontend/variation_1.css
pages/checkout.php

Solution to get the best possible appearance whether they have reCAPTCHA v2, TOS agreement, free or paid level.

Moving checkout button, TOS, and recaptcha outside a 'box'

---

js/pmpro-checkout.js

Before this PR, applying a discount code using the top field would show a message above and below the form. Applying a discount code with the bottom field would add a message inline with the button.
With this PR, discount code messages always appear both above and below the form.

Abstracting discount code message logic

---

classes/class-pmpro-levels.php

Avoiding "creation of dynamic property" warnings.

Allowing dynamic properties

---

classes/gateways/class.pmprogateway_authorizenet.php

Change field name to API Login ID

Change field name to API Login ID

---

css/frontend/high_contrast.css
css/frontend/variation_1.css
shortcodes/pmpro_account.php

Adjusting spacing when member links are present.

Adjusting member links styles

---

includes/setup.sql
includes/updates/upgrade_3_1.php
includes/upgradecheck.php

Make sure columns are bigints when they reference columns in other tables that are also bigints.

Fixing some db table column types

---

css/admin.css

Alignment of the Search input on the Add Ons filter bar was not correct.

Fixing alignment of search form on Add Ons list in admin.

---

css/admin.css
css/frontend/variation_1.css
css/frontend/variation_high_contrast.css

More specifically targeting the login form items we want to align flex. This prevents things hooking into login_form_top or login_form_bottom from have a flex alignment.

Fix login form additional content

---

adminpages/orders.php
adminpages/templates/orders-email.php
adminpages/templates/orders-print.php
classes/class-pmpro-orders-list-table.php
classes/class.memberorder.php
classes/class.pmproemail.php
classes/gateways/class.pmprogateway_authorizenet.php
classes/gateways/class.pmprogateway_braintree.php
classes/gateways/class.pmprogateway_check.php
classes/gateways/class.pmprogateway_payflowpro.php
classes/gateways/class.pmprogateway_paypalexpress.php
classes/gateways/class.pmprogateway_paypalstandard.php
classes/gateways/class.pmprogateway_stripe.php
classes/gateways/class.pmprogateway_twocheckout.php
includes/checkout.php
includes/email.php
includes/filters.php
includes/functions.php
includes/privacy.php
includes/services.php
includes/upgradecheck.php
pages/invoice.php
preheaders/billing.php
preheaders/checkout.php
services/authnet-silent-post.php
services/braintree-webhook.php
services/ipnhandler.php
services/stripe-webhook.php

Throughout the existing checkout flow, dynamic properties are set on the checkout MemberOrder that are used by all of our payment gateways. All of this data can be calculated without the need of the dynamic properties and, at this point, using those properties is more confusing than helpful.
This PR updates all of our non-deprecated gateways to no longer use those dynamic properties and stops setting them as a part of the checkout flow. Instead, there is code added to the MemberOrder `__get()` magic method to maintain backward compatibility for any gateways still using those properties that also throws a deprecation warning. This will allow us to fully remove these dynamic properties in the next major release to PMPro.
The other big change in this PR is adding a new `billing_street2` …

Deprecating dynamic order properties, adding street2 to billing address

---

classes/class-pmpro-field.php
includes/fields.php
includes/functions.php
js/pmpro-admin.js

* ENHANCEMENT: Added Allowed File Types and Max File Size Upload for the "File" type in User Fields.

User Fields "File" field additional options.

---

classes/gateways/class.pmprogateway_stripe.php

Rewording Stripe "webhook not yet received" message

---

classes/class-pmpro-subscription.php
includes/profile.php

Fixes a few strings that weren't being properly localized.

Fix localized strings

---

css/frontend/base.css
css/frontend/variation_1.css
css/frontend/variation_high_contrast.css

A few adjustments to help frontend pages, especially orders, print nicely.
* ENHANCEMENT: Improved print appearance for frontend membership pages.

Improving the print styles for frontend membership pages

---

includes/updates/upgrade_3_2.php

Fixed misspelled word checkout.
Not needed.

Small spelling typo

---

classes/gateways/class.pmprogateway_stripe.php

No longer using deprecated order property

---

languages/paid-memberships-pro-dev-ca.po
languages/paid-memberships-pro-dev-en-za.po
languages/paid-memberships-pro-dev-es-ar.po
languages/paid-memberships-pro-dev-es-mx.po
languages/paid-memberships-pro-dev-es-uy.po
languages/paid-memberships-pro-dev-es.po
languages/paid-memberships-pro-dev-fr.po
languages/paid-memberships-pro-dev-it.po
languages/paid-memberships-pro-dev-ja.po
languages/paid-memberships-pro-dev-nl.po
languages/paid-memberships-pro-dev-pt-br.po
languages/paid-memberships-pro-dev-sv.po
languages/paid-memberships-pro-dev-tr.po
languages/wp-plugins-paid-memberships-pro-dev-hr.po

Updates for 
- English ZA
- Portuguese BR
- Spanish ES
- Turkish
- Dutch
- Japanese 
- Spanish UY
- Spanish MX
- Spanish AR
- Catalan
- French FR
- Italian
- Swedish

Update PO files for some languages

---

.github/ISSUE_TEMPLATE.MD
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/support.md
README.md
adminpages/dashboard.php
classes/class-pmpro-wisdom-tracker.php
composer.json
includes/admin.php
readme.txt

Updating links throughout the plugin.

Updating links

---

includes/login.php

* Fix warning in wp_redirect hook.

---

css/admin.css

Small adjustment to admin list tables padding.

Small adjustment to match thead and tfoot on large screens

---

classes/gateways/class.pmprogateway_stripe.php

Previously, the Stripe customer ID would only be found for a user if they had an order linked to a Stripe sub/payment. This means that the stripe customer ID would not be set for users who have an entry in the subs table, but no order. This PR fixes that behavior by also checking the subs table for Stripe subscriptions.
A sync error is now also being shown on subscriptions with a customer ID different than the user's to help debug future issues with users not being able to update their subscription info in the Stripe Customer Portal if the subscription did not originally belong to them, for example.

Allow pulling stripe customer ID from subscriptions in subs table

---

classes/email-templates/class-pmpro-email-template.php

* Fix for sitename variable

---

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php
classes/class.pmproemail.php
classes/email-templates/class-pmpro-email-template-admin-change-admin.php
classes/email-templates/class-pmpro-email-template-admin-change.php
classes/email-templates/class-pmpro-email-template-cancel-admin.php
classes/email-templates/class-pmpro-email-template-change-admin.php
classes/email-templates/class-pmpro-email-template-change.php
classes/email-templates/class-pmpro-email-template.php
includes/email-templates.php
paid-memberships-pro.php

* Add Change Membership Classes ( admin and member )

---

adminpages/member-edit.php
adminpages/member-edit/pmpro-class-member-edit-panel-user-fields.php
adminpages/user-fields/field-settings.php
adminpages/user-fields/group-settings.php
adminpages/userfields.php
classes/class-pmpro-field-group.php
classes/class-pmpro-field.php
includes/fields.php
includes/functions.php
scheduled/crons.php
shortcodes/pmpro_member.php

This is a massive PR that touches almost everywhere that user fields are used inside of core PMPro.
There are a few main goals here:
- Move logic for showing/saving fields in field groups to the new PMPro_Field_Group class. This removes a lot of repetitive code from the `/includes/fields.php` file.
- Marking unnecessary functions/methods as deprecated. Currently, many functions serve similar purposes when we only need one. Some areas are also abstracted unnecessarily and are simplified by this PR. During the next major release, these functions can all be deleted, removing a lot of code from our user field files.
- Locking down the PMPro_Field class. The properties and some methods in this class are becoming private. This allows us to throw error messages when custom code tries to use them …

Overhauling user fields logic with abstraction, simplifications, and deprecations

---

classes/gateways/class.pmprogateway_stripe.php

This change should make us ready to updating the Stripe API version past `2023-08-16` by following the last suggestion in the related article here:
https://docs.stripe.com/upgrades/manage-payment-methods

Only allowing creating "card" payment intents with Stripe

---

classes/class-pmpro-field.php
css/frontend/base.css

Updated the `PMPro_Field->displayValue()` method to process values specifically based on the field type. This allows for embedding links and files.

Improving display values for links and files

---

classes/class-pmpro-field.php

Formatting for a number or date user field type.

displayValue case for number or date field types

---

classes/class.pmproemail.php
classes/email-templates/class-pmpro-email-template-cancel-on-next-payment-date-admin.php
classes/email-templates/class-pmpro-email-template-cancel-on-next-payment-date.php
includes/email-templates.php
paid-memberships-pro.php

* Add canceled autorenewal template / classes for member and admin

---

includes/compatibility/elementor/class-pmpro-elementor-content-restriction.php

Elementor - Making sure that array key exists

---

composer.json

* ENHANCEMENT: Simplified composer.json file as we don't utilize all the features of the composer file.

Simplified composer.json

---

includes/currencies.php

Customer request to add Bangladeshi Taka and symbol to our currency list

Bangladeshi Taka

---

adminpages/paymentsettings.php

Just a small fix for a URL that wasn't redirecting when the slug changed on the site.

Fixing link to docs on site for payment gateway settings

---

css/frontend/base.css

Small style fix if there are multiple paragraphs in a contextual message.

Fixing paragraphs in the pmpro message display

---

adminpages/reports/memberships.php

Fixing the table of data so the date column is clear and accurately matches the selections.

Fixing dates output for sales report daily, monthly, and annual

---

includes/level-groups.php

Adding function `pmpro_get_membership_levels_for_user_in_group()` to move in the direction of restricting content per group and checking if a user already has a level from a given group.

Adding function pmpro_get_membership_levels_for_user_in_group()

---

adminpages/license.php

We changed our refund policy to 100 days but hadn't reflected that in the License page descriptive text.

Fixing refund policy for premium plans with us to 100 days.

---

includes/fields.php

Fixing class name typo

---

classes/class.pmproemail.php

Add missing $membership_level variable thanks @kimwhite  !!!
1. Checkout for a free level
2. See paid template is sent
3. Apply this patch
4. Check again

* Checkout free email template is not firing

---

classes/email-templates/class-pmpro-email-template-checkout-paid.php

Fixing spacing for the default body for the checkout paid email

Fixing spacing for the default body for the checkout paid email

---

classes/email-templates/class-pmpro-email-template-payment-receipt.php

Fixing the expiration date for the invoice email. Previously, it may not get the expiration date for the correct level.

Fixing the expiration date for the invoice email

---

classes/class.pmproemail.php
classes/email-templates/class-pmpro-email-template-invoice.php
classes/email-templates/class-pmpro-email-template-membership-recurring.php
paid-memberships-pro.php
scheduled/crons.php

Specifically updating the Invoice and Membership Recurring emails

Make sure template class names match template slugs

---

includes/currencies.php

Add Albanian Leke to the list of currencies in the dropdown within the PMPro Gateway Settings page.
> Add Albanian Leke and symbol to our currencies list

Add Albanian Leke to our currencies list

---

classes/class-pmpro-wisdom-integration.php

We don't want to localize telemetry data as this makes reports more difficult to read.

Don't localize telemetry data

---

paid-memberships-pro.php

Happy new year 🎉

---

classes/gateways/class.pmprogateway_stripe.php

Removed an undefined variable. Also useless, bc the called method can get the secretkey by itself.
1. Open the code in PHPStorm
2. See the error showing up in the IDE

Remove undefined variable in Stripe Gateway

---

classes/email-templates/class-pmpro-email-template-membership-recurring.php
classes/email-templates/class-pmpro-email-template-refund.php

Adding missing "!!" to email template variable.

Adding missing "!!" to email template variable

---

classes/class-pmpro-admin-activity-email.php

* Fixed link to Advanced Settings in the admin activity email. The use of single and double quotes in the code was stripping out the link.
* Improved color scheme for accessibility and modern PMPro styling.
* Left aligning most elements for accessibility.
* Updating to rather link to our Slack community over X or Facebook to grow that space.

Improving the appearance of admin activity email; fixing link to update advanced settings

---

css/frontend/variation_1.css
css/frontend/variation_high_contrast.css

Now also adjusting line height when we name a font size on the frontend.

Adding line height to be more in control of our font size and appearance

---

adminpages/reports/logins.php
css/admin.css
css/frontend/variation_1.css
css/frontend/variation_high_contrast.css
includes/functions.php

Updates to the pagination function to support better accessibility.
This PR also includes frontend CSS for showing the pagination. This will be leveraged, for now, on the Member Directory.
1. The admin's Visits Views and Logins screen uses this pagination function.
2. Or, set up a Directory that has pagination to see and interact with this on the frontend.
Note: This update can coincide with the release of this update in Member Directory Add On but the two do not depend on each other or cause conflicts: https://github.com/strangerstudios/pmpro-member-directory/pull/186
**Example appearance in Member Directory (frontend)**
**Example appearance in Visits, Views, and Logins report**
* ENHANCEMENT: Improved accessibility of the `pmpro_getPaginationString` function.
> Enter a summary of all …

Improved accessibility and added frontend styles for the pagination function

---

includes/rest-api.php

Resolves #2220.
1. Create PMPro Zap
2. Select a trigger
3. Check records
First Name and Last Name values show if present in usermeta
> Now including First Name and Last Name in Zapier trigger data

Include First Name and Last Name in Zapier trigger data

---

css/frontend/base.css
css/frontend/variation_1.css
css/frontend/variation_high_contrast.css

Now supporting a fixed layout table - even width columns.
Also adjusted the responsive layout so table rows look more defined.

Adding fixed table layout; improving table responsive appearance

---

adminpages/wizard/done.php
adminpages/wizard/wizard.php
includes/addons.php

Adjustments to the recommended Add Ons by category/site use case. Fixing hub links to updated URLs.
Now showing 6 Add Ons on wizard final step + randomizing.

Adjusting Add Ons for categories; showing 6 and randomizing on Wizard, fixing hub links

---

includes/addons.php

* BUG FIX: Fixes a race condition when activating Paid Memberships Pro after the Update Manager is already activated.
These functions were only wrapped in `if ( ! function_exists...` calls and does not change code whatsoever. The git diff shows that code was changed but it's a coincidence that the lines changed were the same conditionals/checks in 2 areas of the code base/change.
This resolves an issue with a future release of Update Manager being active and then activating Paid Memberships Pro.
1. Pull the latest `pmpro-update-manager` plugin and install it.
2. Deactivate PMPro core, and try to activate it again (see there's a fatal error).
3. Apply this patch, and repeat step 2.

Add function_exists checks to addons.php

---

classes/class-pmpro-subscription.php

Names similar to order/level creation/edit for consistency.

[ENHANCEMENT] Added subscription hooks

---

classes/gateways/class.pmprogateway_stripe.php

Fix variable name in that context.

[BUGFIXING] Fix stripe application fee on sub creation

---

css/admin.css

Tweaks for welcome and quick links boxes, and postbox buttons on mobile.

Dashboard: Tweaks for small screens

---

classes/class-pmpro-recurring-actions.php

Remove conditional code referencing a setting which did not or no longer exists.
Resolves XXX.
> Fix admin summary emails not being sent.

Fix Admin Activity Emails

---

services/stripe-webhook.php

Currently, our `invoice.created` webhook handler updates the Stripe Application fee for all invoices created by Stripe, not just those that are generated by PMPro subscriptions. This PR adds logic to first verify that the invoice is a part of a PMPro subscription before updating the application fee.

Only updating Stripe application fee for PMPro payments

---

includes/compatibility/lifterlms.php
includes/functions.php
includes/metaboxes.php
includes/rest-api.php

When a course's level restrictions are updated, we will now update course enrollments for all members to reflect the courses' new restrictions. This processes happens asynchronously via Action Scheduler.
Also included in this PR:
- New function `pmpro_update_post_level_restrictions()` that abstracts updating post level restrictions
- New hook `pmpro_after_updating_post_level_restrictions` that fires after post level restrictions are updated
Currently, updating courses on user level change still happens immediately as using Action Scheduler could delay users gaining access to newly purchased courses.
1. Set up LifterLMS in streamline mode
2. Restrict a course to a new membership that has active members
3. See that new members are added to the active course after a couple minutes
(same for …

LifterLMS Streamline Repair Enrollments

---

includes/email-templates.php

Add missing `__()`
> Fixed issue where some email strings could not be translated.

Make strings translatable
