blocks/membership/block.js
* BUG FIX: Fixed an issue where the dropdown "What should users without access see?" for the Require Membership Block would reset on each page load.
Resolves: https://github.com/strangerstudios/paid-memberships-pro/issues/2243
=> Fixed attribute setting for Require membership block.

includes/fields.php
On sites where the string `[Inherit Group Setting]` is localized, user fields will not show on the user profile. This is because of the following check: `if ( empty( $settings_field->profile ) || $settings_field->profile === '[Inherit Group Setting]' )`.
This PR changes the `[Inherit Group Setting]` option to save a value of `""` on the field profile setting so that `empty( $settings_field->profile )` is `true`.
=> Fixing issue where fields may not show on profile

classes/class.memberorder.php
In the database, orders have a `membership_id` column, but the `get_orders()` method tries to reference a non-existent `membership_level_id` column.
=> Fixing col name for membership_id in get_orders()

services/stripe-webhook.php
The `$user_id` was not defined there.
=> Fix reference to the user id

js/pmpro-checkout.js
The required field asterisk was appearing on a new line below the field hint for some field types. This PR introduces new JS to detect and fix this placement. It should look like this now:
1. Add a textarea or select field with a hint.
2. Make sure it is also required.
3. Note the placement of the required asterisk.
> BUG FIX/ENHANCEMENT: The required field asterisk now appears correctly if a hint is used on a textarea, select, or other user field.
=> required asterisk now appears before the hint paragraph if found

classes/class.memberorder.php
When falling back on the user metas to recover the billing address, we were referencing the wrong user meta for the zip code. The correct name is `pmpro_bzipcode`.
1.
2.
3.
=> Fix reference to the billing zipcode's user meta

services/stripe-webhook.php
When creating recurring orders for Stripe, billing address is now pulled from the payment method first, then the Stripe customer if not available on the payment method, then from the previous PMPro order for the subscription if not available there.
Needed for sites affected by this issue: https://github.com/strangerstudios/paid-memberships-pro/pull/2271
Note that this "fallback" change will not restore the billing addresses for websites where renewal orders have already lost them. In these cases, site owners would have to manually bring over billing addresses from past orders to orders that were created without a billing address.
Resolves #2255 
=> Adding fallbacks when finding billing addresses

includes/compatibility/elementor/class-pmpro-elementor-content-restriction.php, includes/compatibility/elementor/class-pmpro-elementor.php
I added the PMPro content restriction settings onto the experimental Elementor container widget. By default the setting is only added to sections and when the Elementor container feature is enabled you can only create containers which are missing the content restriction settings. I needed this on one of my sites and thought I'd share my solution.
> Added an entry for the Elementor container to `PMPro_Elementor->locations`
> Added `pmpro_elementor_should_render` to the container's `should_render` action
=> Add content restriction settings to Elementor containers

includes/functions.php
* BUG FIX: Fixed an issue where non-zero trials were saying pricing was free.
Resolves [[XXX](https://github.com/strangerstudios/paid-memberships-pro/issues/2143).](https://github.com/strangerstudios/paid-memberships-pro/issues/2143)
=> Fix trial wording for non $0 custom trials.

adminpages/reports/sales.php
Adds a checkbox to the Sales chart that allows you to compare results of the current period to the previous period. 
This includes new and renewals. 
1. Navigate to Memberships > Reports > Sales & Revenue
2. Click on the 'Compare to Previous Checkbox' and hit the Run Report button
3. Two sets of data should appear on the chart. 
Added the ability to compare to the previous period on Sales chart
=> Compare to Previous Period Checkbox Added to Sales Chart

adminpages/reports/members-per-level.php
Adds an Active Members per Level Widget and Detailed View to the Reports page
1. Navigate to Memberships > Reports and scroll down to the Active Members per Level widget
2. A chart should show with active members per level
3. Clicking on the Details button will take you to a detailed view where you can click on the level name and view all members with that level.
Added a new report to display Active Members per Level
=> Adds an Active Members per Level Widget and Detailed View to the Reports page

classes/class.pmproemail.php, scheduled/crons.php
The "trial ending" cron has been disabled since 2013. Marking it as deprecated now so that it can be removed in a future version.
=> Marking "trial ending" cron as deprecated

pages/checkout.php
Add HTML ID attribute for the hidden `bcountry` billing address field displayed when filter `pmpro_international_addresses` is set to return true.
Added the appropriate id to the element that should allow gateways to obtain the country ID code at checkout if the billing address country field was hidden.
1. Setup Stripe as the payment gateway and set _Show Billing Address Fields_ option for Stripe set to _Yes_
2. Check out for a membership level that requires payment and fill out the billing address details
3. Confirm that checkout was processed successfully.
=> Add id attribute to hidden bcountry field

includes/compatibility.php, includes/compatibility/avada.php
* BUG FIX/ENHANCEMENT: Add compatibility for Avada Theme. Fixes issue where Avada Layouts/Elements run through the_content such as header, title, footer etc.
=> Add compatibility for Avada Theme

pages/billing.php, pages/checkout.php
Similar to this PR, but both are needed: https://github.com/strangerstudios/paid-memberships-pro/pull/2284
Stripe sometimes throws an error when a user tries to check out or update their payment method while also supplying a billing address. This change ensures that the full address that was entered is always passed to Stripe, avoiding those errors.
=> Adding IDs to billing address fields to avoid Stripe errors

scheduled/crons.php
When sprintf is used during crons runs, sometimes user meta is not being updated correctly. This is a similar fix to the  PMPro Recurring Email Reminders PR here: https://github.com/strangerstudios/pmpro-recurring-emails/pull/25
=> Avoiding sprintf issues during cron runs

classes/gateways/class.pmprogateway_authorizenet.php
In most PMPro payment gateways, we calculate a "profile start date" when setting up a payment subscription. This value is intended to hold the day that the first subscription payment will be charged and is filtered by some of our add ons (ex Subscription Delays and Proration) to change the first subscription payment date.
In Authorize.net, however, the profile start date did not work in the same way. Instead of being set to the first payment date, the profile start date was being set to the current date and a "1 cycle free trial" was being set up to delay the first recurring payment.
Although this approach works when only considering core PMPro, the approach is different than all other PMPro gateways and causes issues when Add Ons/custom code use the `pmpro_profile_start_date` filter to …
=> Fix Authorize.net sites using profile start date filter

classes/gateways/class.pmprogateway_stripe.php
Set Stripe Checkout to create Invoices for one-item payments. This will allow one-time payments to show as Invoices in the Stripe Customer Portal.
=> Invoices for one-time Stripe Checkout payments

classes/class-pmpro-site-health.php, classes/class.pmproemail.php, includes/admin.php, includes/capabilities.php, includes/functions.php, includes/upgradecheck.php, scheduled/adminactivityemail.php, scheduled/creditcardexpiringwarnings.php, scheduled/expirationwarnings.php, scheduled/expirememberships.php, scheduled/trialendingwarnings.php
Moving your site to a staging site can result in unexpected changes such as crons running and live actions occurring. This will check if the site URL has changed and disable the PMPro crons. 
1. Install PMPro - check if the pmpro_site_url option has been created in the db
2. Change the current site URL or copy the site to another domain
3. A notice will appear notifying you of the change, which then puts the site in pause mode.
Core features can now temporarily be turned off or paused when setting up a staging site.
=> PR3 - Pause Mode Functionality

includes/content.php, includes/metaboxes.php, includes/terms.php, paid-memberships-pro.php
Tags can now be restricted by membership level by navigating to `Posts > Tags`, and category restrictions can also be modified in `Posts > Categories`.
=> Restricting tags and improved categories

classes/class.pmproemail.php
The `!!membership_level_confirmation_message!!` email template variable was not being set up for admin checkout emails. This PR adds that email template variable.
=> Adding !!membership_level_confirmation_message!! to admin checkout emails

classes/class.pmproemail.php
The `display_name` property is useful there, but it's declared TWICE into that data array.
Please unfold the code when reviewing too see that this PR removes the duplicate key only.
=> PMPro Email: remove duplicate property "display_name"

classes/gateways/class.pmprogateway_authorizenet.php
Found some notices and fixed.
Also removed that `fwrite` (alias of `fputs`) which was sending an undefined variable.
=> Authorize.net Gateway: Fix some "undefined variable" notices

pages/checkout.php
Fixing issue where `<strong>` tags would be escaped during "review" step of PayPal Express.
=> Fixing escaping for PayPal Express review message

includes/fields.php
When adding or editing a user field, the "Required?" label didn't accurately explain when the field would be required - since we do not and have no intention of coding in field requirements on the frontend user profile edit or admin profile edit screen. This is not something WordPress enforces to user profile edits and can cause more problems with lost field data on submission when errors are present.
We instead recommend sites that MUST require fields to use this approach (with caution): https://www.paidmembershipspro.com/require-user-fields-member-profile-edit-page/
1. Edit User Fields in the admin.
2. Check the label "Required?" should now read "Required at Checkout?"
=> Adjusting label to reflect what required actually means in this context

adminpages/orders-csv.php, adminpages/orders.php
Additional SQL escaping seems to add backslashes to the dates in the filter 'Within date range'.
Each date has escaping on it though so removed the additional escape around the main statement.
1. Navigate to Orders
2. Click on the 'Show' dropdown and select 'Within Date Range' - specify your date
3. Results should now be returned within the range.
Fixed a bug that caused no results to be returned when filtering orders within a date range.
=> Fixes No orders found issue

includes/profile.php
When an admin decides to add an expiration date to a user's membership from the Edit User page, we used to default it to 1 year in the future. We lost that functionality here and now only default it to the current date:
https://github.com/strangerstudios/paid-memberships-pro/commit/9fb79b209a632ed2d97b803501eb6cbec9c90e6e
This PR changes the default expiration date back to 1 year in the future.
=> Setting default expiration date to +1 year

includes/fields.php, shortcodes/pmpro_member.php
Based off the comments in #2314.
Adds function `pmpro_get_label_for_user_field_value()` to standardize converting user field values to their correspoinding labels when displaying user field user selections.
Then uses that function in the `[pmpro_member]` shortcode to fix values being displayed there when user-friendly labels are available.
=> Show user field labels in [pmpro_member] instead of meta values when possible

css/admin.css
This update fixes a text overlap issue on mobile/small screens for our Discount Codes and Orders admin pages.
* BUG FIX: Resolved issue where admin orders and discount codes screens were not displaying nicely on small screens.
=> Updates to support responsive tables for orders and discount codes on small screens using WP core breakpoints.

includes/functions.php, preheaders/checkout.php
PMPro currently waits until after a payment is successful to create a WP user, but this can result in checkout issues that are often plugin conflicts that are difficult to debug (see [troubleshooting article here](https://www.paidmembershipspro.com/troubleshooting-guide-users-not-created-at-checkout/)). Furthermore, not having a WP user set up causes orders to be created in `token` status without an associated user when an offsite gateway, which can be confusing to customers.
Instead, this PR moves the user creation step to before the payment collection step to avoid these kinds of issues entirely.
Main downside is that some websites don't want to have users created unless they have actually paid, so we need to decide if it is more important to keep things as-is for those users or to …
=> Now creating user before payment at checkout

adminpages/reports.php
This PR does not perform the `array_chunk` if the array is empty.
```php
global $pmpro_reports;
unset( $pmpro_reports['login'] );
unset( $pmpro_reports['sales'] );
unset( $pmpro_reports['memberships'] );
```
Then load the pmpro-reports page.
=> Fix fatal in case all the pmpro_reports were unset

adminpages/membershiplevels.php, js/pmpro-admin.js
*ENHANCEMENT: Added the ability to press "esc" to close the levels and Add Ons license popup modal.
=> Close popups in admin by pressing "esc"

classes/class-pmpro-wisdom-integration.php
We used to exclude only .test and .local tlds from wisdom tracking.
There's a list of known staging third party subdomains and other tlds/prefix to consider.
This PR extends the list.
* [] Have you successfully run tests with your changes locally?
=> Extend wisdom tlds exclusion list

scheduled/crons.php
Pause mode PR is here: https://github.com/strangerstudios/paid-memberships-pro/pull/2223/files
That code included a check in the crons/...php files, but those files aren't really used anymore. We need the is_paused check in the cron callbacks themselves. This PR does that.
=> Fix/pause in crons.php

adminpages/reports.php
Additional case to be considered (from #2343).
`$pieces[1]` is null when there's just one widget.
1. unset all the reports' widgets except one
2. load the reports page
3. check the logs
=> Fix warnings in case all the pmpro_reports were unset except one

classes/gateways/class.pmprogateway_stripe.php
The `charges` property of Stripe PaymentIntents has been removed. Switching to `latest_charge instead.
See Stripe API Version `2022-11-15` breaking changes here: https://stripe.com/docs/upgrades
=> Fixing Stripe payment IDs not saving at checkout

includes/rest-api.php
A couple versions ago, we changed MemberOrder properties to be private. Since then, our Orders API endpoint hasn't been working.
This fixes the endpoint.
=> Fixing orders REST API endpoint

includes/login.php
* BUG FIX: Fixed an issue where our frontend login failure would always return the same error message which isn't clear. This now supports the other cases we try to support when the login fails and shows a clearer message.
Resolves: https://github.com/strangerstudios/paid-memberships-pro/issues/2359
1. Try logging in with incorrect details. You may use a combination of correct username, incorrect password or a username that doesn't exist.
2. See the error message now changes to the correct warnings we set out here - https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/login.php#L318-L348
* BUG FIX/ENHANCMENT: Improved error message functionality during the failed …
=> Fixed login error code always showing invalid.

classes/gateways/class.pmprogateway_stripe.php
Making sure `mode` is `payment` before enabling `invoice_creation` when sending user to Stripe Checkout.
I do not see why this change should make a practical difference, but looking to fix the following error and this PR is more verbose:
> Could not create checkout session. You can only enable invoice creation when `mode` is set to `payment`. Invoices are created automatically when `mode` is set to `subscription`, and are unsupported when set to `setup`. To learn more visit https://stripe.com/docs/payments/checkout/post-payment-invoices.
=> Fixing one-time payments with Stripe Checkout

css/admin.css, includes/admin.php, js/pmpro-admin.js
* Added secondary button to dismiss the notification. This should hopefully slow down users to read this notification. (Kept the x dismiss button as well - both do the same thing).
* Minor CSS changes for button-secondary when we use that in our notifications (Increases size).
* JS of clicking the secondary button clicks the X button for the notification to trigger the AJAX.
Screenshot:
=> Updated Pause Notification Bar + Logic

services/stripe-webhook.php
The changelog for the latest version of the Stripe API (2022-11-05), which we will be using in 2.10, says:
> The charges property on [PaymentIntent](https://stripe.com/docs/api/payment_intents/object) has been removed. You can use the latest_charge property instead.
I've confirmed that this causes issues with the payment method not being found in charge.failed and other event types processed by our webhook handler. It would fail to find the payment method, and wouldn't update that info in the new order or include the correct into in the failed emails.
This PR updates the webhook to use the latest_charge property. Note that we had to "expand" it in the API call to get the payment intent so the full data was there.
=> We need to use $payment_intent->latest_charge with the Stripe API now.

adminpages/admin_header.php
In the header added to our admin page we were linking the "Get Support" text to our pricing page. A better landing page for this link is the updated /support/ page that outlines the support process and has a link for logged in members to create a ticket.
=> Updated Get Support Link to Support Page, not Pricing

css/admin.css, includes/admin.php
Adjusted the warning notification shown when a site is paused. Swapped the more dominant "clickable" button to be the dismiss (not the notice to reenable services). Added site URL we think they should be on to the notice similar to the WooCommerce inspiration notice.
=> Updating paused notification to include site URL and adjusted text

adminpages/wizard/save-steps.php
Not fixing a bug here, just stay compliant to the guidelines.
When merging this in, please consider there are 2-3 more cases (in includes/login.php) where using wp_redirect without exit.
=> Exit when using wp_redirect

classes/class-pmpro-site-health.php
There is an error on the site health check page caused by paid-memberships-pro plugin due insufficient check for calling some methods.
Resolves:
Stack trace:
#0 ../wp-admin/includes/class-wp-filesystem-ftpext.php(420): ftp_nlist()
#1 ../wp-content/plugins/paid-memberships-pro/classes/class-pmpro-site-health.php(489): WP_Filesystem_FTPext->exists()
#2 ../wp-content/plugins/paid-memberships-pro/classes/class-pmpro-site-health.php(102): PMPro_Site_Health->get_htaccess_cache_usage()
#3 ../wp-includes/class-wp-hook.php(308): PMPro_Site_Health->debug_information()
#4 ../wp-includes/plugin.php(205): WP_Hook->apply_filters()
#5 ../wp-admin/includes/class-wp-debug-data.php(1457): apply_filters()
#6 ../wp-admin/site-health-info
1. Set different permissions for wp folder that require login/password …
=> Fix for fatal error on site health check page if login/password is required for ftp account

classes/class-pmpro-wisdom-tracker.php
Easier to be tested in production. Go through the wizard and make a choice (enable tracking yes or no).
Then you gonna see the Tracking notice bugging you even if you already made a choice.
This is because we were not checking the option value to be !== false (which means a choice has been made).
=> Wisdom: update block notice if already chosen

adminpages/wizard/save-steps.php, classes/class-pmpro-wisdom-integration.php, classes/class-pmpro-wisdom-tracker.php
4 commits.
1. Fix the case $is_local = false && env != production. It was returning false... wrong.
2. Move the :8888 (=> local) logics into the _integration_ class;
3. The tracker now relies on the _integration_ class filter.
4. Save Wizard "tracking yes" choice.
=> Bug fix and enhance wisdom local detection

adminpages/membershiplevels.php, css/admin.css
Adjusted the UX of the Levels settings page. Putting groups in sections to allow collapse and reordering (no longer drag and drop to move level groups order).
Adjusted the UX to have each group labeled with behavior of multiples.
Added persistent delete button for each group but disabled with message if can't delete. We need to decide if we can support people moving levels between groups via drag and drop. The jQuery .sortable function has a way to move things between lists using this attribute: `connectWith` https://jqueryui.com/sortable/#connect-lists
We would have to update our save function to also update the group data though. Maybe not worth it.
Adjusted single group level reordering to only move on y axis.
Updated the level template popup to accept a group ID so people can add …
=> Updating the  Membership Level settings page for 3.0 branch

includes/reports.php, paid-memberships-pro.php
Changes how we include report files and selectively loads them instead of just loading everything in the reports folder
1. Navigate to Memberships > Reports
2. No errors should be thrown
Changes how we load reports
=> Changes how we load reports

pages/checkout.php
Updating the TOS display to run wp_kses_post BEFORE the pmpro_tos_content filter to allow users of that filter to add JS or otherwise avoid having the content escaped.
This is required if folks were adding content via the pmpro_tos_content filter that would get stripped by wp_kses_post or if e.g. the TOS page was using JS to generate itself from a thirdparty service. (See the related issue.)
Resolves #2385.
Additionally, you may need to run this code gist to output the unescaped content from the assigned TOS page: https://gist.github.com/ideadude/2ce102d7fd554172e4e2a98d80e74352
1. Somehow create a TOS page with some JavaScript in it. You could use a custom shortcode.
2. Choose that TOS page in the advanced settings.
3. View the checkout page. The JS in the TOS is escaped.
4. BUT if you …
=> Escaping before the filter here so it can be overriden.

adminpages/admin_header.php, css/admin.css, includes/admin.php, includes/functions.php
No longer using `pmpro_pause_mode` option to track when a site is in pause mode. Instead, we are now calculating whether a site is paused on an as-needed basis.
=> Simplifying pause mode checks

paid-memberships-pro.php
2.10.1+ specifically requires each report file to avoid conflicts with weird hosting setups that didn't delete files on plugin upgrade. This adds support for the Members Per Level new report for this cycle work.
=> Adding the members per level report specifically for 2.10.1+ report requirements

includes/login.php
#2360 added a required `$error` parameter to the `pmpro_login_failed()` function in PMPro v2.10. This broke backwards compatibility for some websites. Fixing by making the parameter optional.
=> Adding backwards compatibility for new parameter

adminpages/reports/logins.php
Fixing PHP8 deprecation warning:
`Deprecated: setcookie(): Passing null to parameter #3 ($expires_or_options) of type array|int is deprecated in ...\wp-content\plugins\paid-memberships-pro\adminpages\reports\logins.php on line 441`
=> Fixing setcookie argument for PHP8

classes/class-pmpro-field.php
Fixing issue where file type user fields on a multisite install may have the incorrect  URL saved to user meta. Previously, we tried to always build the multisite URL by adding a `/sites/[blog_id]/` prefix to the URL, but that should not be  added for the main site of a multisite.
This PR changes the URL determination  process to completely rely on WP, so it should always be accurate.
Resolves XXX.
1. Set up a multisite install
2. On the “main” site, install PMPro and set up a “file” user field
3. Complete checkout filling the file field (I’m using pngs)
4. Navigate to the frontend profile and see that the attachment shows as a “?” (not found)
=> Fixing file type user fields on main site of multisite

classes/class-pmpro-field.php
Trims spacing around a dropdown's values so that checks validate when the value is selected
1. Create a dropdown field in User fields
2. set the values to have a space after each of them (normal whitespace)
3. Edit the profile using the fronend profile edit page. Choose a new value from the dropdown and save. It saves correctly as before - but it should show the correct/selected field from the dropdown.
Trims whitespace from dropdown values
=> Trims spacing on dropdown values to ensure consistent results

classes/gateways/class.pmprogateway_stripe.php
We currently set the "defualt payment method" for each Stripe customer and each subscription is set up to charge that default payment method. In order to prepare ourselves for MMPU and improve compatibility with Stripe Checkout, this PR changes our integration to instead set payment methods directly for each subscription.
=> Now setting Stripe payment method per subscription

includes/lib/Braintree/lib/Braintree/Digest.php, includes/lib/Braintree/lib/Braintree/Error/ValidationErrorCollection.php
Fixing fatal error when processing Braintree webhooks using PHP 8.
Copied this commit from the Braintree SDK repo: https://github.com/braintree/braintree_php/commit/fb493fa31b316b4c6f3105c17d88018fbaa511cb
=> Fixing PHP 8 errors in Braintree library

classes/class-pmpro-field.php
Fixing issue where coded user fields linked to a taxonomy would save taxonomy label as meta value in database instead of the taxonomy ID. Affected field types are `select`, `select2`, `multiselect`, and `radio`.
It is worth noting that terms were still being added to users as expected. It is just the meta values in the database that are off here.
The cause of this issue are these lines:
https://github.com/strangerstudios/paid-memberships-pro/blob/702614f58840cc57990a8946f557d07730bf4965/classes/class-pmpro-field.php#L361-L367
Since `is_assoc()` only checked whether the `$options` keys are integers and taxonomy terms IDs are integers, that `$options` array was being "repaired" and the term label was becoming both the key and value.
The fix proposed in this PR is to update the the …
=> Fix taxonomy user fields saving incorrectly in database.

adminpages/login-csv.php
Resolves #2249 
Resolves #2193 
This PR addresses two issues:
The first is only 15 rows being exported at a time. This was fixed simply by making the `$limit` variable not default to `15` and updating the SQL query accordingly. I used the same approach that we use in our Orders CSV export.
The other is incorrect data being shown in the `x_this_week` and `x_this_month` columns. Previously, the `thisweek` and `thismonth` data were being shown in those columns, but that data is not the count for the week/month. Instead, `thisweek` was the number week it is in the current year, and `thismonth` is the month number. For example, in April, `thismonth` will be `4`. Changing to using just the `week` and `month` data will show the count instead of the week/month number.
> Enter a summary of all …
=> Fixing output for views, visits and logins CSV export and removing limit

preheaders/checkout.php
After our "create users before payment" change, a bug was introduced where the Account Information checkout box would still show if a user account was created during that page load. This would be the case if a payment fails and the user has to be shown the checkout form again.
This PR makes sure that the Account Information box does not show if a WordPress user was just created.
Check out with fraudulent Stripe test card: 4100000000000019
=> Skipping account fields if user was just created

adminpages/sales-csv.php
Some sites have experienced an issue in exporting sales data where a transient error is thrown even though there is data and the transient is set.
It appears that the discount_code variable is present in the URL but empty, resulting in the generated data having a hash that contains a discount code that is a string (empty) but the export results in an int (0). This PR fixes the issue
#488782 - Mods only - ticket where I was able to replicate and debug 
1. Navigate to Memberships > Resports > Sales & Revenue
2. Ensure report data is present. Ensure that no discount code has been used in filtering the data.
3. Export - data should export as expeced.
Fixed an issue with exporting Sales & Revenue data
=> Fixes Export Sales Report - Transient Error

adminpages/orders.php
Resolves #2363.
1. Set a wp time offset different than UTC
2. Filter orders list based on a certain start/end date
3. You gonna see orders from yesterday/tomorrow based on the +/- of the timezone
4. Apply the patch and it's fixed.
=> Fix timezone offset when filtering orders by date-range

adminpages/membershiplevels.php
Escaping string values in pmpro_membershiplevels_page_action_links filter and updating inline docs.
We could potentially use a function other than `esc_html()` to have more control over how the string is escaped, but as this case should never come up if the filter is being used correctly, escaping aggressively seems like a reasonable solution. In cases where this is over-escaping (ex escaping `<a href=...`), the code adding the link should be updated to use the filter correctly with the expected array input.
=> Escaping string values in pmpro_membershiplevels_page_action_links filter

includes/deprecated.php
Rewrite of #2395 on dev brach instead of 3.0.
Trying to activate a deprecated Add On will currently end up throwing a fatal error for trying to redeclare an already declared function.
This PR avoids that error message by preventing the activation of PMPro Add Ons that have been merged into core.
=> Prevent enabling deprecated Add Ons

includes/deprecated.php
Marking Register Helper Add On as deprecated. Fixes issues when both RH and PMPro 2.9+ are active.
=> Marking Register Helper as deprecated.

classes/class.memberorder.php, includes/functions.php
Checks if the AUTH_KEY constant is present, otherwise creates a value for it. This appears to only be an issue with Local as those constants don't get set. 
Resolves #2450.
1. Remove your WP Salts or setup a new site using LocalWP
2. Try to checkout
3. No error should be present 
Fixed a fatal error during checkout when testing on LocalWP
=> Fixes a Fatal Error when Auth Key constant is not defined

adminpages/orders.php, includes/profile.php
The member history page found in the edit profile page references an invoice timestamp. This has been changed to reference the order timestamp as people expect the two to match when clicking through from the member history.
Resolves #2447
Resolves #2206
1. Edit a user profile and scroll down to the Member History Section
2. Take note of an order's timestamp, click Edit
3. The timestamp should match what you saw in member history
The member history and order timestamps now show as the same times
=> Member History and Order Timestamps Now Correlate

includes/compatibility.php, includes/compatibility/oxygen-builder.php
Introduces 'conditions' functionality in Oxygen Builder that allows you to show/hide elements based on a member's level
1. Click on an element in Oxygen Builder
2. Click on the Conditions tab/icon
3. Add a condition - Select 'Paid Memberships Pro Level' under Other and specify if the element should show/hide for a level or non-member.
Adds support for Oxygen Builder
=> Oxygen Builder Compatibility

classes/class.pmproemail.php, includes/profile.php
Making the "admin changed" email MMPU-compatible by updating the `!!membership_change!!` template variable to be generic instead of listing the individual levels that were changed.
It is possible that we may want to remove that variable altogether, though this may break sites that are already using that variable in custom email templates. Maybe that is ok since we are upgrading to 3.0. This is at least a start in the right direction.
=> Updating admin change email for 3.0

includes/fields.php
Previously, admin_only fields would still show on the PMPro frontend profile if the logged in user was an administrator. This PR changes the frontend profile to never show admin_only fields. Those fields instead need to be viewed/edited in the WP Dashboard.
=> Hide admin_only fields from frontend profile

preheaders/account.php, preheaders/billing.php, preheaders/cancel.php, preheaders/checkout.php, preheaders/confirmation.php, preheaders/invoice.php, preheaders/levels.php
In July 2014, this code was added to every preheader to allow PMPro pages to retrieve a user's membership level using the global `$current_user->membership_level`:
https://github.com/strangerstudios/paid-memberships-pro/commit/11f0fa711d07ff88cce1499ea7e36a0cef9d6326
In August 2014, this process was abstracted to instead set `$current_user->membership_level` on every page load:
https://github.com/strangerstudios/paid-memberships-pro/commit/b33c0fdaa303d6ae28de82c3a21385a04a03b1e3
Since that property is now set on every page load, it should no longer be necessary to set it in preheaders.
=> Removing redundant settings of $current_user->membership_level

adminpages/orders-csv.php
Referencing the same PR that fixed the orders table and using the same patch in the export https://github.com/strangerstudios/paid-memberships-pro/pull/2440
1. Set a wp time offset different than UTC
2. Filter orders list based on a certain start/end date
3. Export the data
4. You gonna see orders from yesterday/tomorrow based on the +/- of the timezone
5. Apply the patch and it's fixed.
=> Fix timezone offset when filtering orders to export by date-range

classes/gateways/class.pmprogateway_stripe.php
When PMPro sends a user to Stripe Checkout to pay, it saves all $_REQUEST variables so that it can process the checkout when the payment is complete. Normally, credit card fields are not shown when Stripe Checkout enabled, but there are cases when they could be. For example, if multiple gateways are being used and some of them have credit card fields.
This PR ensures that the AccountNumber value in $_REQUEST is never saved to the database.
Resolves XXX.
=> Making sure account number is not saved in database when sending to Stripe Checkout

classes/class-pmpro-site-health.php, includes/updates/upgrade_2_10_6.php, includes/upgradecheck.php
Related: https://github.com/strangerstudios/paid-memberships-pro/pull/2468
This PR adds an upgrade check to see if full AccountNumber information was stored in the checkout_request_vars entries of the wp_pmpro_membership_ordermeta table, and if so removes that data.
We are not sure how common this is. It seems to require some amount of customization or misconfiguration for this to happen.
We should consider also showing a notice to explain the issue so admins can check for issues in backups and clean those of sensitive data.
Again, this issue does not seem to happen on standard installs of PMPro. But we can fake the issue and trigger the cleanup using the steps below.
1. Use the Stripe gateway and choose the option to handle payments "offsite". This enables the saving of request vars.
2. …
=> 2.10.6 ugprade, check for sensitive data in ordermeta

includes/rest-api.php
* Remove unused variable in the rest API for a Zapier event.
This feels almost not worth the effort but while debugging Zapier native integration, specifically this function I noticed an unused variable that we will never use.
=> Remove unused variable

adminpages/advancedsettings.php
Change adv settings labels from:
`Bla bla bla?:`
To
`Bla bla bla?`
=> Adv settings: Remove the trailing colons after question marks

pages/billing.php
Previously, if the update billing page was set to not show billing address fields, the logout link would not show either. This PR fixes that bug.
=> Fixed logout not showing if address fields hidden

classes/class.pmproemail.php
Add better fallback for find recipient name and assign to header_name variable. this will fix a bug found in the
“subscription cancelled” email template that is likely present in some other templates, that is actively affecting websites. 
Resolves XXX.
I tested locally, by tweaking code to have null header name, later passed a null parameter to get_user_by to get a false response and checked that flow too. 
=> [bugfixing][release ASAP wanted] 'header_name' variable exposed in some email templates

js/pmpro-checkout.js
* BUG FIX: Fixed an issue where radio button would always show asterisk even when not required. This now applies the asterisk to each and every radio button individually to support multiple radio buttons at checkout.
Resolves: #2293
=> Fix radio button always showing asterisk

pages/billing.php
We removed the "What's this" popup for CVV at checkout. This updates to remove it from membership billing page asl.
* BUG FIX/ENHANCEMENT: Removed the "What's This?" text from the CVV field on Membership Billing page.
=> Removing "what's this" for the CVV field on billing update page

classes/gateways/class.pmprogateway_stripe.php
Clarifying that the Disconnect from Stripe button disconnects all websites connected to the Stripe account, not just the site where the button was pressed.
=> Updating wording for Stripe disconnect hint

preheaders/billing.php, preheaders/checkout.php, scheduled/crons.php, services/ipnhandler.php, services/stripe-webhook.php, services/twocheckout-ins.php, shortcodes/pmpro_account.php
Renames pmpro_getOption to use get_option in all instances in the preheaders, scheduled, services and shortcode folders.
=> getOptionRenaming - preheaders, scheduled, services and shortcode

adminpages/reports/members-per-level.php
Left Joins into the WP users table to get members with accounts that exist on the site. 
The current numbers appear to report on orphaned accounts that no longer exist - this should improve accuracy. 
1. Delete a user account that has order/member history
2. Navigate to /wp-admin/admin.php?page=pmpro-reports&report=members_per_level
3. Members per level should show a more accurate value and exclude those user accounts that don't exist.
=> Adjusts Members Per Level Query For Better Accuracy

includes/login.php
Reworks the password reset email filter to return early if our login page doesn't exist
=> Reworks the password reset email filter

adminpages/wizard/done.php
* BUG FIX: Fixes an issue when not selecting site type during wizard wouldn't show any recommended Add Ons.
1. Run the wizard.
2. Do not select a site type, leave it as "Other"
3. Jump to the last step.
=> Fix: Show popular add ons wizard complete

includes/fields.php
* ENHANCEMENT: Remove associative array check in the pmpro_get_label_for_user_field_value as not all associative arrays (key/values) are identical.
1. Create a select field in User Fields that have a key:value pair. Make sure that the key is underscored for example: `my_value:My Value` etc.
2. Use the Directory Add On to display this field or even the `[pmpro_member]` shortcode to output the values of the field created in step 1.
3. See that the value output would be 'my_value' instead of 'My Value'.
4. Apply this PR and test again, 'My Value' is displayed whenever the `pmpro_get_label_for_user_field_value` is called.
Some notes, this function is only called in the `pmpro_member` shortcode and now the Directory Add On and should have minimal impact.
=> Remove associative array check when trying to get the label value.

includes/fields.php
* BUG FIX: Fixed an issue where "Extra Fields" weren't displaying correctly on admin checkout emails.
=> Show "Extra Fields" for checkout admin email for User Fields.

includes/compatibility/elementor/class-pmpro-elementor-content-restriction.php
* ENHANCEMENT: Added an option for "Show No Access Message" on widgets. Please note that isn't possible due to filter limitation for sections and containers with Elementor.
=> Add no_access message to Elementor Widgets

includes/login.php
Reworks part of the password reset redirect function to make use of pmpro_url when getting the login page URL
=> Reworks the password redirect function

includes/content.php
* Alter search functionality/filtering for posts that may be part of more than one category.
Resolves [2510](https://github.com/strangerstudios/paid-memberships-pro/issues/2510)
=> Alter filter searches logic to support multiple categories

services/stripe-webhook.php
Other gateways currently run the `pmpro_discount_code_used` filter if a discount code was used, even if the discount code can no longer be found in the database. Some add ons, such as the PMPro Group Discount Codes Add On, rely on this behavior.
=> Fixing timing of pmpro_discount_code_used with Stripe Checkout

includes/cleanup.php
* ENHANCEMENT: Automatically cancel subscription when user deletes their own profile from the frontend.
=> Cancel subscription on frontend user deletion.

includes/cleanup.php
Reverts strangerstudios/paid-memberships-pro#2548
Instead of always cancelling subscriptions when a user is deleted via a 3rd party plugin, we should instead figure out how these plugins are deleting users and specifically checking for that somehow (maybe a filter and compat files that check for $_REQUEST vars/etc) and in those cases considering there to be an intent to also delete the sub.
=> Revert "Cancel subscription on frontend user deletion."

pages/confirmation.php
* ENHANCEMENT: Use wpautop() for membership confirmation message. This fixes an issue where Elementor and possibly other solutions were not honoring the `\n` as paragraphs.
Resolves: https://github.com/strangerstudios/paid-memberships-pro/issues/2480
Side note, we escape the entire confirmation when returning it lower down with wp_kses_post.
=> Add wpautop to confirmation message

includes/compatibility.php, includes/compatibility/buddypress.php, includes/functions.php
* Created a new function called pmpro_maybe_cancel_subscription which is filterable and tended to be used for account deletion.
Filterable by 'pmpro_maybe_cancel_subscription' which returns true/false when called.
TODO: Add an option/setting for this to allow site owners to automatically delete subscriptions when deleting users. Could be used for other areas of PMPro and supports "actions" parameter to know where this function is being called from to give developers even more control with the filter.
=> maybe_cancel sub for BuddyPress/Boss

classes/class-pmpro-orders-list-table.php
Pagination on the orders page broke when searching
1. Navigate to Memberships > Orders and search for something
2. Results will be returned but the count will show as 1 and no page numbers
3. Once the fix has been applied the pagination shows as expected
=> Bug Fix: Pagination fixed when searching orders

includes/login.php
Fixes issue where password resets may incorrectly show `invalidkey`.
Switching to using `is_a()` instead of `gettype()` as `gettype()` only returns the string "object", not the class name "WP_User".
Also fixing incorrect variable name `$user`.
=> Fixing logic for invalidkey password reset error

pages/checkout.php
When hooking into the `pmpro_checkout_message` filter to adjust the returned string it only displayed at the top message on the checkout page and not on the bottom message by the submit button. Adding this filter at the bottom as well should allow displaying the filtered message in both locations.
1. Add custom code that hooks into the `pmpro_checkout_message` filter and set a custom checkout error.
2. Check out for a paid membership level using Stripe as the payment gateway and the testing credit card number `4000000000000002` that should be declined.
3. Observer that the custom error message is displayed in both locations on the checkout page.
> ENHANCEMENT: Added a pmpro_checkout_message filter at the bottom of the checkout page that can be used to filter error messages shown at …
=> Add pmpro_checkout_message filter at bottom

classes/class-pmpro-discount-code-list-table.php
Small fix where the "Orders" row action wasn't showing for codes with unlimited uses. We were incorrectly checking the code's total uses, but should rather be checking count of times used (which means there are orders to show when linking over).
* BUG FIX: Fixed issue where row action to view a discount code's orders was not showing for unlimited use codes.
=> Fix where orders link wasn't showing for unlimited use codes

adminpages/login-csv.php
Fixing incorrect value in `enddate` column of the logins report CSV export.
1. Have users with enddates on your website
2. Export the logins report
3. Verify that enddates are correct in exported file
* BUG FIX: Fixed exported enddates in the Visits, Views and Logins Report CSV export.
=> Fixing enddate column in logins csv export

includes/deprecated.php
Adds the Table Layout Plugin Pages Add On to the deprecated plugins check
Resolves #2484
> Marking Table Layout Plugin Pages Add On as deprecated
=> Marking Table Layout Plugin Pages as deprecated

includes/functions.php
Some site setups, including WP Playground, are stricter about ambiguous column names in SQL queries. This fixes an issue that is caused by this in WP Playground by providing more context around a `GROUP BY` variable in our `pmpro_getMembershipLevelsForUser()` function.
Related to #2551, but does not close.
=> Avoiding ambiguous column name - WP Playground Compatibility

adminpages/dashboard.php, adminpages/discountcodes.php, adminpages/login-csv.php, adminpages/memberslist-csv.php, adminpages/reports/logins.php, classes/class-pmpro-discount-code-list-table.php, classes/class-pmpro-members-list-table.php, classes/class.memberorder.php, classes/class.pmproemail.php, includes/functions.php, includes/profile.php, includes/updates/upgrade_1_8_6_9.php, includes/updates/upgrade_1_8_9_1.php, includes/updates/upgrade_1_8_9_3.php, includes/updates/upgrade_2_4.php, pages/invoice.php, shortcodes/membership.php, shortcodes/pmpro_account.php
Build off of #2601 which should be merged first in order to see a clean diff. It may also be easier to just look at the two more recent commits to see individual changes.
Some site setups, including WP Playground, do not support the `LIMIT` SQL keyword during `UPDATE` and `DELETE` queries. In order to fix that incompatibility, this PR removes the `LIMIT` keyword from those queries. The `LIMIT` keyword was mainly used as a safeguard, but all of these queries thoroughly check the data being updated/deleted, so this should not cause issues.
Related to #2551, but does not close.
=> Avoid limit with update query - WP Playground Compatibility

adminpages/dashboard.php, adminpages/discountcodes.php, adminpages/login-csv.php, adminpages/memberslist-csv.php, adminpages/reports/logins.php, classes/class-pmpro-discount-code-list-table.php, classes/class-pmpro-members-list-table.php, classes/class.memberorder.php, classes/class.pmproemail.php, includes/functions.php, pages/invoice.php, shortcodes/membership.php, shortcodes/pmpro_account.php
Some site setups, including WP Playground, do not support SQL functions such as `CONVERT_TZ()`. In order to fix that incompatibility, this PR moves the logic to convert SQL datetimes to timestamps into PHP (specifically the new function `pmpro_convert_utc_datetime_to_timestamp()`).
In the past, we used to pull these dates directly from the db as timestamps using something like:
`UNIX_TIMESTAMP( CONVERT_TZ(startdate, '+00:00', @@global.time_zone) ) as startdate`
When we were doing those conversions, the dates were stored in the db in UTC, but if the server was set to a different timezone, `UNIX_TIMESTAMP()` would incorrectly assume that those dates were in the server's timezone and try to "convert them to UTC". `CONVERT_TZ()` was needed to undo the unnecessary conversion.
Related to #2551, …
=> Avoiding timezone math in SQL - WP Playground Compatibility

includes/functions.php
Some site setups, including WP Playground, have trouble passing `'NULL'` for a datetime value. In these cases, it is defaulting to the current date instead of `0000-00-00 00:00:00` like we assume it would.
This PR updates our `pmpro_changeMembershipLevel()` function to specifically set `0000-00-00 00:00:00` to avoid this issue.
Related to https://github.com/strangerstudios/paid-memberships-pro/issues/2551, but does not close.
=> Avoiding NULL enddates - WP Playground Compatibility

shortcodes/pmpro_member.php
* This happens when required field attribute is not present. Added validation to avoid this scenario. Adding a document update request too.
Added validations and Bail to $atts parameter s and $fields var after extracting shortcode to ensure that fields attribute was passed and avoid the warning.
Fixes https://github.com/strangerstudios/paid-memberships-pro/issues/2618
1.  Run steps described in the issue above.
2. Check that instead ow watning and / or array word print it bails and print the validation message.
=> PHP 8.1 warning: Array to string conversion with [pmpro_member] #2618

preheaders/levels.php
Removing functionality marked to be deprecated and code that is no longer used.
`$pmpro_levels` is being set directly in the levels page template now.
=> Cleaning up level preheader

pages/confirmation.php
Removing code that is duplicated between the invoice page and confirmation page. In the future, this simplifies the code for the confirmation page and, in the future, will prevent needing to update code twice when tweaks are made to the invoice page.
=> Abstracting invoice section on confirmation page

blocks/src/membership/block.json, blocks/src/membership/edit.js, blocks/src/membership/editor.scss, blocks/src/membership/render.php
- Add option to "exclude memberships" to require membership block
- Update Require Membership block to have a dropdown to show to all members, specific levels, and logged-in users
Warning: The settings to this new Require Membership block is one-way. If you test this PR and then revert back to an older version of PMPro, your Require Membership block settings may no longer be correct.
=> Require membership block overhaul

js/pmpro-admin.js
=> Add confirmation when switching tab with changes

pages/billing.php
Just fix how PHP opens and closes wrapping style attribute in the alert message. 
Resolves #2500 .
Check steps to reproduce in the isse #2500 itself/
=> Bug: No notice of failed/successful payment information update

adminpages/member-edit/pmpro-class-member-edit-panel-subscriptions.php, css/admin.css
This change puts the "Cancelled subscriptions" in a toggle box so it isn't taking up real estate or distracting for the active subs.
This still uses the scrollable box, but in the future we may consider pagination, ajax search/filters, or an ajax-based "load more".
=> Cancelled Subscriptions now in a toggle box that defaults to collapsed

adminpages/member-edit.php
This change will only show the User Field groups on the Edit Member screen once there is a true User ID to check field groups for.
=> Only show User Fields Group panels if there is a User ID to check

adminpages/orders.php, js/pmpro-admin.js
When editing a level, the option to choose a membership level is now a select2.
=> Making membership a select2 when editing order

adminpages/admin_header.php
Now hiding the contextual messages set in the admin_header when on the Single Member Edit Dashboard page.
Before and After screenshots
=> Do not show contextual messages on single member edit

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php
When the member has no levels in a "one per" level group, the button was showing as "Change Membership".
This update accounts for the case where the user doesn't have anything in the group and rather shows "Add Membership".
=> Fix button text when adding a membership to a one per group when member has no levels in group

classes/class-pmpro-subscription.php, classes/gateways/class.pmprogateway.php
Moving the default behavior for updating subscription info to the abstract PMProGateway class.
This code that we thought was "universal" may not actually be. The PMPro Pay By Check Add On is one instance where we would not like to have "next payment dates" be automatically updated when they are in the past. Moving this update code to the abstract gateway class allow individual gateways to override this kind of functionality based on their requirements.
=> Moving default behavior for updating sub info

adminpages/member-edit.php, adminpages/member-edit/pmpro-abstract-class-member-edit-panel.php, adminpages/member-edit/pmpro-class-member-edit-panel-user-info.php, css/admin.css, includes/functions.php, js/pmpro-admin.js
1. Hiding the dropdown to choose user role from Add Member form if the site default is Subscriber.
2. Changed to use the matching core WP password generate code and confirmation of weak password.
3. Using a "disabled" field for username once set to match core user-edit.php view.
4. Removed unused password visibility toggle from pmpro-admin.js
5. Save function restructured to operate more like core WP, support for the illegal usernames filter in core WP.
6. Showing a link to edit membership for the found user if an existing member has the same username or email.
7. Update to messages set an array of errors if there are more than one.
Note: there are few TO DO: comments in here.
=> Add Member (User info tab) Updates

js/pmpro-admin.js
* ENHANCEMENT: Added functionality to close popup notifications if clicked outside of the modal.
Resolves https://github.com/strangerstudios/paid-memberships-pro/issues/2682.
1. Connect to Stripe Connect, see the popup.
2. Click inside the modal to ensure it still works for copying/pasting. Should not close in this instance.
3. Click anywhere on the screen outside the modal/popup to close it.
=> Hide popup if outside the popup is clicked.

pages/confirmation.php, preheaders/confirmation.php
The main functional change in this PR is that the `$pmpro_invoice` global is no longer being unset during the confirmation preheader if the checkout was free. Instead, free checkouts are accounted for in the logic of the confirmation page itself.
The other changes in the confirmation page template code basically make the template rely solely on the `MemberOrder` passed in via `$pmpro_invoice` instead of pulling information from other sources. This eliminates the need to use the `$current_user` global and grab the membership level for the user separately.
=> Updating confirmation page logic for 3.0

adminpages/member-edit/pmpro-abstract-class-member-edit-panel.php, adminpages/member-edit/pmpro-class-member-edit-panel-user-fields.php, adminpages/member-edit/pmpro-class-member-edit-panel-user-info.php
Adding a user updated/created message when the "user info" tab is saved on the single member dashboard and when user field panels are saved.
=> Adding message for user updated

classes/class.pmproemail.php
In a previous PR, we updated the "admin changed" email template to be more generic rather than list the specific levels that were changed:
https://github.com/strangerstudios/paid-memberships-pro/pull/2434
Since then, some of the email template variables that were deleted for that email have been re-added and are now throwing errors. This PR removes those email template variables again.
=> Removing deprecated email template variables

classes/gateways/class.pmprogateway_authorizenet.php
After we update an Authorize.net payment method, this PR adds another API call to set the new Payment Profile as the default for the Customer Profile in Authorize.net.
Needed to add a 10 second sleep before calling `updateCustomerPaymentProfileRequest`, otherwise setting the new payment method to "default" would fail. It would be great to find a more elegant solution for this. 
Should fix #2138, though not 100% sure. This is a weird issue. It may be necessary to instead delete all old Payment Profiles besides for the one that was just created, so this may be a next step.
1. Check out for an Authorize.net subscription
2. Uncomment the `// In case we want to check that the payment profile was set to default.` code in the PR
3. Use the update billing page to change payment methods4. 
4. Use …
=> Setting new payment method as default after Authorize.net update billing flow

css/frontend-rtl.css, css/frontend.css, pages/levels.php
A user brought it to our attention that the default levels page wasn't passing an Lighthouse Accessibility check related to tables rows in the body having a <th> element to identify the row.
This PR updates the levels table so the level name column uses the <th> markup and passes Lighthouse Accessibility tests 100%.
Accessibility will always be a two-part issue, where we can do our best in the core product and then the site's chosen WP theme on the site also needs to pass.
This test was done on the latest WordPress Twenty Twenty-Four theme.
* BUG FIX/ENHANCEMENT: Improved accessibility for the frontend membership levels page default table.
=> Fixing levels table for accessibility

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php, adminpages/membershiplevels.php, adminpages/memberslist.php, classes/class-pmpro-members-list-table.php, shortcodes/pmpro_account.php
Establishing a naming structure for what is a Level Cost vs. what is a Fee.
If you get the data using this function: pmpro_getLevelCost, it’s Level Cost.
If you get the data using this function: $subscription->get_cost_text(), it’s Fee.
Exceptions to this right now include the levels page and checkout pages where we call the level's cost a "Price".
=> Updating level cost and fee statements; now showing subscription not level cost on account page

classes/class.memberorder.php, classes/gateways/class.pmprogateway_check.php
Keeps subs table data in sync with Pay By Check Add On. Requires this PR to be merged into PBC in order to work correctly:
https://github.com/strangerstudios/pmpro-pay-by-check/pull/110
=> Subs table compatibility for PBC

adminpages/reports/members-per-level.php, classes/class-pmpro-admin-activity-email.php, includes/compatibility/oxygen-builder.php, includes/functions.php, pages/checkout.php, preheaders/account.php, preheaders/checkout.php, shortcodes/pmpro_account.php
Removing uses of the `$pmpro_levels` global besides for those needed for backwards compatibility. The `pmpro_getAllLevels()` function should be used instead.
Deprecating that global also allows simplifying the arguments for the `pmpro_getAllLevels()` function as the second `$use_cache` argument was unclear.
Looking at our Add Ons, it does not any use the `$pmpro_levels` global without setting it using `pmpro_getAllLevels()`, so backwards compatibility with our Add Ons should not be an issue. The following regex can be used to find all instances of the global being defined: `^(?=.*\bglobal\b)(?=.*\$pmpro_levels).*`
=> Deprecating global $pmpro_levels

adminpages/discountcodes.php
Fixes header / admin notices breaking on "Edit" single discount code view.
=> Moving header end where notices are displayed so it doesn't break the edit code layout

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php, includes/adminpages.php, includes/capabilities.php, includes/profile.php, includes/rest-api.php
* ENHANCEMENT: Added pmpro_edit_members capability for editing membership information for users, or creating new members with the "Edit Member" screen.
Note: The Membership Manager Add On also needs to be updated and will reference this PR shortly.
=> Add 'pmpro_edit_members' capability

adminpages/orders.php
The message formerly said "obscure all but last 4" which in my mind implies that the full number is visible or stored somewhere. This improvement aims to make that field description more clear.
=> More specific message about last 4 CC digits stored

adminpages/subscriptions.php
Improving UI of the Change Subscription Level action on View Subscription page
Changed from a link to a "button" which is a preferred HTML element for this type of interaction (for accessibility).
=> Slight adjustment to form display for change membership level on subscription. using button for a11y

includes/localization.php
* BUG FIX: Fixed an issue where the site locale was loading instead of the user locale (in the admin).
_Don't apply the PR fix for steps 1-3._
1. Set your site locale to Portuguese Brasil.
2. Set your admin user locale to English (United States)
3. See that your Membership menu in the backend is loading the non-English text.
4. Apply the patch and view the dashboard. Your membership dashboard and PMPro page settings should be set to EN_US
5. The frontend of the site should still be PT_BR as it's set in the site settings.
=> Fix localization loading incorrectly.

classes/class-pmpro-site-health.php
If you want to know exactly how the levels are configured, the levels metas are needed.
It's also useful to gather informations from the addons, but this should be delegated to them.
Example:
```php
function pmprosd_site_health_info_membership_level( $membership_level ) {
$membership_level->subscription_delay = get_option( 'pmpro_subscription_delay_' . $membership_level->id, '' );
return $membership_level;
}
add_filter( 'pmpro_site_health_info_membership_level', 'pmprosd_site_health_info_membership_level' );
```
**Btw, if we could use level metas in subscription delay addon, to avoid the need of the code above.**
=> Add level metas for site health info

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php, classes/class-pmpro-subscription.php
- If expiration date is not set for a membership, defaults to subscription's next payment date
- If editing a user's level associated with a subscription, show checkbox to cancel subscription
- Fixing PHP error in subscription class
=> Allow cancelling sub while editing membership

css/frontend.css, pages/billing.php, pages/confirmation.php, pages/levels.php
Fixed display issue on the login page shortcode / block.
Removed back to account link from levels page. The logic here was odd and in practice this never looks great on people's sites.
Fixed all instances of the actions nav to wrap in a div (not a paragraph tag) for consistency.
=> Cleaning up some actions nav css and frontend display

blocks/src/membership/render.php
We added wp_kses_posts to this render but realizing now that the do_blocks applies content filters and is likely already escaped and sanitized safely so we do not need to do this. It was stripping the necessary HTML for the Log In Form block in PMPro.
=> Fixing render for membership block

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php
* [x   ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/paid-memberships-pro/pulls) for the same update/change?
When editing a member, if a level group has no levels in it, show a link to edit membership levels.
=> Link to levels page if group has no levels

adminpages/member-edit/pmpro-class-member-edit-panel-user-info.php
Fixing issue where saving `\\\\` will strip slashes to `\\` on the Member Edit user notes.
=> Removing stripslashes() for user notes

adminpages/member-edit/pmpro-class-member-edit-panel-user-info.php
Missing echo in my code to set the username field to disabled when editing an existing member.
=> disabling username field when editing an existing member on the single member dashboard

classes/class.memberorder.php
Setting start date for subscription to the order date (will automatically adjust later if order is in the future for some reason) and also takes a guess at the "next payment date" (gateways will update this later).
=> Improving default dates on new subscriptions

adminpages/subscriptions.php
Show level ID when editing a subscription with a deleted level
=> Show level ID when editing a subscription with a deleted level

classes/class-pmpro-subscription.php
Fixing issue where the error message returned by the gateway would not be shown to the administrator when a subscription fails to sync with the gateway.
=> Fixing error message when a subscription fails to sync with gateway

includes/functions.php
The `$pmpro_giving_level` global is not needed and adds unnecessary confusion to the code. Instead, we should just check whether `$status` is `changed`, which should only be the case if the user is being assigned a membership level at the same time.
=> Removing unneccessary global $pmpro_giving_level

classes/class.memberorder.php
Previously, subscriptions were only created when an order is saved. This works fine in most cases, but not in a scenario like this:
1. Site upgrades to 3.0
2. Site downgrades to 2.x for whatever reason
3. User checks out for recurring membership on 2.x
4. Site switches back to 3.0
In this case, the upgrade script would not create a subscription for this user since the upgrade script won't run twice. Without this PR, that means that a subscription object wouldn't be created for this user until an order for the subscription is saved, which likely wouldn't happen until the next renewal. But with this PR, a subscription order only needs to be loaded in order for the subscription to be created, which is much more common and may just happen over time by chance.
Resolves XXX.
> Enter a summary …
=> Now creating subscription when constructing orders

classes/gateways/class.pmprogateway_stripe.php
Abstracting getting Stripe order descriptions into its own method and now using that method to add descriptions to payments made via Stripe Checkout.
=> Sending payment descriptions to Stripe Checkout

adminpages/levels/delete-level.php
Fixing issue where if a user has multiple memberships and one of the corresponding levels is deleted, all memberships would be terminated.
=> Fixing removing all memberships on level delete

classes/gateways/class.pmprogateway_stripe.php, includes/checkout.php, includes/scripts.php, js/pmpro-checkout.js, js/pmpro-stripe.js
No longer sending sensitive data to checkout_levels API endpoint when mounting/updating Stripe payment request button.
Also abstracts logic to get sensitive checkout fields and adds a new filter `pmpro_sensitive_checkout_request_vars` for Add Ons and custom code to hook into.
=> Avoid sensitive data in checkout_levels endpoint

includes/functions.php, scheduled/crons.php
1. Now using `pmpro_cancelMembershipLevel()` when processing an expiration
2. Now only trying to cancel a level if the user has it
3. Fixes bug where inactive membership entries would be affected by cancellation status query
=> Only cancel levels that the user has and fix cancellation call when expiring memberships.

classes/class.memberorder.php
Reverts strangerstudios/paid-memberships-pro#2746
This causes an infinite loop with PayPal Express checkout and any other case where subscription orders are being loaded as the subscription is being created.
=> Revert "Now creating subscription when constructing orders"

classes/gateways/class.pmprogateway_stripe.php, services/stripe-webhook.php
Moving check to avoid sending users to Stripe Checkout multiple times to inside the `pmpro_checkout_before_change_membership_level()` method of the Stripe gateway class.
This is helpful to avoid infinite loops where there are multiple hooks on `pmpro_checkout_before_change_membership_level`. We only want users sent to Stripe Checkout when they need to pay.
=> Check transaction IDs before sending to Stripe Checkout

includes/functions.php
If a user has multiple subscriptions for a single level for whatever reason, this change avoids issues where only some of the subscriptions get canceled when the level is lost if one of the subscriptions has an error while canceling.
=> Cancel all subs on level removal

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php, css/admin.css
We're planning user stories + testing to do more with the membership cancel/change/edit stuff. For now, this PR does a few minor things:
- Row Actions for the Memberships tab of the Member Edit screen are now always visible (not just on hover).
- Level name that's being changed / cancelled / edited is now bold and a color for what the change is. We could do more with this. I tried a pill-style tag but it wasn't my favorite.
- Changed the button to "cancel" the action you started to say "Close". This helps a small bit with the confusion over "Cancel Membership" being a button right next to "Cancel" (cancel your change).
=> Cancel to close; adjusting some CSS

js/pmpro-admin.js
Resolves a bug caused by https://github.com/strangerstudios/paid-memberships-pro/blob/b82164df98dc1be3cd905f1815e898dd1f6cf46b/js/pmpro-admin.js#L90-L96.
**If not returning false when opening a modal, then the current click action event is still propagating causing the modal immediately close after opening (not even seeing this, because it's happening too fast).**
To reproduce the issue, install the v3.0 affected by the bug. Go through the wizard NOT setting up a license.
Then try to install an addon from the addons panel. Nothing happens.
Well, the modal is opening and closing, but again: too fast to be seen.
=> Fix compat with auto-close popup on click-outside

adminpages/dashboard.php, adminpages/memberslist.php, adminpages/orders.php, adminpages/reports/logins.php, adminpages/reports/memberships.php, adminpages/reports/sales.php, classes/class-pmpro-members-list-table.php, includes/adminpages.php, includes/capabilities.php
This is the start of better capability checks before we render buttons that do things.
On the adminpages/dashboard.php, we should do a bit more here to adjust who sees the "License" section. We need something else to replace it with or that entire "welcome" box could become separate boxes/collapse without that section (CSS fix).
The member-edit and panels have more specific capability checks we need to have a discussion for.
=> Adjusting capability checks throughout to hide elements where the cap is not present

adminpages/member-edit.php, adminpages/member-edit/pmpro-abstract-class-member-edit-panel.php, adminpages/member-edit/pmpro-class-member-edit-panel-orders.php, adminpages/member-edit/pmpro-class-member-edit-panel-tos.php, adminpages/member-edit/pmpro-class-member-edit-panel-user-fields.php, adminpages/member-edit/pmpro-class-member-edit-panel-user-info.php, adminpages/memberslist.php, adminpages/subscriptions.php, classes/class-pmpro-field.php, includes/adminpages.php, includes/capabilities.php, includes/fields.php, paid-memberships-pro.php
- Improved capabilities for edit member page
- Switched "other" tab to "TOS", only showing if TOS is enabled
- Fixed capabilities for user fields code and now showing group description on edit member tab
=> Improved capabilities for edit member page

includes/functions.php
Caching calls to `pmpro_getLevelAtCheckout()` for performance boost.
=> Re-adding caching of pmpro_getLevelAtCheckout()

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php
One spot where the callback function to get the capability was missed.
=> One missed spot for new callback for edit member cap

adminpages/memberslist-csv.php, classes/class-pmpro-members-list-table.php
On sites with a large numbers of users and/or user meta, members list searches could take a LONG time. The culprit is the join on the user meta table and the checks against user meta in the where clause.
To help with this, we already detect when there is a colon in the search query, and in those cases presearch for a specific user field or meta key. However "non-colon" searches could take a long time or even cause resource issues on the server.
This PR adds a check using the new `wp_is_large_user_count()` added in WP 6.0.0. If this value is true, then a simpler version of the search is done that doesn't join on the user meta table or search any user meta fields.
By default, sites with over 10k users are considered large. This can be adjusted using the `wp_is_large_user_count ` filter. …
=> Avoid user meta joins in member searches on big sites.

classes/class-pmpro-field.php, css/admin.css
Improved the UI for displaying a file type field. When a file exists, the preview and actions to delete or replace are present. Without an existing file, the input form is shown.
New buttons to handle replace / delete and cancelling that action.
=> Formatting for file-type fields on Edit Member and Edit User screen

css/frontend.css, includes/adminpages.php
Styling the dropdown with color context and wording changes.
I think we should add a setting to hide this in advanced settings or usermeta somehow. Most plugins that add things to the WP Toolbar allow them to be disabled (https://yoast.com/help/remove-yoast-seo-admin-bar/).
This was also tested with the Kadence theme that Kim W. found inconsistency with. Looks good in any theme that I've tested with.
=> Adjusting the wording and appearance of the View As toolbar feature for admins

classes/class-pmpro-discount-code-list-table.php, classes/class-pmpro-members-list-table.php, classes/class-pmpro-orders-list-table.php, includes/adminpages.php
Resolves #2497 
In addition to allowing showing/hiding columns and setting "per page" settings on the orders and discount code list tables, this PR also fixes a bug where changing the "per page" setting on the members list changes the corresponding setting on the users list and vice versa.
=> Adds Screen Options for orders and discount codes list tables

classes/class-pmpro-subscription.php, classes/class.memberorder.php, preheaders/billing.php
If we have a saved MemberOrder, use the `get_subscription()` method instead of searching for a subscription manually.
=> Use MemberOrder->get_subscription() where we can

adminpages/member-edit.php, adminpages/member-edit/pmpro-abstract-class-member-edit-panel.php, css/admin.css, js/pmpro-admin.js
Adding a "Show More" if the number of tabs is > 6. 6 is the number that includes all default tabs, the TOS tab if present and one additional user field group tab.
Added filter `pmpro_member_edit_num_visible_tabs` to change the default.
JS to handle the button click and also preserve the expanded tabs view if you make a change and save changes to a panel that would otherwise have the tab hidden.
=> Adding a "show more" button in the case that tabs on the edit member screen gets really long

adminpages/reports.php, adminpages/reports/logins.php
Moving the visits views and logins report to the end. added a note about the data.
=> Sorting visits report to last, adding message about the data inconsistency

includes/rest-api.php
* BUG FIX: The REST API was using the wrong capability during the get_checkout_levels and hide the confirmation message. This would be hidden more times than not due to this incorrect permission.
=> Adjust REST API capability

classes/gateways/class.pmprogateway_stripe.php, preheaders/billing.php
- Fixing misplaced curly brace causing users to not be able to update their payment method on-site when Stripe Checkout is being used at checkout.
- Fixing PHP warnings at checkout when billing fields are not shown. Logic is copied from the checkout preheader.
=> Fix update billing with stripe checkout, php warnings

classes/class-pmpro-subscription.php, classes/class.memberorder.php
Doing a isset() test vs. null !== strict comparison has only one difference: isset does not error in case the array key is actually not set.
Avoid phpcs "Condition is always 'true' because 'isset( $args['user_id'] )' is already 'true' at this point".
Use the following snippet to see that it's the exactly same thing.
```php
$args = [];
var_dump( isset( $args['a'] ) );
var_dump( null !== @$args['a'] );
var_dump( isset( $args['a'] ) && null !== $args['a'] );
echo '--------' . PHP_EOL;
$args['a'] = '';
var_dump( isset( $args['a'] ) );
var_dump( null !== $args['a'] );
var_dump( isset( $args['a'] ) && null !== $args['a'] );
echo '--------' . PHP_EOL;
$args['a'] = 'test';
var_dump( isset( $args['a'] ) );
var_dump( null !== $args['a'] );
var_dump( isset( $args['a'] ) && null !== $args['a'] );
```
=> Query args filtering simplified. isset() is enough to still support empty strings. Removed null !== comparison

includes/admin.php
Inspired by [this tweet](https://twitter.com/verygoodplugins/status/1751228984065446001) and other discussions, this PR removes non-PMPro notices from PMPro settings pages.
This PR needs some discussion.
1. Do we really want to do this?
2. Are we sure we aren't filtering out PMPro callbacks that might not start with pmpro_ or be part of a class that starts with PMPro_?
3. Should we only do this on certain pages?
4. Should we even hide some of our notices?
5. We had some stricter code already running on the wizard that could be merged with this new code: https://github.com/strangerstudios/paid-memberships-pro/blob/74d80891d63a3b65fccb448b52461e7c525b6132/includes/admin.php#L217-L226
> ENHANCEMENT: Hiding non-PMPro notices from PMPro settings pages.
=> Hide non-PMPro notices on PMPro settings pages.

classes/class-pmpro-field.php
The second parameter to `current_user_can()` should be blank unless a meta capability is passed as the first param, in which case the second param should be the object ID that the current user is trying to view/edit.
1. Add this gist to your website, replacing `969` with the ID of an active member: https://gist.github.com/dparker1005/27eab6c0779f3dca9b51f6aa023ab48f
2. Add user fields that would be editable on the Edit Member page
3. Edit user 969 as an admin and see that the user fields cannot be edited. Edit any other user and see that they can.
=> Fix second params to current_user_can

includes/functions.php
* BUG FIX: Fixes cases where passing a string, but valid, level_id to the `pmpro_getLevelAtCheckout` would return NULL.
The proposed fix is to case the level ID to integer as late as possible. This only occurs when you pass through the level ID as a string, a good example of this is the Advanced Levels Page Add On using this function and passing through a string.
=> Cast level_id to be integer in the pmpro_getLevelAtCheckout

adminpages/member-edit.php, adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php, adminpages/memberslist-csv.php, classes/class-pmpro-members-list-table.php, includes/functions.php, shortcodes/pmpro_account.php
This is an alternative to the PR here: https://github.com/strangerstudios/paid-memberships-pro/pull/2767
We are trying to allow new folks to filter the expiration date wherever it is shown using just one filter, while still supporting older versions of this filter which were used in a few different pages/scenarios.
> ENHANCEMENT: Added `pmpro_get_membership_expiration_text()` function and using it whenever an expiration date is shown. This can be filtered by the `pmpro_member_edit_memberships_panel_memberships_enddate_text` and also supports the old `pmpro_account_membership_expiration_text` and `pmpro_memberslist_expires_column` filters from older versions of PMPro.
=> Added pmpro_get_membership_expiration_text() function

classes/class-pmpro-field.php, includes/fields.php, shortcodes/pmpro_member.php
PMPro 3.0 adds a read only view for the new edit member pages. When in this view, we noticed that file type user fields would only show the file name. In most scenarios, it makes sense for folks who are able to "edit_members" and otherwise view members to be able to view the files associated with that user. So we are updating the displayValue method to show previews and links for file type fields.
This should also make it so fields shown through the member shortcode are also shown in this way.
1. Create a user field of type file.
1. As an admin, edit a member to upload a file for them. Use an image to test previews.
2. Edit a user to have a role with the pmpro_edit_members cap but not the edit_users cap
3. Use that user to edit the membership for a member.
4. Go to the tab for the field …
=> Show links and previews when viewing a file field as readonly

adminpages/pagesettings.php, includes/gateway-request-handlers.php
Throwing warnings when deprecated actions/filters are used.
=> Marking some hooks as deprecated for 3.0

shortcodes/pmpro_member.php
* BUG FIX: Fixed a minor typo causing a fatal error in certain cases where the we tried to strip the member shortcode.
=> Fix undefined function error for 2.12.9

adminpages/memberships-csv.php, adminpages/reports/memberships.php, adminpages/reports/sales.php
Invalid dates have caused SQL errors on some websites.
=> Calculating the last day of month instead of assuming 31

adminpages/memberslist-csv.php, classes/class-pmpro-members-list-table.php
Changing "Fee" column to "Subscription" and letting subscription generate the cost text to show. A link will also be shown to view the subscription on hover.
The main benefit of this PR is not relying on the payment data from the memberships_users table, which could be inaccurate. The tradeoff is not showing the initial payment price on the Members List anymore. Custom code could be used to add that information back.
Theoretically, we could also add other subscription info into the Members List (such as next payment date), but it feels right to have this information in a separate "subscriptions" list table.
The subscription billing amount, cycle number, and cycle period were also added to the CSV export along with the removal of the membership_user's initial payment field.
> Enter a …
=> Pulling subscription data into Members List and Members CSV export.

adminpages/member-edit/pmpro-class-member-edit-panel-tos.php, js/pmpro-admin.js
When switching tabs on the edit member page, update the URL accordingly. This means if the page is refreshed, it will go back to the previous tab.
=> Updating edit member tab in URL

adminpages/member-edit/pmpro-class-member-edit-panel-subscriptions.php, adminpages/subscriptions.php
If a subscription has a sync error, display the error when the subscription is viewed.
=> Showing subscription sync errors

js/pmpro-cancel.js, pages/cancel.php, preheaders/cancel.php
The goal of these changes is to allow Add Ons (Such as the Reason For Cancelling Add On) and custom code to easily hook into the cancel page.
Added new actions:
- `pmpro_cancel_before_submit`
- `pmpro_cancel_should_process`
- `pmpro_cancel_processed`
=> Updated cancel page to be a nonced form with new actions

classes/class-pmpro-field.php, classes/gateways/class.pmprogateway.php
Ideally, we would comb through our gateway and field code and stop using dynamic properties altogether, but it is important to address this PHP warning ASAP. So this PR adds the `#[AllowDynamicProperties]` attribute to all gateway classes for now, and we will address this issue fully down the road.
Using `#[AllowDynamicProperties]` is the path that core WP is using to address these PHP warnings as well.
Test using PHP v8.2+
=> Allowing dynamic properties in gateways and fields to avoid PHP warnings

adminpages/reports/sales.php
Now reading empty "prices paid" data instead of always re-calculating.
=> Fixing cache of "empty prices paid" on sales/revenue dashboard report

adminpages/reports/memberships.php
Using `isset()` instead of `empty()` so that we can read cached values that were set to `0` instead of trying to recalculate them.
=> Now reading cached values that are 0

classes/class-pmpro-subscription.php
- Only pull default subscription data from current level settings if the subscription is active. This is to prevent old subscriptions from being updated with current pricing data when the old subscription could have been charged at a different price. If we have the old memberships_users entry, we will use that, but otherwise, we should just 0 out the billing amount and try to sync with the gateway if we can.
- If we are migrating a cancelled subscription, we are now defaulting the "enddate" to the date of the most recent subscription order instead of the current date. This is far more accurate. The other option would be to try to pull the enddate from the memberships users table, but this is potentially problematic since the user could have multiple terminated entries for the same level. …
=> Better subs table migration defaults

adminpages/levels/delete-level.php, includes/functions.php, preheaders/cancel.php
`! empty()` fixed warning when `$worked` is not defined.
`$pmpro_error` change avoids overwritting any error messages that may already be set.
`$_REQUEST['confirm']` change is needed to re-show the cancellation form on error.
=> Fixing error handling on cancel page

adminpages/admin_header.php
Useful to avoid an ajax call at every back-end page load, on high traffic websites.
Usage example: `add_filter( 'pmpro_max_notification_priority', '__return_zero' );`
1. add the snippet
2. load any pmpro admin page
3. the notifications ajax is not running anymore
=> Completely remove the admin notifications and ajax if prio=0

classes/class-pmpro-members-list-table.php
Previously, the `pmpro_manage_memberslist_custom_column` did not pass the full `$item`. This means that Add Ons that use that filter will know the user being shown in the members list, but not other information like the specific level being shown. This is an issue for MMPU compatibility.
This PR passes the entire `$item` being shown so that Add Ons can accurately add data to the Members List.
=> Passing $item to get level ID being shown

classes/gateways/class.pmprogateway_stripe.php
If the user has an unpaid invoice on their Stripe subscription, the next payment date for the subscription in PMPro should be that unpaid invoice's period end date.
=> If there is an unpaid invoice, next payment date should be that due date

classes/gateways/class.pmprogateway_stripe.php
* Add the button
* Catch click event and hide modal.
Resolves #2778 
Commenting all the ifs in show_set_up_webhooks_popup() function is good enough to see t he modal.
=> Add a primary button to close Stripe webhook popup #2778

includes/profile.php
Adds a link to quickly navigate to the Edit Member screen from the Edit User screen. Without better hooks, this has to be done using JavaScript.
=> Adding an Edit Member link inline with the h1 heading on the Edit User screen

includes/updates/upgrade_3_0.php, includes/upgradecheck.php
When updating from 3.0 RC 1 to a future RC or the full release, wipe the subscriptions table data and re-run the migration script.
Check out PR and see that subs table data is wiped and the site is prompted to run the AJAX update again.
=> Re-run migration script after RC 1

js/pmpro-checkout.js
Changes to how certain user fields were rendered broken the JS to attach our required red asterisk to certain fields at checkout. This PR improves the JS logic to locate where to put the asterisk.
Before:
After:
1. Create a variety of required user field types - text, checkbox, select, radio, date
2. Check your checkout page
3. Confirm the asterisks are in the right position.
=> Updating the jQuery to show the required asterisk logic on fields

adminpages/functions.php
Adding nonce to Email Order modal to prevent CSRF. Also prefixing url params to not conflict with the orders list params or other plugins.
Resolves XXX.
Go to `/wp-admin/admin.php?page=pmpro-orders&pmpro_email_order=[order_id]&pmpro_email_to=[user_email]` and see that a security error is thrown when the modal is not used.
=> Adding nonce to email order modal and prefixing params

adminpages/member-edit/pmpro-class-member-edit-panel-user-fields.php, includes/fields.php
When user field are added via custom code, there are a few locations we support to hook into the Membership Checkout page or on profiles only. These groups of fields do not have a nice field group name, so they look somewhat off on the Edit Member screen. Additionally, these fields settings won't be editable in the Settings > User Fields GUI. Is it helpful to show a message about where these fields are coming from?
I'm not 100% sold on the message here.
Note: I also looked into changing the panel's title and the navigation link but it would require more extensive changes to how the fields are architected that didn't feel right at this time.
=> Showing a message on user field groups that are part of custom code for checkout field location hooks

adminpages/member-edit/pmpro-class-member-edit-panel-tos.php, adminpages/member-edit/pmpro-class-member-edit-panel-user-info.php
=> Moving pmpro_after_membership_level_profile_fields to user_info panel

adminpages/memberslist-csv.php
Adding the subscription transaction ID to the export. This is the most useful number to help people cross reference details in the gateway.
=> Adding subscription transaction ID and next payment date to members list export

adminpages/memberslist-csv.php, classes/class-pmpro-members-list-table.php
We are moving away from storing billing addresses in user meta since this would not be MMPU-compatible. Instead, billing addresses should be stored per order.
This PR removes the MMPU-incompatible data from the Members List and CSV export.
=> Removing the billing address from the members list

blocks/src/component-content-visibility/content-visibility-controls.js
We previously thought it was problematic to allow people to nest blocks with visibility settings. We are changing our minds here early testers are confused why the setting isn't always shown.
This could mean people make weird logic and get confused, but the inverse is also true.
Visibility always cascades from the outermost block. We can make this clear in docs.
=> Removing the restriction on setting visibility for nested blocks

js/pmpro-recaptcha-v3.js
* BUG FIX: Added `#pmpro_btn-submit` to offsite gateways that replace the default submit button and had this ID missing. This fixes an issue where reCAPTCHA wouldn't show the badge for v3 and offsite gateways.
Doing it this way will always ensure that reCAPTCHA works, however it has to be an input type of "submit" and any other input type for a button won't work. However even though it may not display the reCAPTCHA badge but that is only cosmetic - I don't think this would negatively affect checkouts and spam.
=> Add `#pmpro_btn-submit` to offsite gateways

js/pmpro-recaptcha-v3.js
For gateways that hide the default submit button span, the recaptcha badge was being hidden as well.
This change pulls the recaptcha div out of the potentially hidden span to make sure that the recaptcha badge is always visible.
Resolves #1789 
1. Set up recaptcha v3
2. Set checkout to PPE
3. View checkout page and see that badge shows
=> Moving recaptcha div out of submit span

includes/updates/upgrade_3_0.php, js/updates.js
Showing number of subs migrated/remaining while running AJAX update.
=> Showing better progress during 3.0 migration

classes/class-pmpro-subscription.php
Add filter to subscriptions class to allow avoiding syncing subscriptions with gateway during CSV import.
This would be great to have for IUCSV, but maybe it's too late to squeeze into 3.0. We could add it in 3.1 if needed. We should build a proof-of-concept to make sure this filter is sufficient for speeding up IUCSV
=> Adding filter to skip fixing default migration data

classes/class.memberorder.php
If multiple checkouts are processed in the same page load, `getMembershipLevelAtCheckout()` needs to be smart enough to get the level that the order is for. This may be the case in plugins like our MMPU-Legacy plugin.
=> Get correct checkout level

includes/upgradecheck.php
Sets the max index length on indexed `varchar` columns with length greater than 191. The addresses the SQL error `WordPress database error Index column size too large. The maximum column size is 767 bytes. for query...`
This is based off the logic in core WP here: https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/includes/schema.php
Note: This will only fix column indexes on new installs, though this SQL error is only an issue since 3.0 where we started setting table collates based on the site's settings.
To test, you can set up a new site and run the following SQL to check if there are "max sizes" set up: `SHOW INDEX FROM wp_pmpro_membership_levelmeta`
=> Setting max index length when needed

readme.txt
A while back, we merged a PR which would theoretically allow us to show a notice on the Plugins page that users would see before upgrading to a particular version of PMPro:
https://github.com/strangerstudios/paid-memberships-pro/pull/2123
That PR was based off of the code in this article:
https://andidittrich.com/2015/05/howto-upgrade-notice-for-wordpress-plugins.html
This PR follows the recommended WP readme template here:
https://wordpress.org/plugins/readme.txt
According to that template, each update notice is limited to 300 characters. The current text in this PR is 222 characters. HTML will also be escaped when showing to the user on the Plugins page.
There is a chance that this will not work as we haven't ever actually been able to test this, but it is worth including in the hopes …
=> Adding upgrade notice for 3.0

includes/rest-api.php, js/pmpro-checkout.js, js/pmpro-stripe.js
In PMPro v3.0+, users can only purchase a single membership level at once. This PR deprecates the `checkout_levels` endpoint, which is only needed when purchasing multiple levels at once. The `checkout_level` endpoint should now be used.
This also has logic to allow the (now deprecated) `checkout_levels` endpoint to process the `#pmpro_level` field and to fix that field being sent when using Stripe's payment request button.
=> Mark the checkout_levels REST endpoint as deprecated

includes/updates/upgrade_3_0.php, js/updates.js
If a subscription fails to have default migration data overwritten (in other words, does not have a billing amount or cycle number), throw an error during AJAX update and halt the AJAX.
1. Run AJAX to migrate subscriptions
2. Whenever you would like an error to occur, add a `return;` at the top of the `PMPro_Subscription->maybe_fix_default_migration_data()` method to break the migration
=> If a sub fails to migrate, throw an error and halt AJAX

classes/gateways/class.pmprogateway_stripe.php
Save the "refunded" order status earlier after processing a Stripe refund to help avoid a race condition where the webhook may try to send the "refunded" emails again, causing the emails to ultimately be sent twice.
Resolves XXX.
1. Add a `sleep()` call to the `process_refund()` method around where the emails are sent to exacerbate the race condition
2. Trigger a refund from PMPro
3. See that without the fix, duplicate emails are sent. But with the fix, duplicate emails are not sent.
=> Save the refunded status change earlier

includes/blocks.php
Issue:
I set up a content visibility block which is set to hide content from users with levels 1 and 2. Currently, if a user has both level 1 and level 2, the content is correctly hidden. If the user has neither level, the content is correctly shown. But if the user has level 1 but not level 2, the content is still shown which is not how we want the Content Visibility block to work
Fix:
Instead of passing negative levels to `pmpro_hasMembershipLevel()` which will be "or'd" together, this PR checks each inverted level one at a time so that if the user has any of the levels, we can hide the content.
=> Fixing inverted visibility logic

classes/class-pmpro-field.php
Missing closing div when we render the field input for a file type field.
=> Missing div close in file type field html / input version

preheaders/account.php
Found some unused logic in the account page preheader. David and I confirmed its 9 years old and logic we don't use anymore. Removing here to clean up the code.
=> Removing unused msg logic from 9 years ago on account preheader

classes/gateways/class.pmprogateway_braintree.php
Adds a new filter so that this code recipe can be used to modify the merchant account ID for subscriptions, not just individual charges:
https://www.paidmembershipspro.com/change-merchant-account-id-braintree/
Once merged, that code snippet should be updated with `add_filter( 'pmpro_braintree_subscription_create_array', 'my_pmpro_braintree_transaction_sale_array' );`.
=> Adding filter `pmpro_braintree_subscription_create_array`

adminpages/wizard/save-steps.php
Adding the Stripe Connect nonce to the wizard so that the Stripe keys can be saved once the user returns to the site.
=> Fix connecting to Stripe during setup wizard

classes/class.memberorder.php
Add support to search for order by multiple matching level ids. Same as multiple status.
Enhanced docblock as well.
=> Add support to search for order by multiple levels

classes/class.memberorder.php
Creates a new property `$discount_code_id` in MemberOrder and allow searching orders by discount_code_id.
These changes work as proxies for querying the `pmpro_discount_codes_uses` table directly and, once Add Ons switch to interacting with discount codes through the MemberOrder object, will give us the option to cleanly deprecate the `pmpro_discount_codes_uses` table in the future in favor of storing this information directly in the `pmpro_orders` table.
If we did want to deprecate `pmpro_discount_codes_uses`, here are the necessary steps:
- Step 1 (v3.0): Create abstracted function for modifying/searching the discount code ID (this PR)
- Step 2 (At least 1 year later): Update Add Ons to use the new abstracted functions.
- Step 3 (Next major release after all Add Ons updated): Add new …
=> Member Order Property - $discount_code_id

services/ipnhandler.php
We have discovered that after a recurring payment fails in PPE multiple times, PMPro will just mark the subscription as cancelled in PMPro even though it is still active in PayPal.
This change will change this behavior to removing the user's membership AND cancelling the subscription in PayPal.
=> Cancelling subscription after failed payment attempts

includes/functions.php
There are code recipes in the wild that passed arrays to `pmpro_next_payment()`'s $order_status parameter. We should still support that code.
=> Backwards compatibility for arrays passed as $order_status in `pmpro_next_payment()`

adminpages/membershiplevels.php
esc_url() is removing the JS needed for the "add level" link and is also unnecessary since the URL is escaped above.
=> Fixing "Add a level" link

classes/class-pmpro-members-list-table.php
Fixed issue where the expired/cancaellation date would be empty for old members in the Members List.
=> Fixing expired/cancelled dates for old members in Members List

includes/functions.php
When null is passed to the `str_replace` arguments used in `pmpro_no_quotes` the follow error got logged in debug:
```
PHP Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated
Resolves XXX.
```
Adding a null coalescing operator to the search string third argument returns an empty string which resolves this issue.
1. Activate the Custom Level Cost Text Add On, navigate to Memberships > Settings > Advanced and check the debug log for the deprecated warning.
2. Apply the patch, reload the page, and confirm that no new log entries were added.
=> pmpro_no_quotes - Add null coalescing operator

pages/levels.php
If no levels will be shown for a level group, hide it from the levels page entirely.
=> Only show a level group if levels will be shown for it

classes/gateways/class.pmprogateway_stripe.php
Fixed over-escaped text in Stripe webhook checker.
=> Fixing webhook checker escaping

includes/metaboxes.php
We have seen plugin conflicts where either our meta boxes aren't being loaded on "edit post" pages with some page builders including Avada, or where `add_meta_box()` is being called before the function is defined. The latter can cause a fatal error when updating to 3.0.
=> Fixing meta boxes added too late or too early

js/pmpro-checkout.js
Fixed an issue where discount codes would not be applied if using an outdated checkout page template.
=> Fix applying discount codes for outdated checkout templates

includes/functions.php
Added in a filter to show/hide the setup wizard based on custom conditions. I assume web developers won't want their customer's running through the setup wizard in some instances and want to hide it from them as things may be overwritten or added when running through the setup wizard?
=> Idea: Filter to hide the setup wizard links in admin.

adminpages/functions.php, classes/class-pmpro-discount-code-list-table.php
* Override single_row function to add error class if the discount code row need to be higlighted due miscounfiguration
Override single_row function to add error class if the discount code row need to be higlighted due miscounfiguration
Resolves #2823
Steps in the linked issue.
=> Discount codes with unsupported billing details are not highlighted

classes/class-pmpro-site-health.php
Adding level group information to site health.
=> Adding level group information to site health

includes/level-groups.php
* remove extra comma that breaks PHP lt 7.3
Resolves https://wordpress.org/support/topic/fatal-error-after-updating-to-3-0-1/
=> Fatal error after updating to 3.0.1 on PHP 7.2.

services/applydiscountcode.php
* Remove unwanted strip quotes function, esc_html should strip all unwanted chars.
Resolves #2882.
1. Reproduce bug with steps from linked issue.
2. Apply this patch
3. Check issue does not happen anymore 
=> Discount code error message strips single quotes

includes/adminpages.php, includes/functions.php
* ENHANCEMENT: Default to "View with my access" when no option is found. Fixes an issue where defaulting to View with access would confuse admins and not highlight the code green as the CSS class is missing.
=> Default to "View: My Access"

includes/login.php
Fix PHP error when passing `null` to `esc_url()`.
=> Don't pass null to esc_url()

pages/checkout.php, services/applydiscountcode.php
Alternative to #1994.
Updates "discount code applied" strings to all be the same and to have the `<strong>` tags outside of the localized string.
=> Removing HTML tags from localized text

adminpages/member-edit/pmpro-class-member-edit-panel-user-info.php
WordPress allows users to not have a role. In our Edit Member page, we don't support that option, so we default to the first value. This default could be a "powerful", like Membership Manager. If the page is then saved, the user will actually be given that role.
The fix is to have an option for "no role" and this PR is based on the core WP Edit User code here:
https://github.com/WordPress/wordpress-develop/blob/13fd2f829b01156174d1ca7ca2236eb9c7248e42/src/wp-admin/user-edit.php#L453-L461
=> Support users without a role

classes/gateways/class.pmprogateway_paypalexpress.php
Sending a content type of `application/json` has started throwing "malformed JSON" errors when creating a PPE subscription in sandbox mode. This PR changes the content type to `application/x-www-form-urlencoded`, which should be the correct content type anyways.
Also fixes a PHP warning `PHP Deprecated:  Implicit conversion from float 1.1274959045124686 to int loses precision`
=> Fixing creating PPE sandbox subscriptions

includes/filters.php
Alternative to #1864.
Resolves #1617
1. Create a level that expires in a month
2. Check out repeatedly
3. See that day of month stays the same each time.
=> Fixing assumption that all months are 30 days

classes/class.pmproemail.php, includes/email-templates.php
* Get membership_level_name and membership_level_id from $order object and add to data object before call sendEmail function in pmproemail class
* Add level name to billable_invoice template
Resolves #2891 .
1. Apply this patch
2. Go to Memberships->Oders 
3. Look into the Orders WP_List_Table and click email link to send en billing invoice from that order. 
4. Check results.
=> Additional email template variables for the Billable Invoice email

includes/login.php
Makes sure that "log in errors" aren't shown when a user is successfully logged in.
Resolves XXX.
Couldn't replicate, but here were the reported steps.
1. Go to your frontend login page
2. Enter a username but no pw, submit form
3. Shows error message Error: The password field is empty.
4. add your PW, submit form.
5. you get logged in, but error message still showing.
=> Don't show login errors when logged in successfully

classes/gateways/class.pmprogateway_stripe.php
=> Stripe: fix reference to PMPRO_MIN_PHP_VERSION const

adminpages/groups/edit-group.php, adminpages/levels/edit-level.php, classes/class-pmpro-orders-list-table.php, classes/class.pmproemail.php, css/admin.css, includes/privacy.php, services/braintree-webhook.php, services/stripe-webhook.php
The approach was to scan for errors using PhpStorm. Then:
- Fixed some variable names that changed after a refactoring
- Removed some duplicate array keys
- Fixed some "undefined variable"
- Some other minor fixes
- Fixed missing color var references
Nothing of this should be affecting the usage. I'm just removing some red marks in the code editors.
=> Fix some code issues in 3.0

classes/gateways/class.pmprogateway_paypalexpress.php, classes/gateways/class.pmprogateway_stripe.php
…request
Running the migration tool from 3.0 for the subs table makes a large number of requests.
Many of them can be avoided if you still have orders for a disabled gateway w/o the credentials set.
This was already implemented for some gateway.
The support is extended to Stripe (checking the secret key only) and to PPE (checking user/pass/signature keys).
1. Open an errored subscription, which has a message from the gateway after trying to connect w/o credentials
2. Apply this patch and update the subscription
3. The error will now be the message from this patch; this means no API request has been made bc there are no credentials set.
=> Stripe/PPE: Ensure the credentials are set on each gateway before performing API requests

adminpages/member-edit/pmpro-class-member-edit-panel-user-info.php
We have seen issues on websites where users could have multiple roles or a role that doesn't show in the Roles list on the PMPro Edit Member page. In these situations, saving the Edit Member page for a user could unintentionally change the user's role on the website, potentially adding or removing capabilities for that user. Either of these situations is dangerous and should be avoided.
In the medium term, we would like to add the Role option back, but this needs to be done to ensure compatibility with the various Role setups and plugins available in WordPress. As a "quick fix", this PR removes the role setting entirely. Admins can still edit roles for users from the default Edit User page in core WP.
> Enter a summary of all changes on this Pull Request. This will appear in the changelog …
=> Removing role from Edit Member page

includes/checkout.php, includes/scripts.php, js/pmpro-checkout.js, preheaders/checkout.php
When a user is created at checkout but the checkout fails (ex Stripe SCA) and the form is shown again, the nonce on that re-generated checkout form will not be specific to the newly created user object. This will cause nonce verification to fail when the form is then submitted again.
This PR adds JS to update the nonce value when the checkout form is displayed to ensure that we have the correct nonce value for the current user.
1. Set up site with Stripe
2. Check out as new user using Stripe SCA test card
3. Choose to authenticate successfully
4. See that nonce fails before PR, but succeeds afterwards
=> Updating checkout nonce via AJAX

adminpages/dashboard.php
* BUG FIX: Fixes an issue where "Recent Members" dashboard widget would throw a warning for a recently deleted user as the code is cached and not cleared on user deletion.
This adds a final check before outputting the data to ensure that the user exists.
Another option would be to cache this for a shorter period in time or clear cache on user deletion.
1. Ensure `WP_DEBUG` is enabled.
2. Delete a member from the Users Table (but it has to be a recent member)
3. Navigate to the dashboard widget "Recent Members" and see the error.
4. Implement this code
5. Re-view the Recent Member widget and see the user is gone. This is same functionality as once the transient is cleared.
See ticket #562793 for reference.
> Enter a summary of all changes on this Pull Request. This will appear in the …
=> Make sure user ID exists

includes/functions.php
Resolves XXX.
1. Change level from Edit Member page
2. See that old level is put into changed status, not admin_changed
=> Fix admin_changed status not being applied on the Edit Member page

adminpages/pagesettings.php, adminpages/wizard/save-steps.php, includes/functions.php
Now generating pages as follows:
Membership Account page is parent of the: Billing, Cancel, Orders, and Profile Edit page.
Membership Checkout page is parent of the Confirmation page.
Membership Levels and Log In are top level pages.
* ENHANCEMENT: Updated the hierarchy and names for generated PMPro pages as part of optional initial setup steps.
=> Adjusting the hierarchy and names of generated PMPro pages

adminpages/member-edit/pmpro-class-member-edit-panel-orders.php
* ENHANCEMENT: Show the payment gateway on the member edit orders panel to make it easier to differentiate where the payments are coming from when using more than one gateway.
Resolves: https://github.com/strangerstudios/paid-memberships-pro/issues/2958
1. Navigate to the Member Edit Screen and choose "Orders"
2. See the gateway name included in the table.
=> Show "Gateway" on Member Edit

adminpages/member-edit/pmpro-class-member-edit-panel-subscriptions.php
* ENHANCEMENT: Added "Gateway" column to Edit panel to subscriptions.
* BUG FIX: Fixed a small issue where a `</td>` was missing from Subscriptions.
=> Added "Gateway" column to the Subscriptions member edit.

includes/login.php
* BUG FIX: Fixed an issue where the redirect would always redirect to the login page.
The issue here was we were ommitting the redirect value entirely from the $login_form_array which would then default to setting a $redirect_to value of the REQUEST URI and it would always redirect to that URL based on the wp_login_form defaults when that parameter was missing.
This fix, fixes issues for custom redirects (snippets) as well as the Member Homepages Add On.
Setting the `redirect` argument to false by default as Paid Memberships Pro handles it's own redirects during the login process and this returns the expected functionality.
=> Fixed always redirect to login page

classes/gateways/class.pmprogateway_paypalexpress.php
Letting the checkout preheader save the MemberOrder during a successful recurring PPE checkout instead of saving sooner.
When an order is saved in "success" status, a PMPro Subscription is created for the user if needed. By saving the order early, the PMPro sub was created early. Then, when the user's level is changed and all of their active subs are deleted, this new subscription is deleted too.
With the fix, the order isn't saved until after the level change occurs. So now, any previous subscriptions are deleted on level change, and the  new subscription is set up in PMPro afterwards.
Resolves XXX.
1. Log in as a user with a membership level
2. Purchase that same membership level again with a recurring membership via PPE
3. See that before the fix, the new subscription was immediately …
=> Fix renewing recurring subscription with PPE

adminpages/userfields.php, includes/fields.php, includes/services.php
`pmpro_get_field_html()` and `pmpro_get_field_group_html()` echo their contents immediately. Those functions do not return their contents.
This PR fixes warnings with code that expects the contents to be returned instead of already being echoed.
=> Fixing warnings on User Fields settings page

adminpages/membershiplevels.php
* ENHANCEMENT: Added group ID value to the menu location within the Level Settings page. This makes it easier to identify the group's ID for developers and future features that may need this.
The idea of putting this to the right of the name is to try and not clutter up the group names and make it easily visible without clicking around to get this data.
**Screenshots**
=> Add Group ID to Level Settings page

classes/gateways/class.pmprogateway_stripe.php
When using Stripe Connect, webhooks are now set up automatically after connecting to Stripe and updated with new events as needed.
This PR also removes the banner to show "set up your stripe webhook" instructions as this is now being done automatically.
=> Setting up Stripe webhooks automatically

css/frontend.css, css/print.css, includes/scripts.php
Consolidating `print.css` into `frontend.css`.
=> Merging print.css into frontend.css

classes/class.pmproemail.php, includes/email.php
* Hook into pmpro_get_membership_levels_for_user filter to "mock" level to send a test email
Hook into pmpro_get_membership_levels_for_user filter to "mock" level to send a test email
Resolves #2980
.
Follow steps described in the issue above
=> Cannot test "Cancel On Next Payment Date" email templates

includes/compatibility/lifterlms.php
* Unregister the CPT that resevers the 'memberships' slug.
Unregister llms_membership if streamline version of lifterlms is enabled.
Resolves #2820
1. Create a page with 'memberships' slug
2. Check that it doesn't render appropriately
3. Apply this patch.
4. Flush cache saving permalinks.
5. Check again.
=> LifterLMS streamline mode and the /membership/ CPT slug

adminpages/admin_header.php, includes/adminpages.php
Fixing "Memberships" menu not being open in sidebar when on the Design Settings tab and fixing the "Settings" header menu not being highlighted.
=> Fixing menu UI when the design tab is selected

adminpages/dashboard.php, adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php, adminpages/member-edit/pmpro-class-member-edit-panel-orders.php, adminpages/templates/orders-email.php, adminpages/templates/orders-print.php, classes/class-pmpro-orders-list-table.php, classes/class.memberorder.php, classes/class.pmproemail.php, includes/functions.php, includes/profile.php, pages/invoice.php, shortcodes/pmpro_account.php
Adds the following filters to adjust how an order's total, subtotal, and tax values are displayed across PMPro:
- pmpro_order_formatted_total
- pmpro_order_formatted_subtotal
- pmpro_order_formatted_tax
Opened as an alternative to #2988 
=> Adding filters for formatted order total, subtotal, tax

adminpages/member-edit/pmpro-class-member-edit-panel-orders.php
Switched to using the `MemberOrder::get_orders()` method on the Edit Member orders page. Also fixes fatal error introduced by #3009 
Resolves XXX.
1. Load the Edit Member orders page
2. See that there is no longer a fatal error in the "total" column
=> Use MemberOrder::get_orders on Edit Member page

classes/class-pmpro-subscription.php
Added filter `pmpro_subscription_cost_text`.
=> Add a filter for subscription cost text

adminpages/dashboard.php
* ENHANCEMENT: Added new filter 'pmpro_dashboard_meta_boxes' which allows developers to hide dashboard widgets, as well as add their very own widgets to the dashboard area.
This resolves an issue where WooCommerce (and most likely other plugins) cause a fatal error when trying to view our dashboard page.
To test this, you can add the following code - this will remove the welcome dashboard from the PMPro dashboard:
```php
// Example to remove a meta box from the dashboard
function my_pmpro_remove_meta_box_from_dashboard( $meta_boxes_array ) {
unset( $meta_boxes_array['pmpro_dashboard_welcome'] );
return $meta_boxes_array;
}
add_filter( 'pmpro_dashboard_meta_boxes', 'my_pmpro_remove_meta_box_from_dashboard' );
```
=> Filterable dashboard widgets

classes/class-pmpro-admin-activity-email.php
* Cant escape link built and term is already escaped
Stop escaping link
Resolves  #2973 .
1.
2.
3.
=> Activity Email Discount Code Usage showing HTML

includes/email.php
* ENHANCEMENT: Added a fallback to get the site URL from the database should the SERVER_NAME parameter not be available in certain cases like using WPCLI and some other instances.
* REFACTOR: Applied WPCS to pmpro_wp_mail_from function
=> Reworked wp_mail_from and WPCS

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php
When an order refund fails on the Edit Member "memberships" tab, show an error message and halt any other changes.
=> Showing an error when order refund fails

css/frontend/high_contrast.css, css/frontend/variation_1.css, shortcodes/pmpro_account.php
Subtle adjustments so that the section shown on Membership Account when user has no memberships is more inline with other sections.
=> Adjust style of Membership Account > My Memberships section when the user has no active level.

classes/gateways/class.pmprogateway_paypal.php, classes/gateways/class.pmprogateway_paypalexpress.php, classes/gateways/class.pmprogateway_paypalstandard.php
Eliminating duplicated PayPal settings in multiple classes. Now, PayPal Express always handles the settings.
=> Eliminating duplicate PP gateway settings code

adminpages/advancedsettings.php
When the Security tab was created, the settings were moved from Advanced Settings. These should not still be here in the Advanced Settings admin page code.
=> Removing moved settings from Advanced Settings admin page

adminpages/paymentsettings.php, adminpages/securitysettings.php, classes/gateways/class.pmprogateway_authorizenet.php, classes/gateways/class.pmprogateway_braintree.php, classes/gateways/class.pmprogateway_check.php, classes/gateways/class.pmprogateway_cybersource.php, classes/gateways/class.pmprogateway_payflowpro.php, classes/gateways/class.pmprogateway_paypal.php, classes/gateways/class.pmprogateway_paypalexpress.php, classes/gateways/class.pmprogateway_paypalstandard.php, classes/gateways/class.pmprogateway_stripe.php, classes/gateways/class.pmprogateway_twocheckout.php
These settings have been moved to the new "Security" settings tab.
=> Removing use_ssl and nuclear_https from gateway settings

services/stripe-webhook.php
Fixing payment transaction ID not showing on PMPro orders after Stripe Checkout one-time payment
=> Fixing payment transaction ID not showing after Stripe Checkout one-time payment

includes/functions.php
* BUG FIX: Fixes an issue for non-member text when no levels are found.
I.e. Show for logged-in users, show now access message in block settings.
=> Reworked non-member message for logged-out

includes/functions.php, shortcodes/pmpro_account.php
Supporting lots of cases here now on the My Memberships section whether the membership is:
- Free
- Recurring, no expiration / active
- Expiring
=> Logic update so we do not have to show an empty expires section on the my memberships area

adminpages/advancedsettings.php, includes/functions.php, includes/updates/upgrade_3_1.php
Only show the option use custom non-member text if that setting is already being used on the site. New sites will not have that option, and the option will be removed in a future version of PMPro.
=> Deprecating nonmember text option

classes/class-pmpro-field.php
Fixes issue where if you add a divclass either in user fields via code OR using the 'Field Wrapper Class (optional)' setting was missing a space.
=> Fix no space between classes when adding a field wrapper class element / divclass

includes/functions.php
* ENHANCEMENT: Added in deprecated filter for previous logged-out filter `pmpro_not_logged_in_text_filter`.
* BUG FIX: Fixed a small typo for deprecating `pmpro_non_member_text_filter` (this is the correct filter).
=> Add deprecated not logged-in content filter.

includes/deprecated.php, js/pmpro-admin.js
Check if the site's theme or child theme is loading a frontend.css override and show an admin notice.
=> Adding notice if we detect a custom frontend.css loaded via theme files

css/frontend/high_contrast.css, css/frontend/variation_1.css, pages/checkout.php
Fixes responsive columns for field layouts and other column layouts.
Adjusts checkout account information section when no confirm email or confirm password fields are shown.
=> Style updates continued for no confirm password; responsive columns

css/frontend/base.css, css/frontend/high_contrast.css, css/frontend/variation_1.css, pages/cancel.php
When a user cancels one or more levels that have an active subscription, the cancel page needed to be more clear on what will actually happen.
This PR builds a better message when a single level being cancelled has an active subscription and shows the next payment date as their new expiration.
This also builds a better message when more than one level is being cancelled and one of the levels has a subscription.
We didn't yet tackle the confirmation message post-cancellation. This works well for a single level cancel where membership expiration is set, but not for multiple levels cancelled in one action where some of them are still active memberships. We can tackle this in another pass or someone else can chime in on this one. 
This PR fixes some mobile collapse styling for the Cancel page …
=> Adjusting the cancel page to have more clear messaging related to CONPD

adminpages/emailsettings.php, includes/email.php
* BUG FIX: Fixed an issue where the From Name email setting would escape apostrophe's but not remove the slash on the frontend (settings and email received).
Also WPCS was applied to the pmpro_wp_mail_from_name function.
1. Set the from name to something like: `PMPro's Test Site` and save your settings. You will see it changes `PMPro\'s Test Site`
2. After pulling this PR, it should set the values back to `PMPro's Test Site` on the settings page as well as the From name within the email browser.
=> Fixed slashes in From Name setting.

css/frontend/base.css
Adds bg color to our view as menu item - when screens are smaller, this wraps outside the admin bar and is not visible. This PR could be closed and not merged - it's a problem with the admin bar overall and also present for the username "Howdy" part, so this only fixes "our" menu item, not any that wrap (which we should not do).
Resolves #3053
=> Adding background color to admin view as admin bar element.

css/frontend/high_contrast.css, css/frontend/variation_1.css, includes/login.php, pages/checkout.php
Fixing bug where "toggle password" buttons would be linked if there were multiple login pages on a single page.
=> Fixing password toggle if there are multiple login forms on page

adminpages/paymentsettings.php
* BUG FIX: Fixed an issue where the Javascript for showing payment option fields on the Payment Settings Page was running too early for _some_ gateways (mainly external gateways).
1. Install a plugin/Add On gateway like Paystack (https://wordpress.org/plugins/paystack-gateway-paid-memberships-pro/)
2. Before pulling this code into your environment, set your gateway to Paystack and reload the page without changing payment gateways and see that the "Currency & Tax Settings" don't display until you toggle the gateway dropdown.
3. Pull the code change and re-run the steps above to see that the settings show on page load.
=> Fixed loading JS on Payment Settings Page

includes/updates/upgrade_3_1.php, includes/upgradecheck.php
In 3.1, we are fixing some user_id columns (order meta, subscriptions, subscription meta) by changing the data type from int(11) to bigint(20). We want to show notices to sites that may have issues due to user IDs having been too high to be tracked in those tables.
Resolves XXX.
Testing this requires editing code to force the 3.1 update to run and either:
1. Having a site with user IDs larger than 4294967295
2. Editing the code to reduce 4294967295 in the query to something like 100
=> Showing notice if order/sub data may be linked to incorrect users

css/frontend/base.css, pages/levels.php
Small catch so the levels table collapses nicely for mobile.
=> Adding data-title attributes to Membership Levels table

css/frontend/base.css, includes/functions.php, js/pmpro-checkout.js
JS to support required billing fields and form field errors on submit.
Required fields indicated with an asterisk, screen reader text, and aria-required field attribute.
After form submit, fields that have errors are highlighted.
* BUG FIX: Fixed styling for fields with errors on checkout form submit.
* BUG FIX: Fixed Billing Address fields required asterisk and aria-required attributed.
=> Required billing fields and submitted form error fields support

pages/checkout.php, shortcodes/checkout_button.php
Resolves the issue we had about required field not filled in in checkout without additional warning.
This is because when not using international addresses, the default country is not written into the hidden field.
1. Deactivate international addresses (via filter)
2. Then see the checkout working again
=> Ensure echoing when escaping attributes

pages/billing.php
Screenshot of up
date billing page after fix with billing address disabled:
=> Removing testing code causing billing address to always show on update billing

css/admin.css, css/frontend/base.css
This fixes the Lost Password view where the action links were justified space-between and looking off.
Before:
After:
=> Fix password form actions nav

pages/confirmation.php
Fixes issue where you cannot save a page with the Confirmation Page block.
=> Fixing saving Confirmation Page block

includes/compatibility/lifterlms.php
PMPro's login form was submitting to the filtered LifterLMS Student Dashboard page. This update unhooks the LifterLMS lostpassword_url filter (similar to how we do for WooCommerce), so that our password reset process works as intended.
=> Fix our lost password form submitting to the LifterLMS form (when streamline is enabled)

includes/login.php
Alternative to #3073
Resolves #3072
This solution mirrors the `pmpro_checkout_before_submit_button` and `pmpro_billing_before_submit_button` hooks that we have on the checkout and update billing forms.
=> Adding hook pmpro_lost_password_before_submit_button

classes/class-pmpro-subscription.php
Fix the next payment date TIME (and the cancel date TIME if using CONPD in core) to consider the timezone.
When usign get_date_from_gmt with format = 'U', the result does not consider the timezone.
Then, a solution is to call that function twice. One to add the timezone, then to format the datetime.
1. Create a new subscription
2. Check the TIME of the next payment/cancellation
It will be a cycle ahead (MINUS or PLUS the timezone).
=> Workaround to use get_date_from_gmt to format into 'U'

adminpages/member-edit/pmpro-abstract-class-member-edit-panel.php
Before this fix, when you change a Level manually, after saving you going to see that:
- You are still on the Member > Membership tab (because of the hidden field `pmpro_member_edit_panel`)
- The URL does NOT contain the `pmpro_member_edit_panel` anymore
- Refreshing the page will bring you away from the Member > Membership panel obviously
Moving the `pmpro_member_edit_panel` directive from the hidden field to the submit action will make the URL consistent after saving.
=> Change submit url to target the specific member panel, to keep the URL consistent

adminpages/member-edit/pmpro-class-member-edit-panel-memberships.php
Fixes the default expire date when manually assigning a new membership level, which is not adding the local offset.
1. Set your WP site to Europe/Rome for instance (that is +1 or +2).
2. Take a random member without a membership and add a new membership, setting to expire.
3. Check the local datetime input default value. The time will be GMT instead of 18zed (+1 year).
**Please note: can't use wp_date bc we still support WP 5.2 compat and wp_date is 5.3+.**
=> Make the new membership level default expire date i18zed

classes/gateways/class.pmprogateway_paypalstandard.php, classes/gateways/class.pmprogateway_twocheckout.php
Fixing free orders when PayPal Standard is the set gateway.
=> Fixing free orders when PPS is the set gateway

includes/functions.php
A user has a site with a single level that they manually add people to. They do not want to have people sign up on their own.
I realized that our smart no access messages assumes there is an assigned levels page and checkout page. While it is 100% advisable for membership sites to do this, I can see a case where a site has no public levels and no checkout process.
This PR makes the smart message smarter.
=> Fixing no access message default if no levels page or checkout pages are assigned.

includes/functions.php
`pmpro_set_expiration_date()` already works with `null` values (since `$wpdb->update()` already works with them), but the PHPDocs do not reflect this. Seeing as that the alternative of zero-dates is [not recommended](https://github.com/strangerstudios/paid-memberships-pro/issues/892), I think it would be good to officially support passing `null` to the `enddate` parameter of this function.
There's not really anything to test, functionality-wise. This just makes static analysis tools like PHPStan/Psalm stop complaining when you pass `null` as the `enddate` argument in `pmpro_set_expiration_date()`.
> Officially support passing `null` as `enddate` argument in `pmpro_set_expiration_date()`.
=> Explicitly allow setting a null expiration date via pmpro_set_expiration_date().

classes/gateways/class.pmprogateway_braintree.php, pages/billing.php, preheaders/billing.php
Adds the CardType hidden field to the Braintree card fields form
Closing #3100  in favor of these changes
1. Use a gateway that uses our own card field form such as Braintree or Auth.net
2. Fill out your card details and hit submit
3. Checkout should go through as expected
=> Adds the CardType field back into the form

js/pmpro-recaptcha-v3.js, js/pmpro-stripe.js
There are two main fixes here:
In `pmpro-recaptcha-v3.js`, we were validating reCAPTCHA when the submit button was clicked. This did not run in cases where the checkout form was submitted via JS. To fix this behavior, this PR updates the validation to occur when the form is submitted. This is closer to how we validate the reCAPTCHA v2 as well.
In `pmpro-stripe.js`, we had code to "force submit" the checkout form with `form.get(0).submit();` after the payment request button was used or 3DS verification was completed. Although this worked for most use-cases, it prevents code running on the jQuery `.submit()` method to run. This prevented our new reCAPTCHA v3 code (and I assume the old v2 code) from running. The fix here was to just call `form.submit();`, which still allows `.submit()` …
=> Fixing reCAPTCHA and payment request button at checkout

pages/billing.php, preheaders/billing.php
The `bemail` and `bconfirmemail` fields were removed from the Update Billing page in PMPro v3.1 which caused errors when updating billing information with some payment gateways.
This PR adds those fields back to the Update Billing page.
=> Adding back bemail fields to the Update Billing page

classes/gateways/class.pmprogateway_stripe.php, js/pmpro-stripe.js
People with dark themes have no way to target and style the Stripe elements fields that get added via JS. This PR adds a new filter `pmpro_stripe_card_element_style` so that custom styles can be added.
Here is an example of using this hook to make the placeholder and field values white. You may still need custom CSS to override core PMPro style variations and how background colors and borders are set.
https://gist.github.com/kimcoleman/ab5282830d18252ec39b9dab124d6e7a
=> Exploratory PR to allow people to adjust the style of the mounted Stripe Elements fields.

classes/gateways/class.pmprogateway_stripe.php, css/admin.css
With Stripe Checkout becoming default, we are hearing more reports of issues caused by webhooks not being set up. We currently automatically set up webhooks when a site connects to Stripe, but this misses cases when legacy API keys are used or when a staging site connects to Stripe and the setup is then migrated to a live site on a different domain.
This PR shows an admin notice when the Stripe gateway is being used and webhooks are not set up on the website.
=> Add admin notice when Stripe webhooks are not set up

preheaders/checkout.php
For core gateways, if the user has a membership level and purchases it again with a subscription, the new subscription will be immediately canceled. This is happening because:
1. The order was being saved in `success` status before the level changed occurred
2. This caused the PMPro_Subscription entry to be added before level change
3. During level change, all existing subscriptions for cancelled levels are deleted
The fix: Delay the saving of the success order (and therefore the creation of the PMPro Subscription) until after the level change and subs cancellations have been completed.
=> Fix subscriptions being immediately cancelled

classes/gateways/class.pmprogateway_braintree.php
By default, the Checkout page loads this code in `checkout.js`, but the billing page loads it inline when the CardType field is generated.
When using Braintree, the generation of the credit card fields is overwritten, so we need to make sure that the JS to populate the CardType field is included in both cases. With this PR, the checkout page will essentially have this JS loaded twice, which seems ok.
Update billing for a Braintree subscription. See that "Fill out required fields" error shows without this Pr, but billing update completes successfully with this PR.
=> Making sure CardType is set on update billing page

css/frontend/variation_1.css, css/frontend/variation_high_contrast.css
Improvements to the select field dropdown appearance across themes.
Fixing the base variation to work better for dark mode - high contrast already had these fixes these I think I missed when we were going back and forth on how we wanted to handle field background colors / text colors.
=> Better select dropdown field arrow; fixes for dark background themes

classes/gateways/class.pmprogateway_stripe.php
Previously, we had to send users to Stripe Checkout on the `pmpro_checkout_before_change_membership_level` hook since user objects would not exist during the gateway's `process()` method. Now, however, users are created before payments are taken.
Currently, if sending a user to Stripe Checkout fails (due to not being able to connect to Stripe, for example), the checkout will complete successfully without collecting payment. Switching to using the `process()` method allows us to halt checkout on these errors and show a relevant error message at checkout.
The easiest way to replicate is to set up a local dev environment and check out with Stripe Checkout with your machine's wifi disabled.
=> Now sending users to Stripe Checkout during the process method

adminpages/securitysettings.php, includes/fields.php, includes/functions.php, includes/recaptcha.php, pages/billing.php, pages/checkout.php, preheaders/billing.php, preheaders/checkout.php
Abstracting reCAPTCHA-specific code out of the checkout and update billing pages to prepare for other CAPTCHAs to be added. All reCAPTCHA code is now within `includes/recaptcha.php` and reCAPTCHA-specific JS files.
Added actions:
- pmpro_security_spam_fields
- pmpro_save_security_settings
- pmpro_billing_update_checks
Deprecated actions:
- pmpro_checkout_after_captcha
=> Abstracting captchas and moving reCAPTCHA into a single file

shortcodes/pmpro_account.php
Now showing the list of a member's active levels in the My Memberships section of the Membership Account page sorted by the levels order stored in wp_options.
* ENHANCEMENT: Now showing a member's list of active memberships sorted by the site's defined levels order.
=> Sorting the display of the My Memberships section of the Membership Account page by the Levels Order stored in options

includes/functions.php
* ENHANCEMENT: Validate the user's IP address using filter_var and check if it's IPV4 or IPV6 within the pmpro_get_ip function.
=> validate IP address in pmpro_get_ip

classes/class.memberorder.php
Fixes a bug with Subscription Delays and any plugin that calls MemberOrder->getDiscountCode() before an order has an ID.
=> Fixing calling getDiscountCode() on orders without an ID

includes/cloudflare-turnstile.php, paid-memberships-pro.php
* ENHANCEMENT: Added support for CloudFlare Turnstile which can be enabled on the checkout and update billing screen. Enable CloudFlare Turnstile via the Security Settings.
Here are a list of test keys - https://developers.cloudflare.com/turnstile/troubleshooting/testing/
=> Added Cloudflare turnstile integration

includes/functions.php
It doesn't make a lot of sense to set the current user even if the cache clean function is called with a different user id.
Btw, just in case, we don't want to completely remove something that might be useful somehow somewhere.
Let's emulate what wp core does. Let's forse setting the current user if cleaning cache for the current user only.
=> Update global user if cleaning cache for the current user only

classes/class.memberorder.php, classes/gateways/class.pmprogateway.php, classes/gateways/class.pmprogateway_paypalexpress.php, includes/functions.php, preheaders/checkout.php
Currently, free and paid MemberOrders are created at different points in the checkout preheader. This PR moves all of the order creation logic to a single location to simplify the overall checkout flow.
Part of this work was reviewing the `PMProGateway` class. This class handles free checkouts and checkouts using the "test" gateway (when the `gateway` for an order is the empty string). In this class, there are many methods (such as `authorize()`, `charge()` and `subscribe()`) that provide an outline for how a payment gateway could function, but ultimately, the approach needed to code each gateway varies significantly and the existing sample code is outdated. For this reason, the sample `process()` function logic along with the corresponding helper methods are being removed and deprecated …
=> Combining the free and paid checkout order creation flow

pages/checkout.php
There were certain cases where custom code might set the `pmpro_skip_account_fields` filter to hide the fields, but the empty box was still showing.
This also resolves cases where that filter would be used to hide the fields but the page wouldn't show that the person was logged in.
This can be tested using the first recipe in this blog post: https://www.paidmembershipspro.com/reduce-form-fields-at-checkout/
* BUG FIX/ENHANCEMENT: Improved conditional that shows the Account Information box at checkout when user fields might be hidden via filter.
=> Adjusting the display of the Account Information box at checkout

includes/checkout.php
Make sure that `$discount_code_id` is set before adding the entry to the memberships users table. This fixes functionality in the deprecated Sponsored Members Add On.
=> Fix setting code_id in memberships users table

adminpages/reports/logins.php
Fixes potential case where the return of the pmpro_logins, pmpro_visits, or pmpro_views usermeta value might be corrupt or otherwise not a string. Now we will always set it to an empty array if it is either empty OR not what we expect it to be.
* BUG FIX: Fixing case where logins report might show a type error if usermeta returned is not an array.
=> Fixing edge case where the logins report might throw a type error if usermeta is corrupted or incorrect

includes/crons.php, includes/deprecated.php, includes/email-templates.php, scheduled/crons.php
Merging the Recurring Emails Add On to notify customers of upcoming payments.
~~The main change from the original Add On is that, by default, users will only be notified of an upcoming payment if their previous payment was 6 months or more in the past. This modification is useful to comply with the laws of various countries and payment processors without spamming users each time that they have a more frequent payment.~~
Resolves XXX.
=> Merging the Recurring Emails Add On

includes/deprecated.php, paid-memberships-pro.php
Sites already using Authorize.net will be able to continue using that gateway, but it will not be shown as an option on new sites.
=> Mark Authorize.net as deprecated

adminpages/wizard/save-steps.php, classes/class-pmpro-site-health.php, classes/class-pmpro-wisdom-integration.php, classes/gateways/class.pmprogateway_stripe.php, services/stripe-webhook.php
Stripe is beginning to require authentication with restricted keys or Stripe connect. This PR hides some "legacy key" errors when using restricted keys and removes "legacy key" wording from some places.
=> Recommending using Stripe restricted keys

classes/gateways/class.pmprogateway_stripe.php, pages/checkout.php
Temporary fix for Stripe 3DS authentication after the 3.2 checkout refactor updates. We should be able to remove this workaround in the future once we get closer to multstep checkout.
=> Clear $pmpro_review when Stripe 3DS is triggered

classes/class-pmpro-subscription.php, includes/functions.php
The pmpro_method_defined_in_class() checks if a method is specifically defined in the given object's class, not inherited.
We then use that method in the PMPro_Subscription class to detect if the gateway classes hasn't overridden the default cancel_subscription() method. In that case, we want to fallback and use the old cancel method instead.
This was tested using the Paystack Add On for PMPro. In versions of PMPro before 3.2, that gateway was able to cancel the subscription at the gateway. When using 3.2 without this fix, the subscription is not cancelled at the gateway (it is cancelled locally though). When using this fix, the subscription is once again cancelled at the gateway.
> BUG FIX: Fixed issue where some third party gateways were no longer cancelling subscriptions at the gateway …
=> Adds pmpro_method_defined_in_class and uses in PMPro_Subscription class

preheaders/checkout.php
Fixes an issue where Stripe 3DS checks will fail when billing addresses are required at checkout.
These lines will be removed in a future update as we are no longer storing billing addresses in user meta.
Resolves XXX.
=> Now only loading billing addresses from user meta when initially loading the checkout page

adminpages/discountcodes.php, includes/functions.php, includes/upgradecheck.php
Add a checkbox input to discount codes to only allow that code to be used once per user.
=> Adding "one use per user" discount code setting

classes/class-pmpro-field-group.php, includes/fields.php, paid-memberships-pro.php
This PR creates a new class `PMPro_Field_Group` that can be used for adding and retrieving user field groups and user fields for each group.
Directly modifying the `$pmpro_field_groups` and `$pmpro_fields` globals should no longer be necessary with this class and those globals will likely be removed in a future major release.
=> Adding PMPro_Field_Group class

adminpages/emailtemplates-edit.php, classes/class.pmproemail.php, classes/email-templates/class-pmpro-email-template-cancel.php, classes/email-templates/class-pmpro-email-template.php, includes/email-templates.php, paid-memberships-pro.php
Adding an abstract `PMPro_Email_Template` class to make email templates more structured along with a sample `PMPro_Email_Template_Cancel` class demonstrating how that class should be extended.
This approach has the immediate benefit of accurately listing email template variables when editing the email template:
This PR still uses the `PMProEmail->sendEmail()` method to send emails and register templates with the `$pmpro_email_templates_defaults` hook, so no custom code should break with these changes. Down the line, though, these changes put us in a position to significantly clean up our code around emails and email templates.
=> Create email template class

includes/functions.php
* BUG FIX: Fixed an issue where IPv6 address would be used and not return an IP address. Moved to an AND condition to fix it.
I also moved around the sanitization of the IP address, it makes sense to use the preg_replace before the filter_var method.
=> Change pmpro_get_ip conditional

classes/class-pmpro-field.php
Enter `0` into a text field at checkout and complete checkout. See that, before this fix, if you go to the checkout page again, the field appears with the "default" value set for the user field instead of `0`. After this fix, `0` shows correctly.
=> Fix user fields applying default value when '0' is set

paid-memberships-pro.php
Avoiding errors if SITENAME constant is already defined.
=> Checking if constant SITENAME is already defined

classes/class-pmpro-site-health.php, classes/gateways/class.pmprogateway_stripe.php
Although using an older version of the Stripe API is fully supported by Stripe, seeing an outdated version has been concerning to some site owners. This PR moves the Stripe API version to Site Health instead of showing it on the PMPro Payment Settings page.
=> Display Stripe API version in site health instead of settings

adminpages/reports.php, adminpages/reports/logins.php, adminpages/reports/members-per-level.php, adminpages/reports/memberships.php, adminpages/reports/sales.php, includes/fields.php, includes/reports.php
Some setups are showing a doing_it_wrong notice starting from WP6.7 (related to https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/)
To investigate on your local env and see all the errors, modify your core `function _load_textdomain_just_in_time` this way:
Causes:
1. Reports registration. Fixed 2e9bfe32341f07547188b0d5716adf2f5e578680
2. (not fixed in this PR) User fields default group name (which is also tricky to be filtered because it runs way before other plugins and themes)
Tests to be done:
=> WordPress 6.7 compat. Fix doing_it_wrong notice related to early translations

adminpages/orders.php, includes/checkout.php
Currently, discount codes are set for orders after the orders have been saved. This means that the discount code attributes are not correct during the `pmpro_added_order` hook and the `pmpro_updated_order` hook.
This PR updates the logic when saving orders at checkout and on the Edit Order page to set the discount code during the order save process to make sure that those actions work as expected.
Note: When using offiste gateways (such as Stripe Checkout or PayPal Express), the discount code will still not be available during the `pmpro_added_order` hook. This is because the order is initially added in `token` status and is later updated to `success` with the discount code added once the checkout is complete. In these cases, it is best to use the `pmpro_after_checkout` or …
=> Now setting the discount code ID on orders before saving

classes/class.memberorder.php
Adding user ID to getRandomCode() in case other hash parameters are identical. Specifically for cases where to orders are purchased at the exact same time and `rand()` produces the same result for the `$auth_code` and `secure_auth_code`.
=> Adding user ID to getRandomCode() in case other hash parameters are identical

pages/confirmation.php
Avoiding fatal error if $pmpro_invoice->user is null for some reason
=> Making sure that the user is not empty.

includes/spam.php
Also limits spam tracking to once per page load in case a discount code is checked multiple times in a single page load.
Alternative to #3203 and #3205.
=> Tracking spam when using an invalid discount code

classes/class.pmproemail.php, classes/email-templates/class-pmpro-email-template-billing-failure-admin.php, classes/email-templates/class-pmpro-email-template-billing-failure.php, includes/email-templates.php, paid-memberships-pro.php
=> Add payment failure classes

adminpages/user-fields/field-settings.php, adminpages/user-fields/group-settings.php, css/admin.css, js/pmpro-admin.js
…; adjusting JS to toggle all file fields properly
This PR moves a few field settings around + improves the markup CSS so that it is easier to:
- Target field settings with JS
- Jump fields around
- Add new fields with a future hook.
There is also some JS improvement to hide the "Required at Checkout" individual field setting based on the group setting.
=> Adjusting CSS to better allow for added field settings by custom code.

classes/gateways/class.pmprogateway_paypalexpress.php
Returning from PayPal results in you still having to click the Confirm Payment button if you don't have PayPal Express as the primary gateway. 
This change moves it out of the if statement and should be okay as we check in that preheader function if the order's gateway is PPExpress and if not, return.
=> Fixing nonces for logged out users with PPE

includes/cloudflare-turnstile.php
* BUG FIX: Fixed an issue where CloudFlare validation would fail for PayPal Express checkouts, and potentially other gateways.
This saves the status to a user's session, similar to how we do it with reCAPTCHA and don't try to validate it more than once.
Resolves: https://github.com/strangerstudios/paid-memberships-pro/issues/3212
=> Fix Cloudflare Turnstile validation for PayPal Express

includes/rest-api.php
Fixes issue where most REST API endpoints would be restricted to `pmpro_edit_members` (see change from `$permission = current_user_can( $permission );` to `$permission = current_user_can( $permission_to_check );`)
Also updates the `post_restrictions` endpoint to check whether the current user can edit the specific post being updated.
Alternative to #3238 
Resolves #3215 
=> Fix capability checks, update capability for post_restrictions

services/stripe-webhook.php
When using Stripe Checkout, PMPro will always use the tax calculated by Stripe. This means that if a site is using the VAT Add On, the tax calculated by the Add On will be overwritten by the $0 tax calculated by Stripe.
This PR fixes that issue to only overwrite tax if Stripe is set up to calculate tax.
=> Fixing Stripe Checkout always overwriting tax value

adminpages/orders.php, classes/class-pmpro-orders-list-table.php, classes/gateways/class.pmprogateway.php, classes/gateways/class.pmprogateway_stripe.php, includes/functions.php
When Stripe webhooks are set up, orders may be stranded in `token` status without allowing admins to complete those checkouts after correcting their webhook setup. This PR adds a "recheck" link for orders. That link will check if the payment has been completed at the gateway and, if so, complete the checkout in PMPro.
This currently only works for Stripe, but can eventually be expanded to all gateways that are completed via webhook. It also gives us the option to automatically check pending orders in the future instead of having it be a manual admin process.
1. Disable Stripe webhooks
2. Check out using Stripe Checkout
3. Note that there is an order stuck in `pending` status and checkout hasn't been completed in PMPro
4. Click the "Recheck" link for the order
5. See that the checkout is …
=> Now allowing checking token orders for completion

classes/class-pmpro-orders-list-table.php, includes/functions.php
Some addresses, such as those in Belgium, have cities and postal codes but not states. Currently in PMPro, if a state is not present, we do not show the city or postal code. This PR updates PMPro to account for these types of addresses.
Resolves XXX.
1. Set up Stripe Checkout to always collect billing address
2. Check out using a Belgian billing address
3. See that city and zip were not shown in PMPro email/orders page before this PR, but are afterwards.
=> Showing city and zip in billing address even when missing a state

classes/class-pmpro-field-group.php
Now passing the field ID to the unique "element" parameter of the pmpro_get_element_class so that the checkout processing experience can append the appropriate error class and highlight the "missing" fields by their field ID
Resolves #3131
=> Logic to add class names based on field ID and passing the field ID to the element param of pmpro_get_element_class so form processing can target

classes/email-templates/class-pmpro-email-template-admin-change-admin.php, classes/email-templates/class-pmpro-email-template-admin-change.php
A few fixes to incorrect template variable usage. Also putting back the correct subject line for the admin change email sent to the user.
=> Fixing incorrect variable usage and subject line that was not meant to change

includes/addons.php
We saw the following fatal error on the plugins/updates page if the site fails to retrieve the list of Add Ons:
`An error of type E_ERROR was caused in line 59 of the file /.../wp-content/plugins/paid-memberships-pro/includes/addons.php. Error message: Uncaught TypeError: array_column(): Argument #1 ($array) must be of type array, null given in /.../wp-content/plugins/paid-memberships-pro/includes/addons.php:59
Stack trace:
#0 /.../wp-content/plugins/paid-memberships-pro/includes/addons.php(59): array_column()
#1 /.../wp-content/plugins/paid-memberships-pro/includes/addons.php(265): pmpro_getAddons()
#2 /.../wp-includes/class-wp-hook.php(326): pmpro_update_plugins_filter()
#3 ......`
This PR checks whether `$addons` is empty to avoid passing `null` into `array_column()`.
> Enter a summary …
=> Fix PHP fatal error if Add On check returns null

classes/class-pmpro-admin-activity-email.php
* BUG FIX: Fixes a minor issue for PHP 5.6 with the admin activity email class.
=> Fix fatal error for PHP 5.6

js/pmpro-admin.js
Alternate to #3254
After installing an Add On via the Memberships > Add Ons page, we try to find an "activate" link to show the user so that they can immediately activate the plugin. This functionality was not working. Upon testing, I found that this may have been due to the Code Snippets having a button with the `.button-primary` class that confused our code in thinking that was the "activate" button.
This PR fixes the issue by specifically looking for a link with `plugins.php?action=activate&plugin=` to greatly increase our chances of finding the correct activation link.
=> Fixing showing activate link after installing Add On

includes/login.php
Previously, the code relied on 'login' parameter checks for error handling, **which is probably a bad copy-paste**. The code now properly checks the 'error' parameter for invalid or expired keys, ensuring more accurate error handling.
Resolves #3261.
1. Check the procedure reported in the issue
2. With the changes in place, the warning is gone
3. Even if you mess up the request changing 'error' to 'error2', no warning.
=> Fix error handling for password reset invalid/expired keys.

includes/adminpages.php
Add a check to ensure `$top_menu_page` is not empty before generating admin page links. Prevents errors or unexpected behavior when the variable is undefined.
Resolves #3263.
=> Fix potential issue with missing top menu links

adminpages/reports/memberships.php, css/admin.css
The "Signups vs. Cancellations" and "Signups vs. Expirations" reports have been broken since v3.0. This PR:
1. Fixes those reports (See abstraction in `function drawVisualization()`. The issue was JS errors caused by `['` and `<?php` being on new lines in the deleted code)
2. Removes unnecessary `if ( $type === 'signup_v_cancel' || $type === 'signup_v_expiration' || $type === 'signup_v_all' ) {` conditions that always evaluate to `true` (resulting indentation changes is most of the diff)
3. Adds the raw report data in a table under the chart.
=> Fixing membership report "vs cancel" and "vs expiration", add table below chart

adminpages/reports/logins.php, adminpages/reports/memberships.php, adminpages/reports/sales.php, adminpages/sales-csv.php, css/admin.css
Allow filtering the sales/revenue report by multiple levels/discount codes.
=> Allow filtering the sales/revenue report by multiple levels/discount codes

adminpages/addons.php, css/admin.css
The install/activate are now HTML "button" elements. This makes them part of the tab order and able to be triggered with keyboard navigation.
This also fixes an issue with skipped heading levels.
Finally, a bug fix where the plugin's action links might be an array with multiple items and for some plugins, named keys (LifterLMS was my test to see this error). The former $actions[0] was causing this error.
This now resets and returns the value of that first element in the array.
Resolves #3266
=> Improving accessibility of the Add Ons admin screen

css/frontend/variation_1.css, css/frontend/variation_high_contrast.css
Small style adjustment so a visible Turnstile has spacing but an invisible turnstile will not leave a gap.
To accommodate this we needed to adjust the elements around the potential captcha rather than the captcha itself.
=> CSS spacing fix when Turnstile is visible

includes/deprecated.php, paid-memberships-pro.php
Sites already using these gateways can continue using them, but they will not be shown as options on new sites.
=> Marking PayFlow, PayPal Standard, and Braintree as deprecated

classes/gateways/class.pmprogateway_stripe.php, includes/checkout.php
Profile start dates are currently calculated and filtered when creating a subscription at the payment gateway. Although this works well for the vast majority of use cases, it gets complicated when custom code wants to adjust the billing amount and set a profile start date at the same time (for example, prorations).
This PR adds a support for a new `profile_start_date` property on the checkout level object that can be adjusted during the `pmpro_checkout_level` filter. This makes adjusting the `profile_start_date` at checkout the same process as any other level property.
This PR will also begin throwing deprecation warnings for the existing `pmpro_profile_start_date` filter to encourage developers to use `pmpro_checkout_level`. This will ensure that everyone is adjusting the profile start …
=> Supporting setting profile start date on checkout level

includes/upgradecheck.php
Some gateways, such as Square, have subscription transaction IDs that are longer than 32 characters. This PR bumps our limit to 64 characters which matches the limit that we already have on payment transaction IDs.
=> Allowing for subscription transaction IDs up to 64 characters

includes/functions.php, pages/checkout.php, preheaders/checkout.php
In 3.0, we added caching to `pmpro_getLevelAtCheckout()` to speed up Add Ons retrieving checkout level information. However, this caching caused issues in edge cases where incorrect level data was retrieved early on page loads.
This PR passes the actual checkout level object to relevant hooks at checkout in lieu of caching the function. This also has the benefit of simplifying Add On code by directly passing checkout levels into functions instead of retrieving them with a function call.
=> Passing the checkout level to hooks during checkout flow instead of caching

includes/checkout.php
During asynchronous checkouts, we are currently saving the discount code used at checkout in an order meta field and also on the checkout level object. We have seen issues where those discount codes do not match which may cause discount code uses not to be saved.
To streamline our data storage and avoid duplicate (and potentially conflicting) information, this PR makes the discount code set on the checkout level the source of truth. In a future breaking update, discount code data will only be pulled from the checkout level object when completing checkout.
=> Using the discount code set on the level object when set

adminpages/levels/edit-level.php, adminpages/levels/save-level.php, css/frontend/variation_1.css, css/frontend/variation_high_contrast.css, includes/functions.php, shortcodes/pmpro_account.php
* ENHANCEMENT: Added logic to now support a "Membership Account Message" content on a per-level basis.
* ENHANCEMENT: Added hook for 'pmpro_member_account_message' which allows developers to show their own information programmatically at the bottom of each membership 'card' on the account page.
* ENHANCEMENT: Added a description to the level's "Description" field to be more clear to members. (TODO: Confirm the UTM arguments are correct).
**Screenshots**
=> Membership Account Message Functionality

adminpages/reports/memberships.php
Before this fix, the last day of the daily membership report would always show `0`.
=> Fixing signups not showing on the last day of memberships report

includes/notifications.php
* BUG FIX: Fixed a potential issue when a callback doesn't exist in PMPro notification conditional JSON.
Resolves XXX.
1. Try the following JS logic for a notification (sample JSON below)
2. Clear all transients for notifications in the database.
3. See that the banner will shows even though these conditions will never bet met.
JSON:
`
[
{
"id": 1,
"name": "abc123",
"title": "Posts per page less than 10",
"content": "<p>This shows if posts per page is less than 10</p>",
"starts": "2020-10-01",
"ends": "2030-01-01",
"type": "general",
"dashicon": "groups",
"priority": 1,
"dismissable": true,
"show_if": {
"check_option": [
"posts_per_page",
"<",
"50"
]
}
}
]`
DM me if you want a hosted URL for this file/JSON to run tests.
=> Fix notification showing when callback doesn't exist.

css/frontend/variation_1.css, css/frontend/variation_high_contrast.css
The previous CSS was targeting any "first child" of another element within the `pmpro_account-membership-message`. This is more specific CSS because we only want to target the VERY FIRST child element inside `pmpro_account-membership-message`, not the first child of all nested elements within.
=> More specific CSS for level-specific account message

css/frontend/variation_1.css, css/frontend/variation_high_contrast.css
Resolves scrunched display for our password reset styling when the container is narrow. Formerly, the Show Password toggle button was breaking to two lines.
This may not need a standalone changelog entry.
=> Fix for narrow containers for the reset password form

includes/localization.php
* BUG FIX: Fixed the incorrect loading of global localization files as the path was incorrect. Removed the `/pmpro/` global path as this hasn't been used in a really long time and should be okay to be removed.
Resolves #1984
=> Fix logic around loading MO files.

classes/class-pmpro-subscriptions-list-table.php
If the subscription cannot be retrieved, the list tables will show errors when displaying the row contents. This will prevent the subscription from being shown entirely.
=> Make sure that the subscription object exists before showing in list table

classes/email-templates/class-pmpro-email-template-checkout-check.php, classes/email-templates/class-pmpro-email-template-checkout-free.php, classes/email-templates/class-pmpro-email-template-checkout-paid.php
Fixed membership_level_confirmation_message variable in checkout check template. Also fixed for free and paid templates how membership_level_confirmation_message is documented.
1. Payment gateway must be pay by check
2. Checkout for a paid level.
3. See email sent to the user
4. Check again the template after applying the patch. membership_level_confirmation_message and discount code should be either blank or properly rendered.
=> [Bugfixing] Checkout check template misses confirmation message and discount code variables.

classes/email-templates/class-pmpro-email-template-payment-reminder.php
Adds missing email template variables for the Membership Recurring email including `!!membership_id!!`, `!!membership_cost!!`, and `!!billing_amount!!`.
=> Adding missing email template variables for the payment reminder email

classes/email-templates/class-pmpro-email-template-billing-admin.php, classes/email-templates/class-pmpro-email-template-checkout-check-admin.php, classes/email-templates/class-pmpro-email-template-checkout-free-admin.php, classes/email-templates/class-pmpro-email-template-checkout-paid-admin.php
Fixed issue where `!!name!!` and `!!display_name!!` would show the admin's name in admin checkout emails instead of the purchaser's name. Also updated email template variable descriptions to clarify this behavior.
=> Fixing display names shown in admin checkout emails

classes/email-templates/class-pmpro-email-template-checkout-check-admin.php, classes/email-templates/class-pmpro-email-template-checkout-check.php, classes/email-templates/class-pmpro-email-template-checkout-free-admin.php, classes/email-templates/class-pmpro-email-template-checkout-free.php, classes/email-templates/class-pmpro-email-template-checkout-paid-admin.php, classes/email-templates/class-pmpro-email-template-checkout-paid.php, includes/email.php
Make sure that we get expiration dates for the newly purchased level when sending checkout emails
1. Have a level in one group that expires
1. Check out for another level that has a subscription (no expiration)
=> Make sure that checkout emails get the expiration date for the right level

classes/class.pmproemail.php, classes/email-templates/class-pmpro-email-template-checkout-check-admin.php, classes/email-templates/class-pmpro-email-template-checkout-check.php, classes/email-templates/class-pmpro-email-template-checkout-free-admin.php, classes/email-templates/class-pmpro-email-template-checkout-free.php, classes/email-templates/class-pmpro-email-template-checkout-paid-admin.php, classes/email-templates/class-pmpro-email-template-checkout-paid.php, classes/email-templates/class-pmpro-email-template-payment-reminder.php, includes/email.php
Fixes issues from #3166 
Fixes issues with test template email sending returning as "failed" in admin
Adding missing membership level data in checkout free/paid email templates
Adding missing template variable !!instructions!!
1. Go to any of the Email templates and send a test
* Fixed test emails where data was empty as per #3166 
* All test emails were returning as "failed" in admin because they did not return the send() method result as the ajax response
* Including missing membership level data in checkout free/paid email templates
* Added missing template variable for !!instructions!! for check payments email
=> Test email variables 3166

includes/deprecated.php, includes/upgradecheck.php
PMPro v3.4 marked Payflow as deprecated to prevent new sites from using that gateway. This deprecation also caused existing sites to no longer be able to use Payflow, which was not intentional. This PR adds Payflow back as an option for sites that are already using it
=> Fixing loading payflow gateway

adminpages/memberslist-csv.php
Fixes an issue where user fields with a string value of `0` would show as blank on the members list CSV export.
1. Set up a checkbox grouped field with multiple options with only labels set (no values)
2. Edit a user and select only the first option (which will have a value of `0`)
3. Export the members list CSV. The `array( 0 )` will be `join()`d to string `'0'`. Before this PR, this would show as an empty cell in the export. After, it will correctly show as `0`.
As a side note, it is highly recommended to set up the grouped checkbox field options in the format `value:label` to avoid values being preset to numbers which could change when options are added or removed from the field.
=> User field string value `0` showing blank on members list export

adminpages/emailtemplates-edit.php
Now only showing the global email template variables when editing the header and footer templates.
=> Only show global variables for header and footer templates

classes/email-templates/class-pmpro-email-template-admin-change-admin.php, classes/email-templates/class-pmpro-email-template-admin-change.php, classes/email-templates/class-pmpro-email-template-billing-admin.php, classes/email-templates/class-pmpro-email-template-billing-failure-admin.php, classes/email-templates/class-pmpro-email-template-billing-failure.php, classes/email-templates/class-pmpro-email-template-billing.php, classes/email-templates/class-pmpro-email-template-checkout-check-admin.php, classes/email-templates/class-pmpro-email-template-checkout-check.php, classes/email-templates/class-pmpro-email-template-checkout-free-admin.php, classes/email-templates/class-pmpro-email-template-checkout-free.php, classes/email-templates/class-pmpro-email-template-checkout-paid-admin.php, classes/email-templates/class-pmpro-email-template-checkout-paid.php, classes/email-templates/class-pmpro-email-template-credit-card-expiring.php, classes/email-templates/class-pmpro-email-template-invoice.php, classes/email-templates/class-pmpro-email-template-membership-expired.php, classes/email-templates/class-pmpro-email-template-membership-expiring.php, classes/email-templates/class-pmpro-email-template-payment-action-admin.php, classes/email-templates/class-pmpro-email-template-payment-action.php
The `!!subject!!` email template variable will be removed in a future version. We don't want sites starting to use it, so this PR removes it from documentation.
=> Removing documentation for !!subject!! email template variable

services/stripe-webhook.php
Fix warning when $subscription is not set
Check out for a one-time payment level with Stripe Checkout.
=> Fix warning in Stripe webhook handler

classes/gateways/class.pmprogateway_paypalexpress.php
Updated message so that we do not mention PayPal Website Payments Pro or Payflow.
=> Updating gateway notice to recommend PayPal Express only.

adminpages/subscriptions.php
Fixes fatal error on the Subscriptions list table if the gateway object for a subscription does not have a `supports()` method defined.
=> Avoid call to undefined `supports()` method

blocks/src/single-level-description/edit.js, includes/scripts.php
When previewing the level description in the editor, line breaks were not being displayed.
=> Fix so preview of level description in block editor uses line breaks

shortcodes/membership.php
* Just that deprecate the filter. It's better to use pmpro_has_membership_access_filter instead.
Deprecate this filter to use pmpro_has_membership_level instead.  The only place the filter is used is in Approvals Add On and it seems it's a bit problematic when isn't passed any level.
1. Install Approvals
2. Add a memberships shortcode without level [membership] some content [/membership]
3. Check debug.log file. 
=> [ENHANCEMENT] Deprecate pmpro_member_shortcode_access filter

classes/class-pmpro-admin-activity-email.php, classes/class-pmpro-wisdom-integration.php, includes/addons.php, paid-memberships-pro.php
Currently in core PMPro, `includes/addons.php` is loaded in 3 places:
- Whenever `is_admin()` is `true` (This is the most common case)
- When sending the Admin Activity email
- When sending telemetry data to Wisdom
In the PMPro Update Manager Add On, a duplicate version of `includes/addons.php` is also sometimes loaded after the `init` hook completes. The duplicate version is only loaded if `function_exists()` returns `false` for one of the `addons.php` functions.
Whenever `is_admin()` is true, core PMPro will load `addons.php` when that plugin is initially loaded, meaning that the Update Manager will never try to load the duplicate version. This is good.
Things get trickier with the other two cases (the Admin Activity email and the telemetry data). In these cases, since the core …
=> Fix race condition with Update Manager

classes/gateways/class.pmprogateway_check.php
Instructions for check payments would save with < p > tags wrapping everything and show it in the admin textarea box after saving
Resolves #3293 by using esc_textarea to properly prep the text for the textarea field
1. Admin settings go to Payment Gateway
2. Choose check
3. Enter instructions, save
Fix issue saving check payment instructions adding unnecessary < p > tags in admin settings
=> Fixing HTML in check instructions #3293

classes/class-pmpro-field.php
Our date user field type stores the user's information in the format YYYY-MM-DD. The field class' displayValue method, though, was expecting a timestamp.
This update converts the value from usermeta into a timestamp then, if we have a timestamp, sets the field to display in the site's date format. This also resolves cases when the usermeta is empty (was always showing today's date).
=> Fixing display value issue for date type user fields stored as YYYY-MM-DD format.

shortcodes/pmpro_member.php
* BUG FIX: Fixes a warning when the user is logged-out or if an invalid user_id was passed through.
Alternative to #3334.
While most of our `pmpro_` based functions can handle empty `$user_id` values, to save some performance we can check this early on to save resources and time.
The `$user_id` attribute will be set to `0` when someone is logged-out and no parameter is passed in - due to the `$current_user->ID` being the default value, if a non-zero value is passed in we can check that they exist in WordPress. This logic only runs when the logged-in user ID does not match that of the user_id passed in and we can assume they're viewing the content of another WordPress user, so let's make sure they're existing.
This is a bit of logic to help improve performance and avoid warnings as early …
=> Make sure the user exists when using pmpro_member.

classes/email-templates/class-pmpro-email-template-refund-admin.php, classes/email-templates/class-pmpro-email-template-refund.php
Call `get_formatted_total` instead of  raw `total` function to insert to template data.
1. Without this patch,   refund some orders and check value isn't formatted.
2. After applying this patch check them again
=> [BUGFIXING] Refund email templates are not formatting order_total value properly.

includes/functions.php
* ENHANCEMENT: Added support for not equals '<>' and '!=' operator for the pmpro_int_compare function.
TL;DR - It makes the pmpro_int_compare function easier to work with in some cases for not equals.
While you could do `pmpro_int_compare( $a, $b, '==' );` and check the inverse of the comparison when wanting to check for "not equals" it makes it easier to work with when allowing the not equals operators in this function.
This makes it a bit easier to expect a true result when using this code and making it a little bit easier to understand.
For example:
```
$operator = '!=';
if ( pmpro_int_compare( $value1, $value2, $operator) {
// Let's do something when it's true
}
```
Let me know if this doesn't make sense.
=> Add != or <> to pmpro_int_compare

includes/email.php
Check the `$_REQUEST['subject']` isset
1. Without this patch, go to the header or footer email template and save the template.
2. Check the logs.
3.
=> [BUGFIXING] Header and Footer are logging a warning due te lack of subject when save template on edit template page.

includes/localization.php
* BUG FIX: Updated the localization file location structure. Now it looks for it under `wp-content/languages/plugins/<<file-name>>`
1. Delete all translation files from `paid-memberships-pro/languages`
2. Download and add locale files for PMPro to `wp-content/languages/plugins` with the correct file names.
3. See the site is translating.
=> Fix the localization path to be correct.

adminpages/reports.php
If a user tries to access a report (via URL attribute) that doesn't actually exist, we would get a fatal error.
This PR makes sure the report slug called exists before trying to load the report function.
1. Add a non-existent report slug to your URL, like: `/wp-admin/admin.php?page=pmpro-reports&report=nope`
2. See the fatal error.
3. Pull this code and see no error.
* BUG FIX: Prevents a fatal error when accessing a non-existent report in the admin area.
=> Fixing case where the report called in URL does not exist

classes/class-pmpro-field.php
* BUG FIX: Fixed an issue where `depends` was not working with radio buttons.
The generated JQuery is set to target the input name instead of the field ID. When multiple radio options are added the radio ID is `field_id_x` and increments accordingly. This follows logic of the grouped checkboxes logic as the structure of the radio buttons are similar to this.
Also moved to `esc_js` instead to match that of other generated conditionals.
Resolves #3365.
=> Fix depends issue for radio buttons

classes/class.pmproemail.php
* BUG FIX: Fixed an issue where admin confirmation emails was not sending the "Free" template and was defaulting to "Paid".
* REFACTOR: Applied WPCS to the method `sendCheckoutAdminEmail`.
We were passing a nulled variable $membership_level to each email template class and leveraged the `$order->getMembershipLevel` instead of getting the user level made more sense here (See how it's handled in SendCheckoutEmail as it's slightly different).
Resolves #3362, #3349
=> Fix admin emails not sending free template

includes/addons.php
* BUG FIX: Fixed a warning message that was encoding the `>` on output as well make the message more clear where the settings are to add a license key to PMPro.
It looks like it wasn't just the `esc_html` causing this, tried various other methods like wp_kses/wp_kses_post - WordPress itself may have been interfering with this message. Decoding the $msg after escaping it works. This will still keep the string safe but just decode allowed characters. `esc_html` will still strip out non-allowed HTML entities.
Resolves #3323
=> Fix warning message when updating a plugin

css/frontend/base.css, includes/scripts.php
Updates the minimal style option to provide very basic styling for the password toggle buttons.
Also a small fix to the capitalization of the button text. Before, the PHP was using title case but the JS was using sentence case so it swapped when you clicked to toggle. 
Before
After
* BUG FIX/ENHANCEMENT: Basic styling for password visibility toggle when a site is using the minimal global style setting.
=> Styling password toggle when minimal design setting is active; fixing capitalization of password toggle so PHP matches JS

classes/email-templates/class-pmpro-email-template-membership-expired.php, classes/email-templates/class-pmpro-email-template-membership-expiring.php
Rely on passed by param membership id to retrieve level name inserted to email data.
Resolves #3346 
Follow steps in the issue above
=> [BUGFIXING] Membership Expiring Email Displays Incorrect Membership Level Name with Multiple Levels

includes/compatibility.php, includes/compatibility/bricks.php
-  Add a new callback function to add compat file on `after_setup_theme` to be able to load Bricks compat file ensurins only loads if Bricks is active.
- Add a compat file that adds a new condition to Bricks builder functionality letting builders add conditions related to users PMPro levels memberships.
1. In order to test this patch, you have to install Bricks page builder ( I used V 1.10.3 )
2. Create a page, and in that page go to edit with bricks and add an element. 
3. Click conditions icon and look for PAID MEMBERSHIPS PRO group and add a condition. 
4. Conditions are user has a membership level and user does not have level below. In both cases a level can be added in a dropdown below
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if …
=> [FEATURE] Add Bricks Support

adminpages/paymentsettings.php, classes/gateways/class.pmprogateway_stripe.php, css/admin.css
* changed the contextual color for the enabled gateways on main page to blue so we do not imply "functionally working" with green
* adjustments to the Stripe payment settings edit experience to only show fee info for live mode, move API keys methods inside the connection boxes, and move webhook settings into its own box.
=> Additional changes to the gateway settings overhaul work

includes/functions.php
Alternative to #3376
Previously, if the site change was made using wp-cli search-replace or similar (hosting migration tools working the same way), even the `pmpro_last_known_url` option saved w/o obfuscation/hashing was updated. Then, the site change was not detected, and the pause mode not triggered.
This PR encodes the `pmpro_last_known_url ` option when saving to the database and decodes it when pulling from the database.
=> Encode pmpro_last_known_url option

classes/gateways/class.pmprogateway_paypalexpress.php, services/ipnhandler.php
Replaces the solution implemented in #2901 to fix an issue with subscription not always being marked as `cancelled` in PayPal after failed payment retries are exhausted. The fix in #2901 worked, but meant that we couldn't use the abstracted `pmpro_handle_subscription_cancellation_at_gateway()` function to process the gateway.
Instead, this PR removes legacy optimization code from the PayPal Express `cancel()` method that was causing subscription cancellations to not be sent to PayPal. With this legacy behavior corrected, we can now use the abstracted `pmpro_handle_subscription_cancellation_at_gateway()` function again which fixes a bug where users were not receiving membership cancellation emails when failed payment retries are exhausted. Thanks to @dalemugford for this solution.
> Enter …
=> Simplify logic for handling suspended PayPal subscriptions, fix users not receiving emails

adminpages/memberslist-csv.php
Fixes:
PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in …paid-memberships-pro/adminpages/memberslist-csv.php on line 528
Resolves a rare notice when performing exports from the admin.
=> Fix PHP 8.1+ depreciation Notice

includes/functions.php
Optimizes `pmpro_getMembershipCategories()` using in-memory caching to improve performance when called multiple times form the same page.
using Query Monitor or similar you can observe the reduction in queries when `pmpro_getMembershipCategories()` is called on Paid Memberships Pro front-end pages.
Also adds doc blocks for two nearby methods that were missing them.
Optimized `pmpro_getMembershipCategories()` method to reduce database queries.
=> Optimize pmpro_getMembershipCategories()

adminpages/metaboxes/recent-members.php
=> Fixing the "Recent Members" metabox for sites that do not use the `wp_` prefix

adminpages/metaboxes/recent-members.php
Fixes the Recent Members metabox for sites that do not use the default `wp_` database prefix.
Continuation of #3434 
=> Avoid hardcoded prefix in Recent Members metabox

adminpages/advancedsettings.php, classes/class-pmpro-wisdom-tracker.php
When integrating with Action Scheduler, we moved Wisdom reporting to run on the `pmpro_schedule_monthly` action by default. Although this is the same frequency as previous versions of PMPro, the difference is that the `pmpro_schedule_monthly` action always runs on the first of each month instead of a month from when the plugin was activated. This causes the wisdom data to all be collected on a single day each month instead of having a constant flow of data.
This PR updates Wisdom to instead use the `pmpro_schedule_daily` hook that fires once each day. Even with this change, the code still has protections in place to ensure that data is only sent once monthly. But this change will give Wisdom the chance to send data each day.
The `schedule_tracking()` method is also being deprecated in …
=> Fix wisdom data always sending on the first of the month

classes/email-templates/class-pmpro-email-template-cancel.php, classes/email-templates/class-pmpro-email-template-membership-expired.php, classes/email-templates/class-pmpro-email-template-membership-expiring.php
This update takes the "code recipe" logic in this post (https://www.paidmembershipspro.com/expiring-emails-renewal-links/) and brings it into core PMPro.
The user emails for membership cancelled, membership expiring, and membership expired now all support the variable !!renew_url!!. This will show as a full URL to checkout for the membership level that was cancelled or is set for expiration.
If there are multiple level IDs and we cannot know it's for a "specific" level ID, the URL will instead pull in the Membership Levels page.
There is a chance the level is no longer publicly available. Core PMPro already has logic to redirect back to levels page if this is the case so we aren't account for this in this code.
Also not checking that pmpro_url( 'checkout' ) or pmpro_url( 'levels' ) exist. …
=> Adding !!renew_url!! to appropriate email templates

includes/currencies.php
Polish zloty currency was defined just with ISO 4217 in `currencies.php`. This caused the currency to be displayed on the left and with 'PLN', instead of on the right and with 'zł' symbol.
1. Go to Memberships> Settings > Payments.
2. Set Currency to Polish zloty.
3. Create a new membership level, find a payment field with a currency symbol next to it.
4. Verify the "zł" is displayed on the right side of the text field.
5. Put value e.g. 2137 per year. Save the level.
6. Open this membership level at checkout.
7. Verify that a non-breakin space is displayed for thousands operator and a comma for decimal operator (`2 137,00 zł`).
> Configure Polish zloty (PLN) currency according to local rules
=> Configure Polish zloty (PLN) currency according to local rules

classes/gateways/class.pmprogateway_paypalexpress.php, classes/gateways/class.pmprogateway_stripe.php, services/ipnhandler.php, services/stripe-webhook.php
This update improves the readability of order notes generated by automated processes. Specifically, it ensures that new data appended to an order note begins on a new line, making the notes easier to scan and understand.
This work also lays the groundwork for future improvements to how order notes are displayed in the admin.
* ENHANCEMENT: Improved readability of order notes by adding line breaks before appending data via automated processes.
=> Now adding new lines before appending items to order notes

preheaders/checkout.php
Instead of emptying the message variable if the review value is empty, allow the value that was set before to be used. 
Resolves #3355.
Any errors that originate from Stripe https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/gateways/class.pmprogateway_stripe.php#L2121-L2125 - would result in a generic error message being shown. 
These errors can be caused by a bad configuration in a Stripe account or tax settings. 
To force the error, I added these two lines in the try block to trigger the error. 
```
pmpro_setMessage( __( 'Session Created. ', 'paid-memberships-pro' ), 'pmpro_error', true );
return;
```
This results in the error being shown correctly
Without this fix in place, the generic `Unknown error generating account. Please contact us to set up your …
=> Stops emptying error messages on checkout

services/stripe-webhook.php
Historically, the "payment transaction ID" stored for Stripe initial payments would be the ID of a Stripe Charge (starting with `ch_`) whereas recurring payments would be the ID of a Stripe Invoice (starting with `in_`). This is a result of how the on-site Stripe payment flow is coded where the initial payment is charged separately from setting up a subscription. In this flow, an invoice is not created for the initial payment charge.
With Stripe Checkout, we set up the Checkout Session such that a Stripe Invoice is created for all payments, including initial payments. The primary motivation for creating invoices is so that they show in the "Payments" section of the Stripe Customer Portal. Even though we are creating an Invoice though, we are currently still saving the Charge ID in PMPro …
=> Always save the Stripe invoice ID as the payment transaction ID when there is an invoice

classes/gateways/class.pmprogateway_stripe.php, pages/invoice.php
Adds a new filter `pmpro_order_action_links` to allow modifying the action links when viewing an order on the frontend.
=> Allow filtering action links on frontend invoice page

classes/gateways/class.pmprogateway_stripe.php
Now determining whether to combine initial payment and subscription line items before either is created rather than having to retroactively remove the initial payment line item.
Also now using `$level->initial_payment` as the initial payment amount rather than `$morder->subtotal` for consistency with how the billing amount is handled.
=> Simplifying Stripe Checkout logic for whether to combine initial and recurring line items

services/stripe-webhook.php
Before saving the tax amount calculated by Stripe Checkout to a PMPro order, we wanted to make sure that Stripe Checkout was set up to calculate tax. This is important in case tax is being calculated onsite by the PMPro Vat Add On, for example, so that Stripe Checkout doesn't wipe that value.
Currently, this behavior is broken since the code is checking whether collecting tax IDs is enabled, not whether automatic tax calculations are enabled. This PR fixes that logic to check whether tax is being calculated by Stripe Checkout.
=> Fix Stripe Checkout tax not being saved on PMPro orders

css/admin.css, css/frontend/base.css, css/frontend/variation_1.css, css/frontend/variation_high_contrast.css
Small adjustments to file type fields. Previews are now forced to a 100px square cropped box. Adjusted spacing so things appear more uniform throughout.
I do not think a changelog entry is needed for this or it can be included in general CSS updates.
=> Improving the appearance of file type user fields on frontend and admin forms
